### ISSUE TITLE
Als medewerker monumentenzorg wil ik weten welke verblijfsobjecten, (bergingen en parkeergarages) in het pand zitten

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#1]
Zodat ik de eigenaren hiervan kan opzoeken

**Comment by NicoleKortoomsBAG** [comment]
gevraagde BAGgegevens = vbo's binnen een pand

**Comment by CathyDingemanse** [comment]
> gevraagde BAGgegevens = vbo's binnen een pand

Bergingen en parkeergarages zijn geen VBO's en kan de BAG niet leveren.

**Comment by CathyDingemanse** [comment]
is gerealiseerd in V1.1, parkeergarages in de BRK
