### ISSUE TITLE
Als medewerker riolering wil ik weten wat de oppervlakte is van het dak van het pand 

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#10]
zodat ik kan uitrekenen hoeveel liter water er afstroomt op het riool en door de buis heen moet.

**Comment by NicoleKortoomsBAG** [comment]
Oppervlakte van het dak is geen BAG gegeven. Geometrie van het pand geeft waarschijnlijk de beste indicatie.
Geometrie van het pand: het loodrechte bovenaanzicht van het object met de ware vorm, afmeting en oriëntatie en positie ten opzichte van de aarde, inclusief alle zichtbare en onzichtbare delen boven en onder de grond.
Ook kan worden gegeven :  Oppervlakte van het vbo (alle verdiepingen)

**Comment by CathyDingemanse** [comment]
is gerealiseerd in V1.1
