### ISSUE TITLE
booleans moeten alleen worden opgenomen bij waarde true

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#102]
Bijvoorbeeld: https://api.test.kadaster.nl/lvbag/api/huidigebevragingen/vhc/adressen?zoekresultaatidentificatie=adr-89d5a4d96f09c60716c4671fdb9334b8

Dit levert:
   "nevenadres": false,
   "geconstateerd": false,
   "indicatieInOnderzoek": false,

We willen alleen informatie opnemen in het antwoord die relevant is. Deze indicatoren zijn gedefinieerd om aan te geven of er iets "aan de hand" is, of "bijzonder" is aan het adres. Wanneer dat niet het geval is, hoeft het ook niet in het antwoord te worden opgenomen. 

Bijvoorbeeld indicatieInOnderzoek=false betekent dat er geen onderzoek loopt op de gegevens. Bij andere gegevens, zoals huisletter, nemen we die ook niet op wanneer die leeg is. Voor deze booleans moeten we dus de waarde false beschouwen als leeg.

**Comment by strijm** [comment]
Volgens mij is dit een duplicaat van #87. Kan deze gesloten worden?

**Comment by fsamwel** [comment]
is inderdaad duplicaat dus kan gesloten worden
