### ISSUE TITLE
adres zoeken op verkorte straatnaam ondersteunen

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#103]
https://api.test.kadaster.nl/lvbag/api/huidigebevragingen/vhc/adressen/zoek?zoek=baron%20vd%20oyeln%20voorschoten
Levert nu een 404 (not found)

Er bestaat echter wel een "Baron Schimmelpenninck van der Oyelaan 1, 2252EA Voorschoten" met  nummeraanduiding 0626200000001220 met "verkorteStraatnaam": "Bar S vd Oyeln"

Ik zou verwachten dat je ook op verkorte (afgekorte) straatnaam moet kunnen zoeken. Het gaat hier fout op de "ln" (van laan), want zoeken op "baron vd oyelaan voorschoten" levert wel resultaat.

**Comment by fsamwel** [comment]
@CathyDingemanse is dat gewenste functionaliteit?

@strijm is dit mogelijk?

**Comment by NicoleKortoomsBAG** [comment]
De zoekfunctionaliteit is op dit moment geïmplementeerd op basis van de bestaande zoekfunctionaliteit van de locatieserver van PDOK. Deze ondersteunt dit niet.

**Comment by CathyDingemanse** [comment]
> De zoekfunctionaliteit is op dit moment geïmplementeerd op basis van de bestaande zoekfunctionaliteit van de locatieserver van PDOK. Deze ondersteunt dit niet.

Dit komt natuurlijk uit de BAG zelf, of niet? Als het niet kan, dan kan het niet.

**Comment by NicoleKortoomsBAG** [comment]
De BAG zelf registreert geen verkorte namen. Kort door de bocht gezegd wordt de naam, als deze langer is dan 24 tekens, verkort volgens de NEN 5825 op het moment dat hij wordt opgevraagd. 
Er kan heel veel, maar dit sluit technisch gezien niet aan bij de implementatie op dit moment en is in ieder geval niet zomaar gedaan.

**Comment by fsamwel** [comment]
@CathyDingemanse zal ik het issue sluiten? Het is m.i. een klein dingetje, dat je een laan niet kan vinden met de afkorting "ln". Zou geen reden moeten zijn de hele implementatie overhoop te halen of ingewikkelde dingen te doen om dit mogelijk te maken.

**Comment by CathyDingemanse** [comment]
Ja prima.
