### ISSUE TITLE
charset opnemen in Content-Type

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#104]
De antwoorden van de API kunnen diakrieten bevatten. Dus is het goed om de gebruikte tekenset op te nemen in de response header content-type: "application/hal+json;charset=UTF-8"

**Comment by strijm** [comment]
@JohanBoer  verander jij dit in de yaml?

**Comment by strijm** [comment]
@JohanBoer, m.i. kan dit issue gesloten worden en hoeft de API spec niet aangepast te worden. De JSON RFC (https://tools.ietf.org/html/rfc8259#page-11) zegt hierover (laatste zin van de sectie): 

> Note:  No "charset" parameter is defined for this registration.
>       Adding one really has no effect on compliant recipients.

Het toevoegen van de charset heeft dus geen effect.

Deze specificatie vervangt rfc7159 en daarmee rfc4627. Die laatste is de
specificatie van media type application/json (https://tools.ietf.org/html/rfc4627) en daarin is de default al gespecificeerd op UTF-8.

**Comment by fsamwel** [comment]
@JohanBoer en @strijm mee eens, ik werd hier ook op geattendeerd door @rhengeveld bij vergelijkbaar [issue](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/448) in BRK. Default voor json moet zijn UTF-8. Dus is opnemen charset: UTF-8 niet nodig.
