### ISSUE TITLE
Het opnemen van velden als required die door de provider ALTIJD (en onconditioneel) geleverd worden, maakt de API minder evolvable

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#109]
# Impediment 

Sommige properties worden altijd geleverd door het Kadaster. De elementen die dat betreft moeten echt niet als required worden opgenomen in de OAS, omdat dit  gevolgen heeft voor de evolvability van de API. 
Je kunt met optionele velden altijd besluiten iets niet meer te leveren zonder dat je het contract breekt. De beslissing om een aantal velden required te maken vermindert de evolvability. Aangezien er al getwijfeld werd aan de impact van required op het gedrag van de consumer (die negeert het gewoon), stel ik voor om de velden optioneel te maken. 
Je kunt ze als provider natuurlijk wel gewoon altijd leveren, en daarbij de fields parameter negeren.

Dit gedrag is beschreven in de design decisions. Ook in de description opnemen?

**Comment by lennartvanbergen-kadaster** [comment]
Het voorstel was om velden die altijd geleverd worden wel als required op te nemen. Dit heeft waarde voor de ontwikkelaar, omdat deze weet dat deze altijd in het antwoord zitten. 

Deze design beslissing wordt niet gedragen door mij, en ik heb expliciet aangegeven dat deze uitkomst niet de uitkomst van het overleg mocht worden, waar ik helaas niet bij kon zijn.

**Comment by strijm** [comment]
Volgens mij kan dit issues worden gesloten. Door het toepassen van de fields parameter kan een gebruiker zelf bepalen welke gegevens van een resource wel en niet geleverd moeten worden, daarmee ontstaat weliswaar het risico dat gegevens minder context krijgen en daardoor verkeerd geïnterpreteerd kunnen worden. Het verkeerd gebruik of het evt. foutief interpreteren van gegevens zijn verantwoording van de gebruiker. De gebruiker zal kennis moeten nemen van de BAG catalogus 2018 om dit te voorkomen. 
Door het toepassen van de fields parameter moeten properties wel optioneel zijn. Bovendien staat deze implementatie inmiddels in productie. Het strikter maken van properties door deze required te maken, zou een breaking change veroorzaken, wat in dit stadium niet wenselijk is.
