### ISSUE TITLE
Als PO wil ik dat in onderzoek bij adres op attribuut niveau wordt gedefinieerd

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#110]
...zodat afnemers hierover goed worden geïnformeerd.

InOnderzoek van adres  is nu op als een boolean op de adres resource gedefinieerd, als ‘let op’, niet als aggregatie. De betekenis/description is: let op, er is sprake van dat er iets in onderzoek is, wil je weten welke, zie de HaL-link.

Deze beslissing was een compromis nav in de discussie over dat alleen attributen van de resource zelf in onderzoek kunnen worden gezet ipv de attributen uit "onderliggende resources" (niet RESTful). De booleon op resource niveau was toen het RESTFUL alternatief. Later is afgesproken dat de domeinsdeskundige een mapping zou maken. Wat mij betreft kunnen we voor het woonplaats dilemma iets anders verzinnen dan een boolean. @Pieter, een enumeratie, waarbij voor alle onderzoekssituaties een mooie waarde wordt gemaakt? 

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by JohanBoer** [comment]
Tijdens de sessie van 02-04-2020 is door Pieter de volgende mapping voor MogelijkOnjuist indicatoren opgeleverd voor de resource Adres :

Attribuut in de BAG | Mogelijk onjuist adresAPI
-- | --
Naam woonplaats | Naam woonplaats   mogelijk onjuist
Status woonplaats | Woonplaats bestaat   mogelijk niet
Naam openbare   ruimte | Straatnaam   mogelijk onjuist
Status openbare   ruimte | Straat bestaat   mogelijk niet
Ligt in   gerelateerde woonplaats | Mogelijk verkeerde   woonplaats gebruikt
Huisnummer | Huisnummer   mogelijk onjuist
Huisletter | Huisletter   mogelijk onjuist
Huisnummertoevoeging | Huisnummertoevoeging   mogelijk onjuist
Postcode | Postcode mogelijk   onjuist
Status   nummeraanduiding | Adres bestaat   mogelijk niet
Ligt in   gerelateerde woonplaats | Mogelijk verkeerde   woonplaats gebruikt
Ligt aan   gerelateerde openbare ruimte | Mogelijk verkeerde   straat gebruikt

**Comment by JohanBoer** [comment]
Waar we op andere plaatsen alleen de property-namen gebruiken om dat die in de groep MogelijkOnjuist staan gebruiken we hier ook andere betekenissen (Zoals woonplaatsBestaatNiet). 

Dat betekent dat we een mix krijgen van property-namen die overeenkomen met een property uit het adres (en mogelijkOnjuist kunnen zijn) en properties die wat betekenisvoller zijn. 

Dit geldt alleen voor het Adres....

**Comment by fsamwel** [comment]
mijn voorstel zou zijn wel de propertynamen uit de resource te gebruiken. Alleen zijn sommigen daarvan (straat en woonplaats) een gegevensgroep:
korteNaam << Mogelijk verkeerde straat gebruikt
straat << Mogelijk verkeerde straat gebruikt
- naam << Straatnaam mogelijk onjuist
- status << Straat bestaat mogelijk niet
huisnummer << Huisnummer mogelijk onjuist
huisletter << Huisletter mogelijk onjuist
huisnummertoevoeging << Huisnummertoevoeging mogelijk onjuist
postcode << Postcode mogelijk onjuist
woonplaats
- naam << Naam woonplaats mogelijk onjuist
- status << Woonplaats bestaat mogelijk niet
- relatie << Mogelijk verkeerde woonplaats gebruikt
nummeraanduidingIdentificatie << Adres bestaat mogelijk niet
openbareRuimteIdentificatie << Mogelijk verkeerde straat gebruikt
woonplaatsIdentificatie << Mogelijk verkeerde woonplaats gebruikt
openbareruimte  << Mogelijk verkeerde straat gebruikt
nummeraanduiding << Adres bestaat mogelijk niet
woonplaats << Mogelijk verkeerde woonplaats gebruikt

Ik heb hier zowel de identificaties als de _links opgenomen. Is dat nodig/gewenst?

Je kan nog overwegen in geval van "Adres bestaat mogelijk niet" (Status nummeraanduiding) alle nummeraanduidingattributen (postcode, huisnummer, huisletter, huisnummertoevoeging) op true te zetten, of zelfs alle properties (als het adres niet bestaat, bestaan de relaties naar openbare ruimte en woonplaats ook niet). Je zou ook in mogelijkOnjuist self op kunnen nemen.

**Comment by JohanBoer** [comment]
Volgens mij is in #136 een voorstel gedaan hoe we hiermee omgaan. Als dat Pull request gemerged wordt kan deze geclosed worden.
