### ISSUE TITLE
Openstaande punten n.a.v. pull request #108

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#111]
- Design Decision : ## TypeAdresseerbaarObject is uit nummeraanduiding verwijderd
Moet beter toegelicht worden of verwijderd worden. 

- Voorstel Melvin voor componenten .....Hal   en .....HalBasis 
 
      allOf:
      - $ref: '#/components/schemas/Adres'
      - object:
        properties:
          _links:
             $ref: '#/components/schemas/Adres_links'
    Nu in gebruik en voorstel Johan : 

      allOf:
      - $ref: '#/components/schemas/Adres'
      - properties:
          _links:
             $ref: '#/components/schemas/Adres_links'

**Comment by fsamwel** [comment]
> Design Decision : ## TypeAdresseerbaarObject is uit nummeraanduiding verwijderd
Moet beter toegelicht worden of verwijderd worden.

Is dit een ontwerpbeslissing? Hoezo is type adresseerbaar object een eigenschap van een nummeraanduiding? Dit is een eigenschap van een gerelateerde resource (adresseerbaar object) die redundant is opgenomen in de nummeraanduiding. En is dus geen eigenschap van de nummeraanduiding zelf.

Wat betreft het gebruik object bij een allOf: Voor Swagger (OAS3) is type object default, dus daarvoor hoef je het niet op te nemen. Wanneer dit code generatie issues geeft, moeten we het toch maar opnemen. Melvin kan dat bepalen.
Bij andere componenten nemen we ook type: object op, dus waarom niet hier ook?

Zoals het staat met - object is denk ik niet correct. Dat moet zijn - type: object

**Comment by JohanBoer** [comment]
> Is dit een ontwerpbeslissing? Hoezo is type adresseerbaar object een eigenschap van een nummeraanduiding? Dit is een eigenschap van een gerelateerde resource (adresseerbaar object) die redundant is opgenomen in de nummeraanduiding. En is dus geen eigenschap van de nummeraanduiding zelf.

Volgens mij hebben we besloten op het typeAdresseerbaarObject niet op te nemen in de resource Nummeraanduiding terwijl deze wel in het object Nummeraanduiding staat. Dat typeAdresseerbaarObject een redundant element is in het object Nummeraanduiding is daarvoor een meer dan uitstekend argument. Blijft staan dat het niet opnemen van typeAdresseerbaarObject een ontwerpbeslissing is. Als we deze beslissing te triviaal vinden om te docuemntere vind ik het ook best. 

> Wat betreft het gebruik object bij een allOf: Voor Swagger (OAS3) is type object default, dus daarvoor hoef je het niet op te nemen. Wanneer dit code generatie issues geeft, moeten we het toch maar opnemen. Melvin kan dat bepalen.
> Bij andere componenten nemen we ook type: object op, dus waarom niet hier ook?

Hier heb ik het in een lichtgrijs verleden met Melvin over gehad. Ik meen mij te herinneren dat het toevoegen van -type: "object"  juist een code-generatie-issue opleverde, maar dat weet ik niet zeker meer. In ieder geval heb ik bij alle allOf constructies nu geen - type: object toegevoegd.
Ik kan het overal toevoegen als dat meerwaarde heeft, maar die meerwaarde betwijfel ik. Wat mij betreft heeft @MelvLee daar het laatste woord.

**Comment by fsamwel** [comment]
naast dat type: object default is, is er bij een allOf al gedefinieerd dat het een object is in het object dat je hergebruikt met de $ref. Het is dus dubbel overbodig
