### ISSUE TITLE
Invalid API Key

### ISSUE THREAD

**Issue by anikbin** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#112]
Sinds gisteren ben ik achter gekomen, dat de communicatie met Haal Centraal BAG bevragen niet meer werkt.
Ik gebruik de volgende API key, maar ik krijg de foutmelding (Invalid API Key)
 
o	API key  
     •	header: x-api-key
     •	waarde: l782d424a28a3b4fec8b96917288aa887a
Is inmiddels de Key gewijzigd? 
    Indien ja, kan ik hem ontvangen?
    Indien nee, kunnen jullie de oorzaak van de melding bekend maken?
Alvast bedankt voor jullie reactie
 
Met vriendelijke groet,
Aida Nikbin

**Comment by strijm** [comment]
Deze API key was alleen geldig voor de HC fieldlab.
Als HC hiermee akkoord is, dan kunnen we een API key maken voor de betreffende organisatie.

**Comment by CathyDingemanse** [comment]
Ja, daarmee zijn wij akkoord. @anikbin van welke organisatie ben je? Dan plaats ik je op de lijst om een permanente API key te ontvangen voor de testomgeving en evt. voor de P omgeving.

Wil jij ook een API key voor jouw organisatie? Stuur mij een mail: cathy.dingemanse@denhaag.nl

**Comment by anikbin** [comment]
Mijn productmanager denkt, dat ooit voor een andere afdeling de APIkey voor onze organisatie (NedGraphics B.V.) is aangevraagd. 
Ik ben bezig om deze key te vinden. Als het niet zo is, zal ik naar Cathy de e-mail met de aanvraag voor de key toesturen. Nogmaals bedankt voor jullie snelle reactie

**Comment by CathyDingemanse** [comment]
E-mailadres is ontvangen. Ik zorg dat je zsm een key krijgt!

**Comment by JohanBoer** [comment]
@CathyDingemanse  Kan deze gesloten worden ?

**Comment by anikbin** [comment]
Ik heb nog geen nieuw Key ontvangen

**Comment by CathyDingemanse** [comment]
Irina heeft een key ontvangen van het kadaster als het goed is. @anikbin klopt dat?
Kan deze worden gesloten?

**Comment by anikbin** [comment]
Ik heb net met Irena gecontroleerd. Inderdaad heeft zij een key ontvangen. Cathy en Johan, bedankt voor jullie help. deze kan worden gesloten.

**Comment by CptChaos** [comment]
Nu ben ik een buitenstaander, maar wellicht een idee de API-key verwijderen, nu het issue opgelost is en eigenlijk sowieso beter om API-keys te maskeren, uit veiligheidsoverwegingen.
