### ISSUE TITLE
Als PO wil ik kortere descriptions bij endpoints

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#113]
Graag de descriptions naast de endpoints weghalen, deze zitten er nog in.
Graag ook het info endpoint weghalen. 
Beiden zijn niet consistent met de andere API's.

adressen/zoek
Graag wijzigen in: 
free query zoeken van adressen met postcode, woonplaats, straatnaam, huisnummer, huisletter, huisnummertoevoeging. Delen van de adressen in het antwoord matchen exact met jouw invoer. Je vindt een adres door de zoekresultaatidentificatie uit het antwoord te gebruiken in get/adressen.

/adressen
Graag wijzigen in: 
Vind een actueel adres met de identificatie van het zoekresultaat uit de operatie get /adressen/zoek.  Gebruik de fields parameter als je alleen specifieke velden je in het antwoord wil zien, zie {link naar field feature}. Gebruik de expand parameter als je het antwoord wil uitbreiden met (delen van) de gerelateerde resources nummeraanduiding, woonplaats en openbare ruimte, zie {link naar expand feature}.

/adressen​/{nummeraanduidingidentificatie}
Graag wijzigen in: 
Raadpleeg een actueel adres met de nummeraanduiding identificatie. 
Gebruik de fields parameter als je alleen specifieke velden je in het antwoord wil zien, zie {link naar field feature}. Gebruik de expand parameter als je het antwoord wil uitbreiden met (delen van) de gerelateerde resources nummeraanduiding, woonplaats en openbare ruimte, zie {link naar expand feature}.

/adresseerbareobjecten/{identificatie}
Graag wijzigen in: 
Raadpleeg een actueel adresseerbaar object met de identificatie. Dit is de identificatie van een verblijfsobject, ligplaats of standplaats.
Gebruik de fields parameter als je alleen specifieke velden je in het antwoord wil zien, zie {link naar field feature}. Gebruik de expand parameter als je het antwoord wil uitbreiden met (delen van) de gerelateerde resources adres en pand, zie {link naar expand feature}.

/adresseerbareobjecten
Graag wijzigen in: 
Zoek actuele adresseerbaar objecten (verblijfsobjecten, standplaatsen of ligplaatsen) met een nummeraanduiding identificatie of pand identificatie. 
Gebruik de fields parameter als je alleen specifieke velden je in het antwoord wil zien, zie {link naar field feature}. Gebruik de expand parameter als je het antwoord wil uitbreiden met (delen van) de gerelateerde resources adres en pand, zie {link naar expand feature}.

/woonplaatsen/{identificatie}
Graag wijzigen in: 
Raadpleeg een actuele woonplaats met de identificatie. Een woonplaats is een gedeelte van het grondgebied van de gemeente met een naam. Gebruik de fields parameter als je alleen specifieke velden je in het antwoord wil zien, zie {link naar field feature}. Gebruik de expand parameter als je het antwoord wil uitbreiden met de gerelateerde resource geometrie, zie {link naar expand feature}.

/openbareruimten/{identificatie}
Graag wijzigen in:
Raadpleeg een actuele openbare ruimte met de identificatie. Een openbare ruimte is een buitenruimte met een naam die binnen één woonplaats ligt, bijvoorbeeld een straat of een plein. Gebruik de fields parameter als je alleen specifieke velden je in het antwoord wil zien, zie {link naar field feature}

/nummeraanduidingen/{identificatie}
Graag wijzigen in:
Raadpleeg actuele nummeraanduidingen. Een nummeraanduiding is een postcode, huisnummer met evt een huisletter en -toevoeging die hoort bij een verblijfsobject, een standplaats of een ligplaats. Gebruik de fields parameter als je alleen specifieke velden je in het antwoord wil zien, zie {link naar field feature}

/panden/{identificatie}
Graag wijzigen in:
Raadpleeg actuele panden. Een pand is een bouwkundige, constructief zelfstandige eenheid die direct en duurzaam met de aarde is verbonden en betreedbaar en afsluitbaar is. Gebruik de fields parameter als je alleen specifieke velden je in het antwoord wil zien, zie {link naar field feature}.  

/panden
Graag wijzigen in:
Zoek actuele panden met de identificatie van een nummeraanduiding of adresseerbaar object. 
Gebruik de fields parameter als je alleen specifieke velden je in het antwoord wil zien, zie {link naar field feature}. 

post/panden
Graag wijzigen in:
Zoek actuele panden met een geometrische punt. Gebruik de fields parameter als je alleen specifieke velden je in het antwoord wil zien, zie {link naar field feature}.

**Comment by CathyDingemanse** [comment]
Descriptions endpoints aangepast. @fsamwel wil jij reviewen?

**Comment by fsamwel** [comment]
@CathyDingemanse moet er bij /adressen/zoek niet ook iets gezegd worden over het antwoord en hoe die gebruikt kan worden om het adres op te halen? (al dan niet via verwijzing naar een feature)

**Comment by fsamwel** [comment]
@CathyDingemanse 
> als je het antwoord wil uitbreiden met (delen van) de resources

hierin opnemen dat het om "gerelateerde" resources gaat?
> als je het antwoord wil uitbreiden met (delen van) de gerelateerde resources

**Comment by fsamwel** [comment]
Bij /woonplaatsen/{identificatie} ontbreekt verwijzing naar fields en expand (geometrie)

**Comment by CathyDingemanse** [comment]
> @CathyDingemanse
> 
> > als je het antwoord wil uitbreiden met (delen van) de resources
> 
> hierin opnemen dat het om "gerelateerde" resources gaat?
> 
> > als je het antwoord wil uitbreiden met (delen van) de gerelateerde resources

Yes, pas ik aan.

**Comment by fsamwel** [comment]
Bij /openbareruimten/{identificatie} ontbreekt verwijzing naar fields en expand (woonplaats)****

**Comment by fsamwel** [comment]
@CathyDingemanse Bij /panden en ​/panden​/{pandidentificatie} is nu een expand parameter opgenomen, en in het antwoord zit _embedded.adressen. Is nu niet opgenomen in de description. Hadden we niet afgesproken de adressen uit de embedded van panden te halen (zoeken van adressen op een pand gaat door zoeken van adressen op pandidentificatie)?

**Comment by fsamwel** [comment]
Bij post/panden staat "Zoek actuele panden **met met** een geometrische punt. " Met staat er dubbel.

**Comment by CathyDingemanse** [comment]
> @CathyDingemanse moet er bij /adressen/zoek niet ook iets gezegd worden over het antwoord en hoe die gebruikt kan worden om het adres op te halen? (al dan niet via verwijzing naar een feature)

done

**Comment by CathyDingemanse** [comment]
> Bij /woonplaatsen/{identificatie} ontbreekt verwijzing naar fields en expand (geometrie)

done

**Comment by JohanBoer** [comment]
Deze was in Done beland. Dat is volgens mij per ongeluk gebeurd want volgens mij moet ik deze descriptions nog in de specificatie opnemen.

**Comment by CathyDingemanse** [comment]
@JohanBoer ik heb alle descriptions uit issue #130 (die was nl. ook gesloten zonder te zijn doorgevoerd:-)) naar deze issue gekopieerd. Deze descriptions dus graag doorvoeren!

**Comment by fsamwel** [comment]
@CathyDingemanse je hebt nog niks gedaan met de volgende opmerkingen. Dus daar is niks voor gewijzigd in wat nu is doorgevoerd.
Is dat een keuze of nog te doen (dus blokkerend voor doorvoeren pull request #170?
- Bij /openbareruimten/{identificatie} ontbreekt verwijzing naar fields en expand (woonplaats)
- Bij post/panden staat "Zoek actuele panden met met een geometrische punt. " Met staat er dubbel.

**Comment by JohanBoer** [comment]
> Vind een actueel adres met de identificatie van het zoekresultaat uit de operatie get /adressen/zoek. Gebruik de fields parameter als je alleen specifieke velden je in het antwoord wil zien, zie {link naar field feature}. Gebruik de expand parameter als je het antwoord wil uitbreiden met (delen van) de gerelateerde resources nummeraanduiding, woonplaats en openbare ruimte, zie {link naar expand feature}.

Naast de zoekresultaatidentificatie kan je ook nog een adres zoeken op basis van pandidentificatie en adresseerbaarobjectidentificatie. Die ontbreken aan de description. Verder staat nu ook de nummeraanduidingidentificatie in de spec nog als query-parameter, maar die kan volgens mij weg. (is ook path parameter geworden. 

> /openbareruimten/{identificatie}
> Graag wijzigen in:
> Raadpleeg een actuele openbare ruimte met de identificatie. Een openbare ruimte is een buitenruimte met een naam die binnen één woonplaats ligt, bijvoorbeeld een straat of een plein.

Bij openbare ruimten is nu een embedded woonplaats gedefinieerd. Moet die weg of moet dit in de description opgenomen worden. Ook de fields parameter ontbreekt in de description (zie ook opmerking Frank)

> /nummeraanduidingen/{identificatie}
> Graag wijzigen in:
> Raadpleeg actuele nummeraanduidingen. Een nummeraanduiding is een postcode, huisnummer met evt een huisletter en -toevoeging die hoort bij een verblijfsobject, een standplaats of een ligplaats.

Bij nummeraanduidingen zijn de expand en fields parameters ook niet toegelicht. Nu hebben nummeraanduidingen ook adres, openbareRuimte en woonplaats in de embedded staan. 

> /panden/{identificatie}
> Graag wijzigen in:
> Raadpleeg actuele panden. Een pand is een bouwkundige, constructief zelfstandige eenheid die direct en duurzaam met de aarde is verbonden en betreedbaar en afsluitbaar is. Gebruik de fields parameter als je alleen specifieke velden je in het antwoord wil zien, zie {link naar field feature}.

Moet dit niet zijn "Raadpleeg een actueel pand " ?

**Comment by CathyDingemanse** [comment]
@JohanBoer, sommige van mijn wijzigingen waren niet opgeslagen. Alle wijzigingen na jouw aanpassingen zijn hieronder geformuleerd:

/panden
Graag wijzigen in:
Zoek actuele panden met de identificatie van een nummeraanduiding of adresseerbaar object.
Gebruik de fields parameter als je alleen specifieke velden je in het antwoord wil zien, zie {link naar field feature}.

/openbareruimten/{identificatie}
Graag wijzigen in:
Raadpleeg een actuele openbare ruimte met de identificatie. Een openbare ruimte is een buitenruimte met een naam die binnen één woonplaats ligt, bijvoorbeeld een straat of een plein. Gebruik de fields parameter als je alleen specifieke velden je in het antwoord wil zien, zie {link naar field feature}

/nummeraanduidingen/{identificatie}
Graag wijzigen in:
Raadpleeg actuele nummeraanduidingen. Een nummeraanduiding is een postcode, huisnummer met evt een huisletter en -toevoeging die hoort bij een verblijfsobject, een standplaats of een ligplaats. Gebruik de fields parameter als je alleen specifieke velden je in het antwoord wil zien, zie {link naar field feature}

/adressen
Vind een actueel adres met de identificatie van het zoekresultaat uit de operatie get /adressen/zoek, de pandidentificatie of de adresseerbaarobjectidentificatie. Gebruik de fields parameter als je alleen specifieke velden je in het antwoord wil zien, zie {link naar field feature}. Gebruik de expand parameter als je het antwoord wil uitbreiden met (delen van) de gerelateerde resources nummeraanduiding, woonplaats en openbare ruimte, zie {link naar expand feature}.

/panden/{identificatie}
Raadpleeg een actueel pand. Een pand is een bouwkundige, constructief zelfstandige eenheid die direct en duurzaam met de aarde is verbonden en betreedbaar en afsluitbaar is. Gebruik de fields parameter als je alleen specifieke velden je in het antwoord wil zien, zie {link naar field feature}.

**Comment by CathyDingemanse** [comment]
> 
>  Verder staat nu ook de nummeraanduidingidentificatie in de spec nog als query-parameter, maar die kan volgens mij weg. (is ook path parameter geworden.
> 
Klopt, weghalen idd.
> > /nummeraanduidingen/{identificatie}
> > Graag wijzigen in:
> > Raadpleeg actuele nummeraanduidingen. Een nummeraanduiding is een postcode, huisnummer met evt een huisletter en -toevoeging die hoort bij een verblijfsobject, een standplaats of een ligplaats.
> 
> Bij nummeraanduidingen zijn de expand en fields parameters ook niet toegelicht. Nu hebben nummeraanduidingen ook adres, openbareRuimte en woonplaats in de embedded staan.
Dit is niet correct. Nummeraanduidingen, openbare ruimten en woonplaatsen zijn embedded opgenomen bij het adres om de "adresdetails" mee te kunnen laden die voor sommige afnemers relevant zijn (zie GOALS canvas). Omdat het geen subresources van adres zijn, hebben zij een apart endpoint gekregen. Echter, er is geen behoefte vastgesteld om op hun beurt ook weer embedded resources mee te laden. Expand parameter is dus ook niet gedefinieerd in de descriptions.
@JohanBoer embedded resources bij nummeraanduidingen weghalen.
>

**Comment by NicoleKortoomsBAG** [comment]
vraagje, ik kan het niet meer vinden.
Staat er nu nog ergens in de api dat hier huidig wordt geleverd, zijnde actueel zonder eindstatussen?
