### ISSUE TITLE
Als PO wil ik ofwel bij alle HC API's een get info endpoint, of bij geen enkele

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#114]
...zodat consistentie voor de gebruiker binnen Haal Centraal wordt bereikt

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by fsamwel** [comment]
staat in NL-API strategie niet dat je op het endpoint ook de yaml beschikbaar moet stellen? Dan voegt het info endpoint niks toe

**Comment by strijm** [comment]
De specificatie zal alleen via de endpoint beschikbaar worden gemaakt.
