### ISSUE TITLE
AdresseerbaarObjectType in de resource Adresseerbaar object moet "type" worden

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#115]
...zodat [vul aan].

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by JohanBoer** [comment]
Johan Checked

**Comment by lennartvanbergen-kadaster** [comment]
In BAG catalogus 2.0 heeft dit gegeven: 

7.3.6.a: Beschrijving van het atribuut type adresseerbaar object
Naam type adresseerbaar object 

Het ontgaat me waarom deze naam perse anders moet worden. Lijkt me erg weinig waarde toevoegen en veroorzaakt wel inconsistenties, het introduceert een onnodige synoniem.

**Comment by JohanBoer** [comment]
In de context van de API en i het object wordt dit dan adresseerbaarObject.type Als je de naam niet aanpast wordt het in deze context adresseerbaarObject.adresseerbaarObjectType. In de software wordt deze property altijd in de conteext van het object aangeroepen en niet stand-alone. 
Derhalve is het dubbelop om de objectnaam in de propertynaam te herhalen. 

Aangepast in #137

**Comment by lennartvanbergen-kadaster** [comment]
De naam in de BAT catalogus is: type adresseerbaar object

Het is expliciet niet de bedoeling om namen aan te passen. En als dat nodig is, dan via het juiste beheerproces, vooraan in de keten. 

"dubbelop" is geen zwaarwegend argument, dat is smaak. 

Graag ongedaan maken.
