### ISSUE TITLE
Hoe maken we duidelijk dat de link naar bv. Pand bij Adresseerbaarobject mogelijk niet juist is. 

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#120]
Uit Pull request #118 
Bij de identificaties naar gerelateerde resources,  bij adresseerbaarObjecten panden en hoofdadres, hebben we zowel de identificatie als de relatie in _links. Hoe maken we duidelijk dat ook de link mogelijk niet klopt, en evt. het embedded adres of pand?

**Comment by JohanBoer** [comment]
Daar zou ook een indicator opgenomen kunnen worden. Ik denk dat we hiervoor ook aan Pieter een voorstel moeten vragen. Mogelijk is de de maaktDeelUitVanPand property in plaats van alleen Pandidentififcaties.  @strijm  kan jij deze bij Pieter beleggen?

**Comment by strijm** [comment]
Ik zal dit voorleggen aan Pieter. 
Naar mijn mening is het niet nodig om 3 verschillende MogelijkOnjuist properties te hebben m.b.t. hetzelfde gerelateerde object. Het zijn 3 verschillende representatievormen in een HAL object, nl.: 
1. een identificatie van een gerelateerd object
2. een URI naar een gerelateerd object onder _links
3. het gerelateerd object zelf onder _embedded
Als er één MogelijkOnjuist is voor de object identificatie, dan is dat toch voldoende om te weten dat hetzelfde object onder _links en _embedded ook mogelijk onjuist zijn? Die gegevens horen toch bij elkaar omdat het over hetzelfde gerelateerde object gaat?

**Comment by PieterDijkstraKadaster** [comment]
Het gaat steeds om hetzelfde gegeven in verschillende representaties. Inhoudelijk is het ID waarnaar verwezen wordt mogelijk onjuist. De relatie en het ID kunnen eigenlijk niet los van elkaar gezien worden. De relatie is de naam van de verwijzing en het ID is de inhoudelijke verwijzing. 

De inhoudelijke betekenis van mogelijk onjuist verschilt overigens per type relatie. Bij de (verplichte) relaties naar een pand, openbare ruimte, woonplaats betekent mogelijk onjuist dat er mogelijk naar een verkeerd object verwezen wordt. Deze relatie kan vervolgens ook aangepast worden. 

Bij de (verplichte) relatie naar een hoofdadres zit dit net even anders. Het gerelateerde hoofdadres(ID) mag namelijk niet worden gewijzigd. Het ID van een adresseerbaar object en het NummeraanduidingID van het gerelateerde hoofdadres zijn onlosmakelijke met elkaar verbonden.  Een eventueel verkeerd adres kan dus alleen opgelost worden door de gegevens van de nummeraanduiding te muteren zodat een ander adres ontstaat. 

Bij de relatie naar een nevenadres betekent mogelijk onjuist dat het bestaan van het nevenadres ter discussie staat.  Het nevenadres kan vervolgens ook ingetrokken worden. 

We zullen een becshrijving opstellen met per mogelijk onjuist gegeven de inhoudelijke betekenis hiervan.

**Comment by PieterDijkstraKadaster** [comment]
Ik heb de in onderzoekstabel uitgebreid met elk attribuut dat in onderzoek kan staan. De statussen zijn in dit overzicht terug te vinden. Zie de afbeelding hieronder en de bijlage: 

Toelichting bij het onderscheid tussen verplichte en optionele velden:
Bij verplichte attributen kan uitsluitend een andere waarde geregistreerd worden. 
Bij optionele velden kan naast het registreren van een andere waarde ook het toevoegen of verwijderen van de waarde mogelijk.  



![image](https://user-images.githubusercontent.com/22903349/78990063-b813a600-7b35-11ea-8271-b6cead630edc.png)
[betekenis in onderzoek per attribuut.xlsx](https://github.com/VNG-Realisatie/Haal-Centraal-BAG-bevragen/files/4461474/betekenis.in.onderzoek.per.attribuut.xlsx)

**Comment by CathyDingemanse** [comment]
Ha Pieter, top! 
Ik stel voor om dit te verwerken in alle resources op basis van een feature. 
In deze feature wordt dan bovenstaand voorstel gemapt op op de attributen van onze resources met een toelichting, waar we jouw betekenis en toelichting in verwerken (in sommige gevallen zijn de toelichtingen niet helemaal relevant, bijvoorbeeld in geval van statussen die de resource beëindigen (want die leveren we niet).

**Comment by PieterDijkstraKadaster** [comment]
Hallo Cathy,

Het klopt inderdaad dat niet elke toelichting relevant is voor HC, maar ik heb er (ook voor onszelf) toch maar een totaaloverzicht gemaakt.

**Comment by PieterDijkstraKadaster** [comment]
Ik zie dat ik één attribuut gemist heb. (type adresseerbaar object bij nummeraanduiding): 

Hierbij alsnog:

Nummeraanduiding | Type adresseerbaar object | Verwijzing naar het type   adressserbaar object is mogelijk onjuist | Mogelijk is het verkeerde type   adresseerbaar object gekopppeld. Deze indicatie heeft daarmee feitelijke   betrekking op het gerelateerde adresseerbare object.      Mogelijk is een standplaats ten onrechte afgebakend als verblijfsobject.   Het type Adresseerbaarobject kan echter niet worden aangepast. Dit betekent   dat een eventuele aanpassing doorgevoerd wordt door een nieuw adresseerbaar object (met een nieuw nummeraanduidingID) op te voeren.
-- | -- | -- | --

En een nieuw totaaloverzicht: 

[betekenis in onderzoek per attribuut.xlsx](https://github.com/VNG-Realisatie/Haal-Centraal-BAG-bevragen/files/4474937/betekenis.in.onderzoek.per.attribuut.xlsx)

**Comment by fsamwel** [comment]
@PieterDijkstraKadaster op sommige plekken, met name bij statussen wordt nu een behoorlijke opsomming gemaakt van mogelijke oorzaken. Zou het mogelijk zijn in een bericht de specifiekere oorzaak op te nemen in het antwoord?
Bijvoorbeeld als in een Pand de status in onderzoek is, weet je denk ik wat de huidige status is (wat de lijst korter maakt). Maar weet je (in de LVBAG) ook welke daarbinnen van toepassing is?
Dus als Pand.status="Bouwvergunning verleend", kan je dan ook aangeven dat in dit geval "mogelijk is de bouw al gereed" van toepassing is?

We zouden namelijk het mogelijkOnjuist duidelijker en eenvoudiger kunnen maken (voor de gebruiker) door naast de booleans (of andere vorm) ook een toelichting op te nemen, waarin deze specifieke uitleg opgenomen is.

```
"status": "Bouwvergunning verleend",
"mogelijkOnjuist": {
   "status": true,
  "toelichting": "mogelijk is de bouw al gereed"
}
```

**Comment by PieterDijkstraKadaster** [comment]
@fsamwel: het lastige bij de statussen is dat er per status meerdere scenario's mogelijk zijn. Bij huidige statussen is het nogal een verschil of het een verkeerde huidige status is, of dat het object niet meer bestaat. 
Ik kan bij elke status wel het meest voordehandliggende sccenario beschrijven in de toelichting, maar dat is dan niet in alle gevallen juist.
