### ISSUE TITLE
We willen descriptions consumervriendelijk en to-the-point maken

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#121]
M.i moeten de descriptions in het algemeen "gebruiksvriendelijker" opgesteld worden.

@fsamwel heeft op PR #108 feedback gegeven dat door een procedurefoutje tussen wal en schip is beland. Een deel daarvan ging over descriptions. 

api-specificatie/openapi.yaml
@@ -145,67 +133,62 @@ paths:
        Huidige gegevens zijn actuele gegevens die geen eind status hebben, zoals 'Naamgeving ingetrokken'.
        Als de nummeraanduiding is ingetrokken, dan levert een bevraging geen adres op.
        Relaties met adresseerbaarobject (ligplaats, standplaats of verblijfsobject) en als het adresseerbaare object een verblijfsobject betreft het/de gerelateerde pand(en).
  @fsamwel
fsamwel Member Pending
ik begrijp deze zin niet

api-specificatie/openapi.yaml
@@ -145,67 +133,62 @@ paths:
        Huidige gegevens zijn actuele gegevens die geen eind status hebben, zoals 'Naamgeving ingetrokken'.
        Als de nummeraanduiding is ingetrokken, dan levert een bevraging geen adres op.
        Relaties met adresseerbaarobject (ligplaats, standplaats of verblijfsobject) en als het adresseerbaare object een verblijfsobject betreft het/de gerelateerde pand(en).
        Parameter keuzeItemIdentificatie bevat identificatie van een gekozen item verkregen uit een zoek-operatie."
        Parameter zoekresultaatidentificatie bevat identificatie van een gekozen item verkregen uit een zoek-operatie."
  @fsamwel
fsamwel Member Pending
zou je in de description kunnen toevoegen waarop expand mag worden? Idem voor alle andere endpoints met expand parameter

api-specificatie/openapi.yaml
@@ -145,67 +133,62 @@ paths:
        Huidige gegevens zijn actuele gegevens die geen eind status hebben, zoals 'Naamgeving ingetrokken'.
        Als de nummeraanduiding is ingetrokken, dan levert een bevraging geen adres op.
        Relaties met adresseerbaarobject (ligplaats, standplaats of verblijfsobject) en als het adresseerbaare object een verblijfsobject betreft het/de gerelateerde pand(en).
        Parameter keuzeItemIdentificatie bevat identificatie van een gekozen item verkregen uit een zoek-operatie."
        Parameter zoekresultaatidentificatie bevat identificatie van een gekozen item verkregen uit een zoek-operatie."
  @fsamwel
fsamwel Member Pending
De verschillende zinnen van de description staan in de yaml op verschillende regels. Maar in Swagger worden ze wel achter elkaar getoond. Het wordt duidelijker wanneer ook in Swagger de verschillende onderwerpen in de description in een nieuwe alinea beginnen.

api-specificatie/openapi.yaml
@@ -434,67 +402,62 @@ paths:
      summary: Raadpleeg Woonplaats met een woonplaats identificatie
      description: "Raadpleeg een Woonplaats met en woonplaats identificatie
        Geleverd worden de actuele gegevens van een woonplaats en het gerelateerde adres.
        Parameter woonplaatsIdentificatie bevat de 4 cijferige identificatie van een woonplaats."
        Parameter woonplaatsidentificatie bevat de 4 cijferige identificatie van een woonplaats."
  @fsamwel
fsamwel Member Pending
kan deze zin niet weg? Je hoeft in de description niet te noemen welke parameters er zijn en al helemaal niet hoe die technisch gedefnieerd zijn (4 cijfers lang)

api-specificatie/openapi.yaml
  description: >-
    "Dit is de Haal Centraal BAG Bevragen API."
    "Dit is de huidige bevragingen API."
  @fsamwel
fsamwel Member Pending
Wat betekent dat? "huidige bevragingen API"? Kan je hier niet beter uitleggen dat deze api alleen actuele gegevens levert (en wat dat betekent)?

api-specificatie/openapi.yaml
@@ -434,67 +402,62 @@ paths:
      summary: Raadpleeg Woonplaats met een woonplaats identificatie
      description: "Raadpleeg een Woonplaats met en woonplaats identificatie
        Geleverd worden de actuele gegevens van een woonplaats en het gerelateerde adres.
  @fsamwel
fsamwel Member Pending
Is "en het gerelateerde adres" relevant? Van belang is dat het alleen actuele gegevens levert. Maar dat kan eigenlijk beter in de description van de api worden toegevoegd (zie mijn comment bij regel 18).

api-specificatie/openapi.yaml

     woonplaatsIdentificatie:
    woonplaatsidentificatie:
      description: Identificatie van een object uit de BAG. Deze is 4 lang bij een woonplaats en 16 lang bij de andere objecten.
  @fsamwel
fsamwel Member Pending
"en 16 lang bij andere objecten"?

api-specificatie/openapi.yaml
      description: Identificatie van een object uit de BAG. Deze is 4 lang bij een woonplaats en 16 lang bij de andere objecten.
      name: woonplaatsIdentificatie
      name: woonplaatsidentificatie
      in: path
      required: true
      schema:
        description: 'Deze wordt gebruikt in de operation, bv. /woonplaatsen/0123. Waarde: 0001-9999.'
  @fsamwel
fsamwel Member Pending
Swagger negeert deze description, toont alleen die van regel 883. Kan dus weg.

@@ -504,67 +467,59 @@ paths:
      summary: Raadpleeg openbareruimte met een openbareruimte identificatie
      description: "Raadpleeg een openbareruimte met en openbareruimte identificatie
        Geleverd worden de actuele gegevens van een openbareruimte evt. met gerelateerde woonplaats en adres.
        Parameter openbareRuimteIdentificatie bevat de 16 cijferige identificatie van een openbareruimte."
        Parameter openbareruimteidentificatie bevat de 16 cijferige identificatie van een openbareruimte."
  @fsamwel
fsamwel Member Pending
Volgens mij is alleen eerste zin van de description relevant. (zie eerdere opmerkingen bij woonplaatsen)

api-specificatie/openapi.yaml
@@ -504,67 +467,59 @@ paths:
      summary: Raadpleeg openbareruimte met een openbareruimte identificatie
      description: "Raadpleeg een openbareruimte met en openbareruimte identificatie
  @fsamwel
fsamwel Member Pending
en=een
  @fsamwel
fsamwel Member Pending
of en=de

api-specificatie/openapi.yaml
@@ -574,67 +529,59 @@ paths:
      summary: Raadpleeg nummeraanduiding met een nummeraanduiding identificatie
      description: "Raadpleeg een nummeraanduiding met en nummeraanduiding identificatie
  @fsamwel
fsamwel Member Pending
en=een
  @fsamwel
fsamwel Member Pending
of en=de

api-specificatie/openapi.yaml
@@ -574,67 +529,59 @@ paths:
      summary: Raadpleeg nummeraanduiding met een nummeraanduiding identificatie
      description: "Raadpleeg een nummeraanduiding met en nummeraanduiding identificatie
        Geleverd worden de actuele gegevens van een nummeraanduiding evt. met gerelateerde woonplaats, openbare ruimte en adres.
        Parameter nummeraanduidingIdentificatie bevat de 16 cijferige identificatie van een nummeraanduiding."
        Parameter nummeraanduidingidentificatie bevat de 16 cijferige identificatie van een nummeraanduiding."
  @fsamwel
fsamwel Member Pending
alleen eerste zin is relevant. zie eerdere opmerking bij woonplaatsen

api-specificatie/openapi.yaml
@@ -644,65 +591,60 @@ paths:
      summary: Raadpleeg Pand met een pand identificatie
      description: "Raadpleeg een pand met de pand identificatie
        Geleverd worden de actuele gegevens van een pand evt. met gerelateerde verblijfsobjecten en adressen.
        Parameter pandIdentificatie bevat de 16 cijferige identificatie van een pand."
        Parameter pandidentificatie bevat de 16 cijferige identificatie van een pand."
      parameters:
  @fsamwel
fsamwel Member Pending
alleen eerste zin is relevant, plus benoemen van te expanden resources (maar dan graag iets duidelijker expand parameter daarbij noemen)

api-specificatie/openapi.yaml
@@ -722,134 +664,124 @@ paths:
      description: "Raadpleeg een pand met een geometrische locatie (punt).
        Geleverd worden de actuele gegevens van één of meer panden evt. met gerelateerde verblijfsobject en adres."

api-specificatie/openapi.yaml
        Parameter nummeraanduidingIdentificatie-query bevat de 16 cijferige identificatie van een nummeraanduiding.
        Parameter adresseerbaarObjectIdentificatie-query bevat de 16 cijferige identificatie van een ligplaats, standplaats of verblijfsobject"
      summary: Raadplegen van één of meer panden met een nummeraanduiding of adresseerbaarobject identificatie vekregen uit een zoek-operatie
      description: "Raadplegen van één of meer panden met een nummeraanduiding of adresseerbaarobject identificatie vekregen uit een zoek-operatie en indien gevraagd de gerelateerde verblijfsobjecten en het/de adres(sen).
  @fsamwel
fsamwel Member Pending
vekregen = verkregen
vekregen uit een zoek-operatie? welke zoekoperatie?

Duidelijk maken dat een van de twee parameters verplicht is
 @fsamwel

**Comment by CathyDingemanse** [comment]
Ik zal een nieuw voorstel doen. @Pieter, wil jij reviewen?

**Comment by JohanBoer** [comment]
Zie ook #113
