### ISSUE TITLE
pattern bij path-parameter woonplaatsidentificatie 

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#123]
.api-specificatie/openapi.yaml
      description: Identificatie van een object uit de BAG. Deze is 4 lang bij een woonplaats en 16 lang bij de andere objecten.
      name: woonplaatsIdentificatie
      name: woonplaatsidentificatie
      in: path
      required: true
      schema:
        description: 'Deze wordt gebruikt in de operation, bv. /woonplaatsen/0123. Waarde: 0001-9999.'
        type: string
        pattern: '[0-9]{3}[1-9]|[0-9]{2}[1-9][0-9]|[0-9][1-9][0-9]{2}|[1-9][0-9]{3}'
  @fsamwel
fsamwel Member Pending
wat is dit voor pattern? Woonplaats is toch 4 cijfers lang?
Dan pattern "[0-9]*" en maxLength=4 (zie eerdere opmerkingen Kayo bij BRP over scheiden maxLength en pattern). Overwegen of maxLength nodig is, i.v.m. evolvability.
api-specificatie/openapi.yaml

**Comment by strijm** [comment]
Het gespecificeerde pattern voldoet bij de omschrijving 0001-9999.
Het door Frank gesuggereerde pattern niet, die staat 0000 ook toe. In het geval dat op ID=0000 wordt gezocht zal er altijd een 404 optreden. De vraag is of dat het gewenste gedrag is en of het gebruikersvriendelijk is?

**Comment by fsamwel** [comment]
@strijm dus juiste patten is '[0-9]{3}[1-9]'?

**Comment by strijm** [comment]
Nee, want dan kan het laatste getal niet 0 zijn, maar er zijn natuurlijk wel woonplaatsen met een ID die eindigt op 0.
