### ISSUE TITLE
Als PO wil ik weten of de relatie van Pand en ADO met met hoofd en nevenadressen apart moeten worden weergeven.

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#126]
...zodat we dat in de OAS spec kunnen opnemen.

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by JohanBoer** [comment]
Johan maakt voorstel

**Comment by JohanBoer** [comment]
Uiteindelijk ebben we dit opgelost door een array van adresidentificaties te specificeren waarbij per adresidentificatie een indicatieneveadres als boolean is opgenomen. Als een adres een hoofadrs is wordt deze niet meegeleverd en bij een nevenadres staat deze op true. 
Deze constructie is zowel voor adressen als voor nummeraanduidingen doorgevoerd. 


    AdresIdentificatiesArray:
      type: object
      properties:
        adresIdentificatie:
          type: string
        indicatieNevenadres:
          type: boolean

en deze wordt als volgt opgenomen :

    AdresseerbaarObject:
      type: object
      description: Een adresseerbaarobject is een standplaats, ligplaats of verblijfsobject.
      properties:
        ---
        adresIdentificaties:
          description: Identificatie(s) van het hoofdadres en/of de nevenadressen
          items:
            $ref: "#/components/schemas/AdresIdentificatiesArray"
          type: array
        pandIdentificaties:
          ---

**Comment by CathyDingemanse** [comment]
review: akkoord
