### ISSUE TITLE
Als medewerker vergunningen en burgerzaken wil ik net zo'n informatierijke toelichting voor gecontateerd als voor mogelijkOnjuist

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#128]
...zodat ik maximaal ben geïnformeerd bij het behandelen van een (splitsings)vergunning (#13 en #5 ) en een inschrijving in de BRP (#32).  

@PieterDijkstraKadaster kun jij voor geconstateerd ook zo'n mooie lijst met toelichtingen opleveren voor gecontateerd? Dat is denk ik heel informatief! Deze is denk ik eenvoudiger, zodat waarschijnlijk geen feature nodig zal zijn. Maar dat kunnen we bepalen als de toelichtingen er zijn. 
 

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by PieterDijkstraKadaster** [comment]
@CathyDingemanse 
De indicatie geconstateerd is inderdaad een stuk eenvoudiger. Geconstateerd wordt op objectniveau bijgehouden en heeft voor elk object ook dezelfde betekenis: 

De indicatie geconstateerd wordt gebruikt voor objecten die op basis van een feitelijke constatering zonder regulier brondocument in de registratie zijn opgenomen. De indicatie geconstateerd geeft aan dat er sprake is van een mogelijk illegaal object. Het is niet per definitie een illegaal object, omdat na onderzoek kan blijken dat er sprake is van een vergunnningsvrije situatie. 

Een voorbeeld is een situatie waarin de gemeente op basis van een luchtfoto constateert dat ergens een gebouw staat, waarvan het bestaan onbekend was en waarvan ook geen brondocument terug te vinden is. 

In de BAG praktijkhandleiding hebben we meerdere informatieve artikelen over de indicatie geconstateerd gepubliceerd:

https://imbag.github.io/praktijkhandleiding/attributen/geconstateerd

https://imbag.github.io/praktijkhandleiding/artikelen/wanneer-worden-indicaties-geconstateerd-en-in-onderzoek-gebruikt-in-de-bag

https://imbag.github.io/praktijkhandleiding/artikelen/wat-wordt-verwacht-van-een-gemeente-bij-een-geconstateerd-object

https://imbag.github.io/praktijkhandleiding/artikelen/hoe-kan-ik-een-standplaats-ligplaats-of-openbare-ruimte-constateren 

https://imbag.github.io/praktijkhandleiding/gebeurtenissen/constatering-nieuw-object

**Comment by PieterDijkstraKadaster** [comment]
De indicatie geconstateerd betekent voor elk object hetzelfde:

Het object is in de registratie opgenomen zonder regulier brondocument. De gemeente heeft feitelijk geconstateerd dat er sprake is van een object waarvan het bestaan onbekend was. 

De indicatie geconstateerd geeft aan dat het bestaan van het object mogelijk illegaal is. 
Een voorbeeld; De gemeente constateert dat een vrijstaande schuur bij een woning is omgebouwd tot zelfstandige woonruimte. In dat geval voert de gemeente een verblijfsobject en een nummeraanduiding op in de registratie met indicatie geconstateerd.  

Een geconstateerd object is niet per definitie een illegaal object. Het object kan ook achteraf vrij van vergunning zijn gerealiseerd. 

Zodra duidelijk is dat er sprake is van een vergunningvrije situatie wordt de indicatie geconstateerd op nee gezet. Als op het moment van constateren al bekend is dat er sprake is van een vergunningvrij object, wordt het object opgevoerd zonder indicatie geconstateerd.

**Comment by CathyDingemanse** [comment]
We laten het zoals het is in V1.1, is gerealiseerd in V1.1.
