### ISSUE TITLE
_links in zoekresultaten van /adressen/zoek is niet correct 

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#129]
De definitie van zoekresultaten levert nu (voorbeeld gegenereerd door Swagger):
"zoekresultaten": [
      {
        "weergavenaam": "string",
        "identificatie": "string",
        "_links": {
          "self": {
            "href": "datapunt.voorbeeldgemeente.nl/api/{major-versie}/resourcename/{resource-identificatie}",
            "templated": true,
            "title": "string"
          },
          "adressen": [
            {
              "href": "datapunt.voorbeeldgemeente.nl/api/{major-versie}/resourcename/{resource-identificatie}",
              "templated": true,
              "title": "string"
            }
          ]
        }
      }
    ]

1. de self link heeft geen zin. dit is geen resource die je direct kan opvragen, dit zijn zoekresultaten
2. adressen is geen array, het gaat hier om de _links die per zoekresultaat is opgenomen. op elk zoekresultaat is er altijd exact 1 bijbehorend adres

**Comment by fsamwel** [comment]
Waarom zijn de zoekresultaten niet gewoon alleen HAL links? Je levert dan voor elk zoekresultaat de href met de uri naar het adres en de title met daarin de weergavenaam. Enige nadeel daarvan is dat met "verplicht" is de HAL link te gebruiken, i.p.v. met de identificatie zelf de link samen te stellen.

-sorry dat ik met deze opmerking een oude afgesloten discussie opnieuw te begin-

**Comment by JohanBoer** [comment]
Door #165 en #150 is deze issue achterhaald.
