### ISSUE TITLE
Aanpassen van de descriptions zodat die voor consumers optimaal begrijpelijk zijn.

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#130]

**Comment by CathyDingemanse** [comment]
descriptions naast de endpoints weghalen, is niet consistent met de andere HC API's.

adressen/zoek
Is:
Zoeken van adressen via free query op postcode, woonplaats, straatnaam, huisnummer, huisletter, huisnummertoevoeging
wordt:
free query zoeken van adressen met postcode, woonplaats, straatnaam, huisnummer, huisletter, huisnummertoevoeging. Jouw invoer wordt exact gematcht met (een deel van) de te retourneren adressen. 

adressen
Is nu:
Raadpleeg het adres met de identificatie van het gekozen item verkregen via de zoek-operatie. Geleverd worden de huidige gegevens van een adres evt. met embedded woonplaats, openbare ruimte, nummeraanduiding. Huidige gegevens zijn actuele gegevens die geen eind status hebben, zoals 'Naamgeving ingetrokken'. Als de nummeraanduiding is ingetrokken, dan levert een bevraging geen adres op. Relaties met adresseerbaarobject (ligplaats, standplaats of verblijfsobject) en als het adresseerbaare object een verblijfsobject betreft het/de gerelateerde pand(en). Parameter zoekresultaatidentificatie bevat identificatie van een gekozen item verkregen uit een zoek-operatie.
Moet worden:
Vind een adres met de identificatie van het zoekresultaat uit zoek-operatie get/adressen/zoek. 


​/adressen​/{adresidentificatie}
Is:
Raadpleeg het adres met de nummeraanduiding identificatie. verkregen via de zoek-operatie Geleverd worden de huidige gegevens van een adres evt. met embedded woonplaats, openbare ruimte, nummeraanduiding. Huidige gegevens zijn actuele gegevens die geen eind status hebben, zoals 'Naamgeving ingetrokken'. Als de nummeraanduiding is ingetrokken, dan levert een bevraging geen adres op. Relaties met adresseerbaarobject (ligplaats, standplaats of verblijfsobject) en als het adresseerbaare object een verblijfsobject betreft het/de gerelateerde pand(en). Parameter nummeraanduidingidentificatie bevat de 16 cijferige identificatie van een lnummeraanduiding.
Moet worden:
Raadpleeg een adres met de identificatie van het adres. Dit is de nummeraanduiding identificatie. 

/adresseerbareobjecten/{adresseerbaarobjectidentificatie}
Is:
Raadpleeg het adresseerbaar object met de identificatie verkregen via de zoek-operatie Geleverd worden de huidige gegevens van een adresseerbaarobject evt. met adres en pand. Huidige gegevens zijn actuele gegevens die geen eind status hebben, zoals 'Naamgeving ingetrokken'. Als de nummeraanduiding is ingetrokken, dan levert een bevraging geen adres op. Parameter adresseerbaarobjectidentificatie bevat de 16 cijferige identificatie van een ligplaats, standplaats of verblijfsobject.
Moet worden:
Raadpleeg een adresseerbaar object met de identificatie van het adresseerbaar object. Dit is de identificatie van een verblijfsobject, ligplaats of standplaats.

/adresseerbareobjecten
Is:
Raadpleeg het adresseerbaar object met de identificatie van een nummeraanduiding of pand via de zoek-operatie. Geleverd worden de huidige gegevens van een adresseerbaarobject evt. met adres en pand. Huidige gegevens zijn actuele gegevens die geen eind status hebben, zoals 'Naamgeving ingetrokken'. Als de nummeraanduiding is ingetrokken, dan levert een bevraging geen adres op. Parameter nummeraanduidingidentificatie-query bevat de 16 cijferige identificatie van een nummeraanduiding. Parameter pandidentificatie-query bevat de 16 cijferige identificatie van een pand
Moet worden:
Zoek een adresseerbaar object met een adresidentificatie, nummeraanduidingidentificatie of pandidentificatie.

**Comment by JohanBoer** [comment]
> Vind een adres met de identificatie van het zoekresultaat uit zoek-operatie get/adressen/zoek.

Ik heb zojuist bij /adressen nav #134 een aantal query-parameters toegevoegd. Dat zou weer impact op deze description kunnen hebben.
