### ISSUE TITLE
Eindstatussen uit de enumeratie Pand verwijderen

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#132]
De enumeratie van Status Pand bevat nu nog eindstatussen. Gaarne aangeven welke statussen er verwijderd kunnen worden.

**Comment by JohanBoer** [comment]
@PieterDijkstraKadaster  @strijm Kan één van jullie aangeven welke eindstatussen er uit de enumeratie moeten worden verwijderd ?

**Comment by strijm** [comment]
Eindstatussen van een pand zijn:
- Niet gerealiseerd pand
- Pand gesloopt
- Pand ten onrechte opgevoerd

**Comment by fsamwel** [comment]
In StatusNaamgeving_enum zie ik "Naamgeving ingetrokken" staan. Is dat geen eindstatus? Zo ja, dan kan OpenbareRuimte.status verwijderd worden, want is er bij een actuele openbare ruime maar één waarde bij status mogelijk.

**Comment by fsamwel** [comment]
Idem bij Woonplaats.status (StatusWoonplaats_enum) waarde 'Woonplaats ingetrokken'

**Comment by NicoleKortoomsBAG** [comment]
Naamgeving ingetrokken en Woonplaats ingetrokken zijn beide inderdaad eindstatussen

**Comment by JohanBoer** [comment]
> Zo ja, dan kan OpenbareRuimte.status verwijderd worden, want is er bij een actuele openbare ruime maar één waarde bij status mogelijk.

Het feit dat er maar 1 waarde geretourneerd kan worden betekent toch niet dat je het element niet op hoeft te nemen. Wij weten dit, maar de afnemer wil waarschijnlijk gewoon de status van de openbareRuimte en van de woonplaats terugkrijgen. Als je hem weghaalt moet je als consumer maar net weten dat de actuele status "Woonplaats aangewezen"  is. 

In dat geval moet deze ook niet uit de mogelijkOnjuist worden verwijderd. Ook een actuele status kan toch in Onderzoek zijn ?

**Comment by CathyDingemanse** [comment]
> > Zo ja, dan kan OpenbareRuimte.status verwijderd worden, want is er bij een actuele openbare ruime maar één waarde bij status mogelijk.
> 
> Het feit dat er maar 1 waarde geretourneerd kan worden betekent toch niet dat je het element niet op hoeft te nemen. Wij weten dit, maar de afnemer wil waarschijnlijk gewoon de status van de openbareRuimte en van de woonplaats terugkrijgen. Als je hem weghaalt moet je als consumer maar net weten dat de actuele status "Woonplaats aangewezen" is.
> 
Alle actuele woonplaatsen zijn toch "aangewezen" als woonplaats, anders waren ze er niet.
Ik twijfel dus idd ook aan de noodzaak pom dat gegeven er bij te leveren.


> In dat geval moet deze ook niet uit de mogelijkOnjuist worden verwijderd. Ook een actuele status kan toch in Onderzoek zijn ?

Ja, dat klopt, maar we geven in de toelichting van mogelijkOnjuist aan wat er aan de hand is. Voor een juist begrip hiervan hoeven we de status niet te leveren.
