### ISSUE TITLE
Als PO wil ik dat queryparameters onderdeel uitmaken van de resource

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#135]
...zodat de API restful wordt.

Queryparameters ADO:
adresidentificatie
nummeraanduidingingidentificatie

Queryparameters PAND:
adresidentificatie
nummeraanduidingingidentificatie
ADOidentificatie (kan ik nu niet vinden)

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by JohanBoer** [comment]
Volgens mij is deze inmiddels ahterhaald met alle wijzigingen van de afgelopen dagen. 

@CathyDingemanse  @fsamwel kunnen we dat straks checken las de pull-requests doorgeveoerd zijn ?

**Comment by CathyDingemanse** [comment]
> Volgens mij is deze inmiddels ahterhaald met alle wijzigingen van de afgelopen dagen.
> 
> @CathyDingemanse @fsamwel kunnen we dat straks checken las de pull-requests doorgeveoerd zijn ?

Yes!!

**Comment by lennartvanbergen-kadaster** [comment]
Kan iemand een example hier posten wat het voorstel is? 

(wordt hier bedoeld dat de query parameter hetzelfde heet als de property in de resource? Of dat de query parameter niet algemeen gedefinieerd is, maar lokaal bij de GET zelf? Of ... )

**Comment by JohanBoer** [comment]
Ik heb een check uitgevoerd en alle queryparameters hebben dezelfde naam als de corresponderende properties die in de resource zitten met als uitzondering dat alle query-parameters in enkelvoud zijn en de property een meervoudsvorm kan zijn. 

Bijvoorbeeld bij /panden kennen we de queryparameter "adresseerbaarobjectidentificatie" terwijl de property in pand 'adresseerbaarObjectIdentificaties" heet. Dat lijkt mij geen issue. 

@CathyDingemanse kan deze dan gesloten worden ?

**Comment by CathyDingemanse** [comment]
Jazeker!
