### ISSUE TITLE
We gaan de nummeridentificatie als identificatie voor het adres gebruiken

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#141]
De eerdere oplossing om voor het adres een eigen identificatie te introduceren wordt n.a.v. voortschrijdend inzicht herzien. Het adres wordt geïdentificeerd op basis van de nummeraanduidingidentificatie. 

Bij alle resources waarbij ook een link naar het adres wordt dus ook de nummeraanduidingidentificatie opgenomen om de link te kunnen opbouwen.

**Comment by lennartvanbergen-kadaster** [comment]
Strikt genomen weet de gebruiker toch niet wat de inhoud van een identificatie is? 

Als het echt functioneel de nummeraanduiding identificatie moet zijn, zouden we die dan niet beter ook zo moeten noemen? 

"nummeraanduidingIdentificatie". Het intuitieve bij de naam identificatie is dat het de identificatie van het adres zelf is.
