### ISSUE TITLE
adresIdentificaties in adresseerbaar object niet juist

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#148]
In AdresseerbaarObject zit nu:
```
        adresIdentificaties:
          description: Identificatie(s) van het hoofdadres en waar van toepassing de nevenadressen
          items:
            $ref: "#/components/schemas/AdresIdentificatiesArray"
          type: array
```
en:
```
        nummeraanduidingIdentificaties:
          description: Identificatie(s) van de nummeraanduidingen die als hoofdadres en waar van toepassing de nevenadressen gerelateerd zijn.
          items:
            $ref: "#/components/schemas/NummeraanduidingIdentificatiesArray"
          type: array
```

Dit is denk ik verwarrend, omdat:
1. de arrays niet alleen een identificatie bevatten, maar ook  indicatieNevenadres. het zou dus niet moeten eindigen op "Identificaties"
2. we hebben geen aparte adresIdentificatie meer, adressen worden geïdentificeerd door de nummeraanduidingIdentificatie. adresIdentificaties kan dus vervallen

Ook bevat AdresseerbaarObjectMogelijkOnjuist nog hoofdadresIdentificatie en nevenadresIdentificaties.

**Comment by JohanBoer** [comment]
> 2\. we hebben geen aparte adresIdentificatie meer, adressen worden geïdentificeerd door de nummeraanduidingIdentificatie. adresIdentificaties kan dus vervallen

DIt is aangepast in PR #143 .

> Ook bevat AdresseerbaarObjectMogelijkOnjuist nog hoofdadresIdentificatie en nevenadresIdentificaties.

Is ook aangepast in PR #143 

> 1. de arrays niet alleen een identificatie bevatten, maar ook  indicatieNevenadres. het zou dus niet moeten eindigen op "Identificaties"

We hebben alle properties waarmee de relatie naar een andere resources gelegd wordt voorzien van de postfix "identificatie". Ook deze property heeft die rol. Overigens sta ik zoals altijd open voor een beter alternatief. "Nummeraanduidingen" dekt de lading namelijk ook niet en ik kan eigenlijk geen betere property-naam bedenken.

**Comment by fsamwel** [comment]
het laatste punt, discussie over naam property die eindigt op "Identificaties" doen we niks aan. 
We weten geen beter alternatief
