### ISSUE TITLE
ligtInWoonplaats moet zijn woonplaatsIdentificatie of woonplaats

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#149]
in OpenbareRuimte en OpenbareRuimte_embedded zit een property ligtInWoonplaats .

In OpenbareRuimte  is dit de identificatie van de woonplaats, dus moet deze heten "woonplaatsIdentificatie"

In OpenbareRuimte_embedded is de woonplaats embedded, dus moet de property "woonplaats" heten

**Comment by JohanBoer** [comment]
In de huidige master zit dit zoals je hierboven hebt beschreven. Misschien dat hier nog een conflict openstond in PR #143, maar dat is dan dus conform bovenstaand opgelost.
