### ISSUE TITLE
Als PO wil ik kortere descriptions in het schema

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#151]
Zoekresultaat en ZoekresultaatHal
Resultaat van een zoekoperatie dat je kunt gebruiken om een adres te vinden met  /adressen

AdresBasis
Eigenschappen van het adres die kunnen worden hergebruikt in andere API's waarin adresgegevens worden opgenomen. 
- straat: Een naam die door de gemeente aan een openbare ruimte is gegeven 
- huisnummer: Een nummer dat door de gemeente aan een adresseerbaar object is gegeven.
- huisletter: Een toevoeging aan een huisnummer in de vorm van een letter of een cijfer die door de gemeente aan een adresseerbaar object is gegeven.
- huisnummertoevoeging: een toevoeging aan een huisnummer of een combinatie van huisnummer en huisletter die door de gemeente aan een adresseerbaar object is gegeven.
- postcode: De door PostNL vastgestelde code die bij een bepaalde combinatie van een straatnaam en een huisnummer hoort.
- woonplaats: Een woonplaats is een gedeelte van het grondgebied van de gemeente met een naam.

Adres
Het adres is de benaming van een locatie bestaande uit straatnaam, huisnummer, (mogelijk met huisletter, huisnummertoevoeging, postcode) en woonplaatsnaam. Dit is de vereenvoudigde samenstelling van de officiële naamgeving gebaseerd op woonplaats, openbare ruimte en nummeraanduiding.

- korteNaam
de officiële openbareruimtenaam of een verkorte versie. Beiden hebben maximaal 24 tekens.
- IndicatieNevenadres
Indicatie dat dit adres een nevenadres is van een adresseerbaar object. Het adres is een hoofdadres als deze indicatie niet wordt meegeleverd.

- Indicatie geconstateerd
Indicatie dat dit adres in de registratie is opgenomen door een feitelijke constatering, zonder dat er sprake was van een brondocument/vergunning. Het adres is mogelijk illegaal. 

Nummeraanduiding:  een postcode, huisnummer met mogelijk een huisletter en -toevoeging die hoort bij een verblijfsobject, een standplaats of een ligplaats.
- geconstateerd: Indicatie dat de nummeraanduiding in de registratie is opgenomen door een 
feitelijke constatering, zonder dat er sprake was van een brondocument/vergunning. De nummeraanduiding is mogelijk illegaal.

Openbareruimte
Een openbare ruimte is een buitenruimte met een naam die binnen één woonplaats ligt, bijvoorbeeld een straat of een plein.
- openbare ruimtenaam: de naam die door de gemeente aan een openbare ruimte is gegeven.
- korteNaam:  de officiële openbareruimtenaam of een verkorte versie. Beiden hebben maximaal 24 tekens.
- geconstateerd: indicatie dat de openbare ruimte in de registratie is opgenomen door een feitelijke constatering, zonder dat er een brondocument aan ten grondslag ligt. De openbare ruimte is mogelijk illegaal.

Woonplaats
Een woonplaats is een gedeelte van het grondgebied van de gemeente met een naam. 
-woonplaatsnaam: de naam van een woonplaats.
-geconstateerd: indicatie dat een woonplaats in de registratie is opgenomen door een feitelijke constatering, zonder dat er een brondocument aan ten grondslag ligt. De woonplaats is mogelijk illegaal.

adresseerbaarobject
- identificatie: dit is de identificatie van een ligplaats, standplaats of verblijfsobject.
- documentdatum (graag overal toepassen): De vaststellingsdatum van het brondocument dat de basis is voor opname, wijziging of een verwijdering van een object.
- documentnummer (graag overal aanpassen): De aanduiding van het brondocument dat de basis is voor opname, wijziging of een verwijdering van een object.
- pandidentificatie(s): identificatie(s) van het pand of de panden waar het verblijfsobject onderdeel van is.
- nummeraanduidingidentificatie(s): Identificatie(s) van de hoofd- en nevenadressen van de standplaats, ligplaats of verblijfsobject.
- geconstateerd: indicatie dat een standplaats, ligplaats of verblijfsobject in de registratie is opgenomen door een feitelijke constatering, zonder dat er een brondocument aan ten grondslag ligt. Het adresseerbaar object is mogelijk illegaal.

openbare ruimte: een buitenruimte met een naam die binnen één woonplaats ligt, bijvoorbeeld een straat of een plein.
- openbareruimtenaam: de naam die door de gemeente aan een openbare ruimte is gegeven.
- type: codering van de waarden voor verschillende typen openbare ruimtes.
- status: weglaten
- de officiële openbareruimtenaam of een verkorte versie. Beiden hebben maximaal 24 tekens.
- geconstateerd: indicatie dat een openbare ruimte in de registratie is opgenomen door een feitelijke constatering, zonder dat er een brondocument aan ten grondslag ligt. De openbare ruimte is mogelijk illegaal.

openbareruimteMogelijkOnjuist:
De waarde is mogelijk onjuist. De juistheid van dit gegeven wordt op dit moment onderzocht (zie toelichting). @JohanBoer de waarde wordt toch alleen teruggeven als =true?

nummeraanduiding: postcode, huisnummer met mogelijk een huisletter en -toevoeging die hoort bij een verblijfsobject, een standplaats of een ligplaats.
- geconstateerd: Indicatie dat de nummeraanduiding in de registratie is opgenomen door een 
feitelijke constatering, zonder dat er sprake was van een brondocument/vergunning. De nummeraanduiding is mogelijk illegaal.
- huisnummer: Nummer dat door de gemeente aan een adresseerbaar object is gegeven.
- huisletter: Toevoeging aan een huisnummer in de vorm van een letter of een cijfer die door de gemeente aan een adresseerbaar object is gegeven.
- huisnummertoevoeging: Toevoeging aan een huisnummer of een combinatie van huisnummer en huisletter die door de gemeente aan een adresseerbaar object is gegeven.
- postcode: Door PostNL vastgestelde code die bij een bepaalde combinatie van een straatnaam en een huisnummer hoort.
- status: weglaten
- mogelijkOnjuist: De waarde is mogelijk onjuist. De juistheid van dit gegeven wordt op dit moment onderzocht (zie toelichting). (@JohanBoer de waarde wordt toch alleen teruggeven als =true?)

Pand: 
Een pand is een bouwkundige, constructief zelfstandige eenheid die direct en duurzaam met de aarde is verbonden en betreedbaar en afsluitbaar is. 
- oorspronkelijk bouwjaar: het jaar waarin een pand oorspronkelijk als bouwkundig gereed is wordt opgeleverd. Door de gemeente wordt een inschatting gemaakt van het bouwjaar, en aangepast als het pand wordt opgeleverd. Wijzigingen aan een pand na oplevering leiden niet tot wijziging van het bouwjaar.
- status: weghalen
- geconstateerd: Indicatie dat het pand in de registratie is opgenomen door een 
feitelijke constatering, zonder dat er sprake was van een brondocument/vergunning. Het pand is mogelijk illegaal.
- nummeraanduidingidentificatie(s): Identificatie(s) van de hoofd- en nevenadressen van het pand.
- mogelijkOnjuist / Pandmogelijkonjuist: de waarde is mogelijk onjuist. De juistheid van dit gegeven wordt op dit moment onderzocht (zie toelichting). (@JohanBoer de waarde wordt toch alleen teruggeven als =true?)

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by JohanBoer** [comment]
> * woonplaats: Een woonplaats is een gedeelte van het grondgebied van de gemeente met een naam.

Het gaat hier om de woonplaatsnaam die in het adres is opgenomen, niet het object woonplaats. Ik denk dat je daar de omschrijving zou moeten aanpassen. 

> openbareruimteMogelijkOnjuist:
> De waarde is mogelijk onjuist. De juistheid van dit gegeven wordt op dit moment onderzocht (zie toelichting). @JohanBoer de waarde wordt toch alleen teruggeven als =true?

Klopt alleen als een van de boleans true is wordt deze geleverd

- Status bij openbare ruimte blijft wel opgenomen (n.a.v. bespreking 30-04)
- Status bij nummeraanduiding blijft wel opgenomen (n.a.v. bespreking 30-04)
- Status bij pand blijft wel opgenomen (n.a.v. bespreking 30-04)

Ik heb alle descriptions voorzien van dubbele quotes. Er kwamen descriptions met dubbele, enkele en zonder quotes voor

**Comment by CathyDingemanse** [comment]
> > * woonplaats: Een woonplaats is een gedeelte van het grondgebied van de gemeente met een naam.
> 
> Het gaat hier om de woonplaatsnaam die in het adres is opgenomen, niet het object woonplaats. Ik denk dat je daar de omschrijving zou moeten aanpassen.
> 

Ok :-) hier is hij dan:
De naam van een door het gemeentebestuur aangewezen woonplaats.
