### ISSUE TITLE
Adresseerbareobjecten zijn nu opgenomen bij Pand.. Dat zouden we hier toch niet meer doen? 

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#153]
Adresseerbareobjecten zouden we hier toch niet meer doen, omdat dit er nogal veel kunnen zijn? De aan een pand gerelateerde adresseerbare objecten kunnen met het pand ID worden opgevraagd via de /adresseerbareobjecten endpoint, zodat paginering toegepast kan worden, dat kan hier niet.

Hetzelfde geldt voor adressen overigens, die kunnen via /adressen worden opgevraagd met paginering.

_Originally posted by @strijm in https://github.com/VNG-Realisatie/Haal-Centraal-BAG-bevragen/pull/143/files/60cdc8feed5ab80363ed5c9e8a1683c8310904c5_

**Comment by JohanBoer** [comment]
Ik kan me deze beslissing niet herinneren, maar gaarne een check door de rest van het team.....

**Comment by CathyDingemanse** [comment]
Besproken en besloten is dat we adresseerbareobjecten en adressen niet embedden zouden opnemen om te kunnen expanden bij Pand. Wel nemen we alle relaties op naar adresseerbare objecten en adressen.

**Comment by JohanBoer** [comment]
Dit is inmiddels opgelost.
