### ISSUE TITLE
Hoe weet een gebruiker straks nog of het onderzoek een hoofd- of nevenadres betreft?

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#154]
We hebben de hoofdadresidentificaties en de nevenadresidentificaties vervangen door de nummeraanduingIdentificaties n.a.v. #141. 

In de MogelijkOnjuistcomponent is nu ook een indicatie opgenomen of er een nummeridentificatie in onderzoek is (of eigenmlijk mogelijk onjuist is) Dat werpt onderstaande vraag op. Is het nodig om hier aan te geven of het een hoofdadres of een nevenadres betreft  ? (Zo ja, hoe gaan we dat dan doen ?)

Hoe weet een gebruiker straks nog of het onderzoek een hoofd- of nevenadres betreft?

_Originally posted by @strijm in https://github.com/VNG-Realisatie/Haal-Centraal-BAG-bevragen/pull/143_

**Comment by fsamwel** [comment]
dat kan de gebruiker toch opzoeken in de betreffende nummeraanduidingen?

**Comment by JohanBoer** [comment]
Dan is de conclusie dat het niet nodig is dat hier aan te geven en dat het acceptabel is dat de consumer de nummeraanduidingen ophaalt om te kijken welke in onderzoek is. 

Conclusie is dan dat er niets hoeft te worden gewijzigd in de OAS3.

**Comment by strijm** [comment]
Aan een nummeraanduiding zelf kun je niet zien of het een hoofd- of nevenadres is. Dat zit hem nl. in de relaties (heeftAlsHoofdadres en heeftAlsNevenadres) tussen een adresseerbaarobject en een nummeraanduiding, maar die zijn er niet meer.

**Comment by lennartvanbergen-kadaster** [comment]
Hoofdadres is een eigenschap van het adresseerbare object. Nevenadres ook. Niet van de NUM. Die cinclusie klopt niet. 

Je kan niet zomaar betekenisvolle relatie namen van relaties vervangen door 'gerelateerd object' namen. De relatienaam geeft duiding aan de relatie. De relatie is een eigenschap. 

In dit geval is de relatie mogelijk onjuist, en niet de nummeraanduiding zelf. Als de relatienaam  verwijderd moet worden om een of andere reden en vervangen wordt door een alternatie relatienaam, dan is deze laatste mogelijk onjuist.

**Comment by fsamwel** [comment]
Wanneer het hoofdadres in onderzoek is, terwijl er ook een nevenadres is, staat in het antwoord bijvoorbeeld:
```
  "nummeraanduidingIdentificaties": [
    {
      "nummeraanduidingIdentificatie": "1234200000000001",
    },
    {
      "nummeraanduidingIdentificatie": "1234200000000002",
      "indicatieNevenadres": true
    }
  ],
  "mogelijkOnjuist": {
    "nummeraanduidingIdentificaties": true,
    "toelichting": [
      "AdresseerbaarObject heeft mogelijk een verkeerd adres. Het gerelateerde hoofdadres(ID) mag niet worden gewijzigd want is onlosmakelijk met het adresseerbaar object verbonden. Kan alleen opgelost worden door de gegevens van het adres te veranderen, zodat een ander adres ontstaat."
    ]
  }
```

Wanneer het nevenadres in onderzoek is, staat in het antwoord bijvoorbeeld:
```
  "nummeraanduidingIdentificaties": [
    {
      "nummeraanduidingIdentificatie": "1234200000000001",
    },
    {
      "nummeraanduidingIdentificatie": "1234200000000002",
      "indicatieNevenadres": true
    }
  ],
  "mogelijkOnjuist": {
    "nummeraanduidingIdentificaties": true,
    "toelichting": [
      "Mogelijk is ten onrechte een nevenadres toegekend of ontbreekt de relatie met een nevenadres."
    ]
  }
```

We hebben nu juist toelichting toegevoegd aan de mogelijkOnjuist om dit soort informatie te melden aan de gebruiker.

**Comment by CathyDingemanse** [comment]
We hebben speciaal voor de toelichtingen (een goede interpretatie door een mens, bijvoorbeeld een medewerker vergunningen) een de "mogelijk onjuist feature" gemaakt.
