### ISSUE TITLE
maxLength op response properties gedefinieerd

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#159]
Op response properties is een maxLength meestal niet nodig. Het opnemen hiervan kan tight coupling met de bronregistratie tot gevolg hebben.

- AdresseerbaarObject.documentnummer
- AdresBasis.straat
- AdresBasis. woonplaats
- OpenbareRuimte.naam
- OpenbareRuimte.documentnummer
- Nummeraanduiding.documentnummer
- Woonplaats.naam
- Woonplaats.documentnummer
- Pand.documentnummer

N.B. bij Adres.korteNaam en OpenbareRuimte.korteNaam is het wellicht wel van belang de maxLength te laten staan, want dat is de hele bestaansreden van dit property

N.B. Pand. oorspronkelijkBouwjaar is gedefinieerd als string met maxLength 4. @MelvLee wil je een jaar niet liever als integer krijgen?

**Comment by fsamwel** [comment]
ook minLength is nog op verschillende plekken opgenomen in de response definities:
- AdresBasis.straat
- AdresBasis.woonplaats
- Adres.korteNaam
- OpenbareRuimte.naam
- OpenbareRuimte.korteNaam
- OpenbareRuimte.documentnummer
- Nummeraanduiding.documentnummer
- Woonplaats.naam
- Woonplaats.documentnummer

**Comment by JohanBoer** [comment]
Ik heb Pand. oorspronkelijkBouwjaar als integer gedefinieerd. We hebben in de BRK ook het koopjaar als integer gedefinieerd.

**Comment by JohanBoer** [comment]
minLength ook verwijderd uit Pand.documentnummer

**Comment by NicoleKortoomsBAG** [comment]
@JohanBoer, Met BAG 2.0 wordt volgens de BAG catalogus ISO 8601 gehanteerd voor tijdstippen. Met deze wijziging wordt daar vanaf geweken. Ik kan me voorstellen dat dit niet bekend was en dat je om het gelijk te houden bij beide de ISO-norm zou willen volgen. 
Anders ten minste de afwijking omschrijven.

**Comment by NicoleKortoomsBAG** [comment]
@JohanBoer , Pieter kijkt naar de aantallen van de bouwjaren voor 1000.

**Comment by PieterDijkstraKadaster** [comment]
Er zijn 10 panden met een huidige status met een bouwjaar voor 1000:

![image](https://user-images.githubusercontent.com/22903349/81825118-8461dc80-9536-11ea-96ac-c6db778eb01d.png)

**Comment by fsamwel** [comment]
@NicoleKortoomsBAG 
> Met BAG 2.0 wordt volgens de BAG catalogus ISO 8601 gehanteerd voor tijdstippen. Met de wijziging van het bouwjaar naar integer wordt daar vanaf geweken.

Volgens mij nemen we in principe naamgeving over uit het informatiemodel (met inachtneming van naamgevingsconventies zoals camelCase, enz.) en betekenis (soms tekstueel ingekort maar altijd met dezelfde essentie). Maar de structuur in het informatiemodel, zoals de technische definities, volgen we nadrukkelijk niet. We kiezen hiervoor om te communiceren in de voor de ontvanger duidelijkste en makkelijkste vorm.
Bijvoorbeeld een veld met mogelijke waarden "Ja" en "Nee" zouden we een boolean maken. 
Voor een jaartal is sturen als een integer het beste voor de ontvanger. Daarmee kan de ontvanger namelijk direct rekenen, bijvoorbeeld berekenen hoe oud het pand is.

Ik zie dit niet als een afwijking, maar als een volledig losstaand iets.

**Comment by NicoleKortoomsBAG** [comment]
@JohanBoer @fsamwel Ik weet niet of de vergelijking met de boolean opgaat omdat het daarbij gaat om een weergave van iets wat in de catalogus als 'indicatie' wordt omschreven. 
Mijn opmerking was vooral bedoeld als signaalfunctie. Als er voor wordt gekozen om dit anders te doen, moet dat wel bewust gebeuren.

**Comment by fsamwel** [comment]
@NicoleKortoomsBAG je signaal wordt ook gewaardeerd. Deze keuze hebben we gemaakt vanuit de doelstelling van evolvability en developer experience.
