### ISSUE TITLE
Als burger wil ik mijn nieuwe adres kunnen selecteren

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#16]
zodat ik op correcte wijze mijn verhuizing bij de gemeente kan opgeven

**Comment by strijm** [comment]
Is deze user story (qua specificatie) niet hetzelfde als beschreven in issue #18?

**Comment by CathyDingemanse** [comment]
Ja, er zijn meer afnemers die deze functionaliteit vragen, zijn allen verwerkt in de GOALS canvas.

**Comment by fsamwel** [comment]
@CathyDingemanse moet hiervoor nog iets worden gedaan of kan deze worden gesloten, net als #18? het endpoint adressen/zoek bestaat immers al

**Comment by CathyDingemanse** [comment]
kan worden gesloten
