### ISSUE TITLE
Resources worden nog geïdentificeerd met een NEN3610ID

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#161]
De identificatie van de verschillende resources, behalve Adres en AdresseerbaarObject is nog gedefinieerd als NEN3610ID. Dat moet denk ik gewoon een string worden.

Betreft:
- OpenbareRuimte
- Nummeraanduiding
- Woonplaats
- Pand

**Comment by fsamwel** [comment]
@CathyDingemanse mee eens dat we dit nu consequent doorvoeren in de specs die wij nu maken?

**Comment by lennartvanbergen-kadaster** [comment]
Kunnen we die identificatie wel/niet conform NEN3610 issues even bundelen in 1 issue (en de rest sluiten en ze in 1x doorvoeren zodra we er uit zijn)?

**Comment by CathyDingemanse** [comment]
> @CathyDingemanse mee eens dat we dit nu consequent doorvoeren in de specs die wij nu maken?

Natuurlijk eens.

**Comment by JohanBoer** [comment]
> Kunnen we die identificatie wel/niet conform NEN3610 issues even bundelen in 1 issue (en de rest sluiten en ze in 1x doorvoeren zodra we er uit zijn)?

Daarvoor hebben we een tijdje geleden #35  opgevoerd. Die staat nog op in progress.
