### ISSUE TITLE
korteNaam toevoegen aan OpenbareRuimteMogelijkOnjuist

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#162]
in OpenbareRuimteMogelijkOnjuist is wel "naam" opgenomen, maar niet afgeleid gegeven "korteNaam". Die moet n.m.m. ook worden opgenomen, zodat de gebruiker weet dat ook dat gegeven mogelijk onjuist is.

ook mogelijkOnjuist.feature moet dan worden aangepast in regel 80.

**Comment by lennartvanbergen-kadaster** [comment]
Ja, eens met Frank. 

Let wel, de verkorte naam is niet in onderzoek. 

Maar deze is wel mogelijk onjuist.
