### ISSUE TITLE
AdresBasis hernoemen naar Adres en Adres naar AdresUitgebreid o.i.d.

### ISSUE THREAD

**Issue by strijm** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#164]
# Impediment
AdresBasis bevat nog geen kortenaam, deze moet nog toegevoegd worden en kan dan verwijderd worden uit Adres.
Het zou m.i. beter zijn om AdresBasis te hernoemen naar Adres. Deze bevat dan precies datgene wat een adres vormt.
Adres bevat op dit moment veel meer dan alleen adres gegevens en zou m.i. beter hernoemd kunnen worden naar AdresUitgebreid o.i.d. en zou dan Adres (i.p.v. AdresBasis) omvatten.
Door bovenstaande acties wordt het (nieuwe) Adres herbruikbaarder als echt Adres.

**Comment by fsamwel** [comment]
goed voorstel Mark om de basis "Adres" te noemen en de uitbreiding "AdresUitgebreid "!

Of korteNaam in de herbruikbare basiscomponent hoort hangt er vanaf of die ook elders gebruikt moet worden. We gebruiken het adres, zoals die hier voor BAG is gedefinieerd ook in BRK. We zouden die ook kunnen gebruiken in BRP (personen) en later ook in HR (KvK Handelsregister). 

Het is dan de vraag of zij ook de korteNaam kunnen leveren. Is er een algoritmebeschrijfing hiervoor die met andere domeinen gedeeld kan worden? (bijvoorbeeld in de vorm van een feature)

**Comment by strijm** [comment]
Ik begreep van Nicole dat kortenaam er zeker in moet, omdat deze van belang kan zijn voor bv. labels voor poststukken. De korte naam is dan nodig omdat de volledige naam (mogelijk) niet op labels past.

**Comment by JohanBoer** [comment]
We hebben na lange discussie besloten de korteNaam niet op te nemen in het herbruikbare deel. Wel in het AdresUitgebreid deel natuurlijk.  Als je die wel op zou nemen dan dwing je iedereen die dat herbruibare deel in hun spec willen opnemen om ook de korteNaam te ondersteunen.
