### ISSUE TITLE
self link verwijderen uit ZoekResultaat_links

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#165]
ZoekResultaat_links bevat een property self.

Deze moet worden verwijderd want een zoekresultaat-item is geen resource en kan niet direct worden opgevraagd met een uri.

**Comment by JohanBoer** [comment]
Ik was al aan het twijfelen toen ik het feature-voorbeeld aan het opstellen was. Mee eens.
