### ISSUE TITLE
X-Rate-Limit response headers verwijderen

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#168]
De API levert geen X-Rate-Limit headers. Dan moeten ze ook niet in de specificaties zijn opgenomen.

@strijm klopt het dat jullie dit niet (in versie 1) gaan leveren?

**Comment by strijm** [comment]
We zullen dit inderdaad niet in versie 1 gaan leveren. Ik heb het hier vanochtend met Johan over gehad. Omdat de rate limit headers optioneel zijn, hoeven we ze nu niet direct te leveren. Ik zou ze dus, juist omdat ze optioneel zijn wel in de specificatie laten staan. We zijn nl. wel van plan ze in de toekomst te implementeren.

**Comment by fsamwel** [comment]
Wil je dat op heel korte termijn gaan leveren? In principe zou ik namelijk niks in de specs opnemen dat niet geleverd wordt. Komt namelijk allemaal in client code terecht, wat dus initieel dode (onbereikbare) code is.
Toevoegen kan altijd nog. En dan is het voor gebruikers ook erg zichtbaar wat er is toegevoegd (aan de toevoegingen in de specs).

**Comment by lennartvanbergen-kadaster** [comment]
Op zich eens met Frank als uitgangspunt.

Maar gaat in deze toch ook om impact te voorkomen? Oftewel, is dit achteraf toe te voegen zonder major versie ophoging?

Ik denk van wel. Dus nu idd weglaten en toevoegen zodra het geimplementeerd gaat worden.

Let wel, dat ze er niet staan betekent niet dat het oneindig veel is. Het betekent dat het niet gespecificeerd is. 

In de SLA/DNO zal wel een getal (moeten) komen te staan.

**Comment by lennartvanbergen-kadaster** [comment]
Dit lijkt me een item om in een ontwerpsessie vast te stellen. Of als oneens, bespreken .
