### ISSUE TITLE
Als burger wil ik een adres kunnen selecteren 

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#17]
zodat ik een afspraak kan maken voor het laten ophalen van grof vuil

**Comment by strijm** [comment]
Is deze user story (qua specificatie) niet hetzelfde als beschreven in issue #18?

**Comment by CathyDingemanse** [comment]
Ja. Er zijn meer afnemers die deze functionaliteit vragen. Alle user stories zijn opgenomen in de GOALS CANVAS.

**Comment by fsamwel** [comment]
@CathyDingemanse ook voor deze (net als #16): moet hiervoor nog iets worden gedaan of kan deze worden gesloten, net als #18? het endpoint adressen/zoek bestaat immers al

**Comment by CathyDingemanse** [comment]
kan worden gesloten
