### ISSUE TITLE
Als burger wil ik een adres kunnen selecteren

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#18]
zodat ik dit kan opgeven bij het indienen van een zaak

**Comment by strijm** [comment]
In update #58 is adres/zoek endpoint gespecificeerd waarmee gezocht kan worden met bv. postcode, straatnaam, huisnummer en/of woonplaats. Daarnaast is een endpoint gespecificeerd waarbij met een geselecteerd keuze item ID (verkregen uit de zoek actie) een adres opgevraagd kan worden. Hiermee kan een adres geselecteerd worden.
Verder is er een endpoint gespecificeerd waarbij met een nummeraanduiding ID een adres opgevraagd kan worden.
