### ISSUE TITLE
Als PO wil ik descriptions naast de endpoints

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#183]
...zodat sneller duidelijk wordt wat het endpoint levert.

adressen/zoek                                                                                           "fuzzy" zoeken van adressen 
/adressen                                                                                                    levert adressen
/adressen/{nummeraanduidingidentificatie}                                              levert een adres
/nummeraanduidingen/{identificatie}                                                        levert BAG details van een nummeraanduiding
/openbareruimten/{identificatie}                                                                levert BAG detals van een openbare ruimte            
/woonplaatsen/{identificatie}                                                                      levert BAG details van een woonplaats
/adresseerbaarObjecten                                                                              levert verblijfsobjecten, ligplaatsen, standplaatsen
/adresseerbaarObjecten/{Identificatie}                                                       levert een verblijfsobject, standplaats of ligplaats
/panden                                                                                                      levert panden
/panden/{identificatie}                                                                                  levert een pand

@JohanBoer, sorry, toch wel, maar dan wel anders... :-)  Zal het bij de andere domeinen ook doen.

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by strijm** [comment]
@CathyDingemanse kun jij verifiëren dat bij het viewen van de geresolvede yaml in Swagger, de beschrijvingen kloppen en als dat zo is, dit ticket sluiten?

**Comment by JohanBoer** [comment]
De resolved is 27 dagen oud. De API-specificatie is 3 uur oud. Er moet dus een resolved versie gemaakt worden en gemerged worden. Dat zal ik nu doen.

**Comment by JohanBoer** [comment]
De bovenvermelde summaries zijn overigens achterhaald door issue #190 en en pull request #210.
