### ISSUE TITLE
Opmerkingen uit Pull request #189 t.a.v. summaries

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#190]
![image](https://user-images.githubusercontent.com/18071357/81107302-3d149400-8f17-11ea-9c64-b4d9ce75c36f.png)

![image](https://user-images.githubusercontent.com/18071357/81107345-4dc50a00-8f17-11ea-8a77-7b058cd1f9f5.png)

**Comment by CathyDingemanse** [comment]
@strijm
Functioneel gaat het er om dat de adresgegevens waarin de meeste afnemers geïnteresseerd in het adres staan. Ben je nou geïnteresseerd in de BAG details van woonplaats, nummeraanduiding en openbare ruimte (denk aan bezwaarcommissie, advocaten),  dan kun je die via deze resources al dan niet tegelijkertijd met het adres opvragen.  Deze endpoints hebben dus een specifieke, andere functie voor de gebruiker dan de endpoints voor adressen, adresseerbaar objecten en panden.

**Comment by CathyDingemanse** [comment]
@fsamwel 
OK, dan maken we er vindt panden, vindt adressen en vindt adresseerbaar objecten van. Het gaat om de beschrijving van het endpoint, niet de activiteit van de gebruiker.
