### ISSUE TITLE
De specificatie voor de contentCrs en acceptCrs headers zijn te ruim

### ISSUE THREAD

**Issue by strijm** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#192]
# Impediment
De specificatie van de contentCrs en acceptCrs headers in de common.yaml is nu zo ruim gedefinieerd, dat de HC API als default WGS84 en daarnaast iedere willekeurige andere CRS kan ondersteunen. Dit is niet realistisch en niet acceptabel. Om te beginnen zal de API alleen EPSG:28992 ondersteunen voor inkomende als uitgaande geometrie, zoals initieel aangegeven. Dit moet voor de 1.0.0 versie worden aangepast in de API specificatie. Op termijn kunnen er nieuwe versies worden gereleased, die andere CRS-en ondersteunen als daar behoefte aan is.
De huidige stand van de API specificatie zorgt ervoor dat clients alle CRS-en kunnen meesturen als content of kunnen opvragen dmv accept. Echter krijgen ze alleen bij EPSG:28992 geen foutmeldingen, in alle andere gevallen wel. Ook voor de default (WGS84).
Ik stel voor de enumeraties zoals die initieel waren gespecificeerd op te voeren, zodat een gebruiker weet wat hij kan opgeven en waardoor er minder (onnodige) foutmeldingen worden gegenereerd.

**Comment by fsamwel** [comment]
zie ook https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/408 en #59

**Comment by JohanBoer** [comment]
Deze specificaties zijn aangepast in common.yaml en kunnen op die manier geïmplementeerd worden.

**Comment by strijm** [comment]
Dit is aangepast in de HC common.yaml specificatie en kan als zodanig gebruikt worden. Dit ticket kan gesloten worden.
