### ISSUE TITLE
Vraag onderscheid huidig en actueel

### ISSUE THREAD

**Issue by NicoleKortoomsBAG** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#193]
vraagje, ik kan het niet meer vinden.
Staat er nu nog ergens in de api dat hier huidig wordt geleverd, zijnde actueel zonder eindstatussen?

**Comment by CathyDingemanse** [comment]
Huidig en actueel zijn in het normale taalgebruik synoniemen. De meeste mensen zullen een actuele resource interpreteren als iets dat nu bestaat. Het tegenovergestelde is historische (iets met een eindstatus). Ik stel voor om de definitie van actueel nader toe te lichten bovenaan in de toelichting.

@JohanBoer: zou je willen opnemen:
Deze API levert actuele gegevens over adressen, adresseerbaar objecten en panden. Actueel betekent "zonder eindstatus". De bron voor deze API is de basisregistratie adressen en gebouwen (BAG).

**Comment by NicoleKortoomsBAG** [comment]
graag 'in deze api' toevoegen. De API heet huidige bevragingen, dus dan is de context duidelijk en omdat het inderdaad bij normaal taalgebruik synoniemen zijn, maar in de BAG actueel en huidig een andere betekenis hebben, is het belangrijk het goed toe te lichten.

Deze API levert actuele gegevens over adressen, adresseerbaar objecten en panden. Actueel betekent in deze API "zonder eindstatus". De bron voor deze API is de basisregistratie adressen en gebouwen (BAG).

**Comment by CathyDingemanse** [comment]
@JohanBoer: zou je willen opnemen:
Deze API levert actuele gegevens over adressen, adresseerbaar objecten en panden. Actueel betekent in deze API "zonder eindstatus". De bron voor deze API is de basisregistratie adressen en gebouwen (BAG).
