### ISSUE TITLE
Geen pagination headers bij opvragen adresseerbare objecten met pand ID

### ISSUE THREAD

**Issue by strijm** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#194]
# Impediment
Bij de endpoint waar met een pand ID de gerelateerde adresseerbare objecten (VBO's) opgevraagd kunnen worden zijn voor de response geen pagination headers gespecificeerd. 
Bij de zoekresultaten is dat wel gedaan. Is er een reden om het bij de ene endpoint wel en bij een andere niet op te nemen?

**Comment by JohanBoer** [comment]
Er bleek een probleem te zijn bij het vormgeven van de adresseerbaarObjectHalCollectie. Dat heb ik inmiddels aangepast en de wijziging is aangeboden in een pull request.
