### ISSUE TITLE
Mogelijk onjuist is niet intuitief bij adressen

### ISSUE THREAD

**Issue by NicoleKortoomsBAG** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#199]
Bij mogelijk onjuist wordt zie ik attributen en id’s, waarbij ik aanneem dat woonplaats de woonplaatsnaam is en dus een attribuut.  Een object waaruit het adres wordt opgebouwd, worden zo te zien aangegeven met …identificatie. 

Als ik dit zo zie staan, begrijp ik dat het id niet klopt, terwijl ik met mijn kennis weet dat er iets aan het object niet klopt of de relatie vanuit NUM mogelijk onjuist is. Welke van de twee moet denk ik blijken uit de toelichting? 

Belangrijkste onduidelijkheid is wat mij betreft NUMID.
Van numID staan ook heel veel attributen in de mogelijk onjuist en omdat het NUM id de basis is voor het adres, is het ook geen relatie. Ik kan niet vinden wat er onjuist is als het NUMid als mogelijk onjuist wordt aangegeven want alle attributen staan er ook al bij. 
*(voorbeeld bij numid onjuist is trouwens: woonplaats bestaat mogelijk niet) 

Ander ding dat ik onduidelijk vind:
Er staat woonplaats en woonplaatsidentificatie en het voorbeeld van de toelichting gaat over de geometrie. Drie zaken van de woonplaats die ik niet aan elkaar kan linken.  Dus ik lees iets anders dan wat ik verwacht. Door het voorbeeld denk ik dat het id een verzamelgroep is voor alle attributen binnen het object, maar ik weet dus niet of dat klopt.

**Comment by fsamwel** [comment]
@NicoleKortoomsBAG je bedoelt hier neem ik aan intuïtief voor de eindgebruiker?

In mogelijkOnjuist wordt naar de gebruiker gecommuniceerd op twee niveau's:
1. computer leesbaar: de mogelijkOnjuist properties (booleans), geven aan welke gegevens in de resource mogelijk onjuist zijn, zodat een algoritme in de clientapplicatie kan beslissen bepaalde gegevens al dan niet te gebruiken of daar al dan niet beslissingen op te nemen

2. voor mens (eindgebruiker) leesbaar: de mogelijkOnjuist toelichting, geeft aan wat en waarom het mogelijk onjuist is, zodat deze persoon de situatie (en consequenties voor het eigen proces) kan inschatten

Dus de booleans hebben niet de intentie te communiceren wat er in de bron in onderzoek staat, maar communiceren alleen iets over de betrouwbaarheid van de geleverde gegevens.

Alle interpretatie over de consequenties van het mogelijkOnjuist zijn moeten uit de toelichting gehaald worden.

MogelijkOnjuist heeft dus niet de intentie te communiceren wat er precies in de bron in onderzoek staat. Daarom hebben we er ook voor gekozen het "mogelijkOnjuist" te noemen en niet "inOnderzoek".

Bijvoorbeeld wanneer de status van de nummeraanduiding in onderzoek is, zijn alle gegevens in het adres die uit de nummeraanduiding zijn gehaald (inclusief daaruit afgeleide relaties) mogelijk onjuist. De toelichting moet dan meer duidelijk maken: "Adres bestaat mogelijk niet (meer)."

Bijvoorbeeld wanneer in object woonplaats van een adres de geometrie in onderzoek is, is het daarmee niet meer zeker of het adres wel in de aangegeven woonplaats ligt. 
Dan is het onzeker of de waarden in de resource Adres op properties woonplaats (met daarin de woonplaatsnaam) en woonplaatsIdentificatie staan correct zijn.
Naar de API gebruiker wordt dus gecommuniceerd dat deze properties mogelijk onjuist zijn, door ze op te nemen met waarde true, plus de toelichting "Geometrie of woonplaatsgrens is mogelijk onjuist, waardoor gaten of overlappingen ontstaan in de registratie van woonplaatsen. Gevolg kan zijn dat een object in een verkeerde woonplaats, in twee woonplaatsen, of in geen enkele woonplaats ligt."

Voorbeeld voor de toelichting bij nummeraanduiding mogelijkOnjuist is inderdaad niet correct. Die toelichting kan niet komen. Een correct voorbeeld zou zijn "Mogelijk verkeerde woonplaats gebruikt." @JohanBoer kan jij dit aanpassen?

**Comment by NicoleKortoomsBAG** [comment]
Ik begrijp hieruit dat het er staat zoals het bedoeld is. 
Bij mij ontstaat de verwarring doordat er aan de ene kant achtergrondinformatie gegeven wordt vanuit de NUM (postcode, huisnummer, etc) onjuist en een overall op numID. Toelichting zegt wat mij betreft eigenlijk meer dan de boolean. 

Featureomschrijving moet goed duidelijk zijn om (deze) verwarring bij afnemers te voorkomen.
Ik heb @PieterDijkstraKadaster gevraagd deze te bekijken omdat hij de input voor mogelijk onjuist heeft geleverd.

**Comment by NicoleKortoomsBAG** [comment]
@fsamwel 

Naar aanleiding van ons overleg en na het besproken te hebben met Pieter, zie onderstaande tekstvoorstellen:

Aanvulling toelichting bij:
Abstract Scenario: mogelijkOnjuist vullen bij onderzoek naar de status van het object
      | Pand             | Pand in gebruik (niet ingemeten)            | Pand                 | status                   | Mogelijk is de geometrie al ingemeten **of is de bouw ten onrechte gereedgemeld**. |
      | Verblijfsobject  | Verblijfsobject in gebruik (niet ingemeten) | Adresseerbaar object | status                   | Mogelijk is de geometrie al ingemeten, **of is de bouw ten onrechte gereedgemeld.** |

Verduidelijking toelichting bij   Scenario: wanneer de status van een object in onderzoek is, zijn alle daaruit afgeleide properties van de resource mogelijk onjuist, adressen endpoint
| Nummeraanduiding | Status nummeraanduiding                  | Adres                | straat,korteNaam,huisnummer,huisletter,huisnummertoevoeging,postcode,woonplaats,nummeraanduidingIdentificatie,woonplaatsIdentificatie,openbareRuimteIdentificatie | Adres bestaat mogelijk niet (meer) **omdat de nummeraanduiding mogelijk niet (meer) bestaat**. |

Straat en Korte naam een  eigen toelichting geven bij 2 onderdelen.
Bestaand: 
Openbare ruimte  | Naam openbare ruimte                     | Adres                | straat,korteNaam         | Straatnaam komt mogelijk niet overeen met de vermelding in het straatnaambesluit. |
Openbare ruimte  | Naam openbare ruimte                     | Openbare ruimte      | naam,korteNaam           | Openbare ruimtenaam komt mogelijk niet overeen met de vermelding in het straatnaambesluit. |

Voorstel:
Openbare ruimte  | Naam openbare ruimte                     | Adres                | **straat** | Straatnaam komt mogelijk niet overeen met de vermelding in het straatnaambesluit. |
Openbare ruimte  | Naam openbare ruimte                     | Adres                | **korteNaam**         | **Korte naam is mogelijk onjuist omdat de straatnaam mogelijk niet overeen komt met de vermelding in het straatnaambesluit. Dit is geen indicatie dat de straatnaam mogelijk onjuist is verkort.**
Openbare ruimte  | Naam openbare ruimte                     | Openbare ruimte      | **naam** | Openbare ruimtenaam komt mogelijk niet overeen met de vermelding in het straatnaambesluit. |
Openbare ruimte  | Naam openbare ruimte                     | Openbare ruimte      | **korteNaam**           | **Korte naam is mogelijk onjuist omdat de openbare ruimtenaam mogelijk niet overeen komt met de vermelding in het straatnaambesluit. Dit is geen indicatie dat de straatnaam mogelijk onjuist is verkort.**

**Comment by CathyDingemanse** [comment]
Ik vind het een mooie aanvulling! 
Ik twijfel over de aanvulling "omdat de nummeraanduiding mogelijk niet meer bestaat" omdat dit begrip vergt van een andere resource en deze toevoeging in de adresresource niet nodig is. Als de nummeraanduiding (mogelijk) niet meer bestaat, bestaat het adres (mogelijk) immers ook niet meer.

**Comment by NicoleKortoomsBAG** [comment]
>Ik twijfel over de aanvulling "omdat de nummeraanduiding mogelijk niet meer bestaat" omdat dit begrip vergt van een andere resource en deze toevoeging in de adresresource niet nodig is. Als de nummeraanduiding (mogelijk) niet meer bestaat, bestaat het adres (mogelijk) immers ook niet meer.

Met Frank besproken dat hier de blik van een user bij moet worden betrokken. Voor mij was het te weinig info en daardoor verwarrend, maar misschien kwam dit omdat ik teveel weet.

**Comment by fsamwel** [comment]
De grote vraag is dus of het voor de gebruiker duidelijker of minder duidelijk wordt wanneer bij het mogelijk onjuist zijn van een adres de nummeraanduiding wordt benoemd. Ik denk dat sommige gebruikers dit verwarrend zullen vinden, vooral die gebruikers die nauwelijks kennis hebben van BAG. Zij denken -vermoed ik- in begrippen als "adressen" eerder dan "nummeraanduidingen". 
Maar het kan juist duidelijker zijn voor gebruikers die wel enige kennis van BAG hebben en behoefte kunnen hebben te relateren aan iets in BAG. Mijn gevoel (niet meer dan dat) is dat dit wel een goede toevoeging is, omdat gebruikers zonder BAG kennis uit het eerste deel van de zin begrijpen dat het adres zelf mogelijk niet bestaat. Voor hun is het onderscheid tussen nummeraanduiding en adres niet zo relevant (ik begrijp zelf het verschil tussen beide ook niet).

Als ik de wijziging op naam en korteNaam goed begrijp, is het resultaat van onderzoek naar de straatnaam, dat er dan twee toelichtingen worden getoond. Begrijp ik dat goed? Dus:
        "mogelijkOnjuist": {
          "korteNaam": true,
          "straat": true,
          "toelichting": [
            "Straatnaam komt mogelijk niet overeen met de vermelding in het straatnaambesluit.",
            "Korte naam is mogelijk onjuist omdat de straatnaam mogelijk niet overeen komt met de vermelding in het straatnaambesluit. Dit is geen indicatie dat de straatnaam mogelijk onjuist is verkort."  ]

**Comment by fsamwel** [comment]
@NicoleKortoomsBAG @PieterDijkstraKadaster bij openbare ruimte staat voor korteNaam de toelichting "Korte naam is mogelijk onjuist omdat de openbare ruimtenaam mogelijk niet overeen komt met de vermelding in het straatnaambesluit. Dit is geen indicatie dat de straatnaam mogelijk onjuist is verkort."
Hier wordt door elkaar openbare ruimtenaam (eerste zin) en straatnaam (tweede zin) gebruikt. Is het niet duidelijker één term te gebruiken (ik stel dan voor "openbare ruimtenaam" te gebruiken)

**Comment by NicoleKortoomsBAG** [comment]
Ik had nog zo opgelet dat de termen overeenkwamen met die worden gebruikt in het endpoint. Dat is voor adres (straat) en openbare ruimte (openbareruimtenaam)  namelijk anders. Lijkt me goed om het consistent door te voeren. Tweede stukje van de toelichting had ik gemist.

**Comment by NicoleKortoomsBAG** [comment]
@fsamwel 
> Als ik de wijziging op naam en korteNaam goed begrijp, is het resultaat van onderzoek naar de straatnaam, dat er dan twee toelichtingen worden getoond. Begrijp ik dat goed? Dus:

Dat is wel de consequentie. Wel een beetje dubbelop, is dat erg lelijk?

**Comment by CathyDingemanse** [comment]
> @fsamwel
> 
> > Als ik de wijziging op naam en korteNaam goed begrijp, is het resultaat van onderzoek naar de straatnaam, dat er dan twee toelichtingen worden getoond. Begrijp ik dat goed? Dus:
> 
> Dat is wel de consequentie. Wel een beetje dubbelop, is dat erg lelijk?

Ik vind het niet zo erg. Als het maar duidelijk is, en dat is het als de termen gelijk worden getrokken.
