### ISSUE TITLE
OpenAPI specificaties onvoldoende ondersteuning als documentatie/generatie middel

### ISSUE THREAD

**Issue by KayodeBakker** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#20]
# Impediment

~~Er is een API opgezet met tot zo verre één bevragingspad, maar er zijn geen OpenAPI specificaties om als basis voor object generatie of documentatie te dienen.~~

~~Dit zou ik graag willen zien omdat het tussentijds beoordelen van de functionaliteit hierdoor lastig wordt.~~

[Update na ontvangen specificaties]

De specificaties worden nu aangeboden in niet één specificatie maar in meerdere. De verwachting is dat niet per onderwerp (nummeraanduiding, verblijfsobject etc.) een specificatie is, maar per API. Dit impliceert namelijk dat er meer dan één API is, nummeraanduiding API, verblijfsobject API etc. Dit zou één specificatie moeten zijn want het gaat ook om één API, namelijk de BAG API.

**Comment by CathyDingemanse** [comment]
vraag staat uit!

**Comment by lvbag** [comment]
Via onderstaande link zijn de specificaties te vinden. Onder generated-specification vind je de basis voor codegeneratie.
https://github.com/lvbag/BAG-API/tree/master/Technische%20specificatie

**Comment by KayodeBakker** [comment]
Dank voor de specificaties. Echter zou ik niet zeggen dat deze volstrekken. Om deze reden, pas ik de issue aan.

**Comment by JohanBoer** [comment]
@Kayo In een  discussie binnen het BAG-team is aangegeven dat er geen dubbele objecten voorkomen in de BAG-API's. Vraag is dan ook of het hebben van meerdere API's om de BAG-objecten in de praktijk leidt tot dubbelingen in het code-genereren van objecten. 

Of is er een ander bezwaar dat jij vanuit technisch perspectief hebt op meerdere verschillende API's i.p.v. 1 BAG-API met alle objecten?

**Comment by strijm** [comment]
Dit issue heeft betrekking op de BAG Individuele Bevragingen API en niet op de HaalCentraal API. Wat mij betreft wordt dit ticket afgesloten. Als het issue zich met de laatste versie van de BAG Individuele Bevragingen API nog voordoet, dan kan een issue worden ingediend in de BAG Individuele Bevragingen API github repository.

**Comment by fsamwel** [comment]
dit is opgelost in de Haal Centraal API
