### ISSUE TITLE
Overal templated links toegepast.

### ISSUE THREAD

**Issue by NicoleKortoomsBAG** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#200]
Bij adressen zie ik dat er overal templated links zijn toegepast. Dit is waarschijnlijk gewoon een keus. Maar een templated link lijkt me meer werk voor de consumer als er maar 1 item is dat gelinkt wordt, dus even een check. 
Bijvoorbeeld templated link van adres naar Openbare ruimte. Dat is er nooit meer dan 1.

**Comment by fsamwel** [comment]
@NicoleKortoomsBAG waaruit concludeer je dat overal templated links zijn gebruikt? In de huidige implementatie zijn die niet (overal) gebruikt. 

We gebruiken voor alle links één generieke definitie van een HAL link. 

Het is aan het Kadaster om te kiezen waar en wanneer de link templated wordt aangeboden. In de specificaties is daarom overal een property "templated" opgenomen, waarmee in het bericht kan worden aangegeven of de link templated is. Dit kan per link worden aangegeven en dus per link verschillen, hoewel enigszins consequent gebruik hiervan wel handig is. 

Zelfde speelt ook voor de BRK API, waar we ook aan het zoeken zijn naar de juiste keuzes voor templated links: https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/issues/467

**Comment by NicoleKortoomsBAG** [comment]
Ik zie overal templated = true staan. 
Maar ik ben geen ontwikkelaar, uit je antwoord begrijp ik dat ik dat fout heb geïnterpreteerd.

**Comment by JohanBoer** [comment]
> Ik zie overal templated = true staan.
> Maar ik ben geen ontwikkelaar, uit je antwoord begrijp ik dat ik dat fout heb geïnterpreteerd.

De waarde "true" is een example value (voorbeeld): Bij het opstellen van de resource geeft de provider aan of de meegeleverde link templated is of niet. Bij die links die niet templated zijn zal deze waarde dus "false"  zijn. Kan je daarmee uit de voeten @NicoleKortoomsBAG  ?

**Comment by NicoleKortoomsBAG** [comment]
>Kan je daarmee uit de voeten @NicoleKortoomsBAG ?
Ja, is duidelijk
