### ISSUE TITLE
Omschrijving bij endpoint nummeraanduiding wijkt af van andere objecten-endpoints

### ISSUE THREAD

**Issue by NicoleKortoomsBAG** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#201]
bij alle objecten-endpoints wordt aangegeven wat de parameter is. Bij nummeraanduiding niet.
In meervoud, andere objecten in enkelvoud.

Raadpleeg een actuele woonplaats met de identificatie. 
Raadpleeg een actuele openbare ruimte met de identificatie.
Raadpleeg actuele nummeraanduidingen.

**Comment by fsamwel** [comment]
@CathyDingemanse ik ben het met Nicole eens. Kan dit worden "Raadpleeg een actuele nummeraanduiding met de identificatie."?
Of was er een specifieke reden het hier anders te doen?

**Comment by CathyDingemanse** [comment]
> @CathyDingemanse ik ben het met Nicole eens. Kan dit worden "Raadpleeg een actuele nummeraanduiding met de identificatie."?
> Of was er een specifieke reden het hier anders te doen?

Nee, gewoon vergeten. Pas maar aan!
