### ISSUE TITLE
AdresseerbaarObject_links bevat adressen en nummeraanduidingen

### ISSUE THREAD

**Issue by strijm** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#202]
# Impediment
AdresseerbaarObject_links bevat zowel adressen als nummeraanduidingen. Volgens mij is dit dubbelop. De beschrijvingen zijn ook nagenoeg hetzelfde en volgens de goals canvas worden er alleen relaties met adressen en panden teruggegeven en niet met nummeraanduidingen. Volgens mij kunnen de nummeraanduidingen dan ook weg. 
Daarnaast is de description niet heel duidelijk en er zitten nog wat typfoutjes in.

**Comment by JohanBoer** [comment]
@CathyDingemanse Mark refereert hier terecht naar de Goals-canvas en dat daar de nummeraanduidingen niet zijn genoemd. Mee eens dat we de nummeraanduidingen uit de adresseerbaarobject_links halen ?

**Comment by CathyDingemanse** [comment]
@strijm je hebt helemaal gelijk! Deze moeten er idd uit,scherp!

**Comment by fsamwel** [comment]
wordt opgelost in pull request #243

**Comment by strijm** [comment]
Opgelost in #243.
