### ISSUE TITLE
Toelichtingen uit mogelijkonjuist.feature opnemen in yaml

### ISSUE THREAD

**Issue by strijm** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#203]
# Impediment
Kunnen de toelichtingen uit de mogelijkonjuist.feature beschrijving in (bv. een enum) in de yaml worden opgenomen? Daardoor hoeven de toelichtingen niet allemaal handmatig in de code opgenomen te worden en krijgen we aan de client en server kant dezelfde waarden.
Dit levert een consistent geheel en mogelijk minder onderhoudsproblemen op.

**Comment by fsamwel** [comment]
ik ben hier erg op tegen. Enumeraties zijn alleen bedoeld voor gebruikers (clients) om vooraf te weten welke mogelijke waarden ontvangen kunnen worden. Hier kunnen dan algoritmes op worden gebaseerd. Daarom is een enumeratie ook altijd een code (weliswaar begrijpelijk, maar toch een code).

Een enumeratie later uitbreiden of aanpassen leidt altijd tot een breaking change, dus een enumeratie neem je alleen op wanneer dat nodig is voor de clients.

Op zich kunnen we natuurlijk een apart bestandje maken met de toelichtingen, maar die horen m.i. dus niet in het contract en moet eenvoudig gewijzigd kunnen worden zonder dat hiervoor een nieuwe versie van de specificaties/het contract nodig is.

Ik denk eerder dat we nog eens kritisch moeten kijken of mogelijk properties die nu als enum zijn gedefinieerd vanuit bovenstaande redenatie eigenlijk geen enumeratie zouden moeten zijn:
- AdresseerbaarObject.gebruiksdoelen
- OpenbareRuimte.type

**Comment by strijm** [comment]
De toelichting in mogelijkonjuist worden hiermee gevuld. Als dit voor een client verder geen waarde heeft, waarom zitten de toelichtingen dan in de API spec? Wat mij betreft mag de toelichting uit de specificatie verwijderd worden. Als het een beschrijving is van wat het betekent als een boolean true is, dan kan dat beter in de description van iedere boolean worden opgenomen.

**Comment by fsamwel** [comment]
het heeft voor een client wel betekenis. de vraag is op welke manier deze gebruikt wordt.

Het is nu zo opgezet dat:
1. de properties als boolean worden opgenomen, zodat de client software dit kan lezen. Deze weet dan welke van de ontvangen gegevens mogelijk onjuist zijn en op basis daarvan bepaalde dingen wel of juist niet doen.
2. een toelichting, zodat een eindgebruiker (een mens) kan begrijpen wat er aan de hand is

Dus de toelichting is bedoel voor een mens om te lezen en interpreteren.

**Comment by strijm** [comment]
Ik heb toch wel wat moeite met deze constructie:

1.	Hoe bepaalt een client nu welke toelichting bij welke (combinatie van) mogelijkOnjuist attributen hoort?
Bv. als alle booleans true zijn kan er in de toelichting staan: Adres bestaat mogelijk niet (meer). Hoe weet een gebruiker dat de toelichting bij alle attributen, een combinatie van attributen of één van de attributen hoort? Ook de volgorde van toelichtingen lijkt mij hierbij van belang. Hoe borgen we die? Stel attribuut A en B zijn true en in de toelichting array staat eerst de toelichting bij B en dan de toelichting bij A, hoe weet een client dan dat de laatste toelichting bij het eerste attribuut hoort? Welke afspraken maken we hierover?
2.	Ik neem aan dat de toelichting als (meta)data wordt gezien en niet als een UI tekst? Dat laatste lijkt me nl. niet wenselijk, want dan ontstaat er een te strikte koppeling tussen de presentatie (view) en de data (model). Een API is bedoeld om tegenaan te programmeren (Application Programming Interface) zodat er data uitgewisseld kan worden tussen client applicaties en server(s). 
De presentatie aan de gebruiker is de verantwoording van een client. Als een gebruiker de tekst in de client anders wil hebben omdat hij de teksten uit de feature beschrijving niet begrijpt of niet mooi vindt, dan mag het niet zo zijn, dat daarvoor het contract gewijzigd moet worden en daardoor impact aan de server kant ontstaat.

**Comment by fsamwel** [comment]
> Hoe bepaalt een client nu welke toelichting bij welke (combinatie van) mogelijkOnjuist attributen hoort?
Moet een client weten welke toelichting hoort bij welke attributen?

> Ik neem aan dat de toelichting als (meta)data wordt gezien en niet als een UI tekst? 
Zo is het denk ik wel bedoeld.
Er zijn toch meer velden die als zodanig in een UI kunnen worden getoond, zonder specifieke manipulatie in de client? Bijvoorbeeld straat en woonplaats in een adres. 
Het ondersteunt inderdaad niet dat een client de teksten aanpast, omdat deze niet mooi genoeg vonden.
Het alternatief zou zijn om het als codes (enumeratie) door te sturen, maar dat zorgt dan weer voor strikte koppeling tussen de bron (LV BAG) en de API. Het toevoegen, wijzigen of vervallen van een oorzaak voor mogelijkOnjuist leidt dan tot een breaking change.

**Comment by strijm** [comment]
@CathyDingemanse kun jij antwoord geven op de vraag van @fsamwel? Ik weet niet of een client wil weten welke toelichting bij welk(e) attribu(u)t(en) hoort. Ik wilde alleen maar aangeven, dat dit met de huidige constructie in de API specificatie niet mogelijk is. Als het voor een client niet relevant is dit te weten, dan implementeren we het gewoon zoals het nu gespecificeerd is.

**Comment by NicoleKortoomsBAG** [comment]
> Als het voor een client niet relevant is dit te weten, dan implementeren we het gewoon zoals het nu gespecificeerd is.

Als het voor een client niet relevant is, voor wie dan wel? (op die plek?) De uitleg staat voor de ontwikkelaars in de featureomschrijving.

**Comment by fsamwel** [comment]
> Als het voor een client niet relevant is, voor wie dan wel? (op die plek?) De uitleg staat voor de ontwikkelaars in de featureomschrijving.

De feature voor mogelijkOnjuist is geschreven met als doelgroep de ontwikkelaar van de API. Dus de ontwikkelaars van het Kadaster. Deze moet m.i. straks niet gepubliceerd worden (want dat levert het risico dat gebruikers gaan bouwen op specifieke toelichtingsteksten).

De API specificaties zijn geschreven met als (primaire) doelgroep ontwikkelaars van clients.

De mogelijkOnjuist constructie is nu ontworpen op basis van de aannames dat:
- clientsoftware moet kunnen uitlezen of bepaalde ontvangen gegevens mogelijkOnjuist zijn, zodat daar bij het gebruik van deze gegevens in code condities voor kunnen worden opgesteld.
- eindgebruikers van clientsoftware moeten kunnen lezen (in normale mensentaal) wat er aan de hand is met de gegevens, zodat zij de consequenties voor hun proces kunnen inschatten. De toelichting moet dus op zichzelf voldoende informatie bevatten. Een koppeling met specifieke gegevens in het bericht, of een koppeling met specifieke gegevens in de bron (LV BAG) is daarvoor niet nodig. De eindgebruiker ziet noch kent de LV BAG en ziet noch kent de API (berichten).

Wanneer de client de toelichting zou moeten kunnen koppelen aan specifieke mogelijk onjuiste properties, moet een andere constructie worden gekozen. Maar ik zie die noodzaak nu niet uit wat ik begrepen heb van Cathy over de functionele wens.
Wanneer de toelichtingen niet duidelijk genoeg zijn voor een eindgebruiker om op basis daarvan te begrijpen waar de onzekerheid zit (in het kader van hun werk), moeten de toelichtingen duidelijker worden gemaakt. Ik denk dat dit uit de praktijk moet blijken. Dit is precies waarom de oplossing nu zo is opgezet dat op enig moment de toelichtingen verbeterd kunnen worden, zonder dat daarvoor een nieuwe versie van de specificaties nodig zijn.

**Comment by CathyDingemanse** [comment]
Ik kan de bedoeling niet beter beschrijven dan Frank gedaan heeft:

> Het is nu zo opgezet dat:
> 
> 1. de properties als boolean worden opgenomen, zodat de client software dit kan lezen. Deze weet dan welke van de ontvangen gegevens mogelijk onjuist zijn en op basis daarvan bepaalde dingen wel of juist niet doen.
> 2. een toelichting, zodat een eindgebruiker (een mens) kan begrijpen wat er aan de hand is
> 
> Dus de toelichting is bedoel voor een mens om te lezen en interpreteren.


> @CathyDingemanse kun jij antwoord geven op de vraag van @fsamwel? Ik weet niet of een client wil weten welke toelichting bij welk(e) attribu(u)t(en) hoort. Ik wilde alleen maar aangeven, dat dit met de huidige constructie in de API specificatie niet mogelijk is. Als het voor een client niet relevant is dit te weten, dan implementeren we het gewoon zoals het nu gespecificeerd is.

Een gebruiker (niet de software) heeft behoefte aan informatie over mogelijk onjuist bij de adres (zie ook GOALS canvas). Om die reden is met Pieter een mapping gemaakt. Deze heeft geleid tot de feature die door provider moet worden geïmplementeerd.

**Comment by strijm** [comment]
We implementeren het zoals het nu in de openapi.yaml is gespecificeerd. Dit issue kan w.m.b. dan gesloten worden.
