### ISSUE TITLE
Expand bij /panden op panden

### ISSUE THREAD

**Issue by strijm** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#204]
# Impediment
Bij de /panden endpoint is nu een expand parameter gespecificeerd. De resource die wordt teruggegeven is een PandHalCollectie. Deze bevat onder _embedded een property panden van type PandHalBasis. Dit is het enige wat hier te expanden valt er zijn geen gerelateerde resources. Is het niet wat vreemd, dat als er wordt gevraagd om panden, dat de expand dan werkt op de collectie van panden die wordt geretourneerd?
Expand wordt toch veelal gebruikt voor het expanden van gerelateerde objecten die embedded staan en niet op de resource (collectie) zelf?

**Comment by CathyDingemanse** [comment]
Het ging toch om de geo-informatie?

**Comment by strijm** [comment]
Bij een pand valt dat vaak wel mee (er zijn natuurlijk panden met veel punten), maar wat jij waarschijnlijk bedoeld is de geo bij woonplaatsen, daar gaat het vaak wel om veel meer data en daar is het verstandig dit separaat op te vragen. 
Bij /panden kunnen we de expand niet goed plaatsen.

**Comment by fsamwel** [comment]
@CathyDingemanse dat met geo heeft hier denk ik niks mee te maken. Alleen bij woonplaatsen hebben we een expand op geometrie.

@strijm heeft hier m.i. een goede waarneming gedaan, dat er nog een foutje zit in de specificaties. Er is een expand parameter gedefinieerd, terwijl er niks te expanden/embedded is op een pand.

Bij /panden/{pandidentificatie} is de expand parameter al verwijderd, bij /panden is dat blijkbaar vergeten. @JohanBoer kan jij de expand parameter hier verwijderen?

**Comment by JohanBoer** [comment]
Correcte observatie. Is aangepast en in pull request #205 aangeboden
