### ISSUE TITLE
Moet de AdresHalCollectie niet een _links: self bevatten?

### ISSUE THREAD

**Issue by strijm** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#207]
# Impediment
De AdresHalCollectie bevat op dit moment alleen een _embeddded met een array van AdresHal resources. Moet de AdresHalCollectie niet een _links: self krijgen voor de request URI, het is immers een Hal resource? Alle andere HalCollecties hebben wel een _links.

**Comment by fsamwel** [comment]
@JohanBoer vreemd dat we dit niet gezien hebben. Is dit op een gegeven moment weggevallen?

Zou je de _links op de collectie weer willen toevoegen?
