### ISSUE TITLE
Lege waardes moeten niet worden getoond

### ISSUE THREAD

**Issue by KayodeBakker** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#21]
# Impediment

In eerder Haal Centraal API's was de afspraak gemaakt dat alle null, lege objecten en lege array's niet werden getoond. De uitzondering op de regel was bij zoek bevragingspaden waar geen resultaat kon worden gevonden. Dit resulteerde in een HAL collectie object zonder embedded.

In de bevraging 'https://api.test.kadaster.nl/lvbag/api/individuelebevragingen/v1/verblijfsobjecten/0518010000842214' zitten de volgende lege array's:

"inonderzoek": [],
"coordinates": []

**Comment by CathyDingemanse** [comment]
Afspraak team: bij geen waarde de property niet meegeven. Samenvattend: 
Of zowel de property en de waarde
Of geen van beiden
Nulwaarden worden niet teruggeven.

**Comment by strijm** [comment]
De lege array coordinates bleek een nog niet geïmplementeerd onderdeel in de code te zijn. De lege inonderzoek array was wel optioneel gespecificeerd, maar mocht nog leeg zijn, dit is aangepast. De yaml specificaties waren op de meeste plaatsen al correct, op sommige plekken zijn deze strikter gemaakt door een minItems: 1 te specificeren voor (optionele) arrays, waardoor het vrijwel niet meer mogelijk is om lege arrays te retourneren. Ondanks dat blijft de oplossing implementatie afhankelijk, de yaml specificatie dwingen niet af dat e.e.a. goed geïmplementeerd is. 
Bovenstaande afspraken impliceren m.i. ook, dat er een foutmelding wordt gegeven in de situatie dat er geen resultaten zijn, daarom hebben evt. arrays in responses eveneens een minItems: 1 gekregen.

**Comment by JohanBoer** [comment]
We hebben in de sessie van 02-04-2020 afgesproken adat alle "required" en alle "minitems" definities uit de YAML verwijderd worden. Tijdens het testen blijven we dit monitoren. Deze issue sluit ik.
