### ISSUE TITLE
Als tester van een client applicatie wil ik testgevallen

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#212]
zodat ik mijn applicatie kan testen.

Het helpt me dus wanneer ik een aantal objectidentificaties aangereikt krijg om verschillende situaties te testen.

- Voor elk soort gegeven een object weet waarbij deze een waarde heeft.
- voor elk soort gegeven dat soms leeg is een object waarbij deze geen waarde heeft.
- Voor gegevens die meer keer kunnen voorkomen wil ik graag testgevallen waarbij deze 0, 1 en meer (wanneer van toepassing: veel) keer voorkomt. Bijvoorbeeld:
  - meerdere panden op één adres
  - meerdere (veel) adressen in één pand
- Verschillende situaties van gegevens in onderzoek (mogelijkOnjuist), incl. een met meerdere toelichtingsregels op één resource/object
- Voor enumeraties (zoals status, type, gebruiksdoel) testgevallen voor de verschillende mogelijke waarden  
- adressen/nummeraanduidingen met huisletter, huisnummerToevoeging, huisletter+huisnummerToevoeging. Ook t.b.v. zoeken situaties waarbij zelfde huisnummer bestaat zonder huisletter, en met huisletter en/of huisnummerToevoeging (bijv. 1, 1a, 1b, en 2a, 2a-1 en 2a-2)
- adres/nummeraanduiding met lange straatnaam (zodat korteNaam is anders dan straatnaam)
- nevenadres
- geconstateerd

**Comment by fsamwel** [comment]
@NicoleKortoomsBAG kan jij dit doen of zorgen dat iemand dit oppakt?

Ik denk dat er een "getting started" document in GitHub moet komen, waarin ook deze testgevallen genoemd worden. Zie bijvoorbeeld de Getting Started van [BRK](https://github.com/VNG-Realisatie/Haal-Centraal-BRK-bevragen/blob/master/docs/getting-started-brkbevragen.md) en [BRP](https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/master/docs/getting-started.md) met daarin een tabel met testsituaties waarmee aansluiters aan de slag kunnen.

**Comment by fsamwel** [comment]
@NicoleKortoomsBAG of @strijm voor de lopende sprint zoek ik nog specifiek naar een adres met meerdere panden. Hebben jullie daar eentje van?

En een met indicatieNevenadres en een met indicatieGeconstateerd?

**Comment by NicoleKortoomsBAG** [comment]
NUM in meerdere panden: 0193200000096680 en 0512200000019932
NUM die een nevenadres is: 0202200000361263
NUM die geconstateerd is: 0014200022188962
voor later een pand met adressen aan verschillende straten: 0014100010904448
