### ISSUE TITLE
Verwijzingen naar feature beschrijving in API specificatie

### ISSUE THREAD

**Issue by strijm** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#216]
# Impediment
In de API specificatie staan nu verwijzingen naar feature beschrijvingen.
Uit #203 begrijp ik, dat de feature beschrijvingen zijn bedoeld voor de provider en niet zijn bedoeld voor publicatie naar 'externe partijen'. Daarnaast begrijp ik uit dit issue, dat de API specificatie is gericht op de clients en de API specificatie moet wel worden gepubliceerd aan externe partijen.
Het lijkt me dan niet wenselijk in de API specificatie te verwijzen naar feature beschrijvingen die bedoeld zijn voor interne communicatie.

**Comment by fsamwel** [comment]
Sommige features zijn geschreven met als doelgroep de provider, dus die beschrijven hoe de API moet werken. Een voorbeeld daarvan is de mogelijkOnjuist feature.

Sommige andere features zijn geschreven met (ook) als doelgroep een client, dus beschrijven hoe de functionaliteit in de API gebruikt kan worden. Eigenlijk zijn er dan twee doelgroepen, het beschrijft voor de provider hoe de API moet werken en voor de client hoe de functionaliteit gebruikt kan worden. Voorbeelden daarvan zijn de fields en expand features. 
Naar die features zijn links opgenomen in de specs. Reden is dat dit redelijk complexe functionaliteit is, en dat niet goed in de API specificaties (yaml) past.

Op enig moment is het wellicht nuttig features die alleen gericht zijn op implementatie van de API (provider) en niet voor clients relevant zijn (en zelfs riskant i.v.m. coupling aan de implementatie) een andere plek te geven of af te schermen. Dit zou dan kunnen gelden voor de mogelijkOnjuist feature, maar niet voor fields of expand.
