### ISSUE TITLE
Bij het gebruik van fields parameter op adres of nummeraanduiding worden huisletter en huisnummertoevoeging indien aanwezig altijd geleverd, ook als daar niet om is gevraagd

### ISSUE THREAD

**Issue by strijm** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#217]
# Impediment
Als een client met de fields parameter niet heeft aangegeven een huisletter en/of huisnummertoevoeging te willen ontvangen, maar deze zijn wel beschikbaar, dan worden deze door de HuidigeBevragingen API wel teruggegeven. Dit wordt gedaan om fouten aan de client kant te voorkomen. Het is van belang dat de client dit ook weet en zowel het huisnummer alsook de huisletter en/of de huisnummertoevoeging gebruikt. 
Aangezien features voor internen communicatie bedoeld zijn kan dit niet in een feature worden beschreven. De API specificatie is bedoeld voor (externe) client ontwikkelaars, daarom lijkt het mij noodzakelijk om bovenstaande in de endpoint beschrijving in de API specificatie op te nemen.

**Comment by fsamwel** [comment]
Ik ben het er niet mee eens dat alle features alleen voor intern gebruik mogen zijn, zie mijn opmerking daarover in #216.

Een duidelijke beschrijving, met als doelgroep de client developers, van wel meeleveren van niet-gevraagde velden (evt. in combinatie met andere velden) is denk ik een goed voorstel. Dat blijkt nu namelijk nergens uit. De vorm zou wat mij betreft een feature kunnen zijn.
Voor BRK wordt ook een dergelijke feature beschreven

**Comment by strijm** [comment]
Er mag geen beschrijving in de yaml specificatie worden opgenomen, er wordt geen feature beschrijving gemaakt waarnaar verwezen mag worden van de yaml specificatie. Dat wordt dan heel goed testen!
