### ISSUE TITLE
Hoe ziet de expand functionaliteit eruit wanneer de response meerdere objecten levert?

### ISSUE THREAD

**Issue by NicoleKortoomsBAG** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#218]
Bij bijvoorbeeld het bevragen van het adressenendpoint of adresseerbaarobjectenendpoint met pand-id kan dit veel adressen of adresseerbare objecten opleveren. Deze endpoints zijn te expanden. Wanneer de afnemer daar gebruik maakt, wat wordt dan als antwoord verwacht?

**Comment by fsamwel** [comment]
als antwoord wordt verwacht dat de gevonden adressen of adresseerbaar objecten worden teruggegeven inclusief de gevraagde expande gerelateerde resources.

Omdat er heel veel resultaten mogelijk zijn, moeten we paginering gebruiken. Dat is nog niet goed opgenomen in de specificaties, maar moet wel.
