### ISSUE TITLE
Self link van VBO bevraging is anders dan verwacht

### ISSUE THREAD

**Issue by KayodeBakker** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#22]
# Impediment

Tot zo verre is de self link een definitie geweest voor wat de gebruiker exact heeft bevraagd. Mijn bevraging is 'https://api.test.kadaster.nl/lvbag/api/individuelebevragingen/v1/verblijfsobjecten/0518010000842214', maar mijn self link is 'https://api.test.kadaster.nl/lvbag/api/individuelebevragingen/v1/verblijfsobjecten/0518010000842214?geldigOp=2019-12-09&beschikbaarOp=2019-12-09T10:27:52.150242' ofwel meer dan dat ik heb gevraagd.

Is dit correct en een nieuwe werkwijze of klopt dit niet?

**Comment by JohanBoer** [comment]
Hoi Kayo, 
Hier hebben we overleg over gehad en dit is correct. Bij de BAG is de Historie verweven met de actuele bevraging. We hebben afgesproken dat als we een VBO opvragen, dat we dan elleen de actuele versie daarvan krijgen. Impliciet vraag je dus met een geldigop- en beschikbaarop- datum van vandaag op. 

Om de self-link altijd hetzelfde resutlaats op te laten vragen moeten dan deze parameters expliciet gemaakt worden. 
Als na het opvragen een wijziging wordt doorgevoerd en je wilt de self link gebruiken dan zou die een "nieuwer" voorkomen opleveren, terwijl de selflink naar dezelfde resource moet verwijzen. 

Complex verhaal. Kunnen we morgen nog even doornemen indien gewenst.

**Comment by strijm** [comment]
Dit issue heeft betrekking op de individuelebevragingen en niet op de huidigebevragingen omdat bij deze laatste niet met historie wordt gewerkt. Wat mij betreft kan dit issue worden gesloten omdat deze voor huidige bevragingen niet relevant is.
