### ISSUE TITLE
HC common.yaml invalidParams niet gelijk aan foutafhandeling.feature invalid-params

### ISSUE THREAD

**Issue by strijm** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#221]
# Impediment
In de Haal Centraal common.yaml staat een invalidParams van het type InvalidParams. In de feature beschrijving heet deze parameter invalid-params. Het lijkt me goed de feature beschrijving aan te passen zodat deze overeenkomt met de common.yaml.

**Comment by fsamwel** [comment]
opgelost met https://github.com/VNG-Realisatie/Haal-Centraal-common/pull/38

**Comment by strijm** [comment]
Ik had gezien dat dit is opgelost in de common.yaml, alleen is de common.yaml nu niet helemaal consistent meer met de foutafhandeling feature beschrijving. De vraag is of dat per se moet? Persoonlijk vind ik het wel beter als feature beschrijving en common.yaml consistent zijn, vandaar mijn voorstel die aan te passen. Het is een detail dingetje.

**Comment by fsamwel** [comment]
daarom heb ik de feature beschrijving nu aangepast in pull request VNG-Realisatie/Haal-Centraal-common#38

**Comment by strijm** [comment]
Volgens mij kan deze ook worden afgesloten.
