### ISSUE TITLE
Als PO wil ik dat features voor de provider worden gescheiden van features voor consumers

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#224]
...zodat consumers gemakkelijker de voor hen relevante feautures kunnen vinden 
EN mogelijke ongewenste vormen van coupling (veroorzaakt door features voor de achterliggende implementatie van de API) worden voorkomen.  

zie ook #216 

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by JohanBoer** [comment]
Daarbij is het volgens mij ook een goed idee om met een link in de OAS3 aan te geven dat er een feature beschikbaar is waar nodig.
