### ISSUE TITLE
invalidParams ontbreekt bij validatiefout

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#235]
/adressen/abcd geeft terecht een foutmelding, want de opgegeven nummeraanduidingIdentificatie voldoet niet aan het pattern.
De foutmelding bevat echter geen invalidParams waarin de foute parameter wordt genoemd.

**Comment by strijm** [comment]
@fsamwel Johan had ticket #23 in review gezet, maar dat kon nog niet, want wij hebben dit nog niet geïmplementeerd. Komende sprint wordt #23 afgehandeld. Ik zal dan de status van dat ticket updaten. Het heeft nu dus nog niet zoveel zin om bugs aan te maken voor iets wat nog niet is geïmplementeerd.
