### ISSUE TITLE
Waar kan ik een API Key aanvragen of krijgen?

### ISSUE THREAD

**Issue by shazada** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#237]
# Impediment
Voor de gemeente Utrechtse Heuvelrug en ontwikkeling aan Open-Zaak willen we integreren met Haal Centraal.
De YAML beschrijving is geimplementeerd, echter kunnen hebben we geen API key of geen plek waar deze aangevraag kan worden.
Vorige week is er een mail verstuurd naar cathy.dingemanse@denhaag.nl maar of dit de juiste persoon is weet ik niet :).
De mail komt van de firma Contezza

**Comment by CathyDingemanse** [comment]
@shazada heb aan het kadaster gevraagd om aan jou een API key te verstrekken.
Als je binnen een week nog niets hebt gehoord, laat het even weten. Meestal gaat dit heel snel!

**Comment by shazada** [comment]
Dankjewel!

**Comment by shazada** [comment]
Hoi @CathyDingemanse moet er voor BRP en BRK eigen API Key's aangevraagd worden?

**Comment by CathyDingemanse** [comment]
voor BRK, zie https://formulieren.kadaster.nl/aanmelden_brk_bevragen. Deze API is deze week live gegaan. Succes!

**Comment by CathyDingemanse** [comment]
Voor BRP kan ik een API key regelen op de testimplementatie van de gemeente Den Haag. Er is echter nog geen centrale BRP API operationeel (bij RvIG). Die wordt eind 2020 verwacht.
