### ISSUE TITLE
Adres vindt alleen woonplaats

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#239]
/adressen/zoek?zoek=landinrichtingscommissie
vindt een adres:
```
         {
            "omschrijving" : "Laan van de landinrichtingscommissie Duiven-Westervoort 1, 6922KZ Duiven",
            "identificatie" : "adr-5c01945883b0f0390d7a52f8462b0686"
         }
```

/adressen?zoekresultaatidentificatie=adr-5c01945883b0f0390d7a52f8462b0686
levert dit adres:
```
{
   "_embedded" : {
      "adressen" : [
         {
            "woonplaats" : "Duiven",
            "woonplaatsIdentificatie" : "2096",
            "_links" : {
               "woonplaats" : {
                  "href" : "https://api.bag.acceptatie.kadaster.nl/esd/huidigebevragingen/v1/woonplaatsen/2096"
               }
            }
         }
      ]
   }
}
```

Hier wordt alleen de woonplaats van het adres teruggegeven.

**Comment by NicoleKortoomsBAG** [comment]
@ frank
Dit komt waarschijnlijk doordat in de testomgeving naar de productieomgeving van pdok wordt verwezen, maar de BAGdata wordt opgehaald op testdatabase. Die is van februari 20018. Dit adres is pas in 2019 ontstaan.

**Comment by fsamwel** [comment]
@NicoleKortoomsBAG dat dacht ik eerst ook, maar er is wel een woonplaats gevonden. Is dat vanuit de implementatie te verklaren?

**Comment by strijm** [comment]
@fsamwel
Het adres kan wel bij de locatieserver worden gevonden, maar dat is een productie omgeving en de data daarin verschilt met de data in de database in de acceptatie omgeving.
1. De openbare ruimte komt voor in de database in de acceptatie omgeving: 0226300000136166.
2. Het pand komt voor in de database in de acceptatie omgeving: 0226100000008856
3. Het verblijfsobject komt NIET voor in de database in de acceptatie omgeving: 0226010000038820
4. De nummeraanduiding komt NIET voor in de database in de acceptatie omgeving: 0226200000038923
De openbare ruimte naam had evt. nog vermeld kunnen worden in het adres, ik zal een ticket aanmaken om hiernaar te laten kijken. Feit blijft, dat het geen compleet adres oplevert door verschillen in de acceptatie en productie database. 
Ik zal een DBA vragen of deze set geupdate kan worden zodat deze overeenkomt met de data in productie en

**Comment by fsamwel** [comment]
> Feit blijft, dat het geen compleet adres oplevert door verschillen in de acceptatie en productie database.

duidelijk. Van mij hoef je verder geen bijzondere dingen te doen om dit op te lossen, behalve wanneer je data in acceptatie volledig gelijk kan krijgen aan productie (als dat redelijkerwijs mogelijk is). anders is het toch maar toeval wat men vindt en of dat goed gaat.

Ik wilde met het issue alleen zeker stellen dat er hier geen fout zit in de implementatie en vooral niet in het ontwerp

**Comment by fsamwel** [comment]
vergelijkbaar geval: /adressen?zoekresultaatIdentificatie=adr-599beab10dec75188189811bc0057c60

**Comment by fsamwel** [comment]
Wanneer het ophalen van een zoekresultaat niks vind door inconsistentie tussen locatieserver en BAG server, is het dan niet netjes om een 500 fout te geven?

- Nu is het resultaat dat de gebruiker een antwoord krijgt in onjuist formaat (levert waarschijnlijk technische fout in client op)
- Door een 500 fout te geven wordt (hopelijk) het probleem opgemerkt bij functioneel beheer van de BAG API en kan daar iets aan worden gedaan. Zonder foutmelding blijft het onopgemerkt
