### ISSUE TITLE
Herbruikbaarheid binnen de specificatie

### ISSUE THREAD

**Issue by KayodeBakker** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#24]
# Impediment

Omdat er meerdere specificaties zijn, is het lastiger voor een ontwikkelaar om code te genereren. Als bijv. alleen de nummeraanduiding en verblijfsobject specificaties worden gebruikt dan worden er in sommige gevallen objecten twee keer gegenereerd. Een voorbeeld is 'NummeraanduidingIO' dat bij beiden wordt opgenomen.

Naast het feit dat dit onhandig is voor een ontwikkelaar die vervolgens uit zijn/haar gegeneerde code de duplicaten moet uitfilteren, zorgt het er ook voor dat onderhoud van de specificaties lastiger wordt. Een object dat bij verschillende specificaties wordt gedefinieërd, zal dus op meerdere plekken worden aangepast bij wijzigingen. Ook brengt dit het risico met zich mee van inconsistentie. Het zou makkelijk kunnen gebeuren dat in één specificatie een object een wijziging mist.

Voorstel zou zijn om deze in een common.yaml te plaatsen om dit soort risico's en problemen te voorkomen.

**Comment by strijm** [comment]
Dit is issue is niet van toepassing op de HaalCentraal BAG Bevragen API, maar op de BAG Individuele Bevragingen API. Daar zijn de yaml specificaties inmiddes dermate veranderd, dat ik me afvraag of dit issue nog steeds speelt. Ik denk dat we dit issue kunnen sluiten. Mocht blijken dat er met de nieuwste versie van de BAG Individuele Bevragingen API, nog code generatie problemen zijn, dan kunnen die gemeld worden via de github repo van BAG Individuele Bevragingen API.
