### ISSUE TITLE
Consequent toepassen casing op parameters

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#241]
alle parameters zijn nu lower case, behalve pageSize. Ik denk dat het mooier is hier een consequente keuze in te maken. Dat betekent dan dat de parameter wordt "pagesize".

Verder is er op NL API strategie https://github.com/Geonovum/KP-APIs/issues/205 wordt voorgesteld dat queryparameters in lowerCamelCase worden geschreven. Wellicht moeten we daar dan nu op vooruitlopen?

**Comment by fsamwel** [comment]
N.B. paginering staat nu in de planning, dus van de lopende sprint. @strijm kunnen we dit nog aanpassen zonder grote consequenties?

**Comment by strijm** [comment]
Ik zie in het genoemde ticket naast een voorstel voor lowerCamelCase nog een aantal andere voorstellen voor schrijfwijzen (kebab, snake etc.), maar ik zie geen duidelijk besluit dat lowerCamelCase in de NL API Strategie gestandaardiseerd wordt.
M.i. kunnen we nu twee dingen doen:
1. We wachten totdat er een definitief besluit is over de schrijfwijze van parameters, attributen etc. Dat strookt echter niet met de wens om binnen afzienbare tijd live te gaan.
2. We besluiten nu zelf welke schrijfwijze we hanteren en accepteren daarmee het risico, dat als het besluit voor een schrijfwijze in de NL API strategie anders wordt dan degene die wij nu besluiten toe te passen, dit een breaking changes oplevert zodra we de API aanpassen zodat deze wel voldoet aan de voorgeschreven schrijfwijze in de NL API Strategie.

Bij onderstaande ben ik er vanuit gegaan dat een geresolvede yaml specificatie wordt gepubliceerd en niet de niet geresolvede yaml specificatie.

Als we vooruit willen lopen op het gebruiken van lowerCamelCase dan betekent dit, dat veel andere parameter namen niet conform de specificatie zijn en bv. pageSize juist wel. Veel/de meeste  property namen zijn wel in lowerCamelCase maar parameter namen niet en het argument om voor lowerCamelCase te kiezen bij parameters, is dat bij sorteren of filteren de naam van de parameter dan overeenkomt met de property naam van een resource. Bij sorteren en filteren gebruik je sowieso al de property naam. Bij het zoeken met een query parameter geldt dit echter wel. In dat geval zullen dus de parameter namen die niet voldoen aan lowerCamelCase aangepast moeten worden.
Bovenstaande betekent overigens impliciet, dat de path en query parameter dus nooit dezelfde naam meer kunnen hebben voor dezelfde property (hetzelfde gegeven) als deze globaal gedefinieerd worden, althans niet in de niet geresolvede yaml specificatie. Wat eigenlijk de stelling om de query parameter naam gelijk te kiezen aan een property naam ontkracht. Het is nl. veel logischer om de path parameter gelijk te kiezen aan de property naam en niet de query naam. Overigens is het wel zo dat in de geresolvede yaml het wel mogelijk is om dezelfde parameter naam voor een query en path parameter te hebben, omdat ze dan niet meer globaal maar lokaal binnen de endpoint gedefinieerd worden. Het gebruik van kebab-case is dan juist wel handig, omdat de resolver tool alles vanaf de '-' weg laat. Of dit voor snake_case ook werkt durf ik niet met zekerheid te zeggen, maar daar ga ik wel vanuit.

Kortom, mijn voorstel is om alle resource properties en path parameters namen lowerCamelCase te maken en de query parameter namen een combinatie van lowerCamelCase en kebab-case. Het lowerCamelCase deel kan dan verwijzen naar een property naam (maar hoeft niet) en de kebab-case extensie bevat '-query' (zoals het nu is gedaan). 
Dit om zo snel mogelijk live te kunnen gaan, wachten op de standaard lijkt geen optie.
Dit betekent dat niet pageSize gerenamed moet worden, maar alle andere parameters en attributen (waar nodig).
Bv.: 
- locatie-query (query parameter) kan zo blijven, wordt locatie in geresolvede yaml.
- nummeraanduidingidentificatie (path parameter) voldoet niet aan de lowerCamelCase notatie en moeten hernoemd worden naar nummeraanduidingIdentificatie. Hier ontstaat dan weer het issue, dat er ook een parameter nummeraanduidingidentificatie-query (query parameter) is die dan hernoemd moet worden naar iets anders dan nummeraanduidingIdentificatie, omdat die naam al wordt gebruikt voor de path parameter voor hetzelfde gegeven.
- nummeraanduidingidentificatie-query (query parameter) wordt dan w.m.b. nummeraanduidingIdentificatie-query. 

Er moet in de NL API Strategie standaard dus ook een schrijfwijze gedefinieerd worden voor een path en query parameter voor hetzelfde gegeven binnen dezelfde API voor het geval deze globaal worden gedefinieerd. Daarbij kan rekening worden gehouden met het gebruik van een resolver die globale parameter definities verplaatst naar lokale definities en het deel van de parameter namen achter '-' verwijdert.

Het veranderen van de parameter (en evt. property) namen heeft impact op de code. Dat kan niet gedurende de huidige sprint en zal in een volgende sprint opgepakt moeten worden. Hoe groot de impact is, ligt aan de hoeveelheid wijzigingen en zal door het development team ingeschat moeten worden.

**Comment by fsamwel** [comment]
@strijm dank voor je analyse. ik ben het met je eens. Voordat we beslissen om de wijziging door te voeren, of welke wijziging, moeten we denk ik de impact op de afgegeven planning wel weten.

Gelukkig heeft dit geen betrekking op Path parameters (die bestaan alleen in de specs en komen niet voor in de url) of headers (die zijn case insensitive). Of heeft dit toch impact op jullie implementatie?
De namen van de schema componenten hoeven niet gewijzigd te worden denk ik, zeker niet wanneer dat op enig manier impact heeft op de implementatie.

Het gaat dus om de volgende parameters:
Als we pageSize wijzigen naar pagesize:
- /adressen/zoek
- /adressen
- /adresseerbareobjecten

Als we de andere parameters wijzigen naar camelCase:
- /adressen
	• pandidentificatie
	• adresseerbaarobjectidentificatie
- /adresseerbareobjecten
	• nummeraanduidingidentificatie
	• pandidentificatie
- /panden
	• adresseerbaarobjectidentificatie

Kan je de impact van beide scenario's (laten) inschatten?

**Comment by strijm** [comment]
Ga ik voorleggen aan het team.

**Comment by strijm** [comment]
Beide opties zijn weinig werk. De tweede optie kost misschien ietsje meer tijd maar zeker geen uren. Ons voorstel is dan ook om toch optie 2 te implementeren. Deze is duidelijker leesbaar en beter toekomstbestendig aangezien het er op lijkt dat dit ook in de NL API strategie opgenomen zal worden.

**Comment by fsamwel** [comment]
@JohanBoer zou jij dit kunnen doorvoeren? Ik ben het eens met @strijm dat gebruik lowerCamelCase voor parameters beter is. 

N.B. de header parameters moeten niet worden aangepast, wel queryparamters.

**Comment by strijm** [comment]
Ik pak deze wel even op. Wij willen de yaml specificaties z.s.m. definitief hebben, anders blijft er impact op de implementatie ontstaan met uitloop tot gevolg.

**Comment by fsamwel** [comment]
@strijm is dit dus ook al toegepast in de implementatie? Of is hier een ander issue voor?

**Comment by strijm** [comment]
nee, deze had ik niet moeten sluiten moet naar implement, excuus/
