### ISSUE TITLE
openbareruimte of openbareRuimte?

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#242]
Adres_links heeft property "openbareRuimte"
Adres_embedded heeft property "openbareruimte"

Ik denk dat het in Adres_links correct staat, namelijk in lowerCamelCase.

@JohanBoer kan je dit corrigeren in Adres_embedded naar "openbareRuimte"?

**Comment by strijm** [comment]
Ik pak deze wel even op.
