### ISSUE TITLE
self link van collecties wordt automatisch page en pageSize toegevoegd

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#244]
Op dit moment bevat de self link van collecties waarbij pagenering mogelijk is altijd page en pageSize. 

Dat is m.i. niet terecht, want deze self link moet de request tonen die geleid heeft tot de getoonde response.

Bijvoorbeeld /adressen/zoek?zoek=bestaatniet%20nootdorp
Dit levert geen resultaten, maar wel page en pageSize toegevoegd aan de self link:
```
{
   "_links" : {
      "self" : {
         "href" : "https://api.bag.test.kadaster.nl/esd/huidigebevragingen/v1/adressen/zoek?zoek=bestaatniet%20nootdorp&page=1&pageSize=20"
      },
      "first" : {
         "href" : "https://api.bag.test.kadaster.nl/esd/huidigebevragingen/v1/adressen/zoek?zoek=bestaatniet%20nootdorp&page=1&pageSize=20"
      }
   },
   "_embedded" : { }
}
```

**Comment by strijm** [comment]
Ik begrijp dat dit gedrag mogelijk anders is dan verwacht. Het is overigens de vraag of dit erg is. Een client ziet in dit geval dat de API voldoet aan de API specificatie, is dat een probleem? Als de client deze informatie niet nodig heeft of nuttig vindt, kan hij deze gegevens ook gewoon negeren. Daarnaast was het gewenste gedrag op het moment van implementeren nog niet gespecificeerd en daarom zijn we uitgegaan van hetgeen we al wel wisten en de default gedrag zoals die in het framework zit dat we gebruiken.
Je kunt er dus over twisten of dit issue een bug of juist gewenst gedrag. Als er nl. geen page en pageSize is opgegeven bij de endpoints waar paginering wordt ondersteund, dan zorgt het framework dat wij gebruiken er standaard voor dat de default wordt gebruikt voor deze parameters, zoals gespecificeerd in de API specificatie. De URI die heeft geleid tot dit resultaat is dus eigenlijk de URI met de page en pageSize parameters, in dit geval met de gespecificeerde default waarden. De afwijking is dus prima te verklaren. Als er geen parameter wordt opgegeven en er zou geen default zijn gespecificeerd in de API specificatie, dan zou het gedrag ook anders zijn. In dat geval hadden we waarschijnlijk ook meer invloed op het gedrag gehad.
De implementatie van de parameter afhandeling bij default waarden (zoals vastgelegd in de API specificatie) is onmogelijk te veranderen, zonder het framework zelf aan te passen. Persoonlijk vind ik dat veel te ver gaan. Ik denk ook dat dat een vrij kostbare aangelegenheid gaat worden en dat we er verstandig aan doen onze tijd te besteden aan het oplossen van andere issues. 
Dit framework is één van de meest gebruikte frameworks in de wereld, waarmee ik niet wil zeggen dat er geen fouten in kunnen zitten, maar ze hebben vast ook de standaarden gevolgd en goed nagedacht over een juiste implementatie daarvan.

**Comment by fsamwel** [comment]
Het is m.i. niet zo erg dat je framework functionaliteit moet gaan omzeilen ofzo. Goed dat je dit aangeeft. @MelvLee kan een client er last van hebben wanneer de self link van een collectie iets anders teruggeeft dan de request die je gedaan hebt?

Het gaat dus tussen het verschil in definitie van een self-link van een collectie:
1. een url met de zoekvraag die leidt tot de getoonde collectie
2. de request url

Het opnemen van defaultwaarden in de url die niet in het request zaten voldoet wel aan 1. maar niet aan 2.

**Comment by MelvLee** [comment]
Ik denk dat de meeste consumers er geen last van zullen hebben. De enige case dat ik kan bedenken dat het fout gaat, is als de consumer asynchroon (tegelijk) meerdere requests naar de provider stuurt. Het is dan mogelijk dat de response van een (iets) later verstuurde request eerder wordt ontvangen. De manier om dan te achterhalen bij welke request de response hoort, is de self link vergelijken met de verstuurde requests. Als de self link niet hetzelfde is als de request, dan wordt het moeilijk voor de consumer om dat te bepalen.

**Comment by fsamwel** [comment]
afgesproken dat dit moet worden opgelost, maar hoeft niet voor livegang

**Comment by strijm** [comment]
Graag even opnieuw testen. Dit probleem is als het goed is opgelost in de laatste versie op onze acceptatie omgeving.

**Comment by fsamwel** [comment]
opgelost
