### ISSUE TITLE
404 fout bij niks vinden

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#245]
De standaardwerking voor zoeken (collecties) is dat bij zoeken geen fout wordt teruggegeven, maar een lege collectie.

Op dit moment levert dit echter een 404 Not found.
Bijvoorbeeld /adressen?zoekresultaatidentificatie=adr-bestaatniet
Bijvoorbeeld /panden?adresseerbaarobjectidentificatie=1234567890123456
Bijvoorbeeld /panden?locatie=50095%2C808495
{
   "status" : 404,
   "title" : "Opgevraagde resource bestaat niet.",
   "type" : "https://tools.ietf.org/html/rfc7231#section-6.5.4",
   "detail" : "Geen pand(en) gevonden",
   "instance" : "https://api.bag.acceptatie.kadaster.nl/esd/huidigebevragingen/v1/panden?locatie=50095%2C808495",
   "code" : "notFound"
}

**Comment by NicoleKortoomsBAG** [comment]
@fsamwel, 
Ik zou zeggen dat het in de voorbeelden niet gaat om zoeken, maar om het bevragen (van een collectie) via een ander uniek ID dan het objectid van de resource zelf.  Als je dit type bevraging gebruikt, dan heb je een uniek object ID (of denk je dat te hebben).

**Comment by fsamwel** [comment]
Naar mijn idee mag je alleen een 404 geven als je een onjuiste uri (unieke resource identificatie) hebt gebruikt, zie https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html: "The server has not found anything matching the Request-URI"

De uri van een pand is bijvoorbeeld: /panden/1234107890123456. Wij bouwen de uri op in een pad. In het geval van een pand is dat "/panden/" gevolgd door de pand identificatie. We hebben in de api geen resources die geïdentificeerd worden met query parameters. Dus /panden?adresseerbaarobjectidentificatie=1234567890123456 is niet de uri van een pand.
De uri /panden is een "collectie", dus een zoekresultaat, ook wanneer een zoekparameter maximaal één pand kan vinden. 
Hetzelfde geldt voor adressen op zoekresultaatidentificatie.

**Comment by fsamwel** [comment]
zelfde/vergelijkbaar probleem speelt bij opgeven van een page die niet bestaat (page>last).

Bijvoorbeeld /adressen?pandidentificatie=0826100000000467&page=12&pageSize=7
```
{
   "status" : 404,
   "title" : "Opgevraagde resource bestaat niet.",
   "type" : "https://tools.ietf.org/html/rfc7231#section-6.5.4",
   "detail" : "Not found.",
   "instance" : "https://api.bag.acceptatie.kadaster.nl/esd/huidigebevragingen/v1/adressen?pandidentificatie=0826100000000467&page=12&pageSize=7",
   "code" : "notFound"
}
```

**Comment by strijm** [comment]
In de vorige sprint is de foutmelding geïmplementeerd zoals die in de paginering.feature is gespecificeerd. Er wordt in het geval dat er een pagina wordt opgevraagd die niet bestaat, een 400 fout gegeven.
Dit staat nu in onze acceptatie omgeving, misschien goed om dit te hertesten.

**Comment by fsamwel** [comment]
Deze is niet helemaal opgelost. De volgende verzoeken leveren een 404 fout i.p.v. een 200 met lege _embedded:
- /adressen?zoekresultaatIdentificatie=adr-bestaatniet
- /panden?adresseerbaarObjectIdentificatie=1234567890123456
- /panden?locatie=50095%2C808495

**Comment by strijm** [comment]
Wordt in huidige sprint opgelost.
