### ISSUE TITLE
ingetrokken verblijfsobject geeft 404 Not found of 410 Gone

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#248]
/adresseerbareobjecten/0518010000781839
Dit geeft een 404 (Not found).
Dit verblijfsobject heeft status "Verblijfsobject ingetrokken".

Moet deze dan niet status 410 Gone hebben?

@MelvLee @JohanBoer @strijm Hoe zien jullie dit? Wat verwacht je bij een resource die een eindstatus heeft?

**Comment by strijm** [comment]
Afweging:
Om onderscheid te maken tussen objecten die nu niet meer bestaan / een eind status hebben (maar in het verleden wel bestonden) en objecten die nu niet bestaan (en ook nooit bestonden), kan het gebruik van een 410 resp. 404 handig zijn. De 410 heeft een meer permanent karakter dan een 404. Bij 410: iets is er wel geweest, maar is er nu niet meer. Bij 404: was er niet, is er niet, maar kan er in de toekomst nog wel komen. 
De 410 status code geeft aan dat er een bewuste keuze is gemaakt om een resource te ‘verwijderen’. Dat is bij het toekennen van een eindstatus aan een object in principe het geval, maar objecten kunnen herleven vanuit bepaalde eind statussen indien ze ten onrechte een eind status hebben gekregen (zie BAG Catalogus 2018 par. 3.6 punt 13).
De vraag is dus of de eind status een permanent karakter heeft en het een bewuste keuze is om deze aan een object toe te kennen.
De intentie is m.i. dat het toekennen van een eindstatus aan een object permanent is en dat dit een bewuste keuze is. Dat zou er voor pleiten om status code 410 te gebruiken.
Mensen kunnen echter fouten maken en op het moment dat er ten onrechte een eindstatus wordt toegekend aan een object, dan is dat (waarschijnlijk) geen bewuste keuze. Op dat moment verdwijnt echter het permanente karakter, want de fout mag hierna hersteld worden. Het lastige hiervan is dat het maken van een fout een onbewuste actie is en dat we dus ook niet weten in hoeverre de eind status van een object juist is omdat we niet weten of er een fout is gemaakt. Daardoor weten we dus ook niet of de eind status permanent is of niet. Dat zou er voor kunnen pleiten om status code 404 te gebruiken. 
Feit blijft echter, dat het object bestond en nu niet meer bestaat of nu niet meer bestaat maar wel had moeten bestaan (omdat deze onterecht een eind status heeft gekregen). Dit is dus iets anders dan de situatie dat het object helemaal niet bestaat. 
Mijn advies zou dan ook zijn om status code 410 te gebruiken. Met de kanttekening dat het kan zijn dat het object er in de toekomst dus wel weer kan zijn als een ten onrechte toegekende eind status wordt gewijzigd naar een status anders dan een eind status!

**Comment by NicoleKortoomsBAG** [comment]
Vanuit een totaal andere kant bekeken,
Je geeft zo wel impliciet informatie over niet huidige voorkomens terwijl de keus is gemaakt om alleen huidige gegevens te tonen.

**Comment by fsamwel** [comment]
@MelvLee kan het onderscheid tussen 410 en 404 voor een gebruiker relevant zijn?

**Comment by MelvLee** [comment]
Ik denk het wel. 404 betekent in principe dat de consumer een fout heeft gemaakt. Bij 410 weet de consumer dat de resource heeft bestaan maar dat het niet meer 'huidig' is. Ik denk daarom dat de reactie van de consumer bij 410 anders zal zijn dan bij 404.

**Comment by JohanBoer** [comment]
Ik ben het met Melvin (en Mark) eens dat er een onderscheid moet zijn tussen de foutmelding op een resource die nooit bestaan heeft en een resource die wel bestaan heeft, maar nu niet meer bestaat.

**Comment by strijm** [comment]
Wat Nicole aangeeft (en waar ik het ook wel mee eens ben) is dat deze HC API alleen huidige informatie teruggeeft. In dit geval is het dan  beter een 404 terug te geven. Er is nl. geen huidige informatie. Als er in dit geval een 410 geretourneerd zou worden, dan geeft dat aan dat er in het verleden wel informatie is geweest. Dat is historische informatie. Aangezien er met deze HC API huidige en geen historische informatie opgevraagd kan worden, matcht dat niet met elkaar. De vraag is inderdaad ook of een 410 dan relevante informatie oplevert voor de clients/afnemers. Het gaat er immers om dat een client weet dat er nu geen huidige informatie is.

**Comment by JohanBoer** [comment]
Er is voor beide varianten wat te zeggen. Ik denk dat we hier met een business-vraagstuk te maken hebben. Is het voor de afnemers relevant om te weten dat een resource bestaan heeft en er nu niet meer is. Ik denk dat dat in de meeste gevallen zo is, of er in de bron nu historie zit of niet. Ik denk dat @CathyDingemanse  hier vanuit businessperspectief kan aangeven wat het beste past.

**Comment by fsamwel** [comment]
Besproken in overleg met @strijm @NicoleKortoomsBAG en @MelvLee. Argumentatie:
- 410 betekent dat de resource niet meer bestaat én  nooit meer zal bestaan
- een eindstatus kan onterecht zijn en dus weer terugwijzen naar een actuele status

Conclusie: geven 404 is gewenste antwoord
