### ISSUE TITLE
Versionering opgenomen in de URL

### ISSUE THREAD

**Issue by KayodeBakker** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#25]
# Impediment

Kijkende naar de aangeleverde endpoint voor VBO bevragingen, is er een versie nummer te vinden in de URL, namelijk https://api.test.kadaster.nl/lvbag/api/individuelebevragingen/**v1**/verblijfsobjecten/{identificatie}

Los van de discussie of versionering handig is of niet, zou ik niet zeggen dat een versie in een URL te plaatsen een goed idee is. Met Haal Centraal is het mogelijk dat er tussen de registraties URL's ontstaan naar andere registraties. Als bijvoorbeeld de BRP API URL's verwerkt heeft voor de BAG en de BAG wordt geüpdatet, dan dient de BRP API ook een update te krijgen.

Beter is om de versionering, als überhaupt gewenst, te ondersteunen als header dan als onderdeel van de URL. Zo is het aan de gebruiker zelf om bij te houden welke versie ze willen ondersteunen.

**Comment by strijm** [comment]
De yaml specificaties voor de LV BAG Individuele Bevragingen API volgen hier de 
[NL API strategie](https://docs.geostandaarden.nl/api/API-Strategie/) (7.1.18 API-20). Hierin staat:

> The URI of an API should include the major version number only.

Als er een verbetervoorstel is, dus een goede reden om af te wijken van de NL API strategie, dan horen wij dat graag.

**Comment by JohanBoer** [comment]
Cathy heeft bij de landelijke API-strategie in [deze issue](https://github.com/Geonovum/KP-APIs/issues/7) uitgelegd waarom er geen versienummer in de URL moet worden opgenomen. Deze argumentatie versterkt het vebetervoorstel dat Melvin Lee in [deze issue](https://github.com/Geonovum/KP-APIs/issues/157) heeft gedaan.

**Comment by lennartvanbergen-kadaster** [comment]
In principe volgen we de API strategie, tenzij er sterke redenen zijn om het niet zo te doen. 

Dit is een inhoudelijke punt die je op verschillende manieren kan oplossen. Ik zie in die discussie op KP-API geen dwingende of goede redenen voor duidelijk het een of het andere. Misschien is iemand vergeten om aan te tonen wat er precies echt helemaal mis gaat, of welke enorme kans we hier missen? Het lijkt een beetje op smaak/voorkeur stijl te zitten. 

Jullie vraag lijkt te zijn: _vooruitlopend op de behandeling van dit item bij KP-API, kunnen we het alvast zo gaan doen?_ 

Dat hangt er gewoon van af of de kans groot is dat bij dit item bij KP-API ook die kant op gaat. Zo ja, dan kunnen we dit alvast gaan doen. Kwestie van dit punt daar goed onder de aandacht brengen met de verwachting dat dit snel bediscussieerd wordt, het hoort immers bij een standaard om urgente punten tijdig te bespreken.

**Comment by lennartvanbergen-kadaster** [comment]
Persoonlijke mening: ik zie geen reden om dit anders te doen. URL's zijn er om op te routeren. Het lijkt mij handig dat je kan routeren met een /v1 in een URI.

**Comment by strijm** [comment]
Is dit issue blocking voor de live gang van de HC dienst, of kunnen we voorlopig besluiten om het versienummer in de URI te zetten?

**Comment by JohanBoer** [comment]
Er is al besloten dat HC zich op dit punt conformeert aan de API-strategie. Dus het major versienummer wordt opgenomen in de URL.

**Comment by strijm** [comment]
Top. Dan graag een review dat de yaml spec hieraan voldoet, dan kunnen we dit ticket sluiten. Review kan op basis van #83.
