### ISSUE TITLE
first (en evt. last) link bij paginering niet altijd tonen

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#254]
zie https://github.com/VNG-Realisatie/Haal-Centraal-common/issues/48

Op dit moment wordt bij collecties met paginering de first link altijd getoond. Dat is niet het gewenste gedrag voor de API. De first link moet alleen worden getoond bij page>1.

Hetzelfde geldt voor de last link. Deze moet alleen worden getoond wanneer page<{last page}

Bijvoorbeeld als de zoekvraag 5 pagina's levert:
```
| page | first | previous | next | last |
| 1    | nee   | nee      | ja   | ja   |
| 2    | ja    | ja       | ja   | ja   |
| 3    | ja    | ja       | ja   | ja   |
| 4    | ja    | ja       | ja   | ja   |
| 5    | ja    | ja       | nee  | nee  |

```
Bijvoorbeeld als de zoekvraag 1 pagina oplevert, worden links first, previous, next en last niet opgenomen.

**Comment by fsamwel** [comment]
afgesproken dat dit moet worden opgelost, maar hoeft niet voor livegang

**Comment by strijm** [comment]
Hiervoor is een release nodig van de HC common..yaml. De huidige versie/tag 1.0.0 bevat bovenstaande wijziging niet en die is voor het correct implementeren van de paginering feature wel nodig. Op dit moment wordt er vanuit de HC BAG API yaml verwezen naar common.yaml versie 1.0.0. Dit moet aangepast worden naar de nieuwe versie van de common.yaml.

**Comment by fsamwel** [comment]
> Hiervoor is een release nodig van de HC common..yaml

Hier doel je op toevoeging van last? Want de hier beschreven functionaliteit (niet altijd tonen van first) kan denk ik wel zonder release.

**Comment by strijm** [comment]
Ja, dat klopt inderdaad.

**Comment by fsamwel** [comment]
Toevoegen last link is apart issue: https://github.com/VNG-Realisatie/Haal-Centraal-BAG-bevragen/projects/1#card-41412436

**Comment by fsamwel** [comment]
Paginering werkt nu op adresseerbareobjecten wel zoals beschreven, dus dat er geen first wordt geleverd op de eerste pagina. Nu werkt de paginering dus niet consistent binnen de API. Kan dezelfde code die nu gebruikt is voor adresseerbareobjecten niet hergebruikt worden voor de andere operaties met paginering? Dan hebben we het consistent en is dit issue direct opgelost
