### ISSUE TITLE
Opschonen foutresponses

### ISSUE THREAD

**Issue by strijm** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#255]
Als HC willen we dat alleen foutresponses in de API specificatie staan, die ook worden ondersteund, zodat clients en provider weten welke foutresponses ondersteund en afgehandeld moeten worden.

**Acceptatiecriteria**
- Alleen foutmeldingen die nu ondersteund worden staan in de API specificatie. 
- Alle foutmeldingen die door de API ondersteund worden, staan in de API specificatie. Dit houdt in dat ook de foutmeldingen die door een evt. API gateway en niet door de applicatie implementatie (bv. 401, 403, 429, 503) worden gegenereerd, onderdeel zijn van de API specificatie.

Foutmeldingen kunnen door een API gateway of in de applicatie (implementatie) zelf worden ondersteund.
- Momenteel worden ondersteund in applicatie: 200, 400, 404, 406, 412, 500, 501 (van de laatste is de vraag of deze in het contract moet, dit lijkt nl. niet heel zinvol)
- Momenteel worden ondersteund in API gateway: 401, 403, 503
- Momenteel worden niet ondersteund in applicatie: 204, 409, 410, 415, 422
- Momenteel worden niet ondersteund in de API gateway: 429

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by fsamwel** [comment]
we hebben gisteren afgesproken dat @strijm dit uitzoekt in de applicatie en vervolgens een pull request indient om dit te wijzigen

**Comment by strijm** [comment]
Dit issue is afhankelijk van #264. Als besloten wordt om 415 toch te ondersteunen, dan moeten we daar bij dit issue rekening mee houden.
