### ISSUE TITLE
Tags onjuist?

### ISSUE THREAD

**Issue by strijm** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#256]
Een aantal endpoints staan nu onder de tag Adres in de yaml specificatie:

- /woonplaatsen/{woonplaatsidentificatie}:
- /openbareruimten/{openbareruimteidentificatie}:
- /nummeraanduidingen/{nummeraanduidingidentificatie}:

Is het niet beter om deze onder de tags: Woonplaats, Openbare ruimte en Nummeraanduiding te plaatsen, zodat deze ook in Swagger onder een apart tag komen te staan?

**Comment by strijm** [comment]
@CathyDingemanse Kun jij deze vraag beantwoorden?

**Comment by JohanBoer** [comment]
Even ruggespraak gehad met @CathyDingemanse . Dit was op verzoek van Cathy op deze manier gedaaan en dat is ook zoals we het bedoeld is. Graag zo houden.
