### ISSUE TITLE
huisletter en huisnummerToevoeging meeleveren bij huisnummer

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#261]
Wanneer met fields wel huisnummer wordt gevraagd, maar niet huisletter en/of huisnummertoevoeging, moeten toch alle drie geleverd worden. Althans dat is -als ik het me goed herinner- in eerder overleg zo gesteld als eis vanuit de bewaarder.

Nu wordt dit echter niet meegeleverd.
/adressen/0484200002040489?fields=postcode%2Chuisnummer levert:
```
{
   "huisnummer" : 1,
   "postcode" : "2391PH",
   "_links" : {
      "self" : {
         "href" : "https://api.bag.acceptatie.kadaster.nl/esd/huidigebevragingen/v1/adressen/0484200002040489?fields=postcode%2Chuisnummer"
      }
   }
}
```

Zonder fields krijg ik ook:
```
   "huisletter" : "A",
   "huisnummertoevoeging" : "3",
```

**Comment by fsamwel** [comment]
Was er niet ook gesteld dat identificatie altijd geleverd moet worden?

Bijvoorbeeld /woonplaatsen/2258?fields=documentdatum%2Cstatus bevat geen identificatie:
{
   "status" : "Woonplaats aangewezen",
   "documentdatum" : "2012-06-15",
   "_links" : {
      "self" : {
         "href" : "https://api.bag.acceptatie.kadaster.nl/esd/huidigebevragingen/v1/woonplaatsen/2258?fields=documentdatum%2Cstatus"
      }
   }
}

**Comment by strijm** [comment]
Als er een huisnummer wordt gevraagd met fields, maar huisletter en huisnummertoevoeging niet, terwijl ze er wel zijn, dan moeten ze inderdaad altijd worden geleverd.

HC wilde de identificatie niet altijd hebben en moet dus ook gefilterd kunnen worden met fields.

**Comment by fsamwel** [comment]
ik zie nu dat voor een nummeraanduiding het samen leveren van huisnummercomponenten wel geïmplementeerd is.

**Comment by fsamwel** [comment]
Althans /nummeraanduidingen/0484200002040489?fields=huisnummer levert ook huisletter en huisnummertoevoeging.
Maar /nummeraanduidingen/0484200002040489?fields=huisletter levert alleen de huisletter.
En /nummeraanduidingen/0484200002040489?fields=huisnummertoevoeging levert zowel huisletter als huisnummertoevoeging, maar niet het huisnummer

**Comment by fsamwel** [comment]
dit geldt ook voor vragen specifieke velden met expand. Dus adressen.huisnummer moet ook adressen.huisletter meeleveren.

/adresseerbareobjecten?nummeraanduidingIdentificatie=0484200002040489&expand=adressen.huisnummer%2Cadressen.straat

levert:
           "_embedded" : {
               "adressen" : [
                  {
                     "straat" : "Belgiëlaan",
                     "huisnummer" : 1
                  }
               ]
            }

Hier zijn dus huisletter en huisnummertoevoeging niet meegeleverd
