### ISSUE TITLE
Welke foutmelding bij ontbrekende coördinaat?

### ISSUE THREAD

**Issue by strijm** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#263]
Als er bij het zoeken met een geometrie 0 of 1 coördinaat wordt opgegeven i.p.v. minimaal 2 welke foutmelding wil HC dan ontvangen?

We gaan er vanuit dat het gaat om een Parametervalidatie fout.
Voor deze situatie is geen goede validatie, reason en code gespecificeerd voor invalidParams.
Deze moeten worden toegevoegd.

Voorstel:
```
| validatie       | reason                                                  | code        |
| minItems        | Array bevat minder items dan verwacht {minItems}.       | minItems    |
| maxItems        | Array bevat meer items dan verwacht {maxItems}.         | maxItems    |
```

**Comment by fsamwel** [comment]
De foutmelding die ik verwacht is inderdaad een 400 parametervalidatie, met invalidParams.name=locatie

Goed voorstel voor de vulling. Ik zal een pull request daarvoor op de feature doorvoeren.

**Comment by fsamwel** [comment]
Ik stel een iets andere toelichting voor:
  | minItems         | Array bevat minder dan {minItems} items.                  | minItems     |
  | maxItems         | Array bevat meer dan {maxItems} items.                    | maxItems     |

**Comment by fsamwel** [comment]
@strijm ik kan je om de een of andere reden niet toevoegen als reviewer op het pull request. Zou je deze wel kunnen beoordelen of die goed is?
https://github.com/VNG-Realisatie/Haal-Centraal-common/pull/50/files
