### ISSUE TITLE
statuscode 406 i.p.v. 415 bij onjuiste content-Crs

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#264]
Wanneer een request wordt gestuurd met query-parameter locatie, en met content-crs die niet ondersteund wordt (epsg:4326) wordt nu een status code 406 teruggegeven:
{
   "status" : 406,
   "title" : "Gevraagde contenttype wordt niet ondersteund.",
   "type" : "https://tools.ietf.org/html/rfc7231#section-6.5.6",
   "detail" : "Header: Accept-Crs moet 1 van [epsg:28992] zijn",
   "instance" : "https://api.bag.acceptatie.kadaster.nl/esd/huidigebevragingen/v1/panden?locatie=98095%2C438495",
   "code" : "notAcceptable"
}

Ik betwijfel of dit correct is. 406 Not Acceptable is voor zover ik begrijp bedoeld voor de gevraagde content-type of content-crs. Hier gaat het om de meegestuurde content-crs. Ik denk dat dan 415 Unsupported Media Type de juiste is.

@MelvLee en @strijm zie ik dat goed?

**Comment by strijm** [comment]
Ik snap de verwarring. 
Wij hebben destijds ook zitten kijken wat nou de beste optie is. Het vervelende is, dat 415 in de NL API strategie specifiek is gedefinieerd voor content-type, maar het gaat hier over content-Crs. Een equivalente foutcode voor content-crs is niet gespecificeerd. Volgens de NL API strategie is 406 eigenlijk meer bedoeld om aan te geven dat de in accept-Crs header gevraagde CRS niet wordt ondersteund. Echter staat er als beschrijving bij 406: 
> Reponse to an unsupported format request (part of content negotiation)
In 17.9 API-24: Support Content Negotiation staat ook de 406 status code genoemd.
Wij vonden in dit geval de 406 code beter passen omdat er bij 406 in ieder geval wordt gesproken over CRS en dat het formaat in de request niet ondersteund wordt, maar deze matched idd. ook niet 100 %.
Als HC hier graag 415 ziet, dan kunnen we dat aanpassen, maar in dat geval lijkt het mij verstandig om een wijziging door te voeren in de NL API strategie, zodat de scope voor statuscode 415 iets ruimer wordt. Deze gaat dan niet meer alleen over content**-type** negotiation. In dit geval zou deze dan beter over alle content negotiation kunnen gaan, dus ook die van CRS.

**Comment by strijm** [comment]
@fsamwel wat gaan we hier nu mee doen? Moet ik hier een 415 van maken?

**Comment by fsamwel** [comment]
@MelvLee welke verwacht jij? of maakt het niet uit?

**Comment by fsamwel** [comment]
wanneer dit via een 400 gaat, moet bij het vragen van een niet ondersteunde content-crs de code enum gebruikt worden: "Waarde heeft geen geldige waarde uit de enumeratie."

{
"status" : 400,
"title" : "Een of meerdere parameters zijn niet correct.",
"type" : "https://tools.ietf.org/html/rfc7231#section-6.5.1",
"detail" : "Header: Content-Crs moet 1 van [epsg:28992] zijn",
"instance" : "https://api.bag.acceptatie.kadaster.nl/esd/huidigebevragingen/v1/panden?locatie=98095%2C438495",
"code" : "paramsValidation",
"invalidParams": [ {
   "name": "Content-Crs",
  "reason": "Waarde heeft geen geldige waarde uit de enumeratie.",
  "code": "enum"
} ]
}

In geval van sturen locatie waarbij er geen content-crs is meegestuurd, denk ik dat sprake is van "Minimale combinatie van parameters moet worden opgegeven.", Bijvoorbeeld:
{
"status" : 400,
"title" : "Minimale combinatie van parameters moet worden opgegeven.",
"type" : "https://tools.ietf.org/html/rfc7231#section-6.5.1",
"detail" : "Header: Content-Crs is verplicht bij zoeken op locatie.",
"instance" : "https://api.bag.acceptatie.kadaster.nl/esd/huidigebevragingen/v1/panden?locatie=98095%2C438495",
"code" : "paramsCombination"
}

@MelvLee is dit hoe je het bedoelt?

@strijm hiervoor is op zich geen toevoeging aan de feature noodzakelijk. (hoewel het toevoegen van bovenstaande twee scenario's wel de boel verduidelijkt. Ik zal deze toevoegen.

**Comment by strijm** [comment]
Ik heb even overleg gehad met iemand die ook aan de NL API Strategie meewerkt. Hij geeft ook aan dat een 415 in dit geval de best passende foutmelding is. Volgens de NL API Strategie geldt deze voor content-type maar in de https://tools.ietf.org/html/rfc7231#section-6.5.13 staat het volgende:

`The 415 (Unsupported Media Type) status code indicates that the origin server is refusing to service the request because the payload is in a format not supported by this method on the target resource. The format problem might be due to the request's indicated Content-Type or Content-Encoding, or as a result of inspecting the data directly.
`
Zal ik er dan toch maar een 415 van maken?

**Comment by fsamwel** [comment]
Oke dan doen we 415

**Comment by fsamwel** [comment]
ik heb het pull request voor de featurebeschrijving hier ook op aangepast. Ook situaties voor accept-crs toegevoegd
