### ISSUE TITLE
opvragen link zonder _links geeft fout

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#265]
Wanneer in de fields parameter de naam van een _links property wordt opgenomen geeft dit een foutmelding.
Bijvoorbeeld /openbareruimten/0599300000002397?fields=status%2Cwoonplaats geeft een 500 fout.
/openbareruimten/0599300000002397?fields=status%2C_links.woonplaats geeft geen fout, maar geeft het correcte gefilterde antwoord terug

De fields feature zegt hierover: "In de fields parameter kan de relatie worden gevraagd door de relatienaam op te nemen al dan niet voorafgegaan door HAL-element _links."

Dus _links.woonplaats moet te vragen zijn met fields=woonplaats én met fields=_links.woonplaats

**Comment by strijm** [comment]
Dit issue is m.i. onterecht. Zie https://github.com/VNG-Realisatie/Haal-Centraal-common/issues/44.
woonplaats wordt hier als een soort alias gebruikt, wat volgens de NL API Strategie niet mag.

**Comment by fsamwel** [comment]
Zie mijn opmerking in VNG-Realisatie/Haal-Centraal-common#44. We kunnen dit issue in ieder geval parkeren tot we een beslissing hebben genomen over dat issue.

**Comment by strijm** [comment]
Voor nu hebben we afgesproken, dat we alleen expliciete fieldnamen ondersteunen en geen 'aliassen'. Dus als er een property woonplaats is en een _link.woonplaats, dan kunnen deze beide worden opgegeven en dan geven we beide terug. Het opgeven van fields=woonplaats zal voorlopig niet resulteren in het leveren van zowel property woonplaats als _links.woonplaats. Na de livegan zal dit nader besproken worden zoals aangegeven in:  VNG-Realisatie/Haal-Centraal-common#44.

**Comment by NicoleKortoomsBAG** [comment]
@fsamwel @JohanBoer @MelvLee @CathyDingemanse 
Naar aanleiding van de reacties op deze story bij de refinement met het team wil ik het graag nog eens hierover hebben.

**Comment by NicoleKortoomsBAG** [comment]
@fsamwel 
Dit issue kan denk ik gesloten worden. Na overleg in september is geconstateerd dat deze feature voor BAG onnodig ingewikkeld is. Afgesproken is dat de featurebeschrijvingen voor BAG, BRK en BRP niet gelijk worden gemaakt op dit punt en BAG zo simpel mogelijk wordt gehouden. Dit betekende een extra feature binnen expand en fields voor BRK en BRP omdat het daar wel een zinvolle feature is.
