### ISSUE TITLE
self link wijzigt array serialisatie

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#266]
/panden?locatie=98095.02%2C438495.09

geeft in het antwoord:
```
   "_links" : {
      "self" : {
         "href" : "https://api.bag.acceptatie.kadaster.nl/esd/huidigebevragingen/v1/panden?locatie=98095.02&locatie=438495.09"
      }
   },
```

De locatie parameter is gedefinieerd met explode=false, maar de self link is gemaakt op basis van explode=true.

**Comment by strijm** [comment]
@fsamwel weet je zeker dat de titel van dit issue juist is?
