### ISSUE TITLE
alle coordinaten in locatie na de tweede lijken te worden genegeerd

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#267]
/panden?locatie=98095.02%2C438495.09%2C15000%2C23000.123%2C123456%2C987654321
dit levert een resultaat, hetzelfde resultaat als /panden?locatie=98095.02%2C438495.09

@strijm Is dit correct gedrag? 
Wat betekenen de 3e en volgende coordinaten bij het zoeken van een pand?

**Comment by strijm** [comment]
De coördinaten van de geometrie van verblijfsobjecten en panden kunnen volgens de BAG Catalogus 2D of 3D zijn. In veel gevallen zal de z-coördinaat niet zijn/worden opgegeven en wordt dan 0 gemaakt. Als de z-coördinaat wel is opgegeven, dan wordt deze ook opgeslagen. De geometrie van een pand is 2D dus een vlak. De z-coördinaat geeft dus de evt. hoogte aan waarop het vlak ligt. Als er met een locatie (punt) wordt gezocht in welk pand (vlak) dit punt valt, heeft het geen zin om te zoeken met een z-coördinaat omdat het over een plat vlak gaat. Als je dit wel zou doen, welk resultaat verwacht je dan als de z-coördinaat van de locatie boven of onder het vlak zou liggen? Het zou alleen maar meer 404 fouten opleveren en dat is niet erg klantvriendelijk. Wij ondersteunen het zoeken met een z-coördinaat op dit moment daarom ook niet en leveren de pand(en) waar de locatie met (x, y) coördinaat binnen het vlak valt.
Het zoeken met een z-coördinaat wordt interessant bij 3D objecten, maar die zitten zoals gezegd nog niet in de LV BAG. 
Als er wordt gezocht met een 3e (z) of volgende coördinaat, dan worden deze genegeerd.

Conclusie:
De LV BAG ondersteund het zoeken met een z-coördinaat op dit moment nog niet, 3e en volgende coördinaten die worden opgegeven, worden genegeerd.

**Comment by fsamwel** [comment]
@strijm moet de specificatie dan niet worden aangepast dat er ook maximaal 2 of maximaal 3 coordinaten mogen worden opgegeven?

**Comment by JohanBoer** [comment]
@fsamwel We maken hiervoor nu gebruik van de opengis-definities voor pointGeoJSON. Als we hier een maxItems aan toevoegen moeten we een eigen definitie maken. Als dat nodig is doen we dat, maar als dit gebruikelijk zou zijn in de geo-wereld dan had die maxItems er bij opengis al wel in gestaan. Ben hoe @strijm hier naar kijkt.

**Comment by JohanBoer** [comment]
Heren, Negeer mijn commentaar maar. Ik keen in de definitie van de property zelf.......

**Comment by fsamwel** [comment]
Moet ik nog wijzigen in mijn test en dan testen.

@strijm zit dit in sprint 13?

**Comment by strijm** [comment]
Toch nog een vraag of opmerking hierover. Tijdens implementatie lopen we tegen het volgende aan:
Als we maxItems toevoegen en er worden een z-coördinaat (of meer) meegegeven, dan ontstaat er een foutmelding omdat de input afwijkt van hetgeen is gespecificeerd in de OAS.
Als de z-coördinaat of volgende genegeerd moet worden zonder een foutmelding, dan kan de maxItems niet gespecificeerd worden.
Wat wil HC? 
1. maxItems specificeren en een foutmelding teruggeven of
2. geen maxItems specificeren en overbodige coördinaten negeren.

**Comment by strijm** [comment]
Foutmelding 400 met maxItems teruggeven.
