### ISSUE TITLE
adresseerbaarObjectIdentificaties en nummeraanduidingIdentificaties ontbreken in panden

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#268]
/panden/0484100000045095

dit bevat in het antwoord:
   "_links" : {
      "self" : {
         "href" : "https://api.bag.acceptatie.kadaster.nl/esd/huidigebevragingen/v1/panden/0484100000045095"
      },
      "adressen" : [
         {
            "href" : "https://api.bag.acceptatie.kadaster.nl/esd/huidigebevragingen/v1/adressen/0484200002040489"
         }
      ],
      "adresseerbareObjecten" : [
         {
            "href" : "https://api.bag.acceptatie.kadaster.nl/esd/huidigebevragingen/v1/adresseerbareobjecten/0484010002033603"
         }
      ]
   }

Er is dus een gerelateerd adres en een gerelateerd adresseerbaar object. Dus had ik ook in het antwoord nummeraanduidingIdentificaties en adresseerbaarObjectIdentificaties verwacht, maar die komen niet voor in het antwoord.

**Comment by strijm** [comment]
duplicaat van #249
