### ISSUE TITLE
woonplaats ontbreekt in nummeraanduiding

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#269]
/nummeraanduidingen/0014200022188962 bevat geen woonplaatsIdentificatie en ook geen _links.woonplaats

/adressen/0014200022188962 bevat wel een link naar een woonplaats:
```
   "woonplaatsIdentificatie" : "1070",
   ...
   "_links" : {
      ...
      "woonplaats" : {
         "href" : "https://api.bag.acceptatie.kadaster.nl/esd/huidigebevragingen/v1/woonplaatsen/1070"
      },
```

gerelateerde openbare ruimte /openbareruimten/0014300010784805 heeft ook een woonplaats:
```
   "woonplaatsIdentificatie" : "1070",
   "_links" : {
      ...
      "woonplaats" : {
         "href" : "https://api.bag.acceptatie.kadaster.nl/esd/huidigebevragingen/v1/woonplaatsen/1070"
      }
```

@NicoleKortoomsBAG kan het kloppen dat er geen relatie is naar een woonplaats vanuit deze nummeraanduiding?
@CathyDingemanse moet een nummeraanduiding in dat geval de woonplaats overerven uit de openbare ruimte (zoals wel gebeurt bij een adres)? Of moet de nummeraanduiding alleen de gegevens tonen zoals die bij de nummeraanduiding zijn opgeslagen? (wanneer dit straks ook voor synchronisatie gebruikt moet worden wellicht wel?)

**Comment by fsamwel** [comment]
@NicoleKortoomsBAG of @strijm heb je een voorbeeld nummeraanduiding waarbij er wel een gerelateerde woonplaats is? Is er ook een voorbeeld waarbij de woonplaats van de nummeraanduiding afwijkt van de woonplaats van de openbare ruimte?

**Comment by strijm** [comment]
0118200000264072
0307200000534874
0362200001221879
