### ISSUE TITLE
Object voor KenmerkOpenbareRuimteInOnderzoek wordt vreemd gegenereerd

### ISSUE THREAD

**Issue by KayodeBakker** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#27]
# Impediment

Gegenereerd via https://editor.swagger.io/
Gekozen voor 'Generate Server' en dan 'aspnetcore'

Het object 'KenmerkOpenbareRuimteInOnderzoek' bevat een attribuut genaamd kenmerk volgens de specificaties wat een 'InOnderzoekOpenbareRuimte' is. Het genereren van KenmerkOpenbareRuimteInOnderzoek resulteert daarentegen niet in een 
`
public InOnderzoekOpenbareRuimte kenmerk { get; set; }
`

maar in een compleet nieuwe initiatie van dat object, namelijk:

```
        public enum InOnderzoekOpenbareRuimte
        {
            /// <summary>
            /// Enum NaamEnum for naam
            /// </summary>
            
            NaamEnum = naam,
            /// <summary>
            /// Enum TypeEnum for type
            /// </summary>
            
            TypeEnum = type,
            /// <summary>
            /// Enum StatusEnum for status
            /// </summary>
            
            StatusEnum = status,
            /// <summary>
            /// Enum GerelateerdeWoonplaatsEnum for gerelateerde woonplaats
            /// </summary>
            
            GerelateerdeWoonplaatsEnum = gerelateerde woonplaats        }

        /// <summary>
        /// Gets or Sets Kenmerk
        /// </summary>
        [Required]
        [DataMember(Name="kenmerk")]
        public InOnderzoekOpenbareRuimte? Kenmerk { get; set; }
```

Ik wil voorstellen om te kijken hoe dit bijv. met 'AanduidingInhoudingVermissingReisdocument_enum' bij Reisdocument van de BRP API specificaties wordt gedaan. Hier genereert het wel goed op dezelfde generatie wijze.

**Comment by strijm** [comment]
@MelvLee: kun jij controleren of er uit de geresolvede yaml specificatie v.w.b. enums juiste code wordt gegenereerd? Als dat zo is, dan kan dit issue gesloten worden. 
Dit issue heeft overigens meer betrekking op de individuelebevragingen dan op huidigebevragingen omdat kenmerk<object type>inonderzoek zaken niet (meer) voorkomen in de huidigebevragingen API. 
Verder is de definiie in de BAG yamls hetzelfde als bij BRP, alleen gebruikt de BRP dubbele quotes om de enumeratie waarden en BAG enkele. Dit maakt echter geen enkel verschil, want in de geresolvede yaml specificatie zijn in beide gevallen de quotes verdwenen.

**Comment by MelvLee** [comment]
Niet meer van toepassing in de BAG yamls
