### ISSUE TITLE
Inconsistentie bij page parameter fout

### ISSUE THREAD

**Issue by strijm** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#270]
Als er een page parameter wordt opgegeven, die niet bestaat, dan moet er in de foutmelding een invalidParams worden opgegeven, zoals beschreven in de foutafhandeling.feature beschrijving. Dit duidt erop dat er een 400 fout gegeven moet worden. Echter is er gezegd dat er een 404 statuscode teruggegeven moet worden, maar die bevat geen invalidParams.
Moet de feature beschrijving worden aangepast zodat een 404 ook een invalidParams kan bevatten? Dat klinkt niet heel logisch, omdat daar een 400 fout voor bedoeld is. Of moeten we i.p.v. een 404 in dit geval een 400 teruggeven?

**Comment by fsamwel** [comment]
@strijm waar is gezegd "dat er een 404 statuscode teruggegeven moet worden"?

In de feature staat dat er een 400 fout moet worden gegeven. Dat is m.i. ook de juiste response, want er is een onjuiste waarde voor een parameter gegeven.

Een 404 fout is bedoeld voor situaties waarbij de uri niet bestaat. Wanneer queryparameters ertoe lijden dat niks gevonden wordt, kan dat niet de oorzaak zijn voor een 404. Dat doen we consequent zo voor alle situaties, bij het zoeken op specifieke query parameters.

**Comment by strijm** [comment]
OK, dan maken we er een 400 van. Was nog een foutieve aanname.
