### ISSUE TITLE
Waar is de nummeraanduidingIdentificatie queryparameter op panden gebleven?  

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#271]
Dit is een hele belangrijke parameter.

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by fsamwel** [comment]
Wijziging is doorgevoerd n.a.v. #141 en #142, pull request #143, maar was onterecht.

Zie ook issue #252 van @strijm die hetzelfde constateert.

@strijm kan je de impact hiervan bepalen voor onze planning? Deze moet zo snel mogelijk toegevoegd worden. 

@JohanBoer ik vermoed dat dit een release 1.1 wordt.

**Comment by fsamwel** [comment]
Getest op acceptatie en werkt daar goed. Pull request #319 ingediend om het weer in de specificaties (nu voor release 1.1) te krijgen.
