### ISSUE TITLE
opvragen links met fields in /panden levert geen links

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#274]
/panden?adresseerbaarobjectidentificatie=0193010000096628&fields=_links.adresseerbareObjecten%2C_links.adressen

dit levert:
```
{
   "_links" : {
      "self" : {
         "href" : "https://api.bag.acceptatie.kadaster.nl/esd/huidigebevragingen/v1/panden?adresseerbaarobjectidentificatie=0193010000096628"
      }
   },
   "_embedded" : {
      "panden" : [
         {
            "_links" : {
               "self" : {
                  "href" : "https://api.bag.acceptatie.kadaster.nl/esd/huidigebevragingen/v1/panden?adresseerbaarobjectidentificatie=0193010000096628&fields=_links.adresseerbareObjecten%2C_links.adressen"
               }
            }
         },
         {
            "_links" : {
               "self" : {
                  "href" : "https://api.bag.acceptatie.kadaster.nl/esd/huidigebevragingen/v1/panden?adresseerbaarobjectidentificatie=0193010000096628&fields=_links.adresseerbareObjecten%2C_links.adressen"
               }
            }
         }
      ]
   }
}
```

De adressen en adresseerbareObjecten worden dus niet geleverd.

**Comment by strijm** [comment]
@fsamwel ik ben het met je eens dat hier de links naar adressen en adresseerbareobjecten ontbreken bij de panden (onder _embedded).
Ik begrijp alleen niet wat je hier doet met de fields parameter. Misschien kun je dat uitleggen?
Zoals je het nu opgeeft probeer je adressen en adresseerbare objecten onder _links van de collectie te filteren, maar daar zullen nooit _links naar adressen en adresseerbare objecten staan. Die horen nl. onder de panden te staan (die ontbreken hier inderdaad en dat is fout). 
De fields parameter werkt normaal gesproken alleen op properties en _links van een resource. In dit geval is de resource een collectie. De collectie zelf staat onder _embedded. Daar heeft de fields parameter geen invloed op. Met de expand parameter kunnen properties of _links van sub resources onder _embedded (in dit geval panden) worden gefilterd.
Of heb ik iets gemist?

**Comment by fsamwel** [comment]
> Zoals je het nu opgeeft probeer je adressen en adresseerbare objecten onder _links van de collectie te filteren, maar daar zullen nooit _links naar adressen en adresseerbare objecten staan. Die horen nl. onder de panden te staan (die ontbreken hier inderdaad en dat is fout).

> In dit geval is de resource een collectie. 

Fields heeft altijd betrekking op de resource. Een collectie is geen resource, het is een collectie van resources. Dus wanneer je een collectie vraagt hoef je niet _embedded.panden voor velden in fields te zetten. _links.adresseerbareObjecten vraagt dus niet adresseerbareObjecten in de collectie links, maar in de resource links.

**Comment by strijm** [comment]
We zullen dit implementeren zoals hierboven aangegeven door @fsamwel. 
@fsamwel zou je de fields.feature willen uitbreiden met een beschrijving hoe de fields parameter te gebruiken i.c.m. HalCollecties, dat ontbreekt nu. Daardoor was het ons niet helemaal duidelijk wat het gewenste gedrag was bij HalCollecties.
