### ISSUE TITLE
404 fout verwijderen bij /adressen/zoek

### ISSUE THREAD

**Issue by strijm** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#279]
Bij /adressen/zoek kan geen 404 fout optreden. Omdat het een zoek actie betreft, zal er een 400 optreden als er iets mis is met de parameter en als er niets is gevonden zal er een lege resultset worden teruggegeven. Een 404 is dus niet nodig en kan verwijderd worden uit de yaml specificatie. Mee eens?

**Comment by fsamwel** [comment]
is opgelost met #280
