### ISSUE TITLE
Code generatie voor Java werkt niet

### ISSUE THREAD

**Issue by KayodeBakker** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#28]
# Impediment

Het viel op dat de code generatie voor C# niet werkte met een hoop build errors en was ik nieuwsgierig wat het verschil zou zijn met Java als deze wel zou werken. Ik heb vervolgens via https://editor.swagger.io als https://openapi-generator.tech/#try geprobeerd om code te genereren en deze te runnen, echter in beide gevallen krijg ik minimaal nog twee build errors. 
Deze kunnen worden gevonden in AdresseerbaarObject.java als Gemeente.java

``` java
  public AdresseerbaarObject() {
    this.adresseerbaarObjectType = this.getClass().getSimpleName();
  }
```

``` java
  public Gemeente() {
    this.gemeente = this.getClass().getSimpleName();
  }
```

In beide gevallen gaat het om een attribuut dat niet bestaat. Dit ontstaat vanwege de volgende notaties in de verblijfsobject.yaml:

``` openapi
    AdresseerbaarObject:
      title: AdresseerbaarObject
      required:
      - heeftAlsHoofdAdres
      type: object
      properties:
...
      discriminator:
        propertyName: adresseerbaarObjectType
```

``` openapi
    Gemeente:
      title: Gemeente
      required:
      - code
      type: object
      properties:
...
      discriminator:
        propertyName: gemeente
```

Dankzij de notatie discriminator met propertyName wordt dit veroorzaakt. Reden van vermoeden dat dit de oorzaak is, dat er geen andere class een build error lijkt te produceren en alleen deze twee hebben deze notatie.

**Comment by sbarendr** [comment]
We hebben inderdaadd nog wel wat issues met de code generatie, vooral de oneOf en allOf constructies. Tooling lijkt nog onvolwassen.
Het is mij wel gelukt een Java client te genereren en succesvol een request te doen.
Met behulp van deze tool:
https://openapi-generator.tech/docs/installation
En deze yaml:
`groupId: nl.kadaster.bag.vs.online
artifactId: bag-bevragen-2.0-vbo-client
typeMappings:
  OffsetDateTime: java.time.LocalDateTime
importMappings:
  java.time.OffsetDateTime: java.time.LocalDateTime
java8: true
dateLibrary: java8
library: jersey2
serializationLibrary: jackson`

Vervolgens API key configureren in de Javacode en certificaat installeren in cacerts file van gebruikte JVM.

**Comment by KayodeBakker** [comment]
@sbarendr Gek genoeg krijg ik wel de boven genoemde build errors terwijl ik dezelfde tool gebruik als dat jij gebruikt, namelijk openapi-generator. 

Jouw referentie naar een yaml volg ik alleen niet helemaal? Ik gebruik iig de resolved variatie die gisteren op het API Lab ter beschikking is gesteld.

**Comment by sbarendr** [comment]
@KayodeBakker 
Het stukje yaml hierboven is de configuratie voor het genereren zelf. Stel deze yaml staat in een file api-client-vbo.yaml, en de resolved vbo yaml specificatie staat in verblijfsobjecten.yaml, dan is de aanroep van de codegeneratie als volgt:

java -jar openapi-generator-cli-4.2.2.jar generate -g java -i verblijfsobjecten.yaml -c api-client-vbo.yml

Ik heb deze generatie overigens nog onder Java 8 gedraaid, nog niet geprobeerd op Java 11.

**Comment by KayodeBakker** [comment]
@sbarendr Duidelijk.
Specifiek had ik jdk1.8.0_181 in gebruik.

**Comment by strijm** [comment]
Ik stel voor dit issue af te sluiten. Dit issue heeft betrekking op de BAG Individuele Bevragingen API en niet op de Haal Centraal BAG Bevragen API. Inmiddels zijn dit twee afzonderlijke API's geworden en in de HC API komen geen discriminators voor. Daarnaast zijn de yaml voor beide specificaties inmiddels dermate gewijzigd, dat ik vermoed dat de code er sowieso anders uit zal zien. Er is o.a. gekozen om niet (of zo min mogelijk) gebruik te maken van oneOf. Er wordt in de BAG Individudele Bevragingen nog wel gebruik gemaakt van de allOf constructie en discriminator. Mocht in de toekomst blijken, dat er met een nieuwe versie van de yaml specificaties toch nog code generatie problemen zijn, dan kunnen die voor HC API via deze repository worden gemeld. Voor de BAG Individuele Bevragingen API is een aparte repository.
