### ISSUE TITLE
Statussen in mogelijkOnjuist.feature beschrijving kloppen niet

### ISSUE THREAD

**Issue by strijm** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#288]
De 2e tabel in de mogelijkOnjuist.feature beschrijving is niet helemaal correct. De volgende verschillen zijn geconstateerd t.o.v. de yaml specificatie:

1. Regel 106 (Niet gerealiseerd pand), mag verwijderd worden, omdat dit een eindstatus is. Deze zal nooit worden geleved, omdat een object die deze status heeft bij HC niet wordt geleverd.
2. Regel 113 (Niet gerealiseerd verblijfsobject), mag verwijderd worden, omdat dit een eindstatus is. Deze zal nooit worden geleved, omdat een object die deze status heeft bij HC niet wordt geleverd.
3. De status 'Plaats aangewezen' ontbreekt voor de Ligplaats en Standplaats (Adreseerbare objecten) resources. Dit is geen eindstatus en resources met deze status kunnen geleverd worden.
4. De status 'Verblijfsobject buiten gebruik' ontbreekt voor de Verblijfsobject resource. Dit is geen eindstatus en resources met deze status kunnen geleverd worden.
5. De status 'Pand buiten gebruik' ontbreekt voor de Pand resource. Dit is geen eindstatus en resources met deze status kunnen geleverd worden.

Deze wijziging is besproken met @JohanBoer tijdens de dagstart op 9-7-2020.

**Comment by fsamwel** [comment]
> De status 'Plaats aangewezen' ontbreekt voor de Ligplaats en Standplaats (Adreseerbare objecten) resources. Dit is geen eindstatus en resources met deze status kunnen geleverd worden.

Ik denk dat er voor standplaatsen en ligplaatsen maar één status is die geen eindstatus is, namelijk 'Plaats aangewezen'. Dus geldt dan denk ik de toelichting die in regels 69 en 70 staat: "De standplaats bestaat mogelijk niet (meer)." of "De ligplaats bestaat mogelijk niet (meer)."

**Comment by fsamwel** [comment]
Hier hadden we inderdaad aangenomen (blijkbaar onterecht) dat dit een eindstatus is. Bij status 'Verblijfsobject buiten gebruik' stel ik als toelichting voor: "Mogelijk is het verblijfsobject weer in gebruik of is het verblijfsobject ingetrokken." (samenvoeging van de twee zinnen van toelichting die Pieter had opgesteld).

**Comment by fsamwel** [comment]
Idem bij 'Pand buiten gebruik'. Hier stel ik als toelichting voor "Mogelijk is het pand weer in gebruik of is het pand gesloopt."

**Comment by fsamwel** [comment]
punten 1, 2, 4 en 5 opgelost in pull request #289.

**Comment by fsamwel** [comment]
@strijm is hier nu ook iets voor gebouwd (omdat het op Test staat)? Ik denk dat dit alleen over toelichtingen gaat, en die krijg ik nog niet.

**Comment by strijm** [comment]
Sorry, da's mijn fout. Toelichting is nog niet geïmplementeerd. Ik heb alleen een ticket dat bij ons gesloten is, onterecht aan dit issue gekoppeld.

**Comment by fsamwel** [comment]
@strijm moet er nog iets aan de implementatie worden gewijzigd n.a.v. dit issue (en pull request #289)? Of is het al zo gebouwd?
Zo niet, dan kunnen we dit issue sluiten

**Comment by strijm** [comment]
De implementatie komt overeen met hetgeen hierboven is gespecificeerd, we hoeven hiervoor dus niets meer aan te passen.
