### ISSUE TITLE
Als PO wil ik dat de field en expand parameter wordt geimplementeerd

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#29]
...zodat de consumer deze kan gebruiken.

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by strijm** [comment]
In de laatste versie (17-1-2020) van de NL API strategie vind ik niets meer terug over een field parameter. Moet de field parameter nog wel gespecificeerd worden?

**Comment by CathyDingemanse** [comment]
Jazeker. De API strategie zegt niets over de behoefte van afnemers. Het is belangrijk dat afnemers (slechts) kunnen opvragen wat zij nodig hebben.

**Comment by JohanBoer** [comment]
Ik neem aan dat hier geen discussie meer over is. Ik zet hem done en ga ervan uit dat de fields parameter geïmplementeerd wordt. (want hij is gespecificeerd....)
