### ISSUE TITLE
adresseerbaarobjectidentificatie ontbreekt in de mogelijkOnjuist bij Adres

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#290]
In de mogelijkOnjuist feature is adresseerbaarobjectidentificatie wel beschreven, maar in de OAS3 ontbreekt de asresseerbaarobjectidentificatie bij de mogelijkOnjuist.

**Comment by fsamwel** [comment]
Ik neem aan dat je doet op adresseerbaarObjectIdentificatie in de mogelijkOnjuist van adressen. Regel 21 in de feature. Die staat daar denk ik onterecht. Ik heb namelijk in de tabel vanaf regel 46 geen situatie waarin die gevuld zou moeten zijn.

Mocht je toch beslissen adresseerbaarObjectIdentificatie toe te voegen, dan moet deze ook toegevoegd worden in de tabel. En dus bepaald onder welke omstandigheden deze in mogelijkOnjuist wordt opgenomen.

@PieterDijkstraKadaster hoe zie jij dit? Moeten we adresseerbaarObjectIdentificatie ook opnemen in mogelijkOnjuist? Wanneer wordt deze mogelijkOnjuist? Alleen bij nummeraanduiding.status in onderzoek, of heb je ook andere situaties?

**Comment by PieterDijkstraKadaster** [comment]
Het ID van een adresseerbaar object maakt geen onderdeel uit van een adres. Er wordt vanuit het adresseerbaar object verwezen naar een nummeraanduiding in plaats van andersom. Het ID van het adresseerbare object kan wat mij betreft dus niet mogelijk onjuist zijn. Mijn advies is dit niet op te nemen bij mogelijk onjuist.

**Comment by fsamwel** [comment]
Dank Pieter, ik zal de feature corrigeren
