### ISSUE TITLE
Expand gerelateerde resource als relatie in onderzoek is

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#293]
De combinatie van fields met expand is nog niet correct beschreven in de feature mogelijkOnjuist. Dit is de situatie dat de relatie tussen de resource en de met expand gevraagde resource in onderzoek is, en met fields de relatie-velden niet zijn gevraagd.

Bijvoorbeeld:
```
Gegeven bij nummeraanduiding 0018200000152130 is “ligt aan” (openbare ruimte) in onderzoek
En voor gerelateerde openbare ruimte 0018300000000271 is niets in onderzoek
Als ik het request wordt gedaan /adressen/0018200000152130?fields=huisnummer,woonplaats&expand=openbareRuimte
Dan …
```

Hier wordt volgens de huidige feature beschrijving op het adres geen mogelijkOnjuist geleverd, want niks van de openbare ruimte (korteNaam, straat, openbareRuimteIdentificatie) is gevraagd met fields. In de embedded openbareRuimte wordt ook geen mogelijkOnjuist geleverd, want de openbare ruimte zelf is niet in onderzoek.

Dat is denk ik niet juist, want dan blijkt nergens uit dat de geleverde embedded openbare ruimte mogelijk niet de juiste openbare ruimte is.

Dus ik stel voor dat dan alsnog mogelijkOnjuist.openbareRuimteIdentificatie = true wordt geleverd.

`Dan bevat het antwoord mogelijkOnjuist.openbareRuimteIdentificatie met de waarde true`

**Comment by fsamwel** [comment]
@PieterDijkstraKadaster @strijm @JohanBoer hoe denken jullie hierover? Lost dit het probleem op?

Of moeten we aan mogelijkOnjuist een property "_embeddedOpenbareRuimte" toevoegen?:
```
   "mogelijkOnjuist" : {
      "_embeddedOpenbareRuimte" : true,
   },
```

**Comment by JohanBoer** [comment]
> Of moeten we aan mogelijkOnjuist een property "_embeddedOpenbareRuimte" toevoegen?:

Ik vind jouw eerste voorstel : 

> Dus ik stel voor dat dan alsnog mogelijkOnjuist.openbareRuimteIdentificatie = true wordt geleverd.

de lading beter dekken. Deze identificatie is de weergave van de relatie. En dat is wat in dit geval mogelijkOnjuist is.

**Comment by PieterDijkstraKadaster** [comment]
Hiermee los je het volgens mij inhoudelijk goed op. Ik denk dat het wel handig is te beschrijven wat er feitelijk aan de hand kan zijn (of te verwijzen naar de toelichting van mogelijk onjuist) zodat duidelijk is wat er mogelijk onjuist is als het ID van de gerelateerde openbare ruimte op true staat: 

Er is mogelijk een verkeerde straat(naam) gebruikt. Het adres moet verwijzen naar de huidige straat waaraan het adres ligt

**Comment by fsamwel** [comment]
Ik denk dat dan hetzelfde geldt voor links. 

```
      Gegeven bij nummeraanduiding 0018200000152130 is “ligt aan” (openbare ruimte) in onderzoek
      Als ik het request wordt gedaan /adressen/0018200000152130?fields=_links.openbareRuimte
      Dan bevat het antwoord:
        """
            "mogelijkOnjuist": {
                "openbareRuimteIdentificatie": true,
                "toelichting": [ "Mogelijk verkeerde straat gebruikt. Het adres moet verwijzen naar de straat waaraan het adres ligt." ]
            }
        """
```

**Comment by fsamwel** [comment]
Maar dat betekent dat voor het verwijderen van adresseerbaarObjectIdentificatie in mogelijkOnjuist van adressen (#290 #292)? 
@PieterDijkstraKadaster zei hierover:
> Het ID van een adresseerbaar object maakt geen onderdeel uit van een adres. Er wordt vanuit het adresseerbaar object verwezen naar een nummeraanduiding in plaats van andersom. Het ID van het adresseerbare object kan wat mij betreft dus niet mogelijk onjuist zijn. Mijn advies is dit niet op te nemen bij mogelijk onjuist.

Er wordt wel een adresseerbaarObjectIdentificatie en _links.adresseerbaarObject geleverd bij een adres. Moet de gebruiker dan niet geïnformeerd worden wanneer dit gegeven mogelijk onjuist is, omdat onderliggende relatie (vanuit adresseerbaar object richting nummeraanduiding) in onderzoek is?

Moet er dan niet worden aangegeven:
```
      Gegeven bij verblijfsobject 0014010011038456 is "Heeft als hoofadres" in onderzoek
      En gegeven "Heeft als hoofadres" heeft de waarde 0014200010844073
      Als ik het request wordt gedaan /adressen/0014200010844073?fields=_links.openbareRuimte
      Dan bevat het antwoord:
        """
            "mogelijkOnjuist": {
                "openbareRuimteIdentificatie": true,
                "toelichting": [ "Mogelijk verkeerde straat gebruikt. Het adres moet verwijzen naar de straat waaraan het adres ligt." ]
            }
        """
```

**Comment by fsamwel** [comment]
Idem voor pandIdentificatie in adressen.

Of kiezen we ervoor bij _links niet te communiceren dat de relatie onzeker is?

**Comment by PieterDijkstraKadaster** [comment]
Er zijn twee soorten relaties: 
1. het geleverde object verwijst naar een ander object 
2. het geleverde object is een gerelateerd object vanuit een ander object.

In het eerste geval is de relatie een attribuut van het object. In het tweede geval niet. In de BAG kan ook alleen de eerste situatie als mogelijk onjuist worden aangemerkt. Dat is namelijk een attribuut. 

Formeel kan het ID van een adresseerbaar object niet fout zijn als we de situatie benaderen vanuit de nummeraanduiding (adres).  

Vanuit een Adreseerbaar object kan overigens de relatie met een hoofdadres niet aangepast worden in de BAG. Een adresseerbaar object ID en een nummeraanduidingID van het hoofdadres zijn onlosmakelijk met elkaar verbonden. 

Dit is een ander soort relatie dan de relatie met een openbare ruimte of een pand. Die kunnen wel wijzigen. Ik zou ervoor kiezen hierover geen informatie te leveren over relaties die niet expliciet in het model benoemd zijn omdat het niet duidelijk is wat dit precies betekent. Je gaat de relaties anders interpreteren dan bedoeld. 

Kortom: Ik zou de relaties naar Pand en adresseerbaar object achterwege laten bij mogelijk onjuist bij de adressen API.

**Comment by fsamwel** [comment]
@PieterDijkstraKadaster duidelijk (niet dat ik het helemaal begrijp, maar dat hoef ik gelukkig ook niet). Hoeven we dus geen extra identificaties toe te voegen aan de mogelijk onjuist

**Comment by NicoleKortoomsBAG** [comment]
@JohanBoer , deze story gaat idd ook over het toepassen van fields, maar daardoor niet in je response meekrijgen dat de relatie vanuit de nummeraanduiding naar de openbare ruimte in onderzoek staat. 
Mogelijk wil je deze toch weer openen.

**Comment by JohanBoer** [comment]
Op verzoek van Nicole weer geopend. @NicoleKortoomsBAG Zou jij dan willen schetsen welk probleem er exact speelt (eventueel in overleg met @PieterDijkstraKadaster zodat we mee kunnen denken over de oplossing ?

**Comment by fsamwel** [comment]
@NicoleKortoomsBAG @strijm 

Zie /adressen/0846200000007550?expand=woonplaats&fields=straat,huisnummer

dit geeft
    "mogelijkOnjuist": {
        "woonplaats": true,
        "woonplaatsIdentificatie": true,
        "toelichting": [
            "Woonplaats bestaat mogelijk niet."
        ]
    
Waarom wordt dit nu meegeleverd? Wanneer "Ligt in gerelateerde woonplaats" in onderzoek had gestaan, dan had ik dat begrepen. Maar dan had de toelichting anders moeten zijn (Mogelijk verkeerde woonplaats gebruikt. Het adres moet verwijzen naar de woonplaats waarin het adres fysiek ligt.)

Net zoiets bij /adressen/0848200000363584?expand=woonplaats&fields=straat,huisnummer
    "mogelijkOnjuist": {
        "woonplaats": true,
        "woonplaatsIdentificatie": true,
        "toelichting": [
            "Geometrie of woonplaatsgrens is mogelijk onjuist, waardoor gaten of overlappingen ontstaan in de registratie van woonplaatsen. Gevolg kan zijn dat een object in een verkeerde woonplaats, in twee woonplaatsen, of in geen enkele woonplaats ligt.",
            "Woonplaats bestaat mogelijk niet.",
            "Woonplaatsnaam is mogelijk onjuist geschreven."
        ]
    },

De eerste toelichting, over de geometrie had ik hier inderdaad verwacht, want het is onzeker of de embedded woonplaats de juiste woonplaats is. Maar de toelichtingen over woonplaats status en naam had ik hier niet verwacht. Dit zitten al in de embedded woonplaats, en zijn voor het adres niet gevraagd

**Comment by fsamwel** [comment]
Idem bij /adresseerbareobjecten/0005018888889105?expand=panden.oorspronkelijkBouwjaar&fields=type

Hier is de relatie "Maakt onderdeel uit van gerelateerd Pand" in onderzoek. Wanneer ik dit verblijfsobject vraag zonder fields, krijg ik o.a. mogelijkOnjuist.pandIdentificaties: true en mogelijkOnjuist.toelichting met o.a. "Verblijfsobject maakt mogelijk deel uit van een ander pand."

Aangezien ik hier met expand de relatie panden vraag, moet ik terugkrijgen dat ik mogelijk niet het juiste pand heb gekregen, door mogelijkOnjuist.pandIdentificaties: true en mogelijkOnjuist.toelichting: ["Verblijfsobject maakt mogelijk deel uit van een ander pand."]

**Comment by NicoleKortoomsBAG** [comment]
@fsamwel , de eerste comment heb ik gecheckt met de featurefile. In het scenario dat start op regel 217 lees ik dat zowel in de response als in de embedded response de mogelijk onjuist informatie van de woonplaats wordt geleverd.

**Comment by NicoleKortoomsBAG** [comment]
@fsamwel 2e comment laat ik naar kijken. Daar hoort volgens mij inderdaad de mogelijk onjuist terug te worden gegeven.

**Comment by NicoleKortoomsBAG** [comment]
@fsamwel  voor de expand.fields bevraging is een aanpassing gedaan. Daardoor geeft deze nu ook aan dat de relatie in onderzoek staat wanneer een veld van een expandes resource wordt gevraagd.
Deze staat klaar om te testen in acceptatie.

**Comment by fsamwel** [comment]
@NicoleKortoomsBAG 

> @fsamwel , de eerste comment heb ik gecheckt met de featurefile. In het scenario dat start op regel 217 lees ik dat zowel in de response als in de embedded response de mogelijk onjuist informatie van de woonplaats wordt geleverd.

In dat scenario zou zonder de expand ook als mogelijkOnjuist woonplaats zijn opgenomen, volgens regel 47:
| Woonplaats       | Naam woonplaats                          | Adres                | woonplaats               | Woonplaatsnaam is mogelijk onjuist geschreven. |

Zie ook het scenario op regel 239 die illustreert dat mogelijkOnjuist niet wordt geleverd als het betreffende veld niet is gevraagd met fields:
```
    Scenario: niet leveren mogelijkOnjuist voor een property dat niet gevraagd is in fields
      Gegeven in object Openbare Ruimte is gegeven "Ligt in gerelateerde woonplaats" in onderzoek
      Als de afgeleide resource Adres wordt opgevraagd met fields=postcode,huisnummer
      Dan bevat het antwoord property "postcode"
      En bevat het antwoord property "huisnummer"
      En bevat het antwoord geen property "woonplaats"
      En bevat het antwoord geen property "woonplaatsIdentificatie"
      En bevat het antwoord geen property "mogelijkOnjuist"
```

Dus bij request /adressen/0846200000007550?expand=woonplaats&fields=straat,huisnummer
- worden woonplaats en woonplaatsIdentificatie niet gevraagd, dus moet mogelijkOnjuist niet worden opgenomen a.g.v. regel 48 | Woonplaats       | Status woonplaats                        | Adres                | woonplaats,woonplaatsIdentificatie | Woonplaats bestaat mogelijk niet. |
- is de relatie naar de expanded/embedded woonplaats niet in onderzoek (scenario op regel 299 is niet van toepassing), dus hoeft mogelijkOnjuist om die reden niet te worden opgenomen bij het adres (uiteraard wél bij de embedded woonplaats).

**Comment by NicoleKortoomsBAG** [comment]
@fsamwel , ik begrijp het. Er gaat iemand naar kijken

**Comment by NicoleKortoomsBAG** [comment]
@fsamwel  Op de acceptatieomgeving is de oplossing weer te testen. 

De featurefile is niet duidelijk voor deze gevallen en zou moeten worden aangevuld. De combinatie van wat er moet gebeuren als fields en expand gecombineerd worden gebruikt is niet weergegeven. Ook het bovenstaande geval dat er wel mogelijk onjuist van de geometrie van de woonplaats wordt gegeven wanneer die in principe niet wordt gegeven omdat die met fields gefilterd is, staat nergens.

**Comment by fsamwel** [comment]
> De featurefile is niet duidelijk voor deze gevallen en zou moeten worden aangevuld. De combinatie van wat er moet gebeuren als fields en expand gecombineerd worden gebruikt is niet weergegeven.

Er staat hoe mogelijkOnjuist moet werken i.c.m. fields en er staat hoe mogelijkOnjuist moet werken i.c.m. expand. Er zijn geen aanvullende regels voor de combinatie van de twee. In alle scenerios over embedded zit er ook fields in het voorbeeld, juist om te tonen hoe embedded en fields met elkaar werken. Zo ook in scenario op regel 239. Kan je aangeven welke aanvullende situaties je zou willen zien waar bij jullie onduidelijkheid of twijfels bestaan over de gewenste werking?

**Comment by fsamwel** [comment]
@NicoleKortoomsBAG 

Deze (met status van expanded resource in onderzoek) geeft nu het correcte, verwachtte antwoord: /adressen/0846200000007550?expand=woonplaats&fields=straat,huisnummer

Deze (met relatie van adresseerbaar object naar het pand in onderzoek) geeft nu ook het correcte resultaat: /adresseerbareobjecten/0005018888889105?expand=panden.oorspronkelijkBouwjaar&fields=type

Deze (met alles van expanded woonplaats in onderzoek, maar niet de relatie) geeft nog niet het verwachtte resultaat: /adressen/0848200000363584?expand=woonplaats&fields=straat,huisnummer
Hier is alles in woonplaats in onderzoek, maar niet de relatie van nummeraanduiding en/of openbare ruimte naar de woonplaats. Dus verwacht ik niet in het adres mogelijkOnjuist de toelichting "Geometrie of woonplaatsgrens is mogelijk onjuist ...". Geometrie wordt niet geleverd (kan namelijk alleen embedded in woonplaats, niet bij het adres), en in _embedded.woonplaats.mogelijkOnjuist.toelichting zit ook geen "Geometrie of woonplaatsgrens is mogelijk onjuist ..."

Ook zonder gebruik van fields is deze onjuist. /adressen/0848200000363584?expand=woonplaats geeft:
```
    "mogelijkOnjuist": {
        "woonplaats": true,
        "woonplaatsIdentificatie": true,
        "toelichting": [
            "Geometrie of woonplaatsgrens is mogelijk onjuist, waardoor gaten of overlappingen ontstaan in de registratie van woonplaatsen. Gevolg kan zijn dat een object in een verkeerde woonplaats, in twee woonplaatsen, of in geen enkele woonplaats ligt.",
            "Woonplaats bestaat mogelijk niet.",
            "Woonplaatsnaam is mogelijk onjuist geschreven."
        ]
    },
```

Dit heeft dus niks te maken met onduidelijkheid over de werking van de combinatie fields en expand

**Comment by NicoleKortoomsBAG** [comment]
> 
> Er staat hoe mogelijkOnjuist moet werken i.c.m. fields en er staat hoe mogelijkOnjuist moet werken i.c.m. expand. Er zijn geen aanvullende regels voor de combinatie van de twee. In alle scenerios over embedded zit er ook fields in het voorbeeld, juist om te tonen hoe embedded en fields met elkaar werken. Kan je aangeven welke aanvullende situaties je zou willen zien waar bij jullie onduidelijkheid of twijfels bestaan over de gewenste werking?

Het was voor mij en de ontwikkelaar beide niet duidelijk dat regel 217 van de featurefile, waarbij juist wordt aangegeven dat mogelijk onjuist wel wordt geleverd, niet geldt wanneer er fields wordt toegepast. Als wij beide dat verkeerd interpreteren, kan het zomaar zijn dat afnemers ook informatie verwachten die ze niet gaan krijgen. Dus het voorbeeld wat we zelf hebben gebruikt om te testen, zou een goede aanvulling zijn.

**Comment by NicoleKortoomsBAG** [comment]
@fsamwel In je reactie van 1 of 2 juni geef je het volgende aan:
> 
> Net zoiets bij /adressen/0848200000363584?expand=woonplaats&fields=straat,huisnummer
> "mogelijkOnjuist": {
> "woonplaats": true,
> "woonplaatsIdentificatie": true,
> "toelichting": [
> "Geometrie of woonplaatsgrens is mogelijk onjuist, waardoor gaten of overlappingen ontstaan in de registratie van woonplaatsen. Gevolg kan zijn dat een object in een verkeerde woonplaats, in twee woonplaatsen, of in geen enkele woonplaats ligt.",
> "Woonplaats bestaat mogelijk niet.",
> "Woonplaatsnaam is mogelijk onjuist geschreven."
> ]
> },
> 
> De eerste toelichting, over de geometrie had ik hier inderdaad verwacht, want het is onzeker of de embedded woonplaats de juiste woonplaats is. Maar de toelichtingen over woonplaats status en naam had ik hier niet verwacht. Dit zitten al in de embedded woonplaats, en zijn voor het adres niet gevraagd

Dit  gaat over hetzelfde geval als je reactie van vandaag. Echter vandaag verwacht je geen mogelijk onjuist. 
Het klopt dat dit niet in de featurefile stond, daarom vroeg ik om het toe te voegen.

Ik kijk misschien niet goed, maar ik zie niet waarom de respons ook zonder fields niet correct zou zijn. Dit lijkt overeen te komen met de regels 47, 48 en 49 van de featurefile.
