### ISSUE TITLE
Als gebruiker wil ik de inhoud van de mogelijkOnjuist gegevensgroep kunnen filteren

### ISSUE THREAD

**Issue by strijm** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#294]
zodat ik geen complexe zoekacties/bevragen hoef te doen.

Eigenlijk moet de mogelijkOnjuist informatie automatisch worden aangepast aan de vraag om gegevens. De mogelijkOnjuist hoeft dan zelf niet gefilterd te worden.

**Acceptatiecriteria**
- Als ik resource properties filter met de fields parameter, dan bevat de mogelijkOnjuist gegevensgroep van de resource alleen de properties die waarde true hebben en corresponderen met de gevraagde resource attributen.
- Als ik subresources opvraag met de expand parameter, dan bevat de mogelijkOnjuist gegevensgroep van de resource alle properties die waarde true hebben en corresponderen met de gevraagde subresources.
- Als ik subresource properties filter met de expand parameter, dan bevat de mogelijkOnjuist gegevensgroep van de subresource de properties die waarde true hebben en corresponderen met de gevraagde subresource attributen. Hier worden dus geen mogelijkOnjuist gegevens geleverd waar niet om is gevraagd. 
- Als ik resource properties filter met de fields parameter en ik filter properties van de mogelijkOnjuist gegevensgroep van de resource, dan worden van zowel de resource als de mogelijkOnjuist gegevensgroep de gevraagde properties geleverd.

De gewenste logica is verspreid beschreven over de expand, fields en mogelijkOnjuist feature beschrijving, dit maakt dit stuk erg lastig te interpreteren. Bovenstaande is bedoeld als voorstel om e.e.a. te vereenvoudigen. Is hetgeen hierboven staat beschreven de gewenste logica?

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by fsamwel** [comment]
> - Als ik resource properties filter met de fields parameter, dan bevat de mogelijkOnjuist gegevensgroep van de resource alleen de properties die waarde true hebben en corresponderen met de gevraagde resource attributen.

Mee eens.

> - Als ik subresources opvraag met de expand parameter, dan bevat de mogelijkOnjuist gegevensgroep van de resource alle properties die waarde true hebben en corresponderen met de gevraagde subresources.

Als je geen fields hebt gebruikt: Nee. De mogelijkOnjuist van de resource geeft alle properties die waarde true hebben.
Als je wel fields hebt gebruikt: dan bevat de mogelijkOnjuist gegevensgroep van de resource alleen de properties die waarde true hebben en corresponderen met de gevraagde resource attributen, plus de properties die waarde true hebben en  corresponderen met de gevraagde subresources.

> - Als ik subresource properties filter met de expand parameter, dan bevat de mogelijkOnjuist gegevensgroep van de subresource de properties die waarde true hebben en corresponderen met de gevraagde subresource attributen. Hier worden dus geen mogelijkOnjuist gegevens geleverd waar niet om is gevraagd. 

Mee eens.

> - Als ik resource properties filter met de fields parameter en ik filter properties van de mogelijkOnjuist gegevensgroep van de resource, dan worden van zowel de resource als de mogelijkOnjuist gegevensgroep de gevraagde properties geleverd.

Zo werkt het nu niet, zie https://github.com/VNG-Realisatie/Haal-Centraal-BAG-bevragen/issues/308#issuecomment-691110237. Ik weet niet zeker hoe je deze nu bedoelt. Ik zie twee alternatieve werkwijzen:
- Zodra je in fields iets zegt over mogelijkOnjuist, moet je ook alleen die gevraagde velden van mogelijkOnjuist leveren. Bijvoorbeeld (bij status nummeraanduiding in onderzoek) /adressen?fields=straat,mogelijkOnjuist.huisnummer levert wel mogelijkOnjuist.huisnummer en niet mogelijkOnjuist.straat.
- In mogelijkOnjuist worden velden opgenomen waar of het corresponderende gegeven uit de resource is gevraagd, of het gegeven in mogelijkOnjuist. Bijvoorbeeld (bij status nummeraanduiding in onderzoek) /adressen?fields=straat,mogelijkOnjuist.huisnummer levert mogelijkOnjuist.huisnummer en ook mogelijkOnjuist.straat.

Ik heb een lichte voorkeur voor de tweede optie, je kan voor mogelijkOnjuist beter iets meer leveren dan gevraagd/verwacht dan te weinig.
