### ISSUE TITLE
Foutmelding bij niet toegestane combinatie van parameters

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#305]
/panden?adresseerbaarObjectIdentificatie=0599010000165822&locatie=98095.02%2C438495.09

dit bevat een niet toegestane combinatie van parameters. De foutafhandeling feature beschrijft hiervoor:
| Niet toegestane parametercombinatie | 400    | De combinatie van opgegeven parameters is niet toegestaan.        | unsupportedCombi  |

Het antwoord is echter:
```
{
   "type" : "https://tools.ietf.org/html/rfc7231#section-6.5.1",
   "title" : "Ten minste één parameter moet worden opgegeven.",
   "status" : 400,
   "detail" : "Precies 1 parameter van adresseerbaarObjectIdentificatie of locatie moet worden opgegeven",
   "instance" : "https://api.bag.acceptatie.kadaster.nl/esd/huidigebevragingen/v1/panden?adresseerbaarObjectIdentificatie=0599010000165822&locatie=98095.02%2C438495.09",
   "code" : "paramsRequired"
}
```

Deze melding is verwarrend, want er zijn parameters opgegeven (zelfs teveel).

Zie ook #23

**Comment by fsamwel** [comment]
dit is consequentie van https://github.com/VNG-Realisatie/Haal-Centraal-common/issues/57

**Comment by fsamwel** [comment]
@strijm in deze situatie komt in "detail" nu te staan "Bad request.". Dat voegt wel heel weinig toe. De bedoeling van detail is om meer informatie (meer detail) te geven over de fout of de oplossing daarvoor. Bijvoorbeeld "De combinatie van parameters nummeraanduidingIdentificatie en pandIdentificatie is niet toegestaan. Slechts één van deze parameters mag tegelijk worden gebruikt."

Of, zoals in de BRK API, een algemenere toelichting "Er zijn meerdere zoekingangen opgegeven. Graag 1 zoekingang gebruiken."

N.B. ik wil niet vanuit Haal Centraal voorschrijven wat er exact in "detail" wordt teruggegeven. Dat hoort echt bij de implementatie. Maar de bedoeling van het veld is wel duidelijk, namelijk gebruikers helpen om het probleem op te lossen. Kunnen jullie hier nog iets aan doen?

**Comment by fsamwel** [comment]
de rest van de foutmelding is trouwens helemaal als verwacht

**Comment by strijm** [comment]
@fsamwel opmerking is duidelijk, we gaan er vandaag naar kijken.

**Comment by fsamwel** [comment]
> @strijm in deze situatie komt in "detail" nu te staan "Bad request.". Dat voegt wel heel weinig toe. De bedoeling van detail is om meer informatie (meer detail) te geven over de fout of de oplossing daarvoor. Bijvoorbeeld "De combinatie van parameters nummeraanduidingIdentificatie en pandIdentificatie is niet toegestaan. Slechts één van deze parameters mag tegelijk worden gebruikt."
> 
> Of, zoals in de BRK API, een algemenere toelichting "Er zijn meerdere zoekingangen opgegeven. Graag 1 zoekingang gebruiken."
> 
> N.B. ik wil niet vanuit Haal Centraal voorschrijven wat er exact in "detail" wordt teruggegeven. Dat hoort echt bij de implementatie. Maar de bedoeling van het veld is wel duidelijk, namelijk gebruikers helpen om het probleem op te lossen. Kunnen jullie hier nog iets aan doen?

Dit wordt opgelost met #327 Bruikbare beschrijving in detail veld van foutmelding
