### ISSUE TITLE
mogelijkOnjuist toelichtingen

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#308]

**Comment by fsamwel** [comment]
Pull request #326 ingediend, want een van de toelichting is m.i. niet correct.

**Comment by fsamwel** [comment]
@strijm vragen om een mogelijkonjuist veld die niet in onderzoek staat levert wel de mogelijkOnjuist van een veld dat wel in onderzoek staat.
Bijvoorbeeld /adressen/0014200010896726?fields=woonplaats,mogelijkOnjuist.woonplaats

Dit levert:
{
    "woonplaats": "Groningen",
    "mogelijkOnjuist": {
        "huisnummer": true,
        "toelichting": [
            "Mogelijk is het verkeerde huisnummer geregistreerd."
        ]
    },
    "_links": {
        "self": {
            "href": "https://api.bag.acceptatie.kadaster.nl/esd/huidigebevragingen/v1/adressen/0014200010896726?fields=woonplaats,mogelijkOnjuist.woonplaats"
        }
    }
}

Ik had hier de mogelijkOnjuist niet verwacht.

**Comment by fsamwel** [comment]
@strijm wanneer de relatie nummeraanduiding ligt aan openbare ruimte in onderzoek is, en _links.openbareRuimte wordt gevraagd, dan wordt mogelijkOnjuist verwacht met openbareRuimteIdentificatie.

Dit staat zo in de feature mogelijk onjuist bij scenario "leveren mogelijkOnjuist bij met fields vragen naar link die mogelijk onjuiste identificatie bevat"

/adressen/0018200000152130?fields=huisnummer,postcode,_links.openbareRuimte
levert nu:
```
{
    "huisnummer": 21,
    "postcode": "9602KD",
    "_links": {
        "self": {
            "href": "https://api.bag.acceptatie.kadaster.nl/esd/huidigebevragingen/v1/adressen/0018200000152130?fields=huisnummer,postcode,_links.openbareRuimte"
        },
        "openbareRuimte": {
            "href": "https://api.bag.acceptatie.kadaster.nl/esd/huidigebevragingen/v1/openbareruimten/0018300000000271"
        }
    }
}
```

Hierin ontbreekt mogelijkOnjuist.openbareRuimteIdentificatie=true en mogelijkOnjuist.toelichting="Mogelijk verkeerde straat gebruikt. Het adres moet verwijzen naar de straat waaraan het adres ligt."

**Comment by fsamwel** [comment]
Idem bij vragen om de relatie met expand, zoals in /adresseerbareobjecten/:adresseerbaarObjectIdentificatie?expand=panden&fields=documentnummer

**Comment by kad-barens** [comment]
> @strijm vragen om een mogelijkonjuist veld die niet in onderzoek staat levert wel de mogelijkOnjuist van een veld dat wel in onderzoek staat.
> Bijvoorbeeld /adressen/0014200010896726?fields=woonplaats,mogelijkOnjuist.woonplaats
> 
> Dit levert:
> {
> "woonplaats": "Groningen",
> "mogelijkOnjuist": {
> "huisnummer": true,
> "toelichting": [
> "Mogelijk is het verkeerde huisnummer geregistreerd."
> ]
> },
> "_links": {
> "self": {
> "href": "https://api.bag.acceptatie.kadaster.nl/esd/huidigebevragingen/v1/adressen/0014200010896726?fields=woonplaats,mogelijkOnjuist.woonplaats"
> }
> }
> }
> 
> Ik had hier de mogelijkOnjuist niet verwacht.

Met Johan en Mark is afgesproken dat wanneer bij fields een waarde die begint met mogelijkOnjuist wordt meegegeven, altijd de volledige mogelijkOnjuist wordt teruggegeven. Alles achter een eventuele punt achter mogelijkOnjuist wordt dan genegeerd. Dus fields=mogelijkOnjuist.woonplaats wordt afgehandeld als fields=mogelijkOnjuist.

**Comment by strijm** [comment]
@fsamwel:
De feature die je hier beschrijft is op 3 augustus in de feature beschrijving terecht gekomen, zonder dat deze door Kadaster is gereviewed, daardoor waren wij niet op de hoogte dat deze functionaliteit gebouwd moest worden en is dus, zoals je hebt geconstateerd, nog niet geïmplementeerd. Om release 1.1.0 niet verder te vertragen, lijkt het mij het beste een known issue op te nemen, dat deze feature nog niet is geïmplementeerd en in een volgende release geïmplementeerd zal worden.

**Comment by fsamwel** [comment]
> De feature die je hier beschrijft is op 3 augustus in de feature beschrijving terecht gekomen, zonder dat deze door Kadaster is gereviewed, daardoor waren wij niet op de hoogte dat deze functionaliteit gebouwd moest worden

Ik neem aan dat je hiermee doet op https://github.com/VNG-Realisatie/Haal-Centraal-BAG-bevragen/issues/308#issuecomment-690977304? Hiervoor is er al issue #293

**Comment by fsamwel** [comment]
gezien bovenstaande is dit issue opgelost. Via e-mail aan Nicole gevraagd om #293 op de backlog te zetten
