### ISSUE TITLE
wijzigen description zoekparameter zoekresultaat get/adressen/zoek e.a.

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#309]
Is: De identificatie van een gekozen zoekresultaat uit de zoekResultatenHalCollectie verkregen bij een zoek-operatie
wordt: de identificatie van een zoekresultaat van het endpoint get/adressen/zoek 

AdresseerbaarObjectMogelijkOnjuist & AdresMOgelijkOnjuist &PandMogelijkOnjuist&NummeraanduidingMogelijkOnjuist & OpenbareRuimteMogelijkOnjuist & WoonplaatsMogelijkOnjuist:
Is: Wanneer hier een property is opgenomen met de waarde true, dan is de waarde van het gelijknamige property in de resource mogelijk onjuist. De juistheid van dit gegeven wordt op dit moment onderzocht. Onder property toelichting wordt toegelicht wat er mogelijk onjuist is aan het betreffende gegeven.
Wordt: Wanneer "true" is de waarde mogelijk onjuist, en wordt juistheid op dit moment onderzocht. Zie toelichting.

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by JohanBoer** [comment]
Check of dit  juist is doorgevoerd en anders in 1.2 meenemen

**Comment by JohanBoer** [comment]
Dit is al doorgevoerd in versie 1.1 In ieder geval staan deze descriptions in de pull request.
