### ISSUE TITLE
Crs header check moet rekening houden met expand punt notatie

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#320]
of accept Crs request header verplicht is hangt af of er geometrie geleverd wordt. Dit moet dus afhangen van wat gevraagd is met fields en expand.

Op dit moment wordt er daarbij nog niet voldoende rekening gehouden met wat er exact is gevraagd met expand. Met expand kunnen namelijk specifieke velden worden gevraagd. Wanneer alleen velden zijn gevraagd waar geen geometrie in zit, is het sturen van accept Crs niet verplicht.

**Comment by fsamwel** [comment]
Deze is denk ik niet opgelost. @strijm Is deze wel op acceptatie gezet?

https://api.bag.acceptatie.kadaster.nl/esd/huidigebevragingen/v1/adresseerbareobjecten/0599010000165822?expand=adressen.postcode,panden.identificatie,adressen.huisnummer,panden.oorspronkelijkBouwjaar&fields=identificatie,type,gebruiksdoelen,oppervlakte

Dit levert een 412 fout. Dat had ik niet verwacht, want in fields wordt geen geometrie gevraagd, en in expand ook niet.

**Comment by strijm** [comment]
We gaan er vandaag naar kijken.
