### ISSUE TITLE
Correctie mogelijkOnjuist toelichting voor huisnummertoevoeging

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#328]
Met pull request #326 is toelichting voor huisnummertoevoeging gecorrigeerd.

In de toelichting voor mogelijkOnjuist bij huisnummertoevoeging stond "Mogelijk is ten onrechte een huislettertoevoeging toegekend, ontbreekt de huislettertoevoeging ten onrechte, of is een verkeerde huislettertoevoeging toegekend."

Het gegeven heet "huisnummertoevoeging", niet "huislettertoevoeging". Daarom toelichting gewijzigd naar "Mogelijk is ten onrechte een huisnummertoevoeging toegekend, ontbreekt de huisnummertoevoeging ten onrechte, of is een verkeerde huisnummertoevoeging toegekend."

Graag deze doorvoeren

**Comment by strijm** [comment]
Deze moet nog verwerkt worden in de release notes v1.1.

**Comment by fsamwel** [comment]
Dit was een bevinding op het toevoegen van toelichtingen #308, dus heeft nooit als open issue op release v1.0.0 gestaan. Vandaar dat ik deze niet had opgenomen.
