### ISSUE TITLE
mogelijKOnjuist voor reverse relaties?

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#329]
Bij een verblijfsobject kan "Maakt onderdeel uit van gerelateerd Pand" in onderzoek zijn, waardoor in de resource adresseerbareobjecten mogelijkOnjuist.pandIdentificaties=true wordt opgenomen.

In de resource panden zit ook deze relatie, in omgekeerde richting, in de vorm van adresseerbaarObjectIdentificaties en _links.adresseerbareObjecten. Maar panden.mogelijkOnjuist.adresseerbaarObjectIdentificaties hebben we niet opgenomen.

Als de relatie van een verblijfsobject naar een pand in onderzoek is, is de relatie van dat pand naar dat verblijfsobject toch ook in onderzoek?  Dan is het toch ook belangrijk voor een gebruiker die een pand opvraagt te weten dat de geleverde adresseerbaarObjectIdentificatie(s) mogelijk onjuist is?

Ik kan me niet herinneren of we destijds een bewuste keuze gemaakt hebben om dit niet op te nemen bij een pand.

@strijm @PieterDijkstraKadaster is mijn conclusie juist (dat de mogelijke onjuistheid van de relatie ook in omgekeerde richting geldt)? En is dit leverbaar?

**Comment by PieterDijkstraKadaster** [comment]
In IMBAG zijn er vanuit een pand geen relaties naar andere objecten. Dat een verblijfsobject in een pand ligt, is daarmee geen gegeven van dat pand. De relatie tussen een pand en een verblijfsobject is alleen mogelijk onjuist als er ook daadwerkelijk een verblijfsobject is. Het is niet terug te vinden in de registratie als er onterecht geen verblijfsobject is. Als de relatie er wel is, kun je dit terugvinden bij het verblijfsobject. 

Het is wat mij betreft een goede keuze dit niet op ten nemen bij een pand.

**Comment by fsamwel** [comment]
oké, dan sluit ik dit issue
