### ISSUE TITLE
Underscores verwijderen uit componentnamen en enumeratienamen. 

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#338]
In het BRK-project is besloten om alleen underscores te gebruiken in de properties _embedded en de _links.
Alle componentnemen en alle enumeratie-namen bevatten geen underscores meer.

Uit Haal-Centraal consistentie overwegingen wordt deze wijziging doorgevoerd als er een volgende minor versie wordt doorgevoerd.

**Comment by strijm** [comment]
Wat moet het dan worden? 
Bv. StatusPand_enum wordt StatusPandEnum?

**Comment by fsamwel** [comment]
> Bv. StatusPand_enum wordt StatusPandEnum?

Inderdaad

**Comment by strijm** [comment]
Geldt dit ook voor de componenten in de commons.yaml?

**Comment by JohanBoer** [comment]
Volgens mij worden er in common alleen underscores gebruikt in namen van headers die op de landelijke API_strategie gebaseerd zijn. Datum_onvolledig is deprecated en ter vervanging hebben we DatumOnvolledig opgenomen. Mis ik dan nog iets ?

**Comment by fsamwel** [comment]
@JohanBoer 

> alle enumeratie-namen bevatten geen underscores meer

ik neem aan je bedoelt de namen van componenten, niet de namen van enumeratiewaarden?

Zie https://github.com/VNG-Realisatie/Haal-Centraal-common/blob/master/docs/design_decisions.md#dd14-enumeratie-waarden-zijn-in-snake_case
