### ISSUE TITLE
expand op templated _link levert niet bijbehorende identificaties

### ISSUE THREAD

**Issue by NicoleKortoomsBAG** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#339]
Reproductie stappen:
Bevraag  /v1/adresseerbareobjecten/0351010000005015?expand=panden._links.adresseerbareObjecten

Verwacht resultaat:
Verwacht is dat de adresseerbaarObjectIdentificaties  in de embedded panden gevuld is

Werkelijk resultaat:
leeg

**Comment by NicoleKortoomsBAG** [comment]
@fsamwel @MelvLee 
Deze bug is opgelost en staat klaar om te testen.

**Comment by fsamwel** [comment]
zo te zien goed opgelost.

getest met o.a. http://api.bag.acceptatie.kadaster.nl/esd/huidigebevragingen/v1/adresseerbareobjecten/0193010000096628?expand=panden._links.adresseerbareObjecten,adressen._links.panden&fields=_links.panden

antwoord bevat o.a.:
```
            {
                "adresseerbaarObjectIdentificaties": [
                    "0193010000050954",
                    "0193010000096628"
                ],
                "_links": {
                    "self": {
                        "href": "http://api.bag.acceptatie.kadaster.nl/esd/huidigebevragingen/v1/panden/0193100000043750"
                    },
                    "adresseerbareObjecten": [
                        {
                            "href": "http://api.bag.acceptatie.kadaster.nl/esd/huidigebevragingen/v1/adresseerbareobjecten/{adresseerbaarObjectIdentificaties}",
                            "templated": true
                        }
                    ]
                }
            }
```

**Comment by NicoleKortoomsBAG** [comment]
We zullen deze dan zo releasen.

**Comment by kad-voordm** [comment]
Hij staat in productie.
