### ISSUE TITLE
Links geven http in plaats van https

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#340]
Bijvoorbeeld request https://api.bag.kadaster.nl/esd/huidigebevragingen/v1/adresseerbareobjecten/0193010000096628

heeft in het antwoord:
```
        "self": {
            "href": "http://api.bag.kadaster.nl/esd/huidigebevragingen/v1/adresseerbareobjecten/0193010000096628"
        }
```

Ook bij foutberichten:
https://api.bag.kadaster.nl/esd/huidigebevragingen/v1/adressen?zoekresultaatIdentificatie=adr-f6b00930705c1ef12c2624623a797d21&fields=postcode,bestaatniet,huisnummer

heeft in het antwoord:
`"instance": "http://api.bag.kadaster.nl/esd/huidigebevragingen/v1/adressen?zoekresultaatIdentificatie=adr-f6b00930705c1ef12c2624623a797d21&fields=postcode,bestaatniet,huisnummer",`

N.B. ik zie dit in productie en in acceptatie

**Comment by NicoleKortoomsBAG** [comment]
@fsamwel 
Links zijn nu standaard met https. 
Dit is opgelost in de gateway en had dus geen codewijzigingen van de API tot gevolg.

**Comment by fsamwel** [comment]
is opgelost
