### ISSUE TITLE
Zoeken van adresseerbare object op pandIdentificatie levert geen resultaten

### ISSUE THREAD

**Issue by KayodeBakker** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#341]
Na een adresseerbare object te hebben geraadpleegd op basis van de identificatie:
`https://api.bag.acceptatie.kadaster.nl/esd/huidigebevragingen/v1/adresseerbareobjecten/0226010000038820`
heb ik een pand identificatie ter beschikking, namelijk "0226100000008856".

Als ik vervolgens andere adresseerbare objecten probeer te zoeken dat gekoppeld staan aan deze pand identificatie, ofwel:

`http://api.bag.acceptatie.kadaster.nl/esd/huidigebevragingen/v1/adresseerbareobjecten?pandIdentificatie=0226100000008856`

dan krijg ik gek genoeg nul resultaten. Ik kan hooguit nog speculeren dat de voorwaarde is dat het pand echt moet bestaan. 
Dit zou apart zijn als ik deze uit een ander response kreeg, maar desondanks probeer ik het pand te zoeken d.m.v.:

`http://api.bag.acceptatie.kadaster.nl/esd/huidigebevragingen/v1/panden/0226100000008856`

maar gek genoeg komt hier resultaat uit.

Mijn conclusie is dus dat de zoekpad van adresseerbare objecten op pandIdentificatie niet werkt naar behoren en zou hier graag een wijziging op willen zien.

**Comment by KayodeBakker** [comment]
@fsamwel Kan jij mij helpen met rechten om labels te plaatsen? Ik kan geen bug label hieraan plakken.

**Comment by JohanBoer** [comment]
> @fsamwel Kan jij mij helpen met rechten om labels te plaatsen? Ik kan geen bug label hieraan plakken.

@KayodeBakker ik heb je een invite gestuurd met de permissies waarmee je ook labels kunt toekennen.

**Comment by PieterDijkstraKadaster** [comment]
Dit is inderdaad een bug. We gaan er mee aan de slag.

**Comment by NicoleKortoomsBAG** [comment]
Het request geeft nu een response. 
Dat het request geen response gaf, kwam doordat bij dit VBO het verplichte attribuut gebruiksdoel niet is gevuld in de testdatabase. (In productie kan dit niet voorkomen). De response die nu wordt teruggegeven (zonder gebruiksdoel)  is daarom niet representatief voor een response in productie omdat daar wel altijd gebruiksdoel wordt teruggegeven.

**Comment by fsamwel** [comment]
@KayodeBakker is dit nu opgelost en kan deze gesloten worden?

**Comment by fsamwel** [comment]
is opgelost
