### ISSUE TITLE
Panden kunnen alleen verblijfsobjecten bevatten en geen ligplaatsen/standplaatsen

### ISSUE THREAD

**Issue by KayodeBakker** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#342]
Bij de bevraging van een pand viel mij het volgende op in het response:
```
    "adresseerbaarObjectIdentificaties": [
        "0226010000038820"
    ],
.....
    "_links": {
        "self": {
            "href": "http://api.bag.acceptatie.kadaster.nl/esd/huidigebevragingen/v1/panden/0226100000008856"
        },
.....
        "adresseerbareObjecten": [
            {
                "href": "http://api.bag.acceptatie.kadaster.nl/esd/huidigebevragingen/v1/adresseerbareobjecten/{adresseerbaarObjectIdentificaties}",
                "templated": true
            }
        ]
    }
```

Waarom staat er adresseerbaarObjectIdentificaties en adresseerbareObjecten in het response van Pand? Deze onduidelijkheid zorgt er voor dat gebruikers impliciet gaan denken dat een pand ook Ligplaats en Standplaats kan hebben als relatie en niet alleen Verblijfsobject.

In het geval dat hiervoor gekozen is zodat de template van raadplegen adresseerbareobjecten (zoals hierboven is weergegeven) duidelijker is dan is dat niet een goede reden. Alles wat deze template is, is een voorbeeld. De template hoeft niet '{adresseerbaarObjectIdentificaties}' te bevatten aangezien dit woordje alleen maar terug verwijst naar het attribuut in het totale response. Als dit '{verblijfsobjectIdentificaties}' was dan is dat net zo duidelijk want het verband tussen die waardes en de template is dan gelegd. Nu wordt de verband gelegd ten kosten van het logisch relationeel gebruik tussen Pand en Verblijfsobject.

Graag zie ik hier aanpassing in of hoor ik een argument voor waarom dit niet een optie is.

**Comment by fsamwel** [comment]
De link verwijst naar de resource adresseerbareobjecten. Deze zal in dit geval alleen links bevatten naar adresseerbareobjecten van het type verblijfsobject, maar het blijft de resource adresseerbareobjecten. 

De identificatie heeft daarom ook adresseerbaarObjectIdentificaties, omdat het de identificaties zijn van de resource adresseerbareobjecten.
In de template wordt vervolgens tussen verwezen naar de waarde in de resource, deze bevat dus een property in de response die je direct kan gebruiken. Daarom staat in de template {adresseerbaarObjectIdentificaties}.

Er is zeker iets voor te zeggen deze link "verblijfsobjecten" te noemen, en de identificaties "verblijfsobjectIdentificaties". Maar de huidige vorm, die de relatie legt tussen resources, vind ik zelf niet direct verkeerd of heel onduidelijk. Ook zou het nu wijzigen breaking changes opleveren. Is dat het waard? Alternatief is de voorgestelde verblijfsobject properties toe te voegen naast de adresseerbaarObject properties, maar dan is het wellicht nog onduidelijker, omdat men dan zowel een verblijfsobject als een adresseerbaar object in het antwoord krijgt.

**Comment by KayodeBakker** [comment]
@strijm Deze issue staat al open sinds vorig jaar november. Heb jij enig indicatie wanneer hier naar wordt gekeken of op z'n minst op gereageerd?

**Comment by fsamwel** [comment]
@KayodeBakker dit is denk ik een issue dat door het Haal Centraal team moet worden beantwoord, dus uiteindelijk door @CathyDingemanse. @strijm kan deze specificatie niet zelf wijzigen. 

Zoals ik in mijn reactie al eerder aangaf denk ik dat het niet zo heel "fout" is hoe het nu gespecificeerd en geïmplementeerd is, en vind ik het zelf niet de moeite waard hiervoor een breaking change (dus versie 2.0) te introduceren.

**Comment by CathyDingemanse** [comment]
Ha Kayo, we hebben het er vanmorgen al even over gehad. Deze benadering biedt op andere plekken in de API veel voordelen, en is hier ook niet heel erg schadelijk (niet genoeg voor een breaking change).

**Comment by KayodeBakker** [comment]
Hoi Cathy, als dat de conclusie vanuit Haal Centraal is dan prima! Als er meer nadelen zijn in ogen van het team dan voordelen dan laten we het hierbij.
