### ISSUE TITLE
Voer discussie over het gebruik vande NEN3610ID

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#35]
Gebruik over de namespace etc van de NEN3610ID bespreken. In hoeverre wordt dit in de praktijk gebruikt.

**Comment by strijm** [comment]
Besproken met @lennartvanbergen-kadaster. Zoals eerder besproken is er een landelijke afspraak om NEN3610ID's uit te leveren. De LV BAG APIs leveren NEN3610ID's uit. Deze NEN3610ID's bevatten de BAG object ID's (naast een namespace en optionele versie). Het is niet veel werk dit ID uit de NEN3610ID te bepalen en verder te gebruiken. 
Als we alleen de BAG object ID's zouden uitleveren, dan voldoen we daarmee niet aan de landelijke afspraak om NEN3610ID's uit te leveren. We laten om die reden de specificaties op dit punt dus intact totdat er een landelijk besluit is, dat het uitleveren van alleen de BAG object ID (dus niet in NEN3610ID formaat) is toegestaan.

**Comment by CathyDingemanse** [comment]
Is de modelversie onderdeel van het ID? Kan deze wijzigen? Kan het ID wijzigen als gevolg van een wijziging in de provider-implementatie (bijvoorbeeld een modelwijziging)?  
Graag duidelijkheid over of er sprake is van tight coupling tussen de consumer en provider-implementatie.

**Comment by strijm** [comment]
De versie in een NEN3610ID verwijst naar een versie (voorkomen) van een object en dus niet naar een informatiemodel versie.

**Comment by fsamwel** [comment]
Discussie is nog niet afgerond.

**Comment by JohanBoer** [comment]
Kadaster heeft bij Geonovum de issue belegd.

**Comment by fsamwel** [comment]
opgelost met #214
