### ISSUE TITLE
als gebruiker wil ik het samengesteld adres krijgen

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#360]
...zodat ik de adrescomponenten direct op de juiste manier kan gebruiken in adressering

Aanleiding is dat bij verschillende implementaties blijkt dat het adres niet altijd goed wordt samengesteld. Bijvoorbeeld wordt straat gebruikt in plaats van korteNaam, zodat het adres niet meer (goed/volledig) op een envelop of binnen een adresvenster past. Ook is bij gebruikers met beperkte domeinkennis van BAG niet altijd duidelijk op welke manier huisnummertoevoeging aan het huisnummer moet worden toegevoegd.

Daarvoor toevoegen adresregel1 en adresregel2. adresregel1 is de eerste regel van het adres, deze bevat normaalgesproken de straatnaam (korteNaam), huisnummer, huisletter en huisnummertoevoeging. adresregel2 is de tweede regel van een adres en bevat postcode plus woonplaatsnaam.

**Comment by NicoleKortoomsBAG** [comment]
@CathyDingemanse @strijm 
Ik lees in de NEN dat wat hier adresregel 1 en 2 wordt genoemd in de NEN bekend staat als adresregels 5 en 6 om ruimte te geven aan de persoons- en bedrijfsgegevens. 
Het lijkt met goed om in de API qua naamgeving de NEN 5825 te volgen.

**Comment by fsamwel** [comment]
Het lijkt met goed om in de API qua naamgeving de NEN 5825 te volgen.

Deze velden worden nu ook al in de BRK en BRP APIs gebruikt en heten daar ook adresregel1 en adresregel2. Het daar wijzigingen zou breaking zijn voor die APIs. De BRP API heeft daarnaast twee velden voor de naar in de adressering (aanschrijfwijze), die volgens NEN5825 dan ergens in adresregels 1 t/m 4 zouden komen.

Ik denk dat het voor gebruikers wel duidelijk is dat adressering een naamdeel heeft en een adresdeel, en dat deze adresregels betrekking hebben op het adresdeel. Dit is immers het adres in de BAG.

Volgens [Postnl](https://www.postnl.nl/versturen/brief-of-kaart-versturen/hoe-verstuur-ik-een-brief-of-kaart/brief-adresseren/) mogen er maximaal 6 adresregels zijn. Ook komt er dan op de laatste regel, in geval van een [buitenlands adres](https://www.postnl.nl/versturen/brief-of-kaart-versturen/brief-of-kaart-buitenland/verzendvoorwaarden/adresseren-van-buitenlandse-zendingen/), het land. Hoe matcht dit met adresregel6 waarin postcode en woonplaats staan? Gaat NEN8525 uit van maximaal 7 adresregels?

Daarom kennen we in BRK en BRP naast adresregel1 en adresregel2 ook adresregel3. Adresregel3 zou dan niet adresregel7 moeten heten (er mogen immers maximaal 6 adresregels zijn).
De gebruiker kan dan namelijk deze drie adresregels zonder kijken in de adressering gebruiken, of het nu een Nederlands adres is, een locatiebeschrijving, antwoordnummer, een postbus of een buitenlands adres. 

Ik ben er dus niet voor om de naamgeving aan te passen.

**Comment by fsamwel** [comment]
@NicoleKortoomsBAG @strijm @CathyDingemanse kunnen jullie deze reviewen?
ik heb een aanzet gemaakt voor een feature die de werking beschrijft, zie https://github.com/VNG-Realisatie/Haal-Centraal-BAG-bevragen/blob/adresregels_nen5825/features/adresregels.feature

In dezelfde branch (adresregels_nen5825) heb ik ook de exampels gecorrigeerd in de api specs. Nog niks gedaan met de naam van de properties (die heten dus nog adresregel1 en adresregel2, niet adresregel4 en adresregel5

**Comment by strijm** [comment]
@fsamwel: zou je een PR kunnen maken van de branch waarin de feature en de yaml aanpassing staan (PR van branch naar develop)? Dat is makkelijker reviewen.

**Comment by fsamwel** [comment]
zie https://github.com/VNG-Realisatie/Haal-Centraal-BAG-bevragen/pull/396

**Comment by CathyDingemanse** [comment]
@NicoleKortoomsBAG ik zou ook de naamgeving niet aanpassen om functionele redenen die Frank aangeeft, en e.e.a. weegt niet op tegen de breaking change in BRK en BRP die dit zou veroorzaken.

**Comment by fsamwel** [comment]
getest en is goed
