### ISSUE TITLE
toevoegen controle op minimale en maximale lengte invoer zoek

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#364]
endpoint /adressen/zoek heeft parameter "zoek" waar nu geen pattern, minLength of maxLength is gedefinieerd. Wel is de parameter required.
Default voor minLength = 0, dus /adressen/zoek?zoek= is een valide request. Voor de gebruiker is het niet duidelijk wat dit betekent. Moeten nu alle adressen worden geleverd of geen enkel adres? Required was hier bedoeld dat parameter zoek verplicht aanwezig moet zijn met een waarde. Dus moet ook een minLength worden toegevoegd.

Er moet ook een maxLength gespecificeerd worden, omdat als we geen maxLength opgeven, de validatie alsnog afgaat bij een string lengte 2097152, dat is nl. de default maxLength waarde die gebruikt wordt als we zelf geen maxLength specificeren. Een string met een lengte langer dan 255, bevat vanaf karakter 256 theoretisch dus nutteloze informatie. Deze default maxLength waarde komt overeen met 4 MB unicode string data. Een gebruiker kan dus gewoon bijna 4 MB nutteloze data over de lijn sturen, wat de verbindingen en de server onnodig belast en vervolgens een foutmelding oplevert. Dan kunnen we beter een foutmelding geven bij een kleiner aantal karakters, zodat de verbindingen en servers niet onnodig worden belast.

**Comment by fsamwel** [comment]
In pull request #345 en #359 is dit doorgevoerd door toevoegen minLength en maxLength.

Dit is nog niet geïmplementeerd op acceptatie en productie.

Er is nu wel discussie over de versionering. Ik denk dat toevoegen van minLength en maxLength (aanscherpen van de specificaties) een breaking change is. Daardoor heeft deze wijziging impact voor alle gebruikers (v1 wordt dan depricated en gebruikers moeten binnen een overgangstermijn over op v2).

**Comment by fsamwel** [comment]
@strijm de consequentie dat dit een breaking change is, is op dit moment te groot  ten opzichte van wat dit oplevert. We (Cathy, Johan) hebben dit besproken en kwamen tot de conclusie dat dit in deze release opgelost kan worden door:
- bij lege zoek parameter te leveren zonder filter (zoals nu al is geïmplementeerd
- bij zoek waarde > 255 tekens leeg resultaat teruggeven

We nemen hier aan dat er geen kloppende zoekvraag van meer dan 255 tekens kan zijn die wel een resultaat had moeten geven. Dus straatnaam + huisnummer/letter/toevoeging + postcode + woonplaats is altijd korter dan 255 tekens. Als die aanname niet klopt is 255 tekens eigenlijk te kort, klopt die aanname wel, dan kan je altijd een lege collectie teruggeven bij ?255 tekens, zonder met de zoekwaarde in de database te hoeven stoppen.
Het risico dat iemand extreem veel tekens stuurt is denk ik niet echt een probleem, omdat het (onder bovenstaande aanname) geen correcte zoekvraag is en daarom niks oplevert.

We willen de toevoeging van minLength en maxLength daarom terugdraaien. Heb je hier bezwaar tegen?

**Comment by fsamwel** [comment]
naast de parameter "zoek" is ook minLength en maxLength toegevoegd op zoekresultaatIdentificatie. Ook hier kan je dit zonder specificatiewijziging afhandelen. Een lege parameterwaarde kan je behandelen als was de parameter helemaal niet opgenomen. Een zoekresultaatIdentificatie langer dan 255 tekens kan je een lege collectie teruggeven, omdat je zeker weet dat er geen enkel zoekresultaat bestaat met een zoekresultaatIdentificatie langer dan 255 tekens.

**Comment by strijm** [comment]
Ik begrijp dat een breaking change niet wenselijk is door een striktere validatie in te bouwen.  
Het voorstel om bij een lege parameter deze te interpreteren als was er geen filter opgegeven (oftewel alles is goed), is nogal vreemd. De zoek parameter is geen filter, maar een zoek string, kortom als je niets opgeeft, vind je ook niets. Door een lege string te accepteren kunnen onze servers onnodig worden belast (security issue). Ik zou dus eerder opteren om in dit geval ook een lege verzameling te retourneren en dus geen zoekactie te starten. Dat komt ook dichter bij de uiteindelijk gewenste situatie. Het betreft hier een query parameter, dus dat lijkt geoorloofd en levert geen onnodige belasting van onze servers op.
Het voorstel om vanaf 255 karakters altijd een leeg resultaat terug te geven vind ik prima. Nadeel daarvan is wel dat dit een uitzondering wordt in de implementatie qua parameter validaties, dat is vanuit ons perspectief niet handig, maar ook niet onoverkomelijk.

Hieronder de berekening achter de maximale lengte van een adres. 
Een zoekstring kan bestaan uit de volgende gegevens:
max lengte straatnaam + spatie +
max lengte woonplaats naam + spatie +
lengte postcode + spatie +
max lengte huisnummer + spatie +
lengte huisletter + spatie +
max lengte huisnummertoevoeging 
Naast de spaties tussen de gegevens kunnen straatnamen en woonplaatsnamen spaties bevatten. Spaties worden vervangen door %20, dus 3 karakters i.p.v. 1. Overigens kunnen ook anders speciale karakters worden gebruikt en die worden dan op een vergelijkbare manier vervangen.
Met de (max) lengtes van de gegevens levert dat:
80 + 80 + 6 + 5 + 1 + 4  + 5x3 (spaties tussen parameters) = 191
Dat is echter exclusief spaties (of speciale karakters) in de straatnamen en woonplaatsnamen. Als we lengte 255 kiezen, dan blijven er 255 – 191 = 64 : 3 ≈ 21 karakters over voor spaties (of andere speciale karakters) in de straatnaam en woonplaatsnaam in een adres. Ik denk dat we met een redelijke zekerheid kunnen zeggen, dat dat voldoende is. Mocht later blijken dat dit toch niet lang genoeg is, dan kunnen we het altijd nog naar boven aanpassen (ruimer kan zonder breaking change, strikter maken wordt lastig, zo blijkt).

**Comment by fsamwel** [comment]
> Het voorstel om bij een lege parameter deze te interpreteren als was er geen filter opgegeven (oftewel alles is goed), is nogal vreemd. De zoek parameter is geen filter, maar een zoek string, kortom als je niets opgeeft, vind je ook niets. Door een lege string te accepteren kunnen onze servers onnodig worden belast (security issue). Ik zou dus eerder opteren om in dit geval ook een lege verzameling te retourneren en dus geen zoekactie te starten.

@strijm Ik vind dat prima, zo wordt het sneller duidelijk voor de gebruiker dat er iets niet goed is gegaan in de zoekvraag. Mijn voorstel (lege zoek levert alles) sloot aan bij hoe de implementatie nu is. Dacht ik het je daarmee makkelijk te maken, is het weer niet goed ;)

**Comment by strijm** [comment]
Goed dat je meedenkt @fsamwel! Maar als we in v2 wel de validaties gaan inbouwen, dan komt de implementatie die we voorstellen daar het best bij in de buurt, oftewel we nemen daar nu een voorschot op en zorgen er tegelijkertijd voor dat onze servers niet onnodig worden belast.
Samenvattend, dit is wat we zullen implementeren:
1. Bij lege zoek of zoekresultaatIdentificatie string -> leeg resultaat en dus geen foutmelding.
2. Bij zoek of zoekresultaatIdentificatie string langer dan 255 -> leeg resultaat en dus geen foutmelding.

**Comment by strijm** [comment]
@fsamwel de yaml blijft nu dus versie 1.1.0 omdat er functioneel niets is gewijzigd?

**Comment by strijm** [comment]
We zagen dat er wat verschillen zijn in descriptions in de yaml, ik maak even een branch aan, merge daar alle wijzigingen in en maak een pull request.

**Comment by fsamwel** [comment]
wijziging van de implementatie is correct doorgevoerd op acceptatie. Zowel lege als erg lange invoer levert lege collectie.

**Comment by fsamwel** [comment]
is opgelost, staat ook op productie
