### ISSUE TITLE
met fields vragen om link of met expand vragen om relatie geeft geen mogelijkOnjuist op betreffende identificatie

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#368]
Vragen om /adressen/0018200000152130 geeft:
```
    "mogelijkOnjuist": {
        "korteNaam": true,
        "straat": true,
        "openbareRuimteIdentificatie": true,
        "toelichting": [
            "Mogelijk verkeerde straat gebruikt. Het adres moet verwijzen naar de straat waaraan het adres ligt."
        ]
    },
```

Maar vragen met fields /adressen/0018200000152130?fields=huisnummer,postcode,_links.openbareRuimte geeft geen mogelijkOnjuist:
```
{
    "huisnummer": 21,
    "postcode": "9602KD",
    "_links": {
        "self": {
            "href": "https://api.bag.acceptatie.kadaster.nl/esd/huidigebevragingen/v1/adressen/0018200000152130?fields=huisnummer,postcode,_links.openbareRuimte"
        },
        "openbareRuimte": {
            "href": "https://api.bag.acceptatie.kadaster.nl/esd/huidigebevragingen/v1/openbareruimten/0018300000000271"
        }
    }
}
```

Tot voor kort werd hier wel mogelijkOnjuist meegeleverd. Dat zou ik ook verwachten, omdat deze link gevuld wordt met het gegeven dat in onderzoek staat. Zie in de [feature mogelijkOnjuist](https://github.com/VNG-Realisatie/Haal-Centraal-BAG-bevragen/blob/master/features/mogelijkOnjuist.feature) scenario "leveren mogelijkOnjuist bij met fields vragen naar link die mogelijk onjuiste identificatie bevat"

Hetzelfde geldt voor het vragen van een gerelateerd gegeven met expand, wanneer de relatie in onderzoek staat. Bijvoorbeeld /adresseerbareobjecten/0005018888889105?expand=panden&fields=documentnummer
Hier is de relatie met panden in onderzoek, dus had ik bij mogelijkOnjuist verwacht:
```
    "mogelijkOnjuist": {
        "pandIdentificaties": true,
        "toelichting": [
            "Verblijfsobject maakt mogelijk deel uit van een ander pand."
        ]
    },
```

**Comment by fsamwel** [comment]
Idem bij:
```
{
    "naam": "Zijdeweg",
    "status": "Naamgeving uitgegeven",
    "_links": {
        "self": {
            "href": "https://api.bag.acceptatie.kadaster.nl/esd/huidigebevragingen/v1/openbareruimten/1931300000000008?fields=naam,_links.woonplaats,status"
        },
        "woonplaats": {
            "href": "https://api.bag.acceptatie.kadaster.nl/esd/huidigebevragingen/v1/woonplaatsen/2387"
        }
    }
}
```

Hierin had ik ook verwacht:
```
    "mogelijkOnjuist": {
        "woonplaatsIdentificatie": true,
        "toelichting": [
            "Mogelijk verkeerde woonplaats gebruikt."
        ]
    },
```

**Comment by fsamwel** [comment]
En zelfde in /adresseerbareobjecten/0005018888889105?fields=_links.panden
Hierin had ik ook verwacht:
    "mogelijkOnjuist": {
        "pandIdentificaties": true,
        "toelichting": [
            "Verblijfsobject maakt mogelijk deel uit van een ander pand."
        ]
    },

**Comment by strijm** [comment]
@fsamwel:
De implementatie is inderdaad nog niet helemaal correct en was dat eerder ook nog niet. Wel was de laatste release meer conform de feature beschrijving dan daarvoor. Om de implementatie helemaal conform de feature beschrijving te maken is issue #294 ingediend, maar deze staat nog open.

**Comment by NicoleKortoomsBAG** [comment]
Het gaat om issue #293

**Comment by fsamwel** [comment]
besproken met Cathy, kan gesloten worden
