### ISSUE TITLE
vragen met fields om mogelijkOnjuist veld levert ander mogelijkOnjuist veld

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#369]
/adressen/0014200010896726?fields=woonplaats,mogelijkOnjuist.woonplaats geeft in het antwoord:
```
    "mogelijkOnjuist": {
        "huisnummer": true,
        "toelichting": [
            "Mogelijk is het verkeerde huisnummer geregistreerd."
        ]
    },
```

Er is met fields niet gevraagd om huisnummer en ook niet expliciet om mogelijkOnjuist.huisnummer.

Voorheen werd daarom mogelijkOnjuist niet geleverd, nu wel. Is dit aangepast zodat fields=mogelijkOnjuist.xxx alle mogelijkOnjuist gegevens levert (ik kan me vaag iets herinneren dat zoiets besproken is)?

**Comment by strijm** [comment]
@fsamwel:
De implementatie is inderdaad nog niet helemaal correct en was dat eerder ook nog niet. Wel was de laatste release meer conform de feature beschrijving dan daarvoor. Om de implementatie helemaal conform de feature beschrijving te maken is issue #294 ingediend, maar deze staat nog open.

**Comment by fsamwel** [comment]
besproken met Cathy, kan gesloten woorden
