### ISSUE TITLE
Description kenmerkNummeraanduidingInOnderzoek van de embedded nummeraanduiding niet correct

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#37]
KenmerkNummeraanduidingInOnderzoek{description:Limitatieve opsomming van alle kenmerken van dit object die in onderzoek zijn op dit moment, _of van alle kenmerken die ooit in onderzoek zijn geweest als er een tijdreisvraag is gesteld of een vraag naar de levenscyclus._ 

De laatste regel is volgens mij niet van toepassing. We stellen geen tijdreisvragen/ levenscyclus vragen.

**Comment by CathyDingemanse** [comment]
Mark definieert een nieuwe specificatie op basis van de feature van Melvin

**Comment by strijm** [comment]
In update #58 is dit aangepast in de specificatie. Er is nu nog één InOnderzoek type (al onderdeel van een Adres) die voor ieder attribuut of relatie van een Adres een boolean (=true) kan bevatten als er een onderzoek loopt naar het attribuut of de relatie. De boolean wordt weggelaten als er geen onderzoek loopt naar het attribuut of de relatie. Het attribuut inOnderzoek in Adres wordt weggelaten als er geen attributen of relaties in onderzoek zijn.

**Comment by fsamwel** [comment]
we zijn nog niet heel blij met de manier waarop in onderzoek nu is gemodelleerd. O.a. omdat er documentgegevens en datum inzitten die niet nodig zijn. Kan daardoor veel eenvoudiger. Hier maken we nieuw issue voor
