### ISSUE TITLE
Http status code 415 voor fout "Coördinatenstelsel {crs} in Content-Crs wordt niet ondersteund." incorrect

### ISSUE THREAD

**Issue by KayodeBakker** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#370]
Als een Content-Crs een CRS bevat dat niet wordt ondersteund dan dient er een 415 te worden geretourneerd volgens de specificaties, echter dit is incorrect. Een HTTP 415 is een "Unsupported Media Type" en dit refereert naar de Content-Type of Content-Encoding. Een CRS is daarentegen geen media type volgens http standaarden zoals te zien is in de volgende overzichten voor Content-Type en Content-Encoding:

[Content-Type beschreven](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Type)
[Mime types die mogen worden gebruikt binnen Content-Type](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types)
[Content-Encoding](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Encoding)

In geen van deze voorbeelden wordt een CRS opzet getoond en sterker nog in de Content-Type dient gezien de standaard van de OpenAPI specificaties juist "application/json" te zijn. Als een gebruiker dit als Content-Type hanteert en vervolgens een 415 terugkrijgt vanwege een foutieve CRS, kan er verwarring ontstaan.

Aangezien dit onderdeel uitmaakt van hoe een gebruiker een request opbouwt en verstuurt, stel ik voor dat niet een 415 wordt gegooid, maar een 400 aangezien dit in wezen inderdaad dan een foutieve request betreft.

Graag hoor ik hier de meningen over.

**Comment by fsamwel** [comment]
@strijm en @MelvLee  wat is jullie mening hierover?

**Comment by MelvLee** [comment]
Ik ben het met Kayo eens dat je geen 415 als status code moet retourneren als een consumer incorrect accept-crs of content-crs stuurt. De 415 moet alleen worden gebruikt voor incorrecte Content-Type headers.
Ik weet niet wat precies foutieve CRS wordt bedoeld. Als het een niet-bestaande CRS, dan verwacht ik een 400. Een CRS die niet wordt ondersteund zou moeten resulteren in een 406.
Mijn mening is gebaseerd op het volgende document dat ik gevonden heb: https://github.com/opengeospatial/conneg-by-crs/blob/master/18-072-Content-Negotiation-by-CRS.md

**Comment by KayodeBakker** [comment]
@strijm Heb jij enig indicatie wanneer hier naar wordt gekeken of op z'n minst op gereageerd?

**Comment by strijm** [comment]
We hebben de 415 fout destijds na overleg met meerdere partijen gekozen omdat die in het verlengde ligt van de Content-xxx headers, maar als de 415 echt alleen gebruikt mag worden voor foutieve media types, dan vind ik een 400 ook prima als dat beter overeenkomt met IETF specificaties.
Betekent dat dan een breaking change ? Wanneer willen we dit evt. doorvoeren?

**Comment by KayodeBakker** [comment]
Ik vermoed dat dit alleen een breaking change is voor partijen die bij generatie op basis van de specs ook de fout objecten meeneemt in het objectenstructuur en dit niet generiek opzet. Bij onze applicatie bijv. maakt het niet uit welk fout we terugkrijgen, we vangen dit op en steken het op basis van de code en dergelijke in het juiste jasje. Ik kan alleen niet spreken voor andere partijen.

@MelvLee Hoe kijk jij hiernaar? Ik vermoed dat dit alleen verkeerd kan gaan bij generatie en het gebruik daarvan. Niet per se koppeling.

**Comment by MelvLee** [comment]
Als consumer zou ik de status code gebruiken om te bepalen of ik verder kan (geen 4xx of 5xx status code) of dat een gefaalde request opnieuw moet worden geprobeerd. Bij 4xx status codes heeft dat weinig zin omdat de fout bij de consumer ligt en in de meeste gevallen moet de request worden aangepast. Bij 4xx status codes vind ik het belangrijk dat ik een goede fout beschrijving krijg en dat ik begrijp wat ik verkeerd heb gedaan, zodat de fout snel kan worden gefixt. Ik verwacht dus niet dat er logica wordt geïmplementeerd om 4xx status codes automatisch af te handelen en is (denk ik) de kans op een breaking change in 4xx afhandeling minimaal tot 0

**Comment by fsamwel** [comment]
@strijm @NicoleKortoomsBAG ik zie nu dat de API op acceptatie in dit geval een 400 fout geeft i.p.v. een 415. Is dit issue al opgelost? Of was er nog een ander issue met dezelfde inhoud?

**Comment by fsamwel** [comment]
Ik krijg hier nu als antwoord:
```
{
    "status": 400,
    "title": "Coördinatenstelsel epsg:4326 in Content-Crs wordt niet ondersteund.",
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
    "detail": "Bad request.",
    "instance": "https://api.bag.acceptatie.kadaster.nl/esd/huidigebevragingen/v1/panden?locatie=98095,438495"
}
```

* code wordt niet meer gevuld (was: "crsNotSupported")
* detail "Bad request" is wel erg weinig informatief. Had hier niet kunnen staan welk coördinatenstelsel wél ondersteund wordt
?

**Comment by strijm** [comment]
Die 400 code is goed. Deze fout kwam alleen voor bij de /panden endpoint omdat daar gezocht kan worden met een geometrie en waar dus de Content-Crs header opgegeven moet worden.
In de Accept-Crs header in de response zou moeten staan welke CRS-en wel ondersteund worden. 
De code zou in de response moeten staan, dat die er niet in staat is dan een foutje.
Dat er in detail alleen 'Bad request.' staat is altijd al zo en voor alle 400 (bad request) fouten hetzelfde. Als dat anders moet dan stel ik voor daar een nieuw issue voor te maken.
De foutafhandeling .feature moet overigens ook nog worden aangepast, omdat die nu nog niet overeenkomt met de nieuwe implementatie.

**Comment by strijm** [comment]
Er staat een nieuwe release in onze testomgeving, waarin e.e.a. is gecorrigeerd.

**Comment by fsamwel** [comment]
@strijm ik verwacht nu uit je opmerking "In de Accept-Crs header in de response zou moeten staan welke CRS-en wel ondersteund worden." dat er in de response een Accept-Crs header zit. Die zit er niet.

**Comment by strijm** [comment]
Dat is dan een bevinding, die we moeten oplossen. Ik geef het door.

**Comment by NicoleKortoomsBAG** [comment]
@fsamwel @MelvLee , 
Er staat een nieuwe versie gereed op de accpetatieomgeving waar deze bevinding is opgelost.
