### ISSUE TITLE
Is Content-Crs noodzakelijk bij bevraging van panden endpoint

### ISSUE THREAD

**Issue by KayodeBakker** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#371]
Bij /panden is er de mogelijkheid om locatie mee te geven en om deze reden is er vast het Content-Crs als header om in te vullen toegevoegd, maar is dat wel logisch en noodzakelijk?

Een gebruiker is al verplicht om een Accept-Crs mee te geven (#343 wat eigenlijk onnodig is) dus waarom is er ook de mogelijkheid om een Content-Crs vanuit de gebruiker in te vullen? Zijn er casussen waar er wordt verwacht dat een gebruiker een WGS84 geometrie meegeeft, maar een RD_NEW terug verwacht? Zo niet dan zou het voldoende moeten zijn om af te leiden vanaf de Accept-Crs wat de meegeleverde geometrie is.

Graag hoor ik hier meer over.

**Comment by KayodeBakker** [comment]
@strijm Heb jij enig indicatie wanneer hier naar wordt gekeken of op z'n minst op gereageerd?

**Comment by fsamwel** [comment]
Deze headers gebruiken we volgens de (API Designrules extensie)[https://docs.geostandaarden.nl/api/API-Strategie-ext/#crs-negotiation]

Hierin staan de beide headers gedefinieerd. Deze headers hebben een verschillende betekenis. De ene beschrijft in welk formaat het request is gestuurd. De ander zegt in welk formaat de response wordt gevraagd. Je kan niet aannemen dat het opgeven van de ene Crs-header de gelijke waarde van de andere Crs-header impliceert: "Request and response may be based on another coordinate reference system."

Als we dit hadden willen uitsluiten, dan hadden we één Crs header moeten definiëren die tegelijk request en response Crs definieert. We hebben hier echter gekozen aan te sluiten bij de NL API Designrules. Deze extensie heeft deze Crs headers weer overgenomen van het volgende voorstel: https://github.com/w3c/sdw/issues/757 

In W3C: https://www.w3.org/TR/sdw-bp/#c-geometrycrs wordt hier wel een kanttekening bij geplaatst (bij het gebruik van Crs-content negotiation in het algemeen). 

@MelvLee @CathyDingemanse hoe zien jullie dit? Maken we het hiermee inderdaad onnodig ingewikkeld?

**Comment by MelvLee** [comment]
Persoonlijk denk ik dat het niet zal voorkomen dat een consumer zijn request in een bepaalde crs formaat stuurt en de response in een andere formaat wil. Dus denk ik dat we het onnodig ingewikkeld hebben gemaakt.

In combinatie met #343 denk ik nu dat het helemaal niet slim is geweest om deze headers nu al aan de API te hebben toegevoegd. Op dit moment ondersteunt zowel BAG als BRK maar één geometrie formaat en volgens mij is het niet bekend wanneer en welke andere formaten er wordt ondersteund. Misschien komt er wel helemaal geen ondersteuning voor andere formaten. Het was veel handiger geweest als we deze headers hadden toegevoegd op het moment dat er wel meerdere formaten wordt ondersteund.

**Comment by NicoleKortoomsBAG** [comment]
Het staat me bij dat deze beslissing is genomen met het oog op het voorkomen van breaking changes. Nu kan een extra formaat worden toegevoegd als dat gewenst is zonder dat bestaande gebruikers daar last van hebben.

**Comment by CathyDingemanse** [comment]
> Het staat me bij dat deze beslissing is genomen met het oog op het voorkomen van breaking changes. Nu kan een extra formaat worden toegevoegd als dat gewenst is zonder dat bestaande gebruikers daar last van hebben.

Het op een later moment toevoegen van de headers was geen breaking change geweest....

**Comment by strijm** [comment]
De Content-Crs is noodzakelijk om aan te geven in welk CRS de aangeleverde geometrie is. Dit zou niet opgegeven hoeven worden als de geometrie in de default CRS WGS84 is voor GeoJSON (zie NL API Strategie design rules extension), maar aangezien de API de default CRS WGS84 (nog) niet ondersteunt kunnen we geen default opgeven in de API specificatie maar alleen een specifieke CRS nl.: EPSG:28992 (RD). Daarnaast is het ook niet handig om RD als default te specificeren, omdat dit een breaking change veroorzaakt zodra we WGS84 wel als default gaan ondersteunen. De header is nu dus verplicht om te zorgen dat er wel altijd een waarde wordt meegegeven en er niet uitgegaan kan worden van een default die nog niet wordt ondersteund. Het later optioneel maken van de header i.c.m. het ondersteunen van de default vormt geen breaking change omdat daardoor de implementatie wordt versoepeld en niet strikter wordt gemaakt.

Voor de Accept-Crs geldt hetzelfde. De Accept-Crs is noodzakelijk zodra de API een resource retourneert die een geometrie bevat, in dat geval moet een gebruiker aangeven in welke CRS de geometrie geleverd moet worden. Op dit moment levert de API alleen RD.

Zie ook #59 en aanverwante issues.

Er is dus eigenlijk maar één oplossing voor dit issue en dat is dat de API WGS84 als default CRS gaat ondersteunen voor zowel de Content-Crs als de Accept-Crs. 
Hiervoor heb ik issue #384 en #385 aangemaakt.

**Comment by CathyDingemanse** [comment]
> Er is dus eigenlijk maar één oplossing voor dit issue en dat is dat de API WGS84 als default CRS gaat ondersteunen voor zowel de Content-Crs als de Accept-Crs.
> Hiervoor heb ik issue #384 en #385 aangemaakt.

@strijm gaan we dit doen dan in Q2 of in Q3? Is dit ook het streven van het geodataplein initiatief?

**Comment by KayodeBakker** [comment]
@CathyDingemanse @fsamwel Hoe is dit dan opgelost bij de BRK? Daar is Accept-Crs niet een verplichting en is RD_NEW de default. Welke keuzes zijn daar gemaakt dat zo anders zijn vergeleken met de BAG?

**Comment by CathyDingemanse** [comment]
@JohanBoer zou jij jouw documentatie van onze voorkeursoplossing oplossing zoals we die hebben besproken hier willen delen? Thnx!

**Comment by JohanBoer** [comment]
Wij hebben binnen het design-team Haal Centraal besproken dat we de werking en afhandeling van content-crs binnen Haal-Centraal API's gelijk willen trekken. 

Daarvoor stellen we dat :
- Content-crs is niet meer verplicht. 
- RD/Amersfoort (EPSG:28992) wordt de default.
Deze twee punten zijn in de BRK-bevragen API al zo geïmplementeerd en moeten in de BAG-API worden aangepast. (=NON-breaking) 

Als we WGS84 (EPSG:4326) kunnen gaan leveren blijft RD de default en moeten consumers expliciet om WGS84 gaan vragen middels de content-crs of de accept-crs header. Dit wordt dan toegelicht in een Design Decision. 

Als we ETRS89, European (EPSG:4258) kunnen gaan leveren blijft nog steeds RD de default en moet er expliciet om ETRS89 gevraagd worden. 

Pas als er een grote (breacking) change vanuit business-belang wordt doorgevoerd, of er ontstaat een grote afnemers-vraag naar een andere default, dan overwegen we om de default van content-crs en accept-crs aan te passen (dat is breaking). Welke waarde dan de default waarde moet worden hangt af van de afnemerswens en eventueel van keuzes die op dat moment in de landelijke API-strategie zijn gemaakt.

**Comment by JohanBoer** [comment]
Tevens worden de Content-CRS en AceptCRS default epsg28992 maken in de common.yaml (versie 1.3.0 maken

**Comment by KayodeBakker** [comment]
Als ik het zo lees dan is er weinig op tegen om dit ook zo bij de BAG te doen of mis ik dan nog iets?

**Comment by fsamwel** [comment]
> Als ik het zo lees dan is er weinig op tegen om dit ook zo bij de BAG te doen of mis ik dan nog iets?

Dat is precies wat we gaan doen. We trekken de BAG implementatie op dit punt gelijk aan de BRK implementatie.

**Comment by fsamwel** [comment]
opgelost
