### ISSUE TITLE
onzekerheid over geo representatie in de response

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#38]
# Impediment

Er is onduidelijkheid over de manier waarop geo informatie in de response wordt beschreven. E.e.a. staat uit bij Geonovum. 
- Wanneer komt hierop een antwoord en door wie wordt dit bewaakt? 
- Geldt dit ook voor de BRK?

[assign aan ..., voeg label 'impediment' toe, kies bij 'projects' voor "organisatie en impediments"]

**Comment by strijm** [comment]
De geometrie zoals deze nu in #83 zit is afgestemd met Geonovum en is conform OGC yaml specificaties. Graag review.

**Comment by JohanBoer** [comment]
Inmiddels door een directe verwijzing naar opengis.net/ocgapi.
