### ISSUE TITLE
Fout bij zoeken op adres zoekresultaat identificatie in sommige gevallen

### ISSUE THREAD

**Issue by KayodeBakker** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#381]
Het valt op dat zoeken op een zoekresultaat identificatie bij adressen niet altijd werkt. We hebben tot zo ver beide werkende als niet werkende scenario's gevonden. Niet werkende zijn bijv:

- adr-3a493f5871ec400cf65f00b9cc3713d7 (Laan van Nieuw-Oost-Indië 210, 2593CC 's-Gravenhage)
- adr-07826475d009741731aa5b924f3bd1bd (Laan van Nieuw-Oost-Indië 210A, 2593CC 's-Gravenhage)

Het response die we ontvangen is helaas ook niks zeggend, namelijk:

```json
{
    "status": 500,
    "title": "Interne server fout.",
    "type": "https://tools.ietf.org/html/rfc7231#section-6.6.1",
    "detail": "Internal server error.",
    "instance": "https://api.bag.acceptatie.kadaster.nl/esd/huidigebevragingen/v1/adressen?zoekresultaatIdentificatie=adr-3a493f5871ec400cf65f00b9cc3713d7",
    "code": "serverError"
}
```

Graag vernemen we waarom deze casussen zonder enig indicatie niet werken.

**Comment by fsamwel** [comment]
@strijm ik kan deze reproduceren op acceptatie, niet (met de door Kayo opgegeven adressen) op productie. Dus op productie krijg ik voor het genoemde adres op zoekresultaatidentificatie geen fout (maar weet niet of er op productie wel andere adressen zijn waar hetzelfde kan gebeuren)

**Comment by NicoleKortoomsBAG** [comment]
Ik zal deze bug door het team laten onderzoeken.

**Comment by strijm** [comment]
Dit heeft er waarschijnlijk mee te maken, dat bij het zoeken naar adressen de locatie server in de productie omgeving wordt gebruikt en op het moment dat er BAG objecten in de acceptatie omgeving worden opgevraagd, deze objecten niet in de database in de acceptatie omgeving staan.

**Comment by KayodeBakker** [comment]
@strijm Wat kan hier dan aan worden gedaan?

**Comment by fsamwel** [comment]
Als ik /adressen?zoekresultaatIdentificatie gebruik met een zoekresultaatIdentificatie die niet bestaat, krijg ik geen 500 fout, maar een lege collectie.

Dit adres staat ook in de acceptatieomgeving (is een pand uit 1907). Als ik dit adres ophaal op de nummeraanduiding identificatie krijg ik ook een 500 server error (geen 404 dus de acceptatieomgeving kent dit adres):
{
    "status": 500,
    "title": "Interne server fout.",
    "type": "https://tools.ietf.org/html/rfc7231#section-6.6.1",
    "detail": "Internal server error.",
    "instance": "https://api.bag.acceptatie.kadaster.nl/esd/huidigebevragingen/v1/adressen/0518200000635033",
    "code": "serverError"
}

De nummeraanduiding (/nummeraanduidingen/0518200000635033) ophalen lukt wel.

Ik vermoed dus dat het probleem ergens anders ligt. Wellicht in de openbare ruimte, want /openbareruimten/0518300000202456 geeft ook een 500 Interne server fout.

@strijm kan je dit nog iets verder uitzoeken? We horen namelijk geen 500 fouten te krijgen, dataproblemen zouden denk ik netjes in de software moeten worden afgevangen (en naar mijn idee moeten leiden tot een signaal aan iemand om het op te lossen).

**Comment by NicoleKortoomsBAG** [comment]
Probleem is opgelost met een herstart.
Omdat er iets was uitgevallen, was ook de foutmelding niet zoals verwacht mag worden.
