### ISSUE TITLE
Adres response soms onvolledig (gelijk trekken acceptatie en productie data)

### ISSUE THREAD

**Issue by KayodeBakker** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#382]
Het is opgevallen dat er soms data lijkt te ontbreken die er wel hoort te zijn. Een voorbeeld hiervan is de Stationsplein 8 in Amsterdam. Volgens de Bagviewer heeft deze identificaties voor nummeraanduiding en een adresseerbaarobject, echter de response vanuit de API is veel beperkter waar de enige genoemde identificaties die van openbare ruimte en woonplaats zijn (naast natuurlijk zaken als straatnaam).

Aldus hier te zien in het response:

```json
{
    "_links": {
        "self": {
            "href": "https://api.bag.acceptatie.kadaster.nl/esd/huidigebevragingen/v1/adressen?zoekresultaatIdentificatie=adr-c2465ff70e262aa75b82b98e090fe282"
        }
    },
    "_embedded": {
        "adressen": [
            {
                "straat": "Stationsplein",
                "woonplaats": "Amsterdam",
                "korteNaam": "Stationsplein",
                "openbareRuimteIdentificatie": "0363300000005036",
                "woonplaatsIdentificatie": "3594",
                "_links": {
                    "openbareRuimte": {
                        "href": "https://api.bag.acceptatie.kadaster.nl/esd/huidigebevragingen/v1/openbareruimten/0363300000005036"
                    },
                    "woonplaats": {
                        "href": "https://api.bag.acceptatie.kadaster.nl/esd/huidigebevragingen/v1/woonplaatsen/3594"
                    }
                }
            }
        ]
    }
}
```

Dit zal waarschijnlijk te maken hebben met een incomplete testset en mocht dit daadwerkelijk het geval zijn dan zou ik heel erg aanraden om dit aan te pakken aangezien een acceptatie representatief dient te zijn voor een productie en data verschillen mogen dan niet tenzij er bijv. een AVG technisch vraagstuk hangt. Dit is daarentegen niet het geval voor BAG data.

Het gaat om bijv. het volgende request:

https://api.bag.acceptatie.kadaster.nl/esd/huidigebevragingen/v1/adressen?zoekresultaatIdentificatie=adr-c2465ff70e262aa75b82b98e090fe282
Voor adres: Stationsplein 8, 1012AB Amsterdam

**Comment by fsamwel** [comment]
het genoemde voorbeeld is inderdaad een nummeraanduiding die in 2018 en een verblijfsobject die in 2020 is geregistreerd. acceptatie is gevuld met productiedata van een paar jaar terug. Wel knap dat je een (weliswaar onvolledig) adres terugkrijgt op het zoekresultaat, terwijl nummeraanduiding (en adresseerbaar object) niet in de database staan.

**Comment by NicoleKortoomsBAG** [comment]
De achterliggende applicatie voor de zoekfunctionaliteit heeft in acceptatie een andere database dan de rest van de acceptatieomgeving. De zoekfunctionaliteit is gebaseerd op de productieomgeving. Omdat de acceptatieomgeving van de API wel een afzonderlijke testomgeving heeft, ontstaat dit probleem. De acceptatieomgeving zal niet gelijk worden getrokken aan productie. De oplossing voor deze specifieke gevallen is om een ander testgeval te kiezen dat geheel voor 2018 ligt.

**Comment by fsamwel** [comment]
Ik heb uitleg hierover toegevoegd aan de [Getting started](https://vng-realisatie.github.io/Haal-Centraal-BAG-bevragen/getting-started#probeer-en-test-de-api):
>  De (acceptatie)testomgeving bevat een kopie van de productiedata van enkele jaren geleden. Het is daardoor mogelijk dat recent toegevoegde of gewijzigde gegevens niet of onjuist worden getoond. Ook kan een recent toegevoegd adres wel verschijnen als adreszoekresultaat, maar niet worden geleverd door de API. Heb je voor het testen van je clientapplicatie volledige en actuele data nodig, dan kun je hiervoor je testomgeving aansluiten op productie.

**Comment by KayodeBakker** [comment]
Niet helemaal hoe een nette OTAP hoort te werken, maar als de keuze wordt gemaakt om het hierbij te laten dan is dat maar zo.

@fsamwel Dank voor de toevoeging aan de getting started!
