### ISSUE TITLE
Kadaster faseert per oktober 2021 de API V1 uit die nu door HaalCentraal wordt gebruikt -> overstap naar V2 noodzakelijk

### ISSUE THREAD

**Issue by joostvkempen** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#387]
# Impediment

De HaalCentraal BAG-API maakt nu gebruik van https://api.bag.kadaster.nl/esd/huidigebevragingen/v1
Vanaf 1-4-2021 wordt deze uitgefaseerd en is https://api.bag.kadaster.nl/lvbag/individuelebevragingen/v2/ de productie API

-----------------------------------

Met de gewijzigde Wet bag zijn de BAG producten in een nieuw jasje gestoken. Naast inhoudelijke veranderingen door de wetswijziging, zijn ook de wensen van onze afnemers en de uitkomsten van klanttevredenheidsonderzoek meegenomen in de productontwikkeling.

De overstap van BAG 1.0 naar BAG 2.0 verloopt in 3 fasen:

- tot en met maart 2021

Wij leveren de BAG 1.0 producten volledig en actueel. U ontvangt bij de BAG 1.0 producten alle gegevens van de bronhouders (door vertalingen in de LV).

- april tot oktober 2021

Wij stoppen met de handmatige controles op de transformatie van BAG 2.0 naar BAG 1.0. Wij geven geen garanties meer op de BAG 1.0 data, bijvoorbeeld als het gaat om de volledigheid en actualiteit. Lees meer op de pagina Gevolgen stoppen actieve controle BAG 1.0.

- vanaf oktober 2021

Wij leveren de BAG 1.0 producten niet meer. Iedereen moet dan overgestapt zijn op de BAG 2.0 producten.

**BAG API Individuele Bevragingen**
Met deze nieuwe API zijn de gegevens uit de LV BAG volgens BAG 2.0 beschikbaar. Daarmee vervalt BAG Bevragen in de huidige vorm. De huidige API REST JSON wordt vervangen door een gewijzigde REST API waarmee ook de gegevens conform BAG 2.0 bevraagd kunnen worden.

meer informatie
https://www.kadaster.nl/zakelijk/registraties/basisregistraties/bag/bag-2.0-producten
https://www.kadaster.nl/zakelijk/producten/adressen-en-gebouwen/bag-api-individuele-bevragingen

**Comment by NicoleKortoomsBAG** [comment]
Hallo Joost, 
De API met als basis URL  https://api.bag.kadaster.nl/esd/huidigebevragingen/v1 blijft gewoon bestaan. Deze is gebaseerd op BAG 2.0 .
De v1 API met de URL https://bag.basisregistraties.overheid.nl/api/v1/ is gebaseerd op BAG 1.0 en wordt vervangen voor de API met als URL https://api.bag.kadaster.nl/lvbag/individuelebevragingen/v2/
Sorry voor de onduidelijkheid hierover. 
Nicole Kortooms

**Comment by joostvkempen** [comment]
Hoi Nicole, duidelijk, ik had inderdaad niet begrepen dat er meerdere basis-url's waren. En even voor de volledigheid: die met 'esd' erin voldoen aan de HaalCentraal specificaties van de VNG? @JohanBoer ?

**Comment by NicoleKortoomsBAG** [comment]
Hoi Joost,
dat klopt. ESD, huidige bevragingen is de API van Haal Centraal.
Groeten Nicole
