### ISSUE TITLE
gegevensgroep "voorkomen" uit de embedded nummeraanduiding van adres bevat irrelevante info

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#39]
# Impediment

omdat deze API geen materiele en formele historie bevat, is dit voor de gebruiker niet te plaatsen. De enige relevante gegevens zijn mijn inziens:
- tijdstip registratie
- begin geldigheid.

Klopt dat? 

Ook het woord "voorkomen" verliest relevantie in deze API. Ik stel voor dit weg te laten en alleen bovenstaande op te nemen conform BRP en BRK bevragen.

**Comment by strijm** [comment]
https://github.com/VNG-Realisatie/Haal-Centraal-BAG-bevragen/pull/48
