### ISSUE TITLE
lokaal ID, namespace en versie ipv padparameter.

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#40]
De identificaties hebben een 

],
	    "identificatie": {
	      "lokaalID": "1234010000000001",
	      "namespace": "NL.IMBAG.Verblijfsobject",
	      "versie": "1"

Dit zijn drie dingen die onderdeel van de resource zijn en en niet 1 padparameter die een gebruiker verwacht. Is er eenzelfde lokaal ID met verschillende versies? Of hetzelfde lokaal ID met een andere namespace? 
Is dit niet een implementatie aangelegenheid die voor de gebruiker onzichtbaar kan blijven? Stel voor om het lokaal ID als padparameter en "identificatie" op te nemen.

**Comment by strijm** [comment]
Dit isues is afhankelijk van #35. De namespaces zijn vast per object type. Het ID identificeert een object uniek en een voorkomen van een object heeft een versie (deze is niet per se uniek). De versie is optioneel en wordt vaak niet meegegeven.

**Comment by JohanBoer** [comment]
Dit issue is gerelateerd met (o.a.) #214  Als die is geímplementeerd is deze issue ook opgelost
