### ISSUE TITLE
Als gebruiker van de API wil ik bij het vragen van een adres direct het bijbehorende adresseerbaar object krijgen

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#403]
...zodat ik minder requests hoef te doen om de benodigde adresgegevens te krijgen.

Vanuit een leverancier voor gemeente Den Bosch komt het verzoek om in de adressen resource met de expand parameter ook adresseerbare objecten te kunnen vragen en krijgen. In hun applicatie moeten gegevens van het adres plus gegevens van het adresseerbare object tegelijkertijd en samen worden geleverd aan de front end. Ook als resultaat van een zoekvraag. Dan scheelt het de helft van het aantal benodigde requests wanneer bij het vragen of zoeken van de adressen ook direct de (benodigde gegevens van de) adresseerbare objecten kunnen worden geleverd.

**Comment by NicoleKortoomsBAG** [comment]
@fsamwel, dit is natuurlijk wel mogelijk, maar betekent dat je het adres zowel met woonplaats, openbare ruimte, nummeraanduiding en verblijfsobject te expanden maakt. Dat kunnen behoorlijk grote responses worden. Er is in eerste instantie bewust voor gekozen om de expand te beperkten tot de objecten van waaruit het adres wordt gevormd.
 
Bij het opvragen van een adresseerbaarobject kan je expand toepassen op het adres. Zou dat in de usecase een uitkomst kunnen bieden? Met uitzondering van de zoekresultaatidentificatie kent deze dezelfde ingangen.

**Comment by fsamwel** [comment]
de user story gaat uit van het zoeken van een adres op (bijv.) meestal postcode + huisnummer. Dit kan meerdere adressen leveren (met huisletters en -toevoegingen). Daarbij zijn in het antwoord ook direct gegevens uit de ado nodig. Nu is zoeken van adresseerbare objecten op adres niet mogelijk

**Comment by fsamwel** [comment]
wordt opgelost met https://github.com/VNG-Realisatie/Haal-Centraal-BAG-bevragen/pull/406

**Comment by NicoleKortoomsBAG** [comment]
@fsamwel 
Wanneer wordt bevraagd met pandID of adoID wordt, wanneer één ado meerdere adressen kent (hoofd en nevenadressen) verschillende keren hetzelfde ADO geretouneerd. 
Mijn voorstel is om geen expand van de ADO toe te staan wanneer het adressenendpoint wordt bevraagd met deze 2 parameters. 
Wanneer het adoID of het pandID bekend is en men wil de gegevens van het ado hebben, dan zijn er andere, logischere bevragingen om te doen. Het voorkomt dat er informatie dubbelop wordt verzonden.
Dit vraagt wel om een tekstuele aanpassing in de specs omdat deze combinatie van parameters nu niet wordt uitgesloten.

**Comment by fsamwel** [comment]
@NicoleKortoomsBAG kunnen we hiermee wachten tot de rest van het team terug is van vakantie?

**Comment by NicoleKortoomsBAG** [comment]
@fsamwel, dat kan dan zetten we de werkzaamheden even on hold

**Comment by fsamwel** [comment]
@NicoleKortoomsBAG 

> dat kan dan zetten we de werkzaamheden even on hold

ik bedoelde wachten met de discussie en beslissing over verbieden bevragen met pandId of adoId i.c.m. expand ado. Dat hoeft op zich de werkzaamheden voor de expand ado niet on hold te zetten, toch? Of begrijp ik je verkeerd?

**Comment by strijm** [comment]
Tijdens overleg met HC is besloten dat gerelateerde resources niet geëxpand kunnen worden als er naar resources wordt gezocht met een identificatie van hetzelfde type als de gerelateerde resource. In PR #435 is dit in de description van de betreffende endpoints toegevoegd.
Bv.
Bij het /adresseerbareobjecten endpoint kan met een pand identificatie worden gezocht naar adresseerbareobjecten. De panden kunnen dan niet geëxpand worden omdat dat voor ieder adres dezelfde pand informatie oplevert.
