### ISSUE TITLE
Als gebruikers van de API wil ik een exact kunnen zoeken zoeken op postcode en huisnummer

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#404]
...zodat ik alleen adressen krijg die exact voldoen aan mijn zoekvraag.

We hebben nu alleen fuzzy zoeken van adressen. Dit levert elk adres dat ook maar enigszins voldoet aan de zoekvraag. In sommige vormen van gebruik wil ik minder resultaten krijgen, alleen die resultaten die exact voldoen aan mijn zoekvraag.

Bijvoorbeeld fuzzy zoeken op "beethovenlaan 4" vindt ook:
- "Beethovenlaan 1, 4102BM Culemborg" (de 4 zit in de postcode)
- "Beethovenlaan 1a-4, 7604GC Almelo" (de 4 zit in de huisnummertoevoeging)
- "Beethovenlaan 4, 1217CJ Hilversum" (de 4 is het huisnummer)
- "Beethovenlaan 41, 2151GT Nieuw-Vennep" (de 4 zit in het huisnummer)

In sommige applicaties worden op de zoekresultaten direct een hoop gerelateerde gegevens erbij gehaald (oma, de hele resources adres en adresseerbaar object), dus wil je niet teveel resultaten krijgen. Daarom is er behoefte om adressen ook te kunnen zoeken op de combinatie postcode + huisnummer. Zoeken met huisnummer 4 moet dan niet huisnummer 41 vinden of huisletter 4, uiteraard wel huisnummer 4 met huisletter "B" enz.

Daarom graag toevoegen query parameters postcode, huisnummer, huisletter en huisnummertoevoeging.

N.B. dit is gevraagd door een leverancier van gemeente Den Bosch

**Comment by NicoleKortoomsBAG** [comment]
@fsamwel 
Zou deze ook een exacte match feature moeten kennen? 
Dis is de feature die we bij deze zoekopdracht bij Individuele Bevragingen hebben geimplementeerd. https://github.com/lvbag/BAG-API/blob/master/Features/exacte_match.feature

**Comment by fsamwel** [comment]
@CathyDingemanse @MelvLee @JohanBoer hoe denken jullie hierover?

**Comment by MelvLee** [comment]
Ik denk dat exacte match ook moet worden toegevoegd. Anders loop je het risico dat bestaande consumers van Individuele Bevragingen niet zonder grote aanpassingen kunnen overstappen naar de HC versie

**Comment by JohanBoer** [comment]
Een alternatief voor de exacteMatch parameter is dan het opgeven van alle parameters die er toe doen. Dus als alternatief voor het 2e scenario geef je dan de huisletter-parameter en de huisnummertoevoegingparameter op zonder een waarde. Dat zit volgens mij wat dichter bij een restfull implementatie. 

Deze exacteMatch maakt het volgens mij wel explicieter voor de developer en laat minder ruimte voor interpretatie. Als het eerste punt niet al te zwaar weegt (en dat denk ik) dan kunnen we ons volgens mij conformeren aan deze feature. Daarbij creëer je dan niet 2 verschillende manieren van zoeken.

**Comment by CathyDingemanse** [comment]
Ik denk dat de exacte match een waardevolle aanvulling is, naast het punt van @MelvLee, wat natuurlijk ook zwaar weegt ivm de integratie van HC API's.

**Comment by JohanBoer** [comment]
Inmiddels in productie.
