### ISSUE TITLE
Als PO wil ik graag 1 endpoint voor adresseerbaar objecten 

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#41]
...zodat een consumer een identificatie (bijvoorbeeld uit een andere registratie) kan opgeven of een provider van een gerelateerde registratie URI kan opbouwen zonder kennis van het type.
 

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by strijm** [comment]
ZIe update #58, hierin bestaat één endpoint voor het opvragen van adresseerbareobjecten met identificatie van een adresseerbaar object.

**Comment by fsamwel** [comment]
onze wens is dat het één resource is. Dus de eigenschappen niet onderbrengen in ligplaats, standplaats en verblijfsobject properties. Graag platslaan van de eigenschappen in de resource. Plus een property "type" die aangeeft of het een ligplaats, standplaats of verblijfsobject is.

**Comment by strijm** [comment]
Dit issue is volgens mij opgelost in #83. Graag review.
