### ISSUE TITLE
Als berichtontwerper wil ik weten of het Keuzeitem moet worden van Hallinks

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#43]
...zodat we het bericht design conform wens kunnen maken. 

Doordat de locatieserver-complexiteit van het zoeken naar BAG_id's (NUM en ADO) op basis van een free query op adres wordt weggehouden bij de consumer krijgen we nu Keuzeitems aangeboden die al voorzien zijn van een Numeraanduidingidentificatie en een adreseerbaarobjectidentificatie. 

De nummeraanduidingidentificatie wordt ook gebruikt om het adres te identificeren dat opgevraagd kan worden op een endpoint /adressen/{identificatie} 

De vraag is nu of we in de respons met keuzeitems ook HAL-links op moeten nemen naar Numeraanduiding, Adresseerbaarobjectaanduiding en adres.

**Comment by JohanBoer** [comment]
Mijn mening is dat we inderdaad die HAL-links op moeten nemen, maar geen embedded.

**Comment by JohanBoer** [comment]
Mark's opmerking of KeuzeitemCollectieHal niet gewoon Keuzelijst moet heten hangt hiermee samen.

**Comment by CathyDingemanse** [comment]
Eens.
- Het opnemen van een embedded nummeraanduiding willen we sowieso niet, want we willen een adres :-)
- het opnemen van een embedded ADO of Adres suggereert dat je naast een selectie van een adresstring (om een adres of ADO op te vragen) ook een expand parameter opgeeft om diezelfde ADO en adres op te vragen. Dat lijkt niet erg zinvol.

**Comment by MelvLee** [comment]
Als we geen _links gaan aanbieden, dan is KeuzeitemCollectieHal geen goede naam en kun je het beter Keuzelijst noemen.

Wil je echter de consumer meer helpen (discoverable), dan kan je de _links gebruiken om aan te geven bij welke endpoints de id's kunnen worden gebruikt. De vulling van de _links zou er dan als volgt uit kunnen zien:
``` json
{
 "_links": {
     "_self": {},
     "adres": {
        "href": "/adressen/{nummeraanduidingidentificatie}",
        "templated": true,
        "title": "templated endpoint waarmee een adres wordt geraadpleegd mbv nummeraanduidingidentificatie" },
     "adresseerbaarObject": {
        "href": "/adresseerbaarobject/{adresseerbaarObjectIdentificatie}",
        "templated": true },
     "pand": {
       "href": "/pand?adresseerbaarObjectIdentificatie={adresseerbaarObjectIdentificatie}",
       "templated": true }
  }
}
```
Het is wel zo dat deze endpoints in de yaml file staan, dus zou je er van uit kunnen gaan dat de consumer dit zelf kan achterhalen.

**Comment by JohanBoer** [comment]
Ik zie argumenten, maar ik zie nog geen duidelijke beslissing. Gaan we wel of geen Hal_links opnemen bij het keuzeitem  en als we dat wel gaan doen, wordt de naam dan ook Keuzelijst ?

**Comment by MelvLee** [comment]
Ik zou het doen. Wij hebben eenmaal gekozen om Hal te gebruiken binnen Haal Centraal. En ik heb geen argumenten gelezen om het niet te doen. En ik zou gaan voor KeuzelijstHal. En misschien ten overvloede, geen KeuzeitemHal, want door templated url's te gebruiken is het niet nodig om per Keuzeitem links op te nemen.

**Comment by CathyDingemanse** [comment]
Ik ben overtuigd! 
We doen de template waar de consumer zelf het id kan invullen. Dan is de belasting voor de provider ook te overzien. Hij hoeft niet voor ieder resultaat de links te leveren, maar kan op het niveau van de collectie templated uri's aanleveren. Let's do this. 
We gaan voor de beste klantbeoordeling, en dus voor topservice! Daar hoort ook bij dat je het contract niet breekt, door met HAL links te werken. Voor de consumers die dat graag willen, bieden we graag deze mogelijkheid.

**Comment by CathyDingemanse** [comment]
Besluit: 
Melvin maakt feature file, zodat deze in de spec kan worden opgenomen door Mark. Melvin levert deze 31-1. Deze wordt gereviewed, zodat Mark deze in de specificatie kan opnemen.

**Comment by MelvLee** [comment]
De feature file is geuploaded met een pull request.
Ik zie dat het nu niet mogelijk is om Frank als reviewer toe te voegen

**Comment by strijm** [comment]
Deze feature is in update #58 in de specificatie opgenomen.

**Comment by fsamwel** [comment]
de lins staat nog niet op de juiste plek. Aangezien we template gebruiken, is één link op overkoepelend (collectie) niveau voldoende. Dus _links van een keuzeitem verwijderen en toevoegen aan de halcollectionlinks

**Comment by JohanBoer** [comment]
Inmiddels is dit issue achterhaald. We hebben de naamgeving aangepast naar Zoekresultaat. De zoekactie levert een collectie met zoekresultaten op en bij ieder zoekresultaat wordt er enkel een link  link naar het adres toegevoegd.
