### ISSUE TITLE
Zoek met postcode + huisnummer: komen adressen met een kleine letter als huisletter voor?

### ISSUE THREAD

**Issue by MelvLee** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#441]
Just checking, omdat ik dit tegenkom in de exacte_match.feature

**Comment by strijm** [comment]
Volgens de BAG Catalogus moet een huisletters voldoen aan de regex [a-zA-z] en zijn kleine letters dus toegestaan en ze komen zeker voor.

**Comment by MelvLee** [comment]
OK. heb je een adres met huisletter in kleine letter? Dan kan ik testen of er hierop kan worden gezocht. En ook een geval voor huisnummertoevoeging? Ik neem aan dat hier hetzelfde geldt

**Comment by kad-pietem** [comment]
kleine huisletter: 0003200000135997
kleine huisnummertoevoeging: 0014200022206096
kleine huisletter EN kleine huisnummertoevoeging 0056200000013624
