### ISSUE TITLE
zoeken op postcode toestaan met spatie tussen cijfers en letters

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#442]
De queryparameter postcode heeft een pattern: ^[1-9]{1}[0-9]{3}[a-zA-Z]{2}$

Dit betekent dat het niet is toegestaan een spatie tussen de cijfers en letters van de postcode te zetten. 

Volgens NEN 5825:2002 en de [adresregels feature](https://github.com/VNG-Realisatie/Haal-Centraal-BAG-bevragen/blob/master/features/adresregels.feature) hoort er een spatie tussen de cijfers en letters van de postcode in een adres. Waarom is het dan niet toegestaan hiermee te zoeken?

**Comment by strijm** [comment]
We zullen de reguliere expressie aanpassen, zodat het zoeken met een spatie (optioneel) in de postcode mogelijk wordt.
