### ISSUE TITLE
Moeten zowel de verkorte als de lange straatnaam opgenomen worden in adres ?

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#45]
N.a.v. opmerking @strijm  in #36 

Als dit de verkorte straatnaam is, dan mag deze slechts 24 karakters lang zijn. Een beter voorbeeld van een verkorte naam is dan denk: de langste straatnaam van Nederland: 'Laan van de landinrichtingscommissie Duiven-Westervoort', de verkorte naam daarvan is: 'Ln vd l D Westervoort'. Moeten niet zowel de verkorte als de volledige straatnaam in Adres worden teruggegeven?

**Comment by CathyDingemanse** [comment]
Goed idee, doen we.

**Comment by JohanBoer** [comment]
Toegevoegd

**Comment by CathyDingemanse** [comment]
gereviewed, staat er in. @ @ # #
