### ISSUE TITLE
Design decisions aanpassen

### ISSUE THREAD

**Issue by strijm** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#450]
Als er een query parameter wordt toegevoegd in de API spec dan moet deze volgens de design decisions een postfix -query krijgen. Voor parameters die een uniek identificerend gegeven betreffen en als path of query parameter in een API kunnen voorkomen, is dat terecht, maar voor gegevens die niet als path parameter kunnen voorkomen is het overbodig.
Bv. een huisnummer is op zichzelf geen uniek identificerend gegeven en zal daarom niet snel als path parameter gebruikt worden. Dan is het niet nodig om de parameter een postfix -query te geven.
Dit zou in de design decisions toegevoegd moeten worden.

**Comment by melsk-r** [comment]
@strijm Waar zie jij deze Design Decision staan? Ik kan deze regel nl. niet vinden.

**Comment by strijm** [comment]
Vreemd, ik kan het ook niet meer vinden. Ik was er van overtuigd dat dit in de HC common stond, maar zie het daar en in het BAG project master branches niet meer staan.

**Comment by melsk-r** [comment]
Ik zal dit issue sluiten. Mocht je de Design Decision alsnog vinden dan kun je dit issue opnieuw opvoeren.
