### ISSUE TITLE
Probleem met de 1.4 versie specs in GitHub pages omgeving

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#459]
In de GitHub pages omgeving leidt [de link naar de 1.4 specificatie in de swagger omgeving](https://vng-realisatie.github.io/Haal-Centraal-BAG-bevragen/swagger-ui-io) tot een foutmelding.

We dachten dit op te kunnen lossen met [PR 458](https://github.com/VNG-Realisatie/Haal-Centraal-BAG-bevragen/pull/458) maar dat hielp niet.
Nu blijkt er zowel in regel 2026 als in regel 2033 van [de genereervariant van openapi.yaml in de develop branch](https://github.com/VNG-Realisatie/Haal-Centraal-BAG-bevragen/blob/develop/specificatie/genereervariant/openapi.yaml) een 'description' property voor te komen. Zeer waarschijnlijk veroorzaakt die het probleem.

**Comment by strijm** [comment]
@melsk-r 
Welke branch heb je hier als uitgangspunt gebruikt? Bedoel je hier versie 1.4 of 1.3? Voor zover ik weet is er nog geen versie 1.4.
Je kunt hier niet de develop branch gebruiken. M.i. moet je hier de develop-1.3 branch gebruiken.

**Comment by melsk-r** [comment]
Nu is inderdaad de versie van de develop branch gebruikt. Ik zal het wijzigen naar de develop-1.3 branch.

**Comment by melsk-r** [comment]
Is aangepast en nu is het correct. Ik sluit dit issue.
