### ISSUE TITLE
Als berichtontwerper wil ik gebruik kunnen maken van de (valide) constructie oneOf

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#46]
zodat het contract (OAS#) precies aangeeft wat de consumer mag verwachten. 

Ik snap dat de oneOf nu code-generatie problemen oplevert bij het Kadaster, en bij de BRK hebben we ervoor gekozen om de oneOf weg te laten en een impliciete constructie te gebruiken. Dit is volgens mij minder duidelijk voor consumers (of ik begrijp het niet goed. Is ook een mogelijkheid :) )

Dit vind ik eigenlijk het pushen van providerproblemen naar de consumers. De provider kan voor het genereren van code uitstekend tijdelijk de oneOf constructie tijdelijke elimineren.

**Comment by JohanBoer** [comment]
Uitleg van een oplossingsrichting van Melvin via mail ontvangen :

Ik bekijk nu vooral code generatie voor C# (.NET) en ik gebruik voornamelijk de NSwag suite om code te genereren. Het genereren van de classes gaat met deze suite tot nu toe altijd goed. Waar het niet goed gaat is het genereren van de methode voor een path met oneOf in zijn response. De return value van de methode is altijd de class die hoort bij de eerste oneOf component.

Een concreet voorbeeld uit de BAG API yaml ter illustratie voor de niet-programmeurs onder ons:

 /adresseerbaarobjecten/{adresseerbaarObjectIdentificatie}:
   get:
     security:
       - apiKeyBAG: []
     operationId: raadpleegAdresseerbaarObject
     tags:
       - Adresseerbaar objecten
     summary: Raadpleeg Adresseerbaar Object  o.b.v. een sleutel
     description: Raadpleeg de adresseerbaar object op basis van de identificatie
     parameters:
       - $ref: '#/components/parameters/adresseerbaarObjectIdentificatie'
     responses:
       '200':
         description: Geslaagd
         content:
           application/hal+json:
             schema:
               oneOf:
                 - $ref: '#/components/schemas/LigplaatsHal'
                 - $ref: '#/components/schemas/StandplaatsHal'
                 - $ref: '#/components/schemas/VerblijfsobjectHal'
               discriminator:
                 propertyName: type 

wordt in c# code

       public System.Threading.Tasks.Task<LigplaatsHal> RaadpleegAdresseerbaarObject(string adresseerbaarObjectIdentificatie);

Dit is niet correct, want met deze methode kan er geen StandplaatsHal of VerblijfsobjectHal worden geretourneerd.

De methode was correct geweest als het er als volgt uit had gezien:

       public System.Threading.Tasks.Task<AdresseerbaarObject> RaadpleegAdresseerbaarObject(string adresseerbaarObjectIdentificatie);

AdresseerbaarObject is namelijk de base class waar LigplaatsHal, StandplaatsHal en VerblijfsobjectHal van afleiden.

Voor code generatie met NSwag kan door het toevoegen van een ref naar AdresseerbaarObject als eerste oneOf waarde ervoor worden gezorgd dat de correcte class als return value wordt gebruikt, dus

               oneOf:
                 - $ref: '#/components/schemas/AdresseerbaarObject'
                 - $ref: '#/components/schemas/LigplaatsHal'
                 - $ref: '#/components/schemas/StandplaatsHal'
                 - $ref: '#/components/schemas/VerblijfsobjectHal'

2 kant tekeningen bij deze hack:
- Ik weet niet of de openapi-generator-maven-plugin in dit geval de gewenste java code genereert. Dit moet ook gevalideerd worden voor andere talen zoals javascript en python
- deze hack moet handmatig gebeuren, want als je het laat staan is de OAS spec niet correct.

**Comment by strijm** [comment]
Dit issue is opgelost in #83 omdat er geen oneOf meer gebruikt wordt. Graag review.
