### ISSUE TITLE
Test-resultaten n.a.v. regeressie-test + 1.4 functionaliteit. 

### ISSUE THREAD

**Issue by JohanBoer** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#468]
- Bij request "/adressen/zoek?zoek=plantage delft&page=32&pageSize=5" worden er 2 zoekresultaten geretourneerd waar dat er eerder 3 waren. 
- Bij request "/adressen/zoek?zoek=plantage delft&page=8" worden er 17 resultaten geretourneerd waar dat er eerder 18 waren.
- Bij request "/adressen/zoek?zoek=plantage delft&page=8" is het eerste  resultaat "Nieuwe Plantage 104, 2611XV Delft" waar dat eerder "Nieuwe Plantage 103, 2611XV Delft" was. 
-  Bij request  "/adresseerbareobjecten?pandIdentificatie=0599100000103376&expand=panden&fields=oppervlakte"  krijg ik een "400" respons waar dat eerder een "200" was. 
- Bij request "/adresseerbareobjecten?pandIdentificatie=0014100022190687&expand=panden" krijg ik een "400"respons waar dat eerder een "200"respons was. 
- Bij request "/adresseerbareobjecten?pandIdentificatie=0037100000016720&expand=panden" krijg ik een "400"respons waar dat eerder een "200"respons was. 
- Bij request "/panden?bbox=52.10544278,5.09890079,52.10423390,5.09996295" krijg ik een "500"internal server error. Hier zijn WGS84 coordinaten ingevoerd voor de bounding box. Ik verwacht hier een 400 bad request.
- Bij Request "/panden?bbox=134647,457842,137512,455907"  (te grote boudning box)  ontrbreekt de "InvalidParams" in de foutmelding.

**Comment by strijm** [comment]
@JohanBoer 
De foutmelding die op dit moment het beste matched met de foutafhandeling.feature (dus zonder deze te moeten aanpassen), is dit:

```
{
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
    "title": "Een of meerdere parameters zijn niet correct.",
    "status": 400,
    "detail": "Bad request.",
    "instance": "http://localhost:8080/v1/panden?bbox=134647,457842,137512,455907",
    "code": "paramsValidation",
    "invalidParams": [
        {
            "name": "bbox",
            "code": "maximum",
            "reason": "Waarde is hoger dan maximum 250000."
        }
    ]
}
```

Mee eens? Of heb jij een beter voorstel?

**Comment by strijm** [comment]
@JohanBoer 
Er is op dit moment niet een foutmelding in de foutafhandeling.feature die past bij de fout dat er een coördinaat wordt opgegeven in een ander CRS dan RD. Waarschijnlijk moet het zoiets worden:

```
{
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
    "title": "Een of meerdere parameters zijn niet correct.",
    "status": 400,
    "detail": "(52.10544278, 5.09890079) is geen geldig epsg:28992 coördinaat.",
    "instance": "http://localhost:8080/v1/panden?bbox=52.10544278,5.09890079,52.10423390,5.09996295",
    "code": "paramsValidation"
}
```
maar dan met een invalidParams blok, maar wat vullen we daar dan in?

**Comment by JohanBoer** [comment]
> @JohanBoer De foutmelding die op dit moment het beste matched met de foutafhandeling.feature (dus zonder deze te moeten aanpassen), is dit:
> 
> ```
> {
>     "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
>     "title": "Een of meerdere parameters zijn niet correct.",
>     "status": 400,
>     "detail": "Bad request.",
>     "instance": "http://localhost:8080/v1/panden?bbox=134647,457842,137512,455907",
>     "code": "paramsValidation",
>     "invalidParams": [
>         {
>             "name": "bbox",
>             "code": "maximum",
>             "reason": "Waarde is hoger dan maximum 250000."
>         }
>     ]
> }
> ```
> 
> Mee eens? Of heb jij een beter voorstel?

Goed voorstel, Alleen de reason kan beter volgens mij. 250000 is namelijk niet de waarde van de bbox. "Oppervlakte van de bbox is groter dan 250000 m2" dekt de lading beter denk ik.
