### ISSUE TITLE
zoeken met oppervlakte min > max geeft geen fout

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#476]
Wanneer ik een oppervlakte[min} opgeef die groter is dan oppervlakte[max] krijg ik een lege collectie, geen foutmelding.

@MelvLee wat zou jij hier liever zien? Een lege collectie (zoals nu) of een foutmelding?

**Comment by strijm** [comment]
Besproken met @JohanBoer: min mag toch niet groter zijn dan max. 
Dan rest de vraag: welke foutmelding moeten we dan geven? Er is op dit moment geen foutmelding in de foutafhandeling feature die hier past.

**Comment by fsamwel** [comment]
@strijm 
> welke foutmelding moeten we dan geven?

Bijvoorbeeld:
```
{
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
    "title": "Een of meerdere parameters zijn niet correct.",
    "status": 400,
    "detail": "Bad request.",
    "instance": "...",
    "code": "paramsValidation",
    "invalidParams": [
        {
            "name": "oppervlakte[min]",
            "code": "range",
            "reason": "min mag niet hoger zijn dan max."
        }
    ]
}
```

@MelvLee mee eens? Of heb je een ander idee voor de fouttekst?

**Comment by strijm** [comment]
OK, dan implementeren we dat, ik heb de foutmelding toegevoegd aan de BAG foutmelding.feature, zie #493. @fsamwel en @MelvLee graag even reviewen
