### ISSUE TITLE
zoeken met oppervlakte < 0 geeft geen fout

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#477]
https://api.bag.acceptatie.kadaster.nl/esd/huidigebevragingen/v1/adresseerbareobjecten?bbox=135207,457400,135418,457162&oppervlakte[min]=-1&oppervlakte[max]=-1

dit geeft resultaten, geen fout. oppervlakte[min] is kleiner dan nu, en ook oppervlakte[max]<0, maar dat kan in de werkelijkheid niet

@MelvLee hoe zou jij dit het liefst zien? een oppervlak kleiner dan 0 accepteren (geeft bij min alles≥0, geeft bij max<1 lege collectie), of zou er een minimum moeten worden gespecificeerd?

**Comment by fsamwel** [comment]
@strijm voeg jij deze conditie toe in de specs, zodat het voor de gebruiker duidelijk is dat een negatief oppervlakte niet mag?

**Comment by fsamwel** [comment]
@strijm bij IntegerFilter is op min nog geen minimum: 0 toegevoegd. Het is dus nog toegestaan oppervlakte[min]=-1 te sturen

voer je de wijzigingen ook door in de code zodat er ook foutmeldingen komen op de beschreven condities?

**Comment by strijm** [comment]
> @strijm bij IntegerFilter is op min nog geen minimum: 0 toegevoegd. Het is dus nog toegestaan oppervlakte[min]=-1 te sturen

> voer je de wijzigingen ook door in de code zodat er ook foutmeldingen komen op de beschreven condities?

Doordat IntegerFilter voor meerdere query parameters wordt gebruikt en er voor iedere parameter andere min of max waarden kunnen gelden, kan er geen minimale of maximale waarde worden gespecificeerd in IntegerFilter. Dat zou wel kunnen als er voor iedere parameter een apart filter wordt gemaakt bv.: BouwjaarFilter en OppervlakteFilter. In de code worden de grenswaarde die nu bij de query parameters in de API specifiatie staan wel gecontroleerd. De release staat nu op de test omgeving!

**Comment by fsamwel** [comment]
> Doordat IntegerFilter voor meerdere query parameters wordt gebruikt en er voor iedere parameter andere min of max waarden kunnen gelden, kan er geen minimale of maximale waarde worden gespecificeerd in IntegerFilter. Dat zou wel kunnen als er voor iedere parameter een apart filter wordt gemaak

@strijm in https://github.com/VNG-Realisatie/Haal-Centraal-BAG-bevragen/issues/477#issuecomment-953984849 geef je zelf ook aan dat er een minimum moet zijn en een 400 fout moet komen.  Ook @MelvLee geeft aan dat dit een goed idee is. En in de implementatie werkt het wel zo dat er een minimum is gedefinieerd:
```
    "invalidParams": [
        {
            "name": "oppervlakte[min]",
            "code": "minimum",
            "reason": "Waarde is lager dan minimum 1."
        }
    ]
```

dus dan zou ik ook verwachten dat dit zo in de specificaties staat. vandaar dit issue. @strijm Pas jij dat aan in de specificaties?

**Comment by strijm** [comment]
@fsamwel De minimum en maximum waarden staan in de description van oppervlakte en bouwjaar. Is dat niet voldoende? Moet dit per se met een minimum en maximum keyword in de parameter definitie?

**Comment by fsamwel** [comment]
@strijm ik zou dat liever in de technische definitie hebben zodat een gebruiker niet aanvullende logica moet lezen in de descriptions en zelf moet implementeren. @MelvLee maakt het wat jou betreft uit?

**Comment by fsamwel** [comment]
bij oppervlakte[min] krijg ik nu een fout. bij oppervlakte[max] nog niet.
ook bij bouwjaar[min] en bouwjaar[max] is dit niet doorgevoerd

**Comment by fsamwel** [comment]
ik heb ook een pull request #505 ingediend om de minimum waarden aan de specificaties toe te voegen. Dan is het voor een gebruiker direct duidelijk dat deze beperking geldt.
