### ISSUE TITLE
zoeken met type standplaats of ligplaats in combinatie met oppervlakte geeft geen resultaten

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#478]
/adresseerbareobjecten?bbox=85960,443847,85973,443850&oppervlakte[min]=0&oppervlakte[max]=100000000&type=standplaats

in de opgegeven contour is er een standplaats. deze standplaats heeft geen oppervlakte (volgens imBAG)

nu wordt de standplaats niet teruggegeven

kan ik als gebruiker niet verwachten dat dit wel wordt teruggegeven (geen oppervlakte == 0 m2)?

@MelvLee hoe denk jij hierover?

**Comment by fsamwel** [comment]
@strijm 
1. kan je in de specificatie bij oppervlakte description toevoegen dat dit zoekt op het oppervlakte van verblijfsobjecten en je hiermee geen ligplaatsen of standplaatsen kan vinden
2. kan je zorgen dat bij de combinatie van oppervlakte met type=ligplaatsen of type=standplaatsen een foutmelding komt

**Comment by strijm** [comment]
We implementeren het zo, dat als oppervlakte wordt opgegeven i.c.m. ligplaats of standplaats, dat we een 400 fout met code unsupportedCombi geven.

**Comment by fsamwel** [comment]
@strijm de implementatie geeft nu:
```
{
    "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
    "title": "De combinatie van opgegeven parameters is niet toegestaan.",
    "status": 400,
    "detail": "Bad request.",
    "instance": "https://api.bag.acceptatie.kadaster.nl/esd/huidigebevragingen/v1/adresseerbareobjecten?bbox=85900,443800,85990,443890&type=standplaats&oppervlakte[max]=100",
    "code": "unsupportedCombi"
}
```

dit geeft helemaal geen informatie over welke combinatie niet is toegestaan. In detail of in invalidParams zou ik meer uitleg verwachten. Zeker omdat op zich de parameters in combinatie wel zijn toegestaan, alleen niet met de gebruikte waarde voor type.
Bijvoorbeeld in detail de tekst "Gebruik van parameter oppervlakte is niet toegestaan in combinatie met type standplaats."

**Comment by fsamwel** [comment]
@MelvLee de werking is nu als volgt:
1. als ik type=ligplaats opgeef in combinatie met oppervlakte krijg ik een foutmelding (zie opmerkingen hierboven van @strijm)
2. als ik geen type opgeef, wel bbox en oppervlakte[max] krijg ik alleen verblijfsobjecten, geen ligplaatsen of standplaatsen
3. als ik type=standplaats opgeef in combinatie met oppervlakte[max]= dan wordt er wel een standplaats gevonden, want de lege parameterwaarde (voor oppervlakte) wordt genegeerd

is dit nu duidelijke functionaliteit voor gebruikers (vanuit REST perspectief en vanuit hoe het in specs staat)

**Comment by strijm** [comment]
@fsamwel 
Volgens de HC common foutafhandeling.feature beschrijving komt er bij een 400 foutmelding met code 'unsupportedCombi' geen invalidParams voor in de response. 
Als we in detail meer informatie geven, waar geven we dan de naam van de 400 foutcode (Bad request) terug? Of wil je die niet ontvangen?
We voegen de tekst zoals hierboven aangegeven toe aan het detail veld.

**Comment by fsamwel** [comment]
@strijm wat mij betreft is de uitleg dat een 400 code Bad request betekent niet nodig. Een developer die een webAPI moet gebruiken weet dat toch hoop ik? Dus ik denk dat wat nu is ingevuld duidelijk is.
