### ISSUE TITLE
Als medewerker splitsingsvergunning wil ik weten of de adressen in de aanvraag overeenkomen met de adressen in de BAG

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#5]
Zodat ik kan controleren of deze adressen legaal tot stand zijn gekomen en kan voorkomen dat woningen gelegaliseerd worden (door de aanvraag buiten behandeling te stellen en te adviseren een omgevingsvergunning aan te vragen om de woningen te creëren die in de aanvraag staan)

**Comment by NicoleKortoomsBAG** [comment]
Gevraagde BAG-gegevens  
- vbo's in pand
- status pand? of vbo?
- oppervlakte vbo
- geconstateerd ja/nee van vbo en pand

**Comment by CathyDingemanse** [comment]
is gerealiseerd in V1.1
