### ISSUE TITLE
queryparameter nummeraanduidingIdentificatie en pandIdentificatie zijn bij het raadpleeg endpoint van addresseerbaar object opgenomen 

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#51]
moeten een eigen eindpoint krijgen
get/adresseerbareobjecten oid

**Comment by strijm** [comment]
Er is een endpoint waar met de padparameter ADO ID gezocht kan worden en er is een aparte endpoint opgenomen waar met de genoemde query parameters gezocht kan worden.

**Comment by fsamwel** [comment]
-query uit parameternamen moeten verwijderd worden. melvin maakt pull request

**Comment by fsamwel** [comment]
Ook gebruiken we voor query parameters alleen kleine letters. Dus "nummeraanduidingidentificatie" en "pandidentificatie"
Idem bij /panden (nummeraanduidingIdentificatie-query wordt "nummeraanduidingidentificatie", adresseerbaarObjectIdentificatie-query wordt "adresseerbaarobjectidentificatie"
