### ISSUE TITLE
Als PO moet ik uitvinden of mijn gebruikers weten hoe ze een adres samenstellen 

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#53]
...zodat ik kan beslissen of het adres ook als string beschikbaar moet worden gemaakt. 

Denk hierbij aan de volgorde van huisnummer, huisletter, huisnummertoevoeging oid...

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by CathyDingemanse** [comment]
Globale inventarisatie gedaan. Voorlopig geen adresstring opnemen. Als er op de API lab naar gevraagd wordt, kunnen we het altijd nog toevoegen. Tenzij afnemers hierbij een verzoek indienen om het wel te doen!

**Comment by strijm** [comment]
In update #58 bevat Adres geen adresstring.
