### ISSUE TITLE
Paginering fout na ophalen meer dan 10K resultaten

### ISSUE THREAD

**Issue by melvin-veenendaal** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#545]
Bij het gebruik van paginering bij het endpoint "/adressen" krijg ik een interne fout bij pagina's waarbij er verder wordt gezocht dan 10000 resultaten.

Voorbeeld request:
`curl -X GET "https://api.bag.kadaster.nl/esd/huidigebevragingen/v1/adressen?page=101&pageSize=100&exacteMatch=false&q=Amsterdam" -H  "accept: application/hal+json" -H  "X-Api-Key: SECRET"`

Voorbeeld response:
`{
  "status": 500,
  "title": "Interne server fout.",
  "type": "https://tools.ietf.org/html/rfc7231#section-6.6.1",
  "detail": "Internal server error.",
  "instance": "https://api.bag.kadaster.nl/esd/huidigebevragingen/v1/adressen?page=101&pageSize=100&exacteMatch=false&q=Amsterdam",
  "code": "serverError"
}`

Het gaat fout voor pagina’s waarbij er verder wordt gezocht dan 10000 resultaten, bijvoorbeeld pagina 101 met 100 resultaten per pagina, of pagina 201 met 50 resultaten per pagina. Alle pagina's hieronder werken wel goed.

De verwachting is dat alle pagina's binnen de paginering een resultaat teruggeven. Het gaat er niet om dat wij 10000 resultaten in 1 keer willen ophalen, maar dat alle pagina's binnen de paginering een resultaat teruggeven.

**Comment by NicoleKortoomsBAG** [comment]
Hallo Melvin,
Bedankt voor je reactie. De zoekfunctionaliteit maakt gebruik van een achterliggende service die maximaal 10.000 resultaten teruggeeft. Gezien het beoogde gebruik van deze API wordt dat niet gezien als een onoverkomenlijk probleem en staat een oplossing hiervoor op dit moment niet op de planning.
Nicole

**Comment by melvin-veenendaal** [comment]
Hoi Nicole, Wellicht goed om dit dan te documenteren. Nu is het zo dat de _page_ parameter geen max heeft en _pageSize_ een max van 100. Dit impliceerd dan dat alle resultaten van een een zoekopdracht binnen bereik zijn.
