### ISSUE TITLE
Als PO wil ik de embedded resources woonplaats, openbare ruimte en nummeraanduiding met eigen endpoints ontsluiten

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#55]
...zodat de API aan de REST architectuurstyle voldoet

De variant gegevensgroep van adres is afgevallen omdat alle gebruikers dan worden lastiggevallen met de meta-informatie (bronbestanden en besluitdatums etc) die voor slechts een enkeling (denk advocaten bezwaar) relevant is.  

**Acceptatiecriteria**
- [ ]
- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by strijm** [comment]
In update #58 zijn de genoemde endpoints toegevoegd.
