### ISSUE TITLE
Pas de pagina 'Getting Started' voor Huidige Bevragingen API 1.5 aan

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#556]
Ik heb een melding ontvangen dat op een van de GitHub Pages pagina's de link voor aanvraag API BAG bevragen niet naar een formulier gaat. De betreffende pagina bereik je via ‘https://vng-realisatie.github.io/Haal-Centraal-BAG-bevragen/’ en vervolgens door achtereenvolgens in de side navigatie op de bovenste ‘Getting Started’ en in de pagina op de tekst 'Vraag een API key voor de productieomgeving aan.' te klikken.

Op zich logisch dat je voor versie 1.5 geen API key meer aan kunt vragen, deze is immers deprecated en moet voor 1 juli a.s. vervangen worden door de Individuele Bevragingen. De term Getting Started onder ‘Haal Centraal BAG Huidige Bevragingen v. 1.5 (Deprecated)’ in de side navigatie is in die context wel vreemd. Ik kan me echter voorstellen dat daar nog wel informatie in staat die voor de huidige gebruikers op dit moment nog van belang kan zijn. Ik stel dan ook voor om de site als volgt aan te passen:

•	Wijzig het kopje in de side navigatie in ‘Functionaliteit en specificaties’;
•	Wijzig de titel van de pagina in ‘Functionaliteit en specificaties – BAG Huidige Bevragingen API’;
•	Verwijder alle tekst na de titel t/m het kopje ‘Functionaliteit en specificaties’ en vervang deze door een waarschuwing;
•	Verwijder de paragraaf ‘Implementeer de API client’;
•	Wijzig de titel ‘Probeer en test de API’ in ‘Test de API’, proberen is immers niet meer aan de orde;
•	Pas de tekst van de paragraaf ‘API key’ aan.

Zie [hier](https://melsk-r.github.io/Haal-Centraal-BAG-bevragen/getting-started) voor een voorbeeld van dat wat ik voorstel. Ik hoor graag of jullie je hierin kunnen vinden en welke aanpassingen jullie evt. graag op mijn voorstel zouden aanbrengen.

**Comment by JohanBoer** [comment]
Zie net de waarschuwing die er op het voorbeeld op jouw repo staat. Lijkt mij uitstekend.

**Comment by brienen** [comment]
Ik ben het ook eens met de voorgestelde wijziging. Wat mij betreft doorvoeren!

**Comment by melsk-r** [comment]
Aanpassingen zijn doorgevoerd.
