### ISSUE TITLE
Ontbrekende CRS specificaties in common.yaml

### ISSUE THREAD

**Issue by strijm** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#59]
# Impediment
In de VNG-Realisatie common.yaml mis ik de headers voor content-crs en accept-crs en de 405 en 412 HTTP status codes.

[beschrijf de belemmering of het risico]
Hierdoor kunnen niet alle headers en foutcodes in de HC BAG bevragen API vervangen worden door HC versies en blijven er een paar BAG verwijzingen over. Dit levert inconsistentie op.

[assign aan ..., voeg label 'impediment' toe, kies bij 'projects' voor "organisatie en impediments"]

**Comment by strijm** [comment]
HTTP status code 422 staat in de default lijst van status codes voor API's in de NL API strategie. Deze staat nog niet in de common.yaml.

**Comment by fsamwel** [comment]
> HTTP status code 422 staat in de default lijst van status codes voor API's in de NL API strategie. Deze staat nog niet in de common.yaml.

Hebben we dan al ergens een API waarin deze statuscode relevant is? De Haal Centraal API's kennen nu vrijwel uitsluitend GET requests (met een enkele POST voor zoeken met request body). 

Ik kan me zo geen situatie bedenken daarvoor waarbij een request alle validaties voor de http status code 400 doorstaat (dus alle parameters voldoen aan OAS schema specificaties), en er alsnog geen antwoord kan worden gegeven door een fout in de aanroep(parameters).

**Comment by fsamwel** [comment]
405 zie ik niet hoe we dit moeten opnemen. Dit gaat over method not allowed. Die kunnen we niet opnemen bij de responses op de methods die we definiëren, want die worden juist wel ondersteund. Dat betekent denk ik niet dat er geen 405 fout mag worden gegeven door de API, op dezelfde manier als bijvoorbeeld een 404 gegeven kan worden bij een onjuiste url.

412 is m.i. niet relevant voor GET requests, maar juist voor bijvoorbeeld een PUT request voor het aanpassen van een resource. Dat doen we niet in Haal Centraal. In welke situaties zou de BAG API een 412 kunnen geven?

**Comment by lennartvanbergen-kadaster** [comment]
**Uit de API strategie (van DSO, die wel in het Nederlands schrijft en wat meer toelichting geeft)**  

Conclusie is denk ik, geprojecteerd op BAG: 

Als je zelf geometrie opstuurt (een POST met een geometrie erin), geef dan de content-CRS mee. Dit mag zijn RD of ETRS89. Als maar 1 hiervan door gemeentes wordt opgestuurd, dan ondersteunt de LVBAG ten minste deze. 

Als je geometrie verwacht in ETR89 of RD, geef dan de accept-CRS mee. Als maar 1 hiervan door gemeentes wordt opgestuurd, dan ondersteunt de LVBAG ten minste deze._ 

--

**CRS-negotiation**
Het default coordinaatreferentiesysteem (CRS) van GeoJSON is WGS84. Dit is het globale coördinatenstelsel dat vanwege de verschuiving van de tektonische platen minder nauwkeurig is dan lokale coördinatenstelsels zoals ETRS89 (EPSG:4258, Europees) of RD New13 (EPSG:28992, Nederlands). Omdat de meeste client-bibliotheken met WGS84 werken, schrijft de W3C/OGC-werkgroep “Spatial Data on the Web” voor om dit standaard te ontsluiten. Dit kan direct op een kaart geplot worden zonder moeilijke transformaties. De API-strategie voorziet hierin door naast ETRS89 en RD New ook Pseudo-Mercator op basis van WGS84 te ondersteunen. De hierbij te gebruiken projectiemethode is EPSG:3856 op basis van WGS84.

API-G06 Het voorkeur-coordinaatreferentiesysteem (CRS) is ETRS89, maar het CRS wordt niet impliciet geselecteerd

_(Lennart: dit is voor DSO, maar volgens mij voor basisregistraties in het algemeen, vanwege Europese richtlijnen)_

Algemeen gebruik van het Europese ETRS89 coördinatenstelsel (CRS) heeft sterk de voorkeur, maar dit wordt **niet door API’s afgedwongen als de “default”**. Derhalve moet het te gebruiken CRS in elke aanroep expliciet worden opgegeven. Het is mogelijk om het CRS voor vraag en antwoord via headers afzonderlijk te specificeren. Hierin zijn vervolgens drie opties (met voorgeschreven projecties) voorhanden: RD New, ETRS89 en WGS84.

**API-G07 Het coordinaatreferentiesysteem (CRS) van de vraag en het antwoord wordt in de header meegestuurd**

**Het gekozen coördinatenstelsel (CRS) voor zowel de vraag als het antwoord worden meegestuurd als onderdeel van de request-header en de response-header. Bij het ontbreken van deze headers wordt 412 Precondition Failed teruggegeven. Hiermee wordt voorkomen dat per abuis met het verkeerde CRS wordt gewerkt.**

13 RD New is een geprojecteerd CRS dat voor het laatst is herzien op 26 oktober 2019. Het is geschikt voor gebruik in Nederland, op land inclusief de Waddenzee, de Waddeneilanden en 12 mijl uit de kust. RD New vervangt EPSG28991 (RD Oud).
Concept | API-strategie | 2.0 pagina 47 van 85
Deelprogramma DSO

De hier genoemde headers zijn puur bedoeld voor de onderhandeling tussen de client en de server. Afhankelijk van de toepassing zal naast de geometrieën ook specifieke metadata-onderdeel vormen van het antwoord, bijvoorbeeld de oorspronkelijke realisatie inclusief, de inwindatum, etc.
Vraag en antwoord kunnen op een ander coördinatensysteem zijn gebaseerd. Hiervoor wordt het HTTP-mechanisme voor content negotiation gebruikt. 

**Het CRS van de geometrie in de vraag (request body) wordt aangeduid met de header Content-Crs.**
HTTP-header Waarde Toelichting
Content-Crs
EPSG:4258
ETRS89, Europees
Content-Crs
EPSG:28992
RD New, Nederlands
Content-Crs
EPSG:3856
WGS84/Pseudo-Mercator, Wereld (een geprojecteerd CRS)
Tabel 8 - Definities Content-Crs

**Het gewenste CRS voor de geometrie in het antwoord (response body) wordt aangeduid met de header Accept-Crs.**
HTTP-header Waarde Toelichting
Accept-Crs
EPSG:4258
ETRS89, Europees
Accept-Crs
EPSG:28992
RD New, Nederlands
Accept-Crs
EPSG:3856
WGS84/Pseudo-Mercator, Wereld (een geprojecteerd CRS)
Tabel 9 - Definities Accept-Crs

**Comment by lennartvanbergen-kadaster** [comment]
Kortom, in eenvoudige taal: 

GET - normaal scenario 
Client: doet een GET (zonder geometrie) 
en stuurt hierbij accept-crs mee, als ze in response RD willen ontvangen

Provider: 
stuurt in de response de content-crs mee om aan te geven in welke crs de geometrie in de reponse is 

Client 
doet een POST met een geometrie 
en stuurt content-crs mee om aan te geven in welk crs de geometrie in de post zit 

en stuurt hierbij accept-crs mee, als ze in response RD willen ontvangen

Provider 
stuurt in de response de content-crs mee om aan te geven in welke crs de geometrie in de reponse is 

Als client bij een POST geen accept-crs heeft meegegeven: 412 
Als client een accept-crs aangeeft: 406 + een lijstje van welke accept-crs wel ondersteund worden.

**Comment by lennartvanbergen-kadaster** [comment]
We gaan voorlopig nog geen WGS84 en ETR89 ondersteunen. Dus dat deel kan nog even weggelaten worden uit de implementatie. 

Maar om de API ook later geschikt te kunnen maken voor WGS84 en/of ETR89 en dan geen breaking changes te krijgen (en aan de API strategie te voldoen), mag de default alleen zijn: WGS84.

**Comment by JohanBoer** [comment]
Melvin werkt een voorbeeld uit om de discussie goed te voeren.

**Comment by MelvLee** [comment]
Als test heb ik de volgende response header gedefinieerd
```
            contentCrs:
              schema:
                type: string
                default: epsg:4258
                enum:
                - epsg:4258
                - epsg:28992
```
in de response definitie van een path en vervolgens client code gegenereerd met NSwag en SwaggerHub.

De gegenereerde code bevat geen contentCrs enum type. Verdere analyse van de gegenereerde code zie ik dat de headers in een response als string in een dictionary worden gestopt en samen met de gedeserialiseerd body worden geretourneerd.

Het definieren van contentCrs als een enum en uitbreiden in een latere versie van de spec heeft hierdoor geen nadelige impact op code gegenereerd met een oudere versie van de spec omdat de contentCrs niet wordt gedeserialiseerd naar een enum type.

**Comment by lennartvanbergen-kadaster** [comment]
Top!

Komt goed uit. @strijm Java same thing?

**Comment by strijm** [comment]
In Java code worden ook geen enumeraties gegenereerd, maar komen de toegestane waarden in annotaties in de methode definitie te staan.
