### ISSUE TITLE
Discussie voeren over: NummeraanduidingIdentificatie hernoemen naar AdresIdentificatie

### ISSUE THREAD

**Issue by strijm** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#60]
# Impediment
Waarom NummeraanduidingIdentificatie ernoemen naar AdresIdentificatie? Een adres heeft geen identificatie afgezien van een nummeraanduiding.

[assign aan ..., voeg label 'impediment' toe, kies bij 'projects' voor "organisatie en impediments"]

**Comment by fsamwel** [comment]
Er zijn voor- en nadelen aan beide opties:
- Gebruik van nummeraanduiding als identificatie van het adres heeft als voordeel dat gebruikers deze vaak hebben en dit begrip kennen. Bijvoorbeeld BRP, HR én BRK slaan nummeraanduiding identificaties op. Voor gebruikers die vanuit deze registraties een adres willen ophalen weten dan direct wat ze als sleutel erin moeten stoppen.

- Nadeel is dat hiermee de resource adres gekoppeld wordt aan de implementatie waarbij nummeraanduiding de identificatie is. 

- Nadeel van een eigen identificatie (bijv. "identificatie" of "adresIdentificatie") is dat gebruikers die een adres willen ophalen op nummeraanduiding hiervoor de collectie moeten gebruiken (bijv. /adressen?nummeraanduidingidentificatie=0518021234567890) i.p.v. direct ophalen van het specifieke adres.

**Comment by JohanBoer** [comment]
Aan de resource adres wordt de property "identificatie" toegevoegd.

**Comment by JohanBoer** [comment]
Aan de resource nummeraanduiding moet ook de adresidentificatie worden toegevoegd. Er staat in de nummeraanduiding_links een link naar adressen en je moet niet willen dat een consumer (bij templated links) maar net de kennis moet hebben dat hij daarvoor de nummeraanduidingidentificatie moet gebruiken. 
Voor de provider geldt dat de inhoud van de adresidentificatie dan gelijk is aan de inhoud van de nummeraanduidingidentificatie

**Comment by fsamwel** [comment]
@JohanBoer in het adresseerbaar object heet de identificatie nog 'adresseerbaarObjectIdentificatie'. Kan je die ook hernoemen naar 'identificatie'?
