### ISSUE TITLE
referenties werken niet

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#69]
# Impediment

op een aantal plekken in de OAS zitten referenties die niet werken. Er mogen geen relatieve referenties gebruikt worden.

Bijvoorbeeld 
 $ref: '../../../../extern/haal-centraal/common-schemas.yaml#/HalCollectionLinks'
 $ref: '../../../../extern/haal-centraal/common-schemas.yaml#/HalLink'
 $ref: '../../../../lvbag/imbag/v20180601/datatypes.yaml#/StatusPlaats'
 $ref: '../../../../geometrie/geometrie.yaml#/components/schemas/Surface'
 $ref: '../../../../lvbag/imbag/v20180601/verblijfsobject.yaml#/StatusVerblijfsobject'

**Comment by fsamwel** [comment]
@strijm Hallo Mark, zou je dit kunnen oplossen? We kunnen nu vrij weinig met de BAG specs.

**Comment by strijm** [comment]
Zoals vorige week besproken, heb ik de geresolvede yaml specificatie ingecheckt. Deze kan gebruikt worden als input voor code generatie.

**Comment by strijm** [comment]
Alle (niet geresolvede) dependencies zijn ook ingecheckt. Volgens mij kan dit issue gesloten worden.

**Comment by strijm** [comment]
Volgens mij is dit punt opgelost in issue #83. Graag review.

**Comment by JohanBoer** [comment]
Inmiddels hebben we afgesproken absolute links te te passen.
