### ISSUE TITLE
Waarom <object>HalCollectie types?

### ISSUE THREAD

**Issue by strijm** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#72]
# Impediment
In de yaml specifcatie is nu het volgende opgenomen voor o.a. collecties van Pand objecten:

    PandHalCollectie:
      type: object
      properties:
        _links:
          $ref: '../../../../extern/haal-centraal/common-schemas.yaml#/HalCollectionLinks'
        _embedded:
          type: object
          properties:
            Panden:
              type: array
              items:
                $ref: '#/components/schemas/PandHal'

    PandHal:
      allOf:
        - $ref: '#/components/schemas/PandInOnderzoek'
        - properties:
            _links:
              $ref: '#/components/schemas/Pand_links'
            _embedded:
              $ref: '#/components/schemas/Pand_embedded'

Het PandHal type bevat informatie m.b.t. een Pand, de onderzoek info m.b.t. het Pand, de links en embedded resources. Waarom is er dan een apart type HalCollectie nodig? Wat moet er worden ingevuld in de links in de HalCollectie? Waarom moet er een object worden gemaakt van de PandHal array? Dit laatste is niet per se nodig, want als een bevraging resulteert in een collectie (of array) van panden, dan kan er in de response een array van PandHal worden geretourneerd.
 
Een vergelijkbaar probleem speelt bij adreseerbare objecten.

[assign aan ..., voeg label 'impediment' toe, kies bij 'projects' voor "organisatie en impediments"]

**Comment by fsamwel** [comment]
We scheiden de definitie van eigenschappen en HAL-elementen. Hierdoor blijft het in de toekomst mogelijk om naast de HAL+json ook andere mediatypes te ondersteunen, zonder alle eigenschappen opnieuw te moeten definiëren en zonder breaking change op de API.

Daarnaast verwijst de ...Collectie in de items naar het object dat ook gebruikt wordt voor de hele resource.

Dus stel dat we een resource Ding hebben met endpoints /dingen en /dingen/{identificatie}, dan maken we de volgende componenten:
- Ding
- DingHal: Ding + _links + _embedded)
- DingHalCollectie: _links (halcollectionlinks) + _embeded (property dingen: array van DingHal)

Mochten we in de toekomst ook de mogelijkheid willen bieden om bijv. ION formaat te bieden, kunnen we Ding hergebruiken en voegen we bijvoorbeeld DingIon en DingIonCollectie toe aan de specs.

**Comment by strijm** [comment]
Volgens mij is dit issue opgelost in #83. Graag review.

**Comment by strijm** [comment]
Volgens mij kan dit issue gesloten worden.
