### ISSUE TITLE
required en minItems verwijderen uit definitie response

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#73]
In componenten die de response specificeren moeten geen properties verplicht zijn, Ook wanneer in de registratie het gegeven een waarde heeft, kan de gebruiker hier niet om gevraagd hebben door gebruik van de fields parameter.

Uitzondering is wanneer een property altijd verplicht meegeleverd moet worden.

Naast required op attributen moet op arrays ook de minItems worden verwijderd. Want ook die zorgt voor het verplicht voorkomen van een gegeven waar met fields niet om gevraagd is.

**Comment by lennartvanbergen-kadaster** [comment]
Voorstel: Fields en required. 

Als een property **altijd** wordt geleverd, dan aangeven dat deze required is. Dat geeft nuttige informatie aan de gebruiker. 

Zo leveren we altijd de identificatie en soms ook altijd bepaalde verplichte velden, zoals huisnummer, ook als daar niet om gevraagd wordt met Fields.

**Comment by lennartvanbergen-kadaster** [comment]
Wat betreft minItems. De property moet toch optioneel zijn? Als dat zo is, dan is minItems op 0 niet meer nodig. Als de property gevuld is, is er immers altijd sprake van 1 item. Dat hoort ook zo te zijn, want het is niet wenselijk om de property wel op te nemen en vervolgens een lege array. Dit is een standaard conventie bij interface specificaties.

**Comment by lvbag** [comment]
Voor fields, in principe wordt alles optioneel. Dat bij een vraag naar huisnummer altijd de huisletter en huisnummertoevoeging wordt geleverd (indien aanwezig) is een feature. Moet goed beschreven worden om te voorkomen dat de applicatie van de afnemer deze gegevens negeert.

**Comment by strijm** [comment]
De yaml specificatie is hierop aangepast in issue #83. De feature beschrijving moet nog worden geschreven. Graag review van de yaml specificatie.
