### ISSUE TITLE
Verschillende opmerkingen

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#74]
/adressen: parameter keuzeItemIdentificatie --> betreffende identificatie staat in "zoekResultaten", dus is parameternaam "zoekresultaatidentificatie" denk ik duidelijker

KeuzeItemCollectieHal heeft de link naar adres opgenomen per zoekresultaat. Wanneer een (lange) lijst met resultaten wordt teruggegeven, nemen we de link templated op. Dus moet deze worden opgenomen op niveau van de collectie.

Documentdatum example: dubbele quotes om voorbeeldwaarde. Wordt nu gezien door Swagger als OrderedMap.

VerkorteNaamOpenbareRuimte.verkorteNaam heeft nu pattern. Deze is overbodig, pattern is alleen relevant voor informatie die door de gebruiker kan worden opgegeven in een request.

Nummeraanduiding.status waarde "Naamgeving ingetrokken" leveren we niet (we leveren immers alleen actuele objecten), dus is er maar één waarde mogelijk. Dus kan property NummeraanduidingInOnderzoek.status verwijderd worden.
Speelt ook bij andere resources, bijvoorbeeld Woonplaats, Standplaats, OpenbareRuimte.

OpenbareRuimte.verkorteNaam is object (VerkorteNaamOpenbareRuimte) met property verkorteNaam, graag direct string maken

OpenbareRuimte.verkorteNaam en OpenbareRuimte.naam. Graag beide voorbeelden op elkaar laten aansluiten, zodat het verschil tussen beide duidelijk is.

**Comment by strijm** [comment]
Een aantal van deze opmerkingen zijn verwerkt in #83.

1. keuzeItem is overal hernoemd naar zoekResultaat
2. zoekResultaatHalCollectie is opgebouwd conform feature beschrijving.
3. enkele of dubbele quotes maakt volgens de yaml specificatie niets uit behalve bij het escapen van bepaalde karakters. Dat is hier niet van toepassing. Wel zijn enkele quotes toegevoegd.
4. pattern bij verkorte naam is verwijderd.
5. geneste verkortenaam is opgelost.
6. voorbeelden van verkorte naam en naam van openbare ruimte zijn op elkaar afgestemd.

Graag review.
