### ISSUE TITLE
inhoud van de resource op hoogste niveau van de resource opnemen

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#76]
de verschillende eigenschappen van een resource horen op het hoogste niveau in de resource, zonder envelop. Dit maakt de resource duidelijker en eenvoudiger te gebruiken, omdat:

- parameters moeten hetzelfde heten als de corresponderende properties van de resource. De parameternamen zijn korter en duidelijker wanneer betreffende property niet dieper in de structuur van het bericht zit

-  met de fieldsparameter kunnen properties in de structuur van het bericht worden gedefinieerd. Bijvoorbeeld om alleen de postcode en huisnummer van een nummeraanduiding te vragen, wil je volstaan met fields=postcode,huisnummer, in plaats van fields=nummeraanduiding.postcode,nummeraanduiding.huisnummer te moeten gebruiken

- paden voor de mapping naar gegevens in het antwoord niet onnodig langer zijn

Zie ook landelijke API strategie [API-28](https://geonovum.github.io/KP-APIs/API-strategie-extensies/#api-28-send-a-json-response-without-enclosing-envelope)

zie ook #50 (plaats van inOnderzoek) en #41 (modelleren adresseerbaarobject als één resource)

**Comment by strijm** [comment]
Volgens mij is dit punt opgelost in issue #83. Graag een review hiervan.
