### ISSUE TITLE
genereerbare enumeratiewaardes

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#77]
Er zijn nu enumeratiewaardes gedefinieerd met andere dan alfanumerieke tekens. Bijvoorbeeld verblijfsobject.status "Verblijfsobject in gebruik (niet ingemeten)".

Volgens mij geeft dit problemen of onwenselijke situaties bij code genereren. Zie https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/issues/330

**Comment by fsamwel** [comment]
Donderdag werd aangegeven dat het Kadaster moeite heeft met het sturen van codes voor de waarden, het gaat om het sturen van de correcte waarden, zoals die gedefinieerd zijn.

@MelvLee kan jij uitzoeken hoe groot de consequenties zijn bij de verschillende code generatoren? Ik begreep donderdag dat in de code die door het Kadasterteam was gegenereerd de niet-alfanumerieke tekens worden omgezet naar underscore. Dus "Verblijfsobject in gebruik (niet ingemeten)" wordt "Verblijfsobject_in_gebruik_niet_ingemeten_". Dat lijkt me niet heel erg (hoogstens een beetje lang).

Ik kan me herinneren dat er destijds voor BRP is besloten dat alleen kleine letters mogen worden opgenomen in enumeraties (geen hoofdletters), ook omdat dit issues zou geven bij code genereren. Ik kan dat alleen niet meer vinden in een issue. Is dat ook een eis?

@joeribekker jij hebt destijds input geleverd op [dit issue](VNG-Realisatie/Haal-Centraal-BRP-bevragen#330) over genereerbare enumeraties. Zou je er bij implementeren van een consumer op de BAG API last van hebben dat bij enumeraties dit soort omschrijvingen worden gestuurd? (overigens zijn de meeste omschrijvingen korter, meestal tot drie woorden, met A-Za-z en spaties)

**Comment by JohanBoer** [comment]
De volgende decisions uit de BRP zijn hier relevant. (Uit https://github.com/VNG-Realisatie/Haal-Centraal-BRP-bevragen/blob/master/docs/design_decisions.md )

**Enumeraties worden in het bericht opgenomen als waarde.**
In de API specificaties worden enumeratiewaarden opgenomen met de waarde, in de description wordt de bijbehorende code genoemd.

Ratio Uitgangspunt binnen Common Ground is gebruik van gegevens, niet opslag van gegevens. Dus de omschrijving (uitgeschreven waarde) is relevant voor de gebruiker. Waar waarde van de enumeratie te lang is wordt deze op een begrijpelijke wijze ingekort.

**Enumeraties-waarden bevatten geen hoofdletters.**
Enumeratiewaarden bevatten alleen kleine letters en underscores. Geen spaties, geen speciale tekenen en geen hoofletters.

Ratio In sommige development-omgevingen leveren hoofletters, spaties of speciale tekens in enumeratie-waarden een probleem op met code-genereren.

**Comment by JohanBoer** [comment]
De volgende is ook relevant (relevanter dan de eerste uit mijn vorige commentaar) 

**Dynamische domeinwaarden worden in de response opgenomen met zowel de code als de omschrijving**
Voor een element van een referentielijst-type, wordt in de response zowel de code als de omschrijving opgenomen. Dit betreft dynamische lijsten (tabellen) met een code en waarde, zoals "Tabel 32 Nationaliteitentabel" en "Tabel 36 Voorvoegselstabel".

Ratio Garanderen dat verschillende systemen binnen en buiten de gemeente dezelfde (toestand) van de referentielijst kennen is duur, ingewikkeld en foutgevoelig.

Kanttekening Als landelijk beheerde dynamische domeinwaarden ook daadwerkelijk landelijk beschikbaar gesteld worden (zoals de common groud gedachte wel beoogd) dan worden deze als resource ontsloten en dus als link (uri) opgenomen.

**Comment by MelvLee** [comment]
spaties, (, ) worden _ in nSwagStudio (v.b. heeft als hoofdadres =>Heeft_als_hoofdadres, Verblijfsobject in gebruik (niet ingemeten) => Verblijfsobject_in_gebruik__niet_ingemeten_)

.NET generator in Swagger Editor verwijdert alle niet-alfanumerieke karakters en gebruikt pascalcase voor de enums en elke enum waarde wordt gepost-fix met Enum (v.b. heeft als hoofdadres =>HeeftAlsHoofdadresEnum, Verblijfsobject in gebruik (niet ingemeten) => VerblijfsobjectInGebruikNietIngemetenEnum)

Nu ik weer kijk naar de design decision om alleen kleine letters en underscores te gebruiken, vraag ik mij af of het niet beter is om dash (-) te gebruiken ipv underscore omdat enums ook als parameter kan worden gebruikt

**Comment by joeribekker** [comment]
Ik blijf bij mijn advies om voor enums alleen (`regex: A-Za-z_`) te gebruiken (dus hoofdletters, kleine letters en underscores). Dit zorgt voor leesbare waarden die vrijwel nooit problemen veroorzaken. 

Vreemde tekens (&+"*:, etc.) waaronder spaties en haakjes worden in code omgezet naar iets anders en zijn onderhevig aan allerlei "[escape](https://en.m.wikipedia.org/wiki/Escape_character)" operaties (url, html formatting) in code, uitwisseling en presentatie. Een `"` wordt `\"` of `_` of `%30` of iets...

Het kan allemaal wel (technisch zijn er allemaal oplossingen voor) maar het zorgt vaak voor onnodige frustratie en problemen.

> Ik kan me herinneren dat er destijds voor BRP is besloten dat alleen kleine letters mogen worden opgenomen in enumeraties (geen hoofdletters), ook omdat dit issues zou geven bij code genereren. Ik kan dat alleen niet meer vinden in een issue. Is dat ook een eis?

Dit staat mij niet bij en ik zou ook niet weten waarom. Het kan netter overkomen maar dat is slechts visueel en in ieders ogen weer anders.

**Comment by strijm** [comment]
Zoals aangegeven tijdens de design sessies, kunnen we de enumeratie waarden niet zomaar veranderen omdat deze zijn voorgeschreven in de BAG Catalogus 2018. Wel zijn er single quotes om de enumeratie waarden gezet. Volgens de yaml specificatie op yaml.org 7.3.2 hoeven speciale karakters niet ge-escaped te worden. Dat dit vreemde namen van constanten in de code oplevert is weliswaar vervelend, maar het is ook niet goed om dat 'probleem' op te lossen door voorgeschreven enumeratie waarden te veranderen, die juist zijn bedoeld om te standaardiseren.

**Comment by strijm** [comment]
Dit issue is volgens mij opgelost in #83. Graag review.

**Comment by joeribekker** [comment]
Beetje kort door de bocht dat dit issue is opgelost, aangezien het issue zelf gaat om "genereerbare waarden in code". Quotes zullen wel helpen in de Open API-spec maar dat staat los van dit issue.

Een beslissing om geen rekening te houden met genereerbare code, het niet als probleem te zien, of het is simpelweg niet mogelijk om het aan te passen, is uiteraard wel een beslissing die reden kan geven om het ticket te sluiten.

**Comment by strijm** [comment]
Het ticket staat in review. Tijdens een review kan er inspectie van de yaml specificatie plaatsvinden, kan er code uit de specificatie worden gegenereerd om te controleren of de specificatie naar code omgezet kan worden en kunnen er evt. testen worden uitgevoerd. Bij de LV BAG hebben we uit de specificatie (server side) code kunnen genereren. Daarnaast hebben we de geresolvede yaml in swagger editor bekeken. Dit ziet er allemaal goed uit. Daarom zin wij van mening dat dit issue is opgelost en hebben het in review gezet. Wij realiseren ons dat er ook client side code uit gegenereerd moet kunnen worden, daarbij zijn wij afhankelijk van anderen, vandaar de review. Verder hebben we in onze testomgeving een release staan, waar deze wijziging in zit. Hier kun je testen of de enumeratie waarden juist overkomen aan de client kant. Mocht er geen code uit de geresolvede yaml specificatie gegenereerd kunnen worden of als de enumeratie waarden niet juist overkomen vanuit onze test omgeving, dan horen we dat natuurlijk graag.

**Comment by lennartvanbergen-kadaster** [comment]
Eens met Mark. 

Code moet ook om kunnen gaan met dergelijke karakters. Die zitten ook in gewone string. 

Wat ik niet volg is waarom de code en code generator dit niet ziet als een String, of als een Enum constante die onderliggend een string is.

Zit er iets scheef in yaml/JSON schema, of alleen in deze API? 

Verder zou ik het wel een good practise vinden om bij een waarde alleen a-z en A-Z en 0-9 en - karakters te gebruiken. En lastige tekens te ontwijken. Ik ben zeer welwillend om daar verzoeken richting waardelijst beheerders te willen doen. 

Maar we kunnen niet in 1 API enums gaan lopen veranderen en in de rest vsn de keten niet. Dat gaat te veel te koste van consistentie in de keten. Dan zou dat in de bron zelf horen te worden verbetert, bij de gemeentes zelf dus al. 

Dus als het alleen maar vervelend maar wel werkbaar is: eens dat het vervelend is. Maar het is wel werkbaar. Inconsistenties in de keten zijn mijn inziens vervelender.

**Comment by lennartvanbergen-kadaster** [comment]
Overigens lijkt het een te overwegen optie om de Enum te vervangen door een waardelijst en een waardelijst API. Dan zit in de yaml alleen: 
code: string
waarde: string 

Zou dat helpen?

**Comment by fsamwel** [comment]
> Code moet ook om kunnen gaan met dergelijke karakters. Die zitten ook in gewone string.

Ik geloof niet dat wij veel invloed hebben over hoe Java, C#, Python, enz. werken. Onze API specificaties moeten zo worden opgesteld dat gebruikers van de API, de developers van API client applicaties, deze makkelijk, snel (goedkoop), foutloos kunnen gebruiken. Ik ben het dus helemaal eens met @joeribekker dat we wel degelijk rekening moeten houden met genereerbare enumeratiewaardes.

We hebben nu vastgesteld dat er in de enumeraties voor de BAG API geen waarden zitten die problemen geven. Er zitten alleen letters en spaties in. Bij code genereren worden de spaties automatisch omgezet naar underscores. Dus was de conclusie dat er nu geen probleem is.

Het heeft op deze plek denk ik niet zoveel zin te discussiëren over de what if met niet-genereerbare enumeratiewaardes. Daarvoor is de API strategie een mooie plek. Daar zijn bijvoorbeeld ook ontwerp regels over naamgeving van urls, parameters en properties (https://github.com/Geonovum/KP-APIs/issues/205#issuecomment-621784037).  Daar zou je prima regels voor enumeratiewaardes kunnen toevoegen.

**Comment by lennartvanbergen-kadaster** [comment]
@Frank. Ik zei niet dat we er geen rekening moeten houden. Ik gaf aan dat als het werkbaar is, we dan die Enum's niet aan kunnen passen. Eenvoudig is een goed streven, maar geen harde eis. Als LV mogen wij geen data veranderen dus we kunnen die Enum's volgens mij niet aanpassen. 

Ik snap de zin: "we" hebben nu vastgesteld daarom niet. Wie bedoel je met we? Ik geef dit aan zodat we het erover kunnen hebben. Als we niet direct tot dezelfde conclusie komen, laten we het hier dan in de volgende ontwerpsessie over hebben. Ok?

**Comment by fsamwel** [comment]
> Ik snap de zin: "we" hebben nu vastgesteld daarom niet. Wie bedoel je met we?
In het API ontwerpteam hebben we de specificaties doorgenomen en gekeken of er ergens enumeratiewaarden waren die echt problemen geven. Onder andere door de specificaties door code generatoren te halen en het resultaat te beoordelen. We hebben daarbij geen problemen gevonden. Dus is er m.i. nu geen probleem. Dus kunnen we nu de enumeratiewaardes gebruiken zoals die in de LV zitten. Dus ik vermoed dat we juist wel tot dezelfde conclusie zijn gekomen. Tenzij je natuurlijk graag enumeratiewaarden wilt die afwijken van wat in het LV zit, dan kunnen we daarover praten ;)

**Comment by lennartvanbergen-kadaster** [comment]
Check, mooi. Bedankt voor snelle reactie. Fijn weekend :-)

**Comment by strijm** [comment]
Volgens mij kan dit issue worden gesloten.
