### ISSUE TITLE
API key definiëren bij endpoints

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#78]
Als ik het goed begrijp gaan we straks ook in productie toegang tot de BAG API regelen via een API-key.

Is het dan niet heel handig wanneer deze als request header wordt gedefinieerd?

**Comment by strijm** [comment]
Het volgende is opgenomen in de specificatie:
`components:

  securitySchemes:

    apiKeyBAG:
      type: apiKey
      name: X-Api-Key
      in: header
      description: >
        De API-key die je hebt gekregen dient bij elke request naar deze
        via de `X-Api-Key` request header meegestuurd te worden. Indien deze
        niet juist wordt meegestuurd, of het een ongeldige key betreft, zul je
        de foutmelding `403 Forbidden` terugkrijgen.
` 
Dit wordt in iedere endpoint gebruikt zoals in onderstaande voorbeeld:
`  /adressen/zoek:
    get:
      security:
        - apiKeyBAG: []
      operationId: zoek
      tags:
        - Adres
      summary: Zoek adressen met verschillende parameters.
      description: Zoeken van adressen via free query op postcode, woonplaats, straatnaam, huisnummer, huisletter, huisnummertoevoeging
      parameters:
        - $ref: '#/components/parameters/zoek'
`
Kortom, de API key is al gedefinieerd als een header.

**Comment by fsamwel** [comment]
sorry, niet gezien. Had de yaml geïmporteerd, maar mijn tool doet blijkbaar niks hiermee...
