### ISSUE TITLE
Geen eenduidige afspraken gebruikte parameters

### ISSUE THREAD

**Issue by NicoleKortoomsBAG** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#82]
In de yaml of andere informatie zijn de namen van de gebruikte parameters niet afgestemd. Hierdoor ontstaan verschillen in de verschillende endpoints.

**Comment by JohanBoer** [comment]
Check de consistentie in de naamgeving van de parameters.

**Comment by JohanBoer** [comment]
Dit issue is in #137 opgelost
