### ISSUE TITLE
BAG API vereist nu Accept: application/hal+json

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#85]
Wanneer ik naar de API Accept: application/json stuur, dan krijg ik een foutmelding:
{
   "detail": "Not Acceptable. Je hebt waarschijnlijk een gewenst formaat met de `Accept` header verstuurd welke niet ondersteund wordt.",
   "status": 406,
   "title": "Not Acceptable",
   "type": "https://tools.ietf.org/html/rfc7231#section-6.5.6",
   "instance": "https://api.test.kadaster.nl/vhc/adressen/0163200000554956"
}

Wanneer ik geen accept header stuur, of wanneer ik Accept: application/hal+json stuur, krijg ik wel gewoon antwoord.

Dit lijkt me niet terecht en niet zo vriendelijk naar de gebruiker. application/hal+json is nog steeds json, dus Accept: application/json zou gewoon het hal+json antwoord kunnen geven.

**Comment by JohanBoer** [comment]
@fsamwel Als je jouw voorstel implementeert dan negeer je de mogelijkheid om in de toekomst content-negotiation toe te voegen zonder een breaking change te introduceren. 

Stel we doen dit en we besluiten over een half jaar ook plainjson aan te bieden in deze API, dan is dat een breaking change omdat een consumer die geen acceptheadr had geïmplementeerd of die  Accept: application/json heeft gebruikt dan een andere response krijgt. 
Ik ben dus voorstander van een verplichte Accept header met de waarde Accept: application/hal+json

**Comment by fsamwel** [comment]
@JohanBoer hal+json is gewoon een invulling van json. Wanneer we meerdere json varianten gaan aanbieden, is het nog steeds handig dat er een default is voor het geval met application/json meestuurt, of helemaal geen accept stuurt. Op dit moment is die default hal+json.
De applicatie geeft nu wel antwoord bij het weglaten van accept, maar geeft een fout bij application/json. Naar mijn mening is dat niet correct.
Het verplichten van application/hal+json en dus niet bieden van een default is denk ik niet vriendelijk voor de gebruikers en verlengt de tijd die iemand nodig heeft om de eerste succesvolle aanroep te doen.
@MelvLee hoe zie jij dit? Wat zou jij graag willen en verwachten van de api?

**Comment by JohanBoer** [comment]
Bij nader inzien ben ik het met je eens dat het weglaten van de accept header een default zou moeten opleveren. 
Als je echter bij application/json nu een HAL antwoord geeft en in de toekomst willen we ook plain json gaan leveren, dan breek je toch de consumers die op basis van application/json het HAL bericht verwachten ?

**Comment by fsamwel** [comment]
> Als je echter bij application/json nu een HAL antwoord geeft en in de toekomst willen we ook plain json gaan leveren, dan breek je toch de consumers die op basis van application/json het HAL bericht verwachten ?

Ja dat klopt. Maar hebben andere varianten niet altijd een eigen toevoeging, zoals application/ld+json, application/collection+JSON, application/vnd.siren+json? Het probleem dat je schetst speelt dus alleen bij echte "plain json", zonder aan te sluiten bij een breder gebruikte standaard of protocol.

**Comment by MelvLee** [comment]
Als de consumer om een content type vraag die de provider niet ondersteunt, kan de provider een response sturen van een andere content type, zolang hij maar de content type meestuurt.
Een consumer kan ook meerdere content types meesturen en dan geeft de volgorde de voorkeur aan.
Persoonlijk zou ik als een consumer application/json als content type vraag en mijn provider zou alleen application/hal+json ondersteunen, dan zou ik geen foutmelding geven omdat de kans heel groot is dat consumer een application/hal+json response kan verwerken.

**Comment by MelvLee** [comment]
En als je toch een foutmelding wil geven, dan zou ik het fijn vinden als in de detail is aangegeven welke content types wel wordt ondersteund, zodat de consumer niet hoeft te gaan raden

**Comment by fsamwel** [comment]
@strijm Mark pas jij de implementatie hierop aan (dus geen foutmelding geven in deze situatie)?

**Comment by JohanBoer** [comment]
Duidelijke uitleg Melvin.

**Comment by strijm** [comment]
Wat is hier nu precies het besluit? Moet de server gewoon altijd application/hal+json terugsturen, ook al wordt er iets anders gevraagd? We sturen dus nooit een 406 response?
Ik zou graag zien, dat er specifiek wordt aangegeven welke content types er wel en niet ondersteund moeten worden, dat dit wordt aangegeven in de yaml specificatie en dat er wordt aangegeven welke response er in iedere situatie wordt teruggestuurd.

**Comment by fsamwel** [comment]
De NL API strategie schrijft over content negotiation:

> 18.10 API-24: Support content negotiation
> 
> Besides JSON, APIs should support other representations as XML and RDF using the default HTTP content negotiation mechanism. In case the requested format cannot be provided, a 406 ot Acceptable response is sent.

Dit zou leiden tot de volgende afhandeling:
```
| Accept header        | Content-type header      | Response code |
| application/json     | application/hal+json     | 200           |
| application/hal+json | application/hal+json     | 200           |
| application/xml      | application/problem+json | 406           |
| application/text     | application/problem+json | 406           |
| application/ld+json  | application/problem+json | 406           |
```

Ik ben het op zich met @MelvLee eens dat het vriendelijker is altijd een antwoord te sturen en dus geen 406.

**Comment by JohanBoer** [comment]
> Ik zou graag zien, dat er specifiek wordt aangegeven welke content types er wel en niet ondersteund moeten worden, dat dit wordt aangegeven in de yaml specificatie

In de yaml spec staat bij iedere '200'response :

          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/KadastraalOnroerendeZaakHalCollectie'

Dus in de specificatie staat welk content type er ondersteund wordt. 
of wil je expliciet 
          content:
            application/hal+json:
              schema:
                $ref: '#/components/schemas/KadastraalOnroerendeZaakHalCollectie'
            application/json:
              schema:
                $ref: '#/components/schemas/KadastraalOnroerendeZaakHalCollectie'

opnemen in de specificatie ? 

Daarmee bereik je wat Frank in de issue heeft beschreven en staat het expliciet in de specificatie. 
Ik weet niet of we hiermee meer duidelijkheid creëren.

**Comment by strijm** [comment]
Het toevoegen van application/json lijkt mij inderdaad een goed idee, als we die moeten ondersteunen. Dan ligt het vast in het contract. Voor alles wat dan niet vastligt in het contract kunnen we dan een 406 response geven. Dat lijkt me juist duidelijker, wat er vastligt in het contract, wordt ondersteund al het andere niet.

**Comment by fsamwel** [comment]
volgens mij gaat dit issue niet over de OAS3 specificaties, maar over de implementatie.

Dus over strikt leveren wat gevraagd is en anders een 406
of
Leveren wat gevraagd is en anders de default

Waarbij mijn punt is dat hal+json ook json is. Dus als iemand vraagt om json, mag deze hal+json krijgen. Ik denk namelijk dat een client die kan omgaan met json, ook om kan gaan met hal+json.

**Comment by strijm** [comment]
Volgens mij is de vraag: moeten we nu application/json ondersteunen? 

1. Zo ja, dan leggen we dat vast in een contract.
We spreken in het contract af dat als application/json ondersteund moet worden, er application/hal+json teruggestuurd mag worden, of we sturen direct application/json terug.
Dat dit in de toekomst mogelijk een breaking change oplevert, dat klopt, maar dat is ook terecht en duidelijk naar gebruikers. Want als we nu impliciet afspreken dat application/hal+json teruggegeven mag worden als er om application/json wordt gevraagd maar we leggen dit niet vast in het contract, dan doe je een implciete aanname dat een client dit wel aan kan en de content types uitwisselbaar zijn, m.i. is dat juist niet heel klantvriendelijk en misschien zelfs niet waar. Wat zou je ervan vinden als je in een restaurant vis besteld en vlees krijgt opgediend, terwijl je vegetariër bent? 
Stel we zetten application/json nu niet in de specificatie en sturen application/hal+json terug terwijl er om application/json wordt gevraagd. De clients passen daar mogelijk hun code op aan, want application/hal+json is toch net even iets anders dan application/json, het is tenslotte niet voor niets een andere content type met een eigen RFC. Als in een later stadium de API specificatie wordt uitgebreid met application/json (wat geen breaking change zou moeten zijn omdat je iets toevoegt), en we geven dan wel application/json terug als daar om wordt gevraagd, dan moeten de clients als ze deze nieuwe versie gebruiken toch hun code aanpassen, want ze krijgen ineens geen application/hal+json maar application/json terug. Dat is vreemd, want het contract is toch alleen maar uitgebreid? Er kan dus wel degelijk impact bij clients zitten als je iets niet vastlegt in een contract. In beide gevallen moeten de clients hun code aanpassen, in de eerste situatie is dit expliciet gemaakt en in de tweede situatie niet. M.i. is de eerste de meest klantvriendelijke oplossing. Kortom het gebruik maken van de default (application/hal+son) is juist niet klantvriendelijk. 
Wat doen we als er wordt gevraagd om application/xml of application/ld+json, ook gewoon application/hal+json terugsturen?
Het doet er dus niet toe dat hal+json ook json is, als er specifieke afspraken worden gemaakt, moeten die worden vastgelegd in het contract. De content-type application/hal+json is niet voor niets een andere content-type dan application/json.

2. Zo nee, dan leggen we dat niet vast in een contract en ondersteunen het ook niet.
We spreken voor application/json niets af in het contract en we ondersteunen deze voorlopig dus niet en geven een foutmelding 406. In dat geval kan later zonder een breaking change de API spec worden uitgebreid met ondersteuning van application/json.

**Comment by fsamwel** [comment]
overwegingen (besproken in overleg vandaag):
- naast hal+json ook json specificeren met identiek hal+json antwoord voegt weinig toe
- als iemand iets vraagt wat niet precies kunnen leveren, maar wel iets vergelijkbaars, wil je liefst geen foutmelding geven, maar gewoon leveren. DX vraagt om zo weinig mogelijk fouten geven (beter iets dan niets).
- hal+json is een specialisatie van json, dus vragen om json en hal+json leveren is correct, want json+hal is ook json
- door geen json variant te specificeren blijft het mogelijk later een "plain" json toe te voegen (met risico op breaking change voor gebruikers die json vragen, maar ook HAL elementen daaruit gebruiken)

conclusie:
- geen wijziging aan specificaties
- vragen om application/json levert application/hal+json (geen foutmelding)
- vragen om andere variant, bijvoorbeeld application/xml levert wel 406 (conform NL API strategie API-26)
