### ISSUE TITLE
verkorteStraatnaam niet opgenomen in het antwoord

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#86]
GET https://api.test.kadaster.nl/lvbag/api/huidigebevragingen/vhc/adressen/0599200000193766

Dit levert het adres, maar zonder verkorteStraatnaam. Heeft een adres niet altijd een verkorte straatnaam (die soms gelijk is aan de straatnaam)?

**Comment by strijm** [comment]
Verkortestraatnaam wordt alleen bepaald (en geleverd) voor straatnamen met een lengte > 24 karakters.

**Comment by fsamwel** [comment]
@CathyDingemanse op andere plekken, zoals woonplaats (zowel in BRP als BAG) zorgen we dat zo'n property altijd gevuld is. Dan hoeft de gebruiker niet af te testen welke gevuld is. Hoe wil jij de functionaliteit op dit punt zien?

Bijvoorbeeld wanneer iemand een korte straatnaam nodig heeft (moet bijvoorbeeld in een envelop vensterenvelop passen), is het m.i. handiger altijd verkorteStraatnaam te kunnen gebruiken, zonder check of deze wel gevuld is (om anders de "gewone" straat te gebruiken).

**Comment by MelvLee** [comment]
Dat staat niet in de description. Dan zou ik als consumer moeten raden waarom ik  wel/geen verkorte naam krijg

**Comment by NicoleKortoomsBAG** [comment]
De straatnaam is alleen verkort als die verkort is en daarom anders niet gevuld. 
Ik kan me voorstellen dat het handig is om een altijd gevuld veld te hebben. Ik ga overleggen of we een oplossing kunnen bedenken. Is de wens voor een gevuld veld er met name binnen adres en de toepassing die daar wordt voorzien of ook binnen de openbare ruimtenaam? die laatste is alleen via de link te bereiken, juist bedoeld voor extra informatie.

**Comment by NicoleKortoomsBAG** [comment]
We gaan de naam van het veld veranderen van verkorte naam naar korte naam. Hiermee kan het veld altijd gevuld zijn. 
De officiële naam was niet langer dan 24 tekens of hij is volgens de NEN5825 verkort tot maximaal 24 tekens.
