### ISSUE TITLE
niks vinden bij zoeken mag geen 404 geven

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#88]
Bijvoorbeeld GET https://api.test.kadaster.nl/lvbag/api/huidigebevragingen/vhc/adressen/zoek?zoek=bestaat%20niet%20in%20nootdorp

Dit levert nu:
{
   "status": 404,
   "title": "Opgevraagde resource bestaat niet.",
   "type": "https://tools.ietf.org/html/rfc7231#section-6.5.4",
   "detail": "Geen resultaten gevonden met query bestaat niet in nootdorp",
   "instance": "https://api.test.kadaster.nl/lvbag/api/huidigebevragingen/vhc/adressen/zoek?zoek=bestaat%20niet%20in%20nootdorp",
   "code": "notFound"
}

Dat is niet terecht. Er is geen resource gevraagd, maar een collectie. De collectie bestaat wel, maar is leeg.
Ik had dus verwacht:
{ "zoekResultaten": [ ] }

**Comment by strijm** [comment]
Een tijdje terug is besloten, dat attributen die geen waarde hebben of booleans met waarde false, dat deze niet worden teruggegeven. Geldt dat dan ook voor een lege collectie? Het heeft toch geen zin om "zoekResultaten": [] terug te geven? In dat geval zou het bij een HalCollectie het _embedded deel vervallen als er geen zoekresultaten zijn, omdat er alleen zoekResultaten in _embedded zitten.

**Comment by JohanBoer** [comment]
@MelvLee zou jij hier je licht op willen laten schijnen ?

**Comment by MelvLee** [comment]
Zoeken zou geen 404 moeten geven als er geen resources zijn die aan de zoekcriteria voldoen. Conform search engine zou je dus geen zoek resultaten verwachten.

Echter, we hebben afgesproken om lege collecties, net als attributen die geen waarde hebben om die niet terug te geven, zodat dit consistent is voor collecties, objecten en attributen.

Alleen is voor _embedded een uitzondering gemaakt. Die wordt altijd teruggegeven, ook als al zijn properties leeg zijn. De reden waarom dit is gedaan, is omdat je anders in code altijd moet controleren of _embedded null is. Zo is het ook geïmplementeerd in BRP en BRK.

**Comment by JohanBoer** [comment]
Dus de conclusie is dan in geval er geen zoekresultaat is om wel de _embedded terug te leveren en geen lege collectie te retourneren. Klopt dat  ?

**Comment by fsamwel** [comment]
Ja, dat klopt.

In BRP en BRK krijg ik bij zoeken zonder resultaten:
```
{
  "_links": {
    "self": { "href": "<request url incl. query parameters>" }
  },
  "_embedded": { }
}
```

**Comment by fsamwel** [comment]
afgezien van #233 (links ontbreken) opgelost
