### ISSUE TITLE
Als medewerker vastgoedorganisatie wil ik kunnen zien of de adressen van een verblijfsobject kloppen met de kadastrale kaart en waar de voordeur zit (hoekpand Janstraat 1 of Pietstraat 1a)

### ISSUE THREAD

**Issue by CathyDingemanse** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#9]
Zodat ik kan terugmelden.

**Comment by NicoleKortoomsBAG** [comment]
De locatie van de voordeur is geen BAG gegeven. Sommige gemeenten kiezen ervoor om de xy van het vbo bij de voordeur te leggen, echter dit is geen voorwaarde.

**Comment by CathyDingemanse** [comment]
> De locatie van de voordeur is geen BAG gegeven. Sommige gemeenten kiezen ervoor om de xy van het vbo bij de voordeur te leggen, echter dit is geen voorwaarde.
> xy van het vbo kan wel worden gegeven evenals geometrie van het pand.

het gaat ook vooral om de relatie van het vbo met de nummeraanduiding. Is er sprake van een "illegaal gecreeerd adres" waarvoor geen vergunning is verleend.

**Comment by CathyDingemanse** [comment]
is gerealiseerd in V1.1
