### ISSUE TITLE
weergavenaam bij adresboeken toont postcode niet altijd

### ISSUE THREAD

**Issue by fsamwel** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#90]
De weergavenaam is normaal gesproken opgebouwd uit straatnaam huisnummer, postcode woonplaats.

Maar soms wordt de postcode niet opgenomen.

Bijvoorbeeld GET https://api.test.kadaster.nl/lvbag/api/huidigebevragingen/vhc/adressen/zoek?zoek=zorgvlietstraat%20den%20haag
levert:
{"zoekResultaten": [
      {
      "weergavenaam": "Zorgvlietstraat 1, 2513RH 's-Gravenhage",
      "identificatie": "adr-08421bd3beee83d8453efe1b3223ca46"
   },
      {
      "weergavenaam": "Zorgvlietstraat 3, 2513RH 's-Gravenhage",
      "identificatie": "adr-bf15ab72a5a98af3b8f98f8a98cf8945"
   },
      {
      "weergavenaam": "Zorgvlietstraat 4T, 's-Gravenhage",
      "identificatie": "adr-020a41140965af965f6f752c5ec5ef18"
   },

**Comment by NicoleKortoomsBAG** [comment]
Niet alle adressen hebben een postcode. Voor verblijfsobject met het gebruiksdoel overige gebruiksfunctie wordt geen postcode uitgegeven.
In het voorbeeld van Zorgvliesstraat 4T is sprake van een adres zonder postcode. Dit betreft een overige gebruiksfunctie.

**Comment by NicoleKortoomsBAG** [comment]
bij het voorstel voor de beschrijving van adres was weggevallen dat tussen haakjes optioneel is. Gezien deze vraag (en vele andere die we hierover ontvangen) lijkt het met goed dat er wel bij op te nemen.
Het adres is de benaming van een adreswaardige locatie bestaande uit straatnaam, huisnummer, (huisletter, huisnummertoevoeging, postcode) en woonplaatsnaam. 
Dit is de vereenvoudigde samenstelling van de officiële naamgeving gebaseerd op de objecten: Woonplaats, Openbare ruimte en Nummeraanduiding.
Tussen haakjes is optioneel

**Comment by JohanBoer** [comment]
Ik heb de aangepaste versie opgenomen. Ik heb de zin iets aangepast (Wat tussen haakjes staat is optioneel).

**Comment by NicoleKortoomsBAG** [comment]
top

**Comment by strijm** [comment]
Dit is issue gefixed in de master en kan afgesloten worden.
