### ISSUE TITLE
Als consumer wil ik adressen kunnen zoeken m.b.v. queryparameters

### ISSUE THREAD

**Issue by strijm** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#97]
...zodat ik de query strikter kan specificeren.

Op dit moment is het met het zoeken met een free query zoek parameter niet helemaal duidelijk hoe het zoek gedrag is.

**Acceptatiecriteria**
- kunnen zoeken met een combinatie van één of meer van de queryparameters: postcode, huisnummer, huisletter, huisnummertoevoeging, straatnaam en/of woonplaats.
bv.
/adressen/zoek?zoek=7522ZA;381-207 levert wel resultaat maar het is onduidelijk welke veld wat is, voorstel is om expliciet te definiëren: /adressen/zoek?postcode=<>&huisnummer=<>&huisletter=<>&huisnummertoevoeging=<>&straat=<>&woonplaats=<>

- [ ]

**Definition of done**
- [ ] functionele specificatie
- [ ] Open API specificatie
- [ ] gegenereerde code
- [ ] testgevallen

**Comment by CathyDingemanse** [comment]
Van wie is deze wens afkomstig? Misschien kan ik deze persoon nog even spreken tijdens het lab?

**Comment by strijm** [comment]
De opmerking kwam van Ivo Lodewijks van SIgmax.

**Comment by JohanBoer** [comment]
Vooralsnog terug naar de backlog. Mocht er n.a.v. Versie 1.0.0. meer behoefte aan zijn, dan bezien we dat op dat moment.

**Comment by CathyDingemanse** [comment]
sluiten, we mikken op het verbeteren van search as you type RESTful zoeken van adressen.
