### ISSUE TITLE
Property 	"adresseerbaarObjectType"  wordt twee keer in een verblijfsobject terug gegeven

### ISSUE THREAD

**Issue by rschrieken** [VNG-Realisatie/Haal-Centraal-BAG-bevragen#98]
Bij het bevragen van dit adresseerbaarobject:

https://api.test.kadaster.nl/lvbag/api/huidigebevragingen/vhc/adresseerbareobjecten/0513010013059147

wordt in het verblijfsobject twee maal dezelfde property terug gegeven, nl: adresseerbaarObjectType

```
{
	"verblijfsobject" : {
		"verblijfsobject" : {
			"adresseerbaarObjectType" : "Verblijfsobject",
			"heeftAlsHoofdAdres" : {
				"lokaalID" : "0513200000003550",
				"namespace" : "NL.IMBAG.Nummeraanduiding"
			},
			"adresseerbaarObjectType" : "Verblijfsobject",
			"identificatie" : {
				"lokaalID" : "0513010013059147",
				"namespace" : "NL.IMBAG.Verblijfsobject"
			},
```

sommige JSON parsers kunnen daar niet tegen.

De verwachte output zou zijn:

```
{
	"verblijfsobject" : {
		"verblijfsobject" : {
			"adresseerbaarObjectType" : "Verblijfsobject",
			"heeftAlsHoofdAdres" : {
				"lokaalID" : "0513200000003550",
				"namespace" : "NL.IMBAG.Nummeraanduiding"
			},
			"identificatie" : {
				"lokaalID" : "0513010013059147",
				"namespace" : "NL.IMBAG.Verblijfsobject"
			},
```

Als die twee adresseerbaarObjectType properties daar niet staan agv een ander onderliggend probleem kan dan de propertybag dan alleen unieke properties bevatten

**Comment by JohanBoer** [comment]
Dit is een achterhaald probleem
